Cray-HPE/csm

- CHANGELOG.md
- rpm/cray/csm/sle-15sp2/index.yaml
…3526
Releases csm-testing which includes changes for csm-1.2
* CASMPET-5003 : AUTOMATION: Refactor goss-k8s-monitoring-url.yaml for Bi-CAN
* CASMINST-3526 : Drax: Velero backup failed during automated goss test in k8 nodes
* Resolves [CASMPET-5003](https://connect.us.cray.com/jira/browse/CASMPET-5003)
* Resolves [CASMINST-3526](https://connect.us.cray.com/jira/browse/CASMINST-3526)
* Change will also be needed in main
Verified test changes work as expected in 1.2 environment
* wasp (1.2)
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? NA
- Were continuous integration tests run? If not, …
> CASMPET-5160 1.2 : Release csm-testing for CASMPET-5003 and CASMINST-3526

- manifests/platform.yaml
Looks like we haven't updated precached images for kea -- adding them.
* Resolves [CASMTRIAGE-2717](https://connect.us.cray.com/jira/browse/CASMTRIAGE-2717)
not tested, simple cm update adding images
N/A
N/A
N/A
> Update kea's pre-cached images to match kea's deployment

- docker/index.yaml
- manifests/core-services.yaml
- manifests/platform.yaml
The cray-dns-powerdns services that were on the CAN when we were developing it on 1.0 systems for 1.1 have the name cray-dns-powerdns-can-[tcp|udp]. With BiCAN in 1.2, we these are now on the CMN so they should be named cray-dns-powerdns-cmn-[tcp|udp].
* Resolves [CASMNET-1016](https://connect.us.cray.com/jira/browse/CASMNET-1016)
* Merge with https://stash.us.cray.com/projects/SHASTA-CFG/repos/stable/pull-requests/761/overview
Tested on:
* wasp - `cray-dns-powerdns` has been upgraded and rolled back successfully.
N/A
Requires:
* CSM fresh install and update testing
> CASMNET-1016 - Change name of cray-dns-powerdns-can to cray-dns-powerdns-cmn

- helm/index.yaml
The version of the spire chart in the manifest doesn't match the version in the helm index. This updates the helm index to match the version in the manifest
* Resolves [CASMINST-3536](https://connect.us.cray.com/jira/browse/CASMINST-3536)
> CASMINST-3536 Update spire version in helm index

- CHANGELOG.md
- docker/index.yaml
- manifests/platform.yaml
Istio is upgraded to 1.8.6 for 1.2 and this required changes to
cray-kiali, cray-istio-operator, cray-istio-deploy, and cray-istio
charts and the associated images.
> CASMPET-5104: Updates for upgrade to Istio 1.8.6

- lib/set-ncns-to-unbound.sh
CSM 1.2 now uses `cloud-init` to manage `resolv.conf` rather than SUSE `netconfig`. The current implementation of this script resulted in no changes occurring when run due to the netconfig DNS policy being disabled.
* Resolves [CASMTRIAGE-2543](https://connect.us.cray.com/jira/browse/CASMTRIAGE-2543)
* wasp
Script was run and it was confirmed that the PIT nameserver entry had been removed from `/etc/resolv.conf` on all NCNs.
This test was repeated multiple times.
> CASMTRIAGE-2543 - set-ncns-to-unbound.sh did not configure DNS correctly

- CHANGELOG.md
- rpm/cray/csm/sle-15sp2/index.yaml
Resolves
* CASMINST-3546 :  csi pit validate for k8s has failed
> CASMINST-3546 1.2 : csi pit validate for k8s has failed

- assets.sh
- rpm/cray/csm/sle-15sp2/index.yaml
PIT ISO, NCNs, and nexus update for:
* MTL-1555 - k8s routes for NCNs
* CASMINST-3538 - (re)add package-utils rpm to list that gets updated on NCN rebuild
* CASMINST-3539 - only wait 5min for spire on m001
> Assets for 2021-11-12

- docker/index.yaml
- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
This change pulls in updates to the FAS CT tests for new expected "errors" fields in the /actions and /snapshots API responses.
* Resolves CASMTRIAGE-2650.
This change was tested by deploying the updated CT tests to Wasp running csm-1.2.0-alpha.16, executing them, and verifying that the previously failing test cases due to unexpected "errors" fields began to pass.
Was an Upgrade tested? N/A
Was a Downgrade tested? N/A
Low risk that impacts FAS CT testing only.
> CASMTRIAGE-2650 Update FAS tests new error fields csm-1.2

- docker/index.yaml
- manifests/platform.yaml
- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
This includes the following changes:
* CASMPET-4299: Configure new nexus Keycloak client and K8s secret
* CASMPET-4714: keycloak-setup create oauth2-proxy client and Secret
This also requires a change to the customizations.yaml to pass the
proxiedHosts list for the new oauth2-proxy client to the
cray-keycloak chart.
The proxied hosts list in cray-keycloak was referenced from the
cray-keycloak-gatekeeper config. Since the cray-keycloak-gatekeeper
is going away soon, I pulled the list from cray-keycloak-gatekeeper
to a new variable in the `spec` section.
> CASMPET-5158: Update keycloak charts for keycloak-setup image

- CHANGELOG.md
- manifests/platform.yaml
Releasing cray-opa version 1.3.0 for CSM 1.2
* Resolves [CASMCMS-7355](https://connect.us.cray.com/jira/browse/CASMCMS-7355)
* Resolves [CASMPET-3940](https://connect.us.cray.com/jira/browse/CASMPET-3940)
* Resolves [CASMPET-5141](https://connect.us.cray.com/jira/browse/CASMPET-5141)
* Resolves [CASMPET-5150](https://connect.us.cray.com/jira/browse/CASMPET-5150)
* Resolves [PE-37952](https://connect.us.cray.com/jira/browse/PE-37952)
> CASMPET-3940 Bump cray-opa to 1.3.0

- manifests/platform.yaml
This adds the opa image to the image cache so that cray-opa can come up if nexus is not responding.
> CASMPET-5150 Add opa image to image cache

- docker/index.yaml
- manifests/sysmgmt.yaml
Added v2 API for HMNFD which includes easily filterable
subscriptions endpoints.  This is to satisfy a security
requirement related to OPA filtering.
Once this is committed it will be possible to fine tune
the OPA filtering for HMNFD to prevent malfeasance with
the subscription API.
DOES THIS CHANGE INVOLVE ANY SCHEME CHANGES?  N
REMINDER: HAVE YOU INCREMENTED VERSION NUMBERS? E.G., .spec, Chart.yaml Y
REMINDER 2: HAVE YOU UPDATED THE COPYRIGHT PER hpe GUIDELINES: © Copyright 2014-2020 Hewlett Packard Enterprise Development LP    ? Y
* Resolves CASMHMS-5230
Tested on:
* wasp
* Local machine
Was a fresh Install tested? N   No need
Was an Upgrade tested?      Y
Was a Downgrade tested?     Y
Was a CT test run?          Y
If schema changes were part of this change, how were those handled in …
> Added v2 API including xname-based subscriptions.

- docker/index.yaml
- manifests/core-services.yaml
This updates the HSM manifest for:
CASMHMS-5239 - HSM now kicks off re-discovery for nodeBMCs when a power on redfish event is received for its slot. This will automate re-discovery of node components when power is restored to a slot.
CASMHMS-5233 - HSM would silently error out on kicking off manual re-discovery of a component list that contained duplicates. This mod changes HSM to ignore the duplicates.
* Resolves [CASMHMS-5239](https://connect.us.cray.com/jira/browse/CASMHMS-5239)
* Resolves [CASMHMS-5233](https://connect.us.cray.com/jira/browse/CASMHMS-5233)
For testing see https://github.com/Cray-HPE/hms-smd/pull/56
Low risk
> Update HSM manifest

- CHANGELOG.md
- manifests/platform.yaml
Bi-CAN : Update the virtual service ingress cray-keycloak gateways to also include customer-admin-gateway and customer-user-gateway.
backward compatible since the service-gateway still remains as an ingress gatgeway.
* Resolves [CASMPET-4953](BI-CAN: Update keycloak to use the new API Gateways)
* Future work required - Release cray-keycloak for csm-1.2
* Documentation changes required NA
vshasta
before
```
$ kubectl get vs -A | grep keycloak
services            keycloak                           ["services-gateway"]            ["*"]                             6h2m
```
after
```
$ kubectl get vs -A | grep keycloak
services            keycloak …
```
> CASMPET-4953 1.2 : BI-CAN: Update keycloak to use the new API Gateways

- CHANGELOG.md
- rpm/cray/csm/sle-15sp2/index.yaml
New goss test to detect when precached images aren't being pulled on workers
* Resolves [CASMPET-4862](https://connect.us.cray.com/jira/browse/CASMPET-4862)
vshasa
Ran success/failure tests
N/A
> Bring in csm-testing v1.8.31 for precache image test

- manifests/platform.yaml
PR
https://github.com/Cray-HPE/cray-sysmgmt-health/pull/38
Resolves
https://connect.us.cray.com/jira/browse/CASMMON-72
https://connect.us.cray.com/jira/browse/CASMMON-101
https://connect.us.cray.com/jira/browse/CASMMON-100
https://github.com/Cray-HPE/cray-sysmgmt-health/releases/tag/v1.2.9
> CASMMON-72, CASMMON-101, CASMMON-100 : Enable SMART metrics, alerts and grafana dashboard for k8s nodes

- rpm/cray/csm/sle-15sp2/index.yaml
In CSM 1.2 if a system is not configured for CHN then the istio-ingressgateway-chn will be pending waiting for an IP address because the customer-high-speed MetalLB pool will not exist.
This will cause the original implementation of the "k8s_all_loadbalancers_have_external_ips" Goss test to always fail on a system without CHN even though it is in the expected state.
This update to the test determines whether CHN is configured by checking for the presence of the customer-high-speed pool and then filtering the list of LoadBalancers appropriately.
* Resolves [CASMINST-3427](https://connect.us.cray.com/jira/browse/CASMINST-3427)
* wasp
* drax
| Test | Expected outcome | Actual outcome | 
| --- | --- | --- |
| Normal run | Test pass | Test pass |
| Run with pending istio-ingressgateway-chn LB …
> CASMINST-3427 - "LoadBalancer Services Have External IP" goss test failure on system with no CHN

- manifests/platform.yaml
- manifests/sysmgmt.yaml
- cray-drydock is updated to 2.11.0 in order to add name label to all namespaces
- cray-spire is updated to 1.2.1 in order to fix access-spire network policy
* Resolves - [CASMPET-4344](https://connect.us.cray.com/jira/browse/CASMPET-4344)
* wasp
> CASMTRIAGE-2730 Fix access-spire network policy

- docker/index.yaml
- install.sh
- manifests/platform.yaml
Update cray-metallb chart (1.0.0) to use upstream chart from metallb.io
This change is dependent on csi change coming to generate metallb config for customizations.yaml
* Resolves [CASMPET-3521](https://connect.us.cray.com/jira/browse/CASMPET-3521)
vshasta
Validated fresh install and upgrade from previous version.
None known yet.
> New metallb chart and docker images, relying on customizations for config

- CHANGELOG.md
- docker/index.yaml
- docker/transform.sh
- manifests/keycloak-gatekeeper.yaml
- manifests/platform.yaml
- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
- vendor/stash.us.cray.com/scm/shasta-cfg/stable/docs/SEALED-SECRETS.md
- vendor/stash.us.cray.com/scm/shasta-cfg/stable/utils/generators/randstr
This commit includes the following JIRAs:
* CASMPET-4714: Update keycloak-installer to reflect new chart setup. (keycloak-setup creates the oauth2-proxy client)
* CASMPET-5158: Release keycloak-installer for CSM 1.2 (Releases CASMPET-4714 so the oauth2-proxy client will exist)
* CASMPET-5156: Stop deploying keycloak-gatekeeper objects (switch to this version of cray-keycloak-gatekeeeper in csm manifest)
* CASMPET-5154: Generate cookie secret and pass to oauth2-proxy
* CASMPET-5155: Another oauth2-proxy-ingress for another interface (oauth2-proxy bi-can)
* CASMPET-5169: oauth2-proxy v7.1.3 image has several vulnerabilites
While there's still a cray-keycloak-gatekeeper chart it doesn't deploy
any K8s objects anymore. Helm cleans the up the objects on upgrade to
make room for the …
> CASMPET-4277: Switch from keycloak-gatekeeper to oauth2-proxy

- rpm/cray/csm/sle-15sp2/index.yaml
Generates the metalLB config in the customizations.yaml so the config map can get rendered into the new metallb chart.
This will still generate the metallb.yaml as well until we confirm that the config map within the chart is fully working.
I will remove the generation of the metallb.yaml once we determine that the new metallb chart is stable.
* Resolves [CASMPET-4873](https://connect.us.cray.com/jira/browse/CASMPET-4873)
* Requires https://github.com/Cray-HPE/csm/pull/121
* surtur
Generated files with CSI and verified that both the metallb.yaml and customizations.yaml look correct.
I tested both with and without the CHN network defined.
Low risk since we are still generating the metallb.yaml as well.  That can be a fallback.
> CASMPET-4873:  Generate metallb config in customizations.yaml

- manifests/platform.yaml
https://connect.us.cray.com/jira/browse/CASMINST-3537
https://connect.us.cray.com/jira/browse/CASMINST-3591
https://github.com/Cray-HPE/cray-sysmgmt-health/pull/40
https://github.com/Cray-HPE/cray-sysmgmt-health/releases/tag/v1.2.10
> Bump version CASMINST-3537 CASMINST-3591

- manifests/platform.yaml
This includes the following fix:
CASMPET-3585 Corrects a mistake in the cray-keycloak chart where the nexus client secret environment variable name was incorrect.
( https://github.com/Cray-HPE/keycloak-installer/pull/29 )
> CASMPET-3585 Bump the cray-keycloak chart patch version

- rpm/cray/csm/sle-15sp2/index.yaml
This includes the fix for:
* CASMINST-3603: ncnhealthchecks failed for goss k8 monitoring URL test case
> CASMINST-3603: Bump csm-testing to 1.8.34

- manifests/platform.yaml
https://connect.us.cray.com/jira/browse/CASMMON-76
https://github.com/Cray-HPE/cray-sysmgmt-health/pull/42
https://github.com/Cray-HPE/cray-sysmgmt-health/releases/tag/v1.2.11
>  sysmgmt-health  bump version

- docker/index.yaml
- manifests/sysmgmt.yaml
Fix gitea import when upgrading a Cray EX product (like CSM) but the gitea import version of csm-config has not changed.
* Resolves [CASMINST-3525](https://connect.us.cray.com/jira/browse/CASMINST-3525)
* Merge after https://github.com/Cray-HPE/csm-config/pull/25
See testing description in https://github.com/Cray-HPE/csm-config/pull/25
None
> CASMINST-3525: update csm-config for gitea import issues

- docker/index.yaml
- manifests/platform.yaml
This bumps the versions of the charts that are built by
keycloak-installer to the versions that include the change for:
* CASMPET-5033: Update image refs in Helm charts
The images refs that were changed in the charts are already in
the docker/index.yaml file.
> CASMPET-5033: Update image refs for keycloak-installer

- manifests/sysmgmt.yaml
This changes all spire containers to run as nobody instead of root.
* Resolves [CASMPET-5178](https://connect.us.cray.com/jira/browse/CASMPET-5178)
Validated running containers in the spire namespace no longer ran as root.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N/.A
- Was downgrade tested? If not, why? Y 
None
> CASMPET-5178 Bump spire to 1.3.0

- docker/index.yaml
- manifests/core-services.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
This change updates the HMS CT smoke tests to execute the HSM tests first to more easily and clearly identify discovery-related problems.
* Resolves CASMHMS-5205 in csm-1.2
This change was tested by deploying the updated smoke tests and wrapper script to Wasp, executing them, and verifying that the HSM tests ran first. Failures of the HSM smoke tests were also verified to stop execution of the wrapper script as expected.
Low risk.
> CASMHMS-5205 Reorder HMS CT smoke test execution csm-1.2

- rpm/cray/csm/sle-15sp2/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
This fixes the test which is causing the CMS part of the CSM health check procedure to fail on every 1.2 install.
See original PR for details:
https://github.com/Cray-HPE/cms-tools/pull/20
This is ready to be merged, pending approvals.
> CASMCMS-7691: Fix broken IMS signing keys test

- docker/index.yaml
- manifests/platform.yaml
This picks up the change for:
* CASMPET-5171: keycloak-setup stop creating gatekeeper client
See https://github.com/Cray-HPE/keycloak-installer/releases/tag/v1.2.6
> CASMPET-5171: Bump Keycloak versions  to pick up CSM 1.2 Release 6

- manifests/core-services.yaml
The appVersion for cray-dns-unbound doesn't match the image specified in the docker index.yaml file.
* Resolves [CASMTRIAGE-2771](https://connect.us.cray.com/jira/browse/CASMTRIAGE-2771)
* `surtur`
Updated manifest and deployed using standard install automation.
> CASMTRIAGE-2771 - Correct cray-dns-unbound image version

- manifests/platform.yaml
https://connect.us.cray.com/jira/browse/CASMMON-57
https://github.com/Cray-HPE/cray-sysmgmt-health/pull/43
https://github.com/Cray-HPE/cray-sysmgmt-health/releases/tag/v1.2.12
> CASMMON-57: Bump version

- docker/index.yaml
- manifests/core-services.yaml
- manifests/platform.yaml
- bugfix in dhcp-helper to append the static mac data for csm-1.0 bss data format
- yes
CASMNET-1052
Fanta
Wasp …
> CASMNET-2052 - fix for dhcp-helper support for csm-1.0 bss data

- manifests/platform.yaml
- manifests/sysmgmt.yaml
This disabled the xname workloads and validation by default. We won't be enabling them by default until we're sure it will work without a performance hit.
* Resolves [CASMPET-5187](https://connect.us.cray.com/jira/browse/CASMINST-5187)
> CASMPET-5187 Disable xname validation by default

- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
This updates the cray-opa issuers to handle having a different set of
issuers per opa policy (CASMPET-5150)
* Resolves [CASMINST-3636](https://connect.us.cray.com/jira/browse/CASMINST-3636)
* surtur
Manually tested that the lines configured the opa policies correctly.
> CASMINST-3636 Update cray-opa issuers

- assets.sh
Fixes:
* CASMINST-3627 (via node-image-build)
* CASMHMS-5205 (via csm-rpms)
> CASMREL-834: NCN assets for csm-1.2

- docker/index.yaml
- manifests/sysmgmt.yaml
This updates the hmcollector manifest version for HPE PDU support.
* Resolves [CASMHMS-5268](https://connect.us.cray.com/jira/browse/CASMHMS-5268)
For testing see https://github.com/Cray-HPE/hms-hmcollector/pull/32
Low risk.
> Update hmcollector manifest version for HPE PDU support Main

- docker/index.yaml
- manifests/sysmgmt.yaml
This updates the hmcollector manifest version for HPE PDU support.
* Resolves [CASMHMS-5268](https://connect.us.cray.com/jira/browse/CASMHMS-5268)
For testing see https://github.com/Cray-HPE/hms-hmcollector/pull/32
Low risk.
> Update hmcollector manifest version for HPE PDU support 1.2

- assets.sh
- rpm/cray/csm/sle-15sp2/index.yaml
This just additionally prints the nexus RPM info when `metalid.sh` is invoked.
**Requires new LiveCD; do not merge until this is updated with a new LiveCD**
> MTL-1574 print nexus info in metalid.sh

- docker/index.yaml
- manifests/platform.yaml
Updating cray-drydock to CSM 1.2 Release 3, see
https://github.com/Cray-HPE/cray-drydock/releases/tag/v1.2.3
> CASMPET-5031: Updates to cray-drydock for casm-2670

- docker/index.yaml
- manifests/core-services.yaml
- manifests/platform.yaml
Run PowerDNS as a non-root user
* Resolves [CASMNET-859](https://connect.us.cray.com/jira/browse/CASMNET-859)
* `wasp`
Release was installed on wasp and it was verified the processes were running as the correct user
```
/ $ id
uid=100(pdns) gid=101(pdns)
/ $ ps -ef
PID   USER     TIME  COMMAND
1 pdns      0:00 {powerdns} /bin/bash /bin/powerdns
86 pdns      0:00 pdns_server
88 pdns      0:04 pdns_server-instance
1068 pdns      0:00 sh
1075 pdns      0:00 ps -ef
```
ExternalDNS functionality was verified by testing access to several web services (Grafana and Gitea).
> CASMNET-859 - Run PowerDNS as non-privileged user

- docker/index.yaml
- manifests/sysmgmt.yaml
The Shasta 1.5 firmware moved to a new power capping control schema. Fix an issue where trying to power cap more than one control at the same time was hanging.
* Resolves CASMHMS-5261
Tested on:
* hela
Manually set power cap values on a single control and multiple controls. Verified via logs that the proper number of controls were attempted and the targets were correct.
HAS A SECURITY AUDIT BEEN RUN? (./runSnyk.sh) Y
Firmware currently broken for Mountain nodes with GPUs: SDEVICE-3701 - Controls API timing out occasionally
> Casmhms 5261 fix power capping 1.0

- docker/index.yaml
- manifests/sysmgmt.yaml
The Shasta 1.5 firmware moved to a new power capping control schema. Fix an issue where trying to power cap more than one control at the same time was hanging.
* Resolves CASMHMS-5261
Tested on:
* hela
Manually set power cap values on a single control and multiple controls. Verified via logs that the proper number of controls were attempted and the targets were correct.
HAS A SECURITY AUDIT BEEN RUN? (./runSnyk.sh) Y
Firmware currently broken for Mountain nodes with GPUs: SDEVICE-3701 - Controls API timing out occasionally
> CASMHMS-5261 Fix power capping for newer nC firmware

- rpm/cray/csm/sle-15sp2/index.yaml
Change timeout from 1000ms to 5000ms to wait longer for output to
return. In many cases output will emit before 1000ms, but it can take
slightly longer. 5000ms would cover most if not all cases.
Yes.
* Resolves [CASMINST-3544](https://connect.us.cray.com/jira/browse/CASMINST-3544)
* Merge with https://github.com/Cray-HPE/csm/pull/200
If a …
> CASMINST-3544 bios-baseline timeout

- assets.sh
- rpm/cray/csm/sle-15sp2/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
This change adds new logging and earlier exits to the metal iPXE configuration. The new early exits will print the error cause, wait for 5 seconds, and then bail. The bail exits the ROM and causes the BIOS to move onto the next boot option.
Yes.
* Resolves [MTL-1501](https://connect.us.cray.com/jira/browse/MTL-1501)
* Future work required by [MTL-1572](https://connect.us.cray.com/jira/browse/MTL-1572)
* Merge …
> MTL-1501 PXE Exit and Disk-fallback

- rpm/cray/csm/sle-15sp2/index.yaml
Changes since 1.11.1:
* CASMINST-3029 - NCN Automation Business Logic
* MTL-1569 add backwards compatibility for handoff bss-metadata command
* CASMINST-3598 generate ipam metadata key and push into bss
> Release CSI 1.12.2

- assets.sh
- rpm/cray/csm/sle-15sp2/index.yaml
**LiveCD is included in `assets.sh`**.
This swaps the old cray-nexus RPM for the new [pit-nexus RPM ](https://github.com/Cray-HPE/pit-nexus), this work is tagged with the recent bugfix for pit-nexus [CASMPET-5173](https://connect.us.cray.com/jira/browse/CASMPET-5173).
Yes.
* Resolves [CASMPET-5173](https://connect.us.cray.com/jira/browse/CASMPET-5173)
* …
> CASMPET-5173 swap-in pit-nexus for cray-nexus

- lib/install-goss-tests.sh
Automatically answer 'yes' for `zypper install` vs prompting the user to confirm.
> CASMINST-3139: auto-answer-yes for zypper install

- manifests/sysmgmt.yaml
This fixes an issue where the spire-agent pod failed to start correctly, causing the API gateway to fail to validate spire JWTs.
* Resolves [CASMTRIAGE-2791](https://connect.us.cray.com/jira/browse/CASMTRIAGE-2791)
* hela
Validated spire-agent worked correctly and spire-jwks returned keys.
> CASMTRIAGE-2791 - Bump spire to 1.5.0

- rpm/cray/csm/sle-15sp2/index.yaml
CANU has been updated to feature complete as of the 1.0.0 release and needs to be included in CSM 1.2 build.
* Resolves CASMNET-1059
* Merge with/before/after `https://github.com/Cray-HPE/csm-rpms/pull/150`
* `wasp`
* Tested upgrade from 0.0.5 and 0.0.6 to 1.0.0.
* On system testing of SHCD validate, configuration generation and validation and cabling checks.
- Were continuous integration tests run? **YES**
- Was upgrade tested? **YES**
- Was downgrade tested? **NO** as downgrade to 0.0.6 or lower will not be useful on CSM 1.2 systems.
None
> CASMET-1059: Bump CANU version to 1.0.0

- docker/index.yaml
- manifests/platform.yaml
Update cray-sysmgmt-health to CSM 1.2 release 13, which includes
the following change:
* CASMPET-5038: Update image refs in charts
> CASMPET-5038: Updates for cray-sysmgmt-health

- docker/index.yaml
- lib/wait-for-unbound.sh
- manifests/core-services.yaml
- manifests/platform.yaml
- error handling when query bss data if data is returned that is not expected
- make sure dhcp-helper does not patch in an IP when there is already an IP outside of loading BSS data
- make sure xname is used when trying to repair SMD data after node move
- csm-service-upgrade.sh "hangs" at cray-dns-unbound-manager section
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_ yes
* Resolves
CASMNET-1053
CASMNET-1054
CSAMNET-1055
CASMINST-3477
Fanta …
> Bugfix/casminst 3477/CASMNET-1053/CASMNET-1054/CASMNET-1055 -  csm 1.2

- docker/index.yaml
the docker/index.yaml is missing artifactory.algol60.net/csm-docker/stable/docker.io/library/busybox:1.28.0-glibc, causing cray-fas-etcd to fail to start.
* Resolves [CASMTRIAGE-2794](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-2794)
* hela
Manually copied over the image and verified that the cray-fas-etcd pods started to work
None
> CASMTRIAGE-2794 Add algol60 busybox image

- assets.sh
Note:
* Tag 0.1.110 was for a CI/CD change.  No node image code has changed since 0.1.109 except for the code that is for CASMINST-3650.
* The pipeline builds k8s and ceph images at the same time.  We _could_ just take the ceph image here and leave k8s at 0.1.109.
> CASMINST-3650: lts/csm-1.0 storage image with fix for CASMINST-3650

- assets.sh
This change removed dnsmasq as a dependency to metal-ipxe, and since it is not explicitly installed by csm-rpms the package is now missing. This is a critical package necessary for the PIT, it provides DHCP, DNS, and netbooting capabilities.
[Build Log](https://jenkins.algol60.net/job/Cray-HPE/job/cray-pre-install-toolkit/view/tags/job/v1.5.8/6/console):
```bash
[ DEBUG   ]: 18:42:21 | (182/217) Installing: dnsmasq-2.78-7.6.1.x86_64 [............done]
[ DEBUG   ]: 18:42:21 | Additional rpm output:
[ DEBUG   ]: 18:42:21 | warning: /etc/dnsmasq.conf created as /etc/dnsmasq.conf.rpmnew
[ DEBUG   ]: 18:42:21 | Running in chroot, ignoring command 'daemon-reload'
``` …
> MTL-1576 Add DNSMASQ back in (new LiveCD)

- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
This is an outdated construct.  The macvlan vlan should always
be the NMN vlan.  As such, there is no need to provide it as a
configuration input value.
Requires https://github.com/Cray-HPE/cray-site-init/pull/100
> CASMTRIAGE-2648: don't specify a vlan for UAI/macvlan

- manifests/platform.yaml
cray-opa 1.6.0 disables xname validation in opa. This was supposed to go into a previous PR, but was incorrectly pushed as 1.5.0.
* Resolves [CASMTRIAGE-2802](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-2802)
* hela
Validated cfs-state-reporter started working after updating the chart.
> CASMTRIAGE-2802 Bump cray-opa to 1.6.0

- assets.sh
This includes this PR's commits: https://github.com/Cray-HPE/node-image-build/pull/126
* Resolves [MTL-1562](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1562)
* `redbull` (smoke-tests)
This includes a change to the OS RAID Array …
> MTL-1562 S3FS

- rpm/cray/csm/sle-15sp2/index.yaml
This updates and fixes the ceph service check
Resolves CASMINST-4569, CASMINST-4570
Testing
manually run on mug and fanta then verified the expected results
Tested on:
mug/fanta
Test description:
Verified the pdsh entry in known hosts no longer happens and verified clean runs w/ expected results
Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? n/a
Were continuous integration tests run? If not, why? n/a
Was upgrade tested? If not, why? n/a
Was downgrade tested? If not, why? n/a
Were new tests (or test issues/Jiras) created for this change? n/a
Risks and Mitigations
Pull Request Checklist
Version number(s) incremented, if applicable
Copyrights updated
License file intact
Target branch correct …
> CASMISNT-4569 - pulling in new ceph check into goss

- docker/index.yaml
- manifests/sysmgmt.yaml
This bumps the versions of the cray-crus chart to the versions that include the change for:
[CASMPET-5033](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7708): Update image refs in charts: cray-crus
See original source PR for details:
https://github.com/Cray-HPE/cray-crus/pull/9
> Update cray-crus to 1.9.1

- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
With the use of the Nexus Keycloak authentication plugin in CSM 1.2 (https://jira-pro.its.hpecorp.net:8443/browse/CASM-2361) Nexus web UI traffic must go to the ingress gateway. This change will update the DNS record for nexus.cmn.system_name to that of the system's ingress gateway.
* Resolves https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5165
* Mug and Wasp
It was confirmed that the changes when applied manually would result in the proper DNS update allowing the integration to work properly.
None
> Move the Nexus web UI's DNS to the ingress gateway.

- docker/index.yaml
- manifests/sysmgmt.yaml
This change bumps csm-config to version 1.9.8 which includes the new HMS CT test RPMs in the list of Ansible CSM packages for CFS.
* Resolves CASMTRIAGE-2815 in csm-1.2.
Not sure how to test this, fixing "No provider of hms-ct-test-crayctldeploy" errors reported in CASMTRIAGE-2815 by the ansible-0 log as part of the CFS session.
Low risk, fixes something that is currently broken.
> CASMTRIAGE-2815 Bump csm-config to 1.9.8 for new HMS test RPMs in CFS csm-1.2

- docker/index.yaml
- manifests/core-services.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
This change adds support for HPE PDUs to the HSM ComponentEndpoints CT test.
* Resolves CASMTRIAGE-2801.
This change was tested by deploying the updated HSM ComponentEndpoints CT test to the system Hela which has HPE PDUs, executing the test, and verifying that the previously failing test cases began to pass.
Low risk.
> CASMTRIAGE-2801 Add support for HPE PDUs to the HSM ComponentEndpoints CT test.

- rpm/cray/csm/sle-15sp2/index.yaml
This updates `assets.sh` with the most recent cray-site-init _and_ a matching LiveCD.
This bumps cray-site-init from 1.12.2 to 1.13.2.
> Latest CSI

- rpm/cray/csm/sle-15sp2/index.yaml
csm-testing and goss-servers rpms are built at the same time, so
both references are updated here.  The important change in this
version of the RPM is that both will now be signed instead of only
csm-testing.
* Resolves https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3679
> Fix signing for the goss-servers rpm

- rpm/cray/csm/sle-15sp2/index.yaml
* Fixes bug where empty CHN network was created in SLS when chn inputs are not provided to CSI
* Fixes bug where CHN interface was being added to ipam parameters in basecamp
* Handles cabinets-yaml with empty string
* Checks for csm-version input to make sure 1.0 inputs are not used in 1.2 installs
* Resolves CASMTRIAGE-2702
* Resolves MTL-1568
* Resolves CASMINST-3410
* Resolves CASMNET-1061
* `drax`
Tested with various valid and invalid inputs to CSI on drax.  Checked the generated files to make sure they were correct.
No known issues
> CSI update for: CASMTRIAGE-2702, MTL-1568, CASMINST-3410, and CASMNET-1061

- manifests/sysmgmt.yaml
FAS chart version to 2.0.4 for v1.16.0
> FAS chart version to 2.0.4 for v1.16.0

- manifests/platform.yaml
cray-istio chart was missing horizontal autoscalers
* Resolves [CASMINST-3406](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3406)
Releasing on behalf of Jeanne
Low
> Release cray-istio 2.4.3 with horizontal autoscalers fix

- manifests/platform.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
Bring in fixed goss test for precache images, removed unused proxyv2 image.
* Resolves [CASMINST-3693](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3693)
hela
* `hela`
Hand edited the test and config map to test.
Low
> Fixes for precache goss test and fix for unused proxyv2 image

- manifests/platform.yaml
Part of the CASM-2670 refactoring prematurely changed the cronjob api version to batch/v1 -- we'll have to hold on that till we're running a later version of K8S.
* Resolves [CASMINST-3694](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3694)
vshasta:
```
ncn-m001-72c7d5a2:/home/bklein # kubectl -n kube-system get cronjob.batch/kube-etcdbackup -o yaml | head -2l
apiVersion: batch/v1beta1
kind: CronJob
```
* `vshasta`
Deployed chart in vshasta, cronjob was created with old api version
Low
> Fix cronjob api version for cray-baremetal-etcd-backup to be compatible with k8s 1.20.13

- docker/index.yaml
- manifests/sysmgmt.yaml
Use the latest pgbouncer master-19 image, which has 0 critical and only 1 high CVE, compared to 2 critical
and 3 high CVEs in the current pgbouncer master-17 image.
* Resolves [CASMPET-5202]
* `wasp`
Tested the new chart on wasp, and verified that the spire-postgres-pooler pods successfully
pulled the latest pgbouncer image. Pod logs showed no errors after being up for more than
30 minutes.
Low. pgbouncer upgrade is a minor version upgrade.
> CASMPET-5202: use pgbouncer master-19 image

- manifests/platform.yaml
There was a problem with gatekeeper 1.5.0 that caused the chart
to fail to deploy because the image used in the hook didn't have
the command that was executed (curl). 1.5.1 fixes this problem.
> CASMTRIAGE-2849: Update gatekeeper to 1.5.1

- assets.sh
New 0.2.33 NCN Images and a LiveCD.
NCN Changes: https://github.com/Cray-HPE/node-image-build/pull/136
LiveCD Changes:
- https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3695
> CASMREL-843 New 1.5.8-20211214220847-ga02c80b LiveCD and 0.2.33 NCN Images

- CHANGELOG.md
- manifests/sysmgmt.yaml
- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
Move cray-uas-mgr to version 1.17.0 to bring in BiCAN and External DNS changes as well as most of the cray-uas-mgr NERSC Phase 2 changes.  Update customizations.yaml to provide BiCAN and External DNS required configuration for cray-uas-mgr.
This is backward compatible.
* Resolves [CASMNET-856](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-865)
No known risks or issues from this PR
- [ N/A ] Copyrights updated
- [ N/A ] License file intact
- [ N/A ] Testing is appropriate and complete, if applicable
- [ N/A ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable
> CASMNET-865 cray-uas-mgr to 1.17.0 / add needed customizations

- manifests/platform.yaml
The existing cray-vault-operator 1.1.0 uses a command that's not available in docker-kubectl image. This is to use cray-vault-operator 1.1.1 chart to use an equivalent command to check pod readiness.
> CASMTRIAGE-2848: use cray-vault-operator 1.1.1

- manifests/sysmgmt.yaml
Update cray-hms-hmcollector chart to v2.15.2 with application version v2.16.0 to resolve CVE-2021-3520 in lz4.
Backwards compatible bugfix.
* Resolves [CASMHMS-5296](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5296)
* Wasp
For testing see: https://github.com/Cray-HPE/hms-hmcollector/pull/33
Low risk.
> (CSM 1.2) CASMHMS-5296: Update cray-hms-hmcollector chart to resolve CVE

- manifests/sysmgmt.yaml
Update cray-hms-hmcollector chart to v2.15.2 with application version v2.16.0 to resolve CVE-2021-3520 in lz4.
Backwards compatible bugfix.
* Resolves [CASMHMS-5296](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5296)
* Wasp
For testing see: https://github.com/Cray-HPE/hms-hmcollector/pull/33
Low risk.
> (main) CASMHMS-5296: Update cray-hms-hmcollector chart to resolve CVE

- vendor/stash.us.cray.com/scm/shasta-cfg/stable/utils/generators/zmq_curve
Update zmq_curve generator to use algol60 pathed image to match what is shipped in the CSM tarball.
* Resolves [CASMINST-3692](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3692)
* Change will also be needed in `csm` to update the generator
* Merge with `https://github.com/Cray-HPE/docs-csm/pull/661`
* `surtur`
New documentation followed, updated generator used to generate PALs SealedSecret.
> CASMINST-3692 - Update zmq_curve generator to use image shipped in CSM tarball

- docker/index.yaml
- lib/wait-for-unbound.sh
- manifests/core-services.yaml
- manifests/platform.yaml
- added preStop to unbound to mitigate dropped requests during pod restart/deploy
- increased granuality of readiness checks for unbound to mitigate dropped request/deploy
- updated kubectl binary for unbound-manager 
- update unbound-manager to use python logger
- fix wait-for-unbound.sh script in csm-1.2
- helm v2 api and removal of dtr references for unbound and kea
* Resolves 
- CASMNET-1051
- CASMNET-1064
- CASMNET-995
- CASMNET-1076
- CASMINST-3706
- …
> Break/fix/casminst 3706 csm 1.2

- docker/index.yaml
- manifests/core-services.yaml
- manifests/platform.yaml
- added preStop to unbound to mitigate dropped requests during pod restart/deploy
- increased granularity of readiness checks for unbound to mitigate dropped request/deploy
- update unbound-manager to use python logger 
* Resolves 
- CASMNET-1051
- CASMNET-1064
- CASMNET-995
* Wasp
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled …
> CASMNET-1051/CASMNET-1064/CASMNET-995/CASMNET-1076 manifest changes

- manifests/platform.yaml
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-106
[Cray-HPE/cray-sysmgmt-health#43](https://github.com/Cray-HPE/cray-sysmgmt-health/pull/45)
https://github.com/Cray-HPE/cray-sysmgmt-health/releases/tag/v1.2.14
> Casmmon 106 : Bump version

- CHANGELOG.md
- manifests/sysmgmt.yaml
Update cfs-operator chart to 1.14.6 to bring in new AEE image. Backwards compatible.
* Resolves CASMTRIAGE-2853
* Resolves CASMCMS-7725
* Merge after https://jenkins.algol60.net/blue/organizations/jenkins/Cray-HPE%2Fcfs-operator/detail/v1.14.6/1/pipeline completes build
* Related PRs:
- https://github.com/Cray-HPE/ansible-execution-environment/pull/19
- https://github.com/Cray-HPE/cfs-operator/pull/33
* `hela`
See https://github.com/Cray-HPE/ansible-execution-environment/pull/19
See https://github.com/Cray-HPE/ansible-execution-environment/pull/19
> CASMTRIAGE-2853: update cfs-operator 1.14.6

- manifests/core-services.yaml
Need to add the PeerASN, MyASN, and MetalLBPoolName to SLS in order to be able to properly upgrade customizations.yaml from 1.0 to 1.2.   For upgrades we are using SLS for the source of truth of the system configuration.   SLS has most of what is needed for MetalLB but it is missing the ASNs and the pool names.     This also cleans things up in CSI for generating customizations.yaml in a fresh install.
DOES THIS CHANGE INVOLVE ANY SCHEME CHANGES?  N
REMINDER: HAVE YOU INCREMENTED VERSION NUMBERS? Y (.version and CHANGELOG.md)
REMINDER 2: HAVE YOU UPDATED THE COPYRIGHT PER hpe GUIDELINES: (C) Copyright 2014-2021 Hewlett Packard Enterprise Development LP    ? Y
LIST AND CHARACTERIZE RELATIONSHIP TO JIRA ISSUES AND OTHER PULL REQUESTS. BE SURE LIST DEPENDENCIES.
* Work required by …
> (CSM 1.2) CASMNET-967: Bump SLS version

- manifests/core-services.yaml
Need to add the PeerASN, MyASN, and MetalLBPoolName to SLS in order to be able to properly upgrade customizations.yaml from 1.0 to 1.2.   For upgrades we are using SLS for the source of truth of the system configuration.   SLS has most of what is needed for MetalLB but it is missing the ASNs and the pool names.     This also cleans things up in CSI for generating customizations.yaml in a fresh install.
DOES THIS CHANGE INVOLVE ANY SCHEME CHANGES?  N
REMINDER: HAVE YOU INCREMENTED VERSION NUMBERS? Y (.version and CHANGELOG.md)
REMINDER 2: HAVE YOU UPDATED THE COPYRIGHT PER hpe GUIDELINES: (C) Copyright 2014-2021 Hewlett Packard Enterprise Development LP    ? Y
LIST AND CHARACTERIZE RELATIONSHIP TO JIRA ISSUES AND OTHER PULL REQUESTS. BE SURE LIST DEPENDENCIES.
* Work required by …
> (main) CASMNET-967: Bump SLS version

- rpm/cray/csm/sle-15sp2/index.yaml
Need to add the PeerASN, MyASN, and MetalLBPoolName to SLS in order to be able to properly upgrade customizations.yaml from 1.0 to 1.2.   For upgrades we are using SLS for the source of truth of the system configuration.   SLS has most of what is needed for MetalLB but it is missing the ASNs and the pool names.     This also cleans things up in CSI for generating customizations.yaml in a fresh install.
DOES THIS CHANGE INVOLVE ANY SCHEME CHANGES?  N
REMINDER: HAVE YOU INCREMENTED VERSION NUMBERS? Y (.version and CHANGELOG.md)
REMINDER 2: HAVE YOU UPDATED THE COPYRIGHT PER hpe GUIDELINES: (C) Copyright 2014-2021 Hewlett Packard Enterprise Development LP    ? Y
LIST AND CHARACTERIZE RELATIONSHIP TO JIRA ISSUES AND OTHER PULL REQUESTS. BE SURE LIST DEPENDENCIES.
* Work required by …
> CASMNET-967:  Update CSI with ASN and pool name fields

- CHANGELOG.md
- docker/index.yaml
- manifests/platform.yaml
This bumps cray-kafka-operator to 0.4.2, which includes the CVE-2021-44228 fix.
* Resolves [CASMPET-5216](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5216)
Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
Were continuous integration tests run? If not, why? N/A
Was upgrade tested? If not, why? Y
Was downgrade tested? If not, why? Y
Were new tests (or test issues/Jiras) created for this change? N
> CASMPET-5216 Bump cray-kafka-operator to 0.4.2

- assets.sh
LiveCD:
* CASMINST-3701 - Fix empty string generated for hmn_api_gw
* CASMUSER-2812 - update craycli with new hard and soft timeouts
* MTL-1586 - Pull AMSD, Mellanox, and firmware RPMs from the new HPE mirror in algol60
NCNs:
* CASMPET-5208 - Add read-only ceph client
* CASMUSER-2812 - update craycli with new hard and soft timeouts
* MTL-1407 - Remove false postive warnings about missing LUKS keystores on worker nodes
* MTL-1540 - net-init.sh fails nicely on missing metadata
* MTL-1586 - Pull AMSD, Mellanox, and firmware RPMs from the new HPE mirror in algol60
* MTL-1588 - Cease `mc reset cold` on HPE servers; prevent crashing the iLO/BMC
* MTL-1590 - Fix squashFS download timeout in dracut when MLAG/STP block is active
> CASMREL-846: LiveCD and NCN images for CSM 1.2 alpha 41

- manifests/platform.yaml
This manifest update will add:
CASMPET-5200 Create the Nexus nx-anonymous role as part of the keycloak-installer process.
Cray-HPE/keycloak-installer#33
> Create the Nexus nx-anonymous role

- docker/index.yaml
- manifests/core-services.yaml
- manifests/platform.yaml
- set imagehost to dtr from algol60 for cray-dns-unbound
- yes
[CASMNET-1087](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1087)
Fanta
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? yes
- Were continuous integration tests run? If not, why? no, we …
> CASMNET-1087 - fix cray-dns-unbound imagehost to point to dtr.

- CHANGELOG.md
- rpm/cray/csm/sle-15sp2/index.yaml
New goss-servers rpm to fix ca-cert test to allow for certs in different order, depending if they come from the file system or from metadata curl call.
* Resolves [CASMTRIAGE-2837](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-2837)
Tested fix on hela
* `hela`
```
ncn-m001:/opt/cray/tests/install/ncn/tests # goss -g /opt/cray/tests/install/ncn/tests/goss-platform-ca-certs-match-cloud-init-brad.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml v
.
Total Duration: 0.058s
Count: 1, Failed: 0, Skipped: 0
```
```
ncn-m002:~ # goss -g /opt/cray/tests/install/ncn/tests/goss-platform-ca-certs-match-cloud-init-brad.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml v
.
Total Duration: 0.059s
Count: 1, Failed: 0, Skipped: 0
```
Low
> New csm-testing and goss-servers rpm for ca-cert test fix

- docker/index.yaml
- manifests/platform.yaml
Bring in etcd-operator image/chart change that supports pod priorities in 1.0.10.
* Resolves [CASMINST-3713](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3713)
Ran the 0.15.2 chart version in vshasta with the later etcd-operator image.
Low
> Backport etcd-operator pod priority change to 1.0.10

- manifests/sysmgmt.yaml
Update the IMS version to 3.4.9. This version moves the IMS jobs from the customer-access subnet to the customer-management subnet.
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_ Yes
* Resolves [CASMCMS-7703](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7703)
* `wasp`
Installed the updated IMS helm chart. Verified that the IMS jobs were now accessible via the customer-managment network.
- Were the …
> CASMCMS-7703 Move IMS jobs to the customer-managment network

- docker/index.yaml
Resolves CVE issue in SHCD parser. 
Rebuild resolved the issue. No further testing required. 
* Resolves CASMHMS-5303
> updated SHCD parser image for CASMHMS-5303

- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
It was found that the password generated for the `crayvcs` user account for Gitea could sometimes have illegal characters that would cause HTTP repo cloning break. This mod enables the `url_safe` for the Gitea secret generation to prevent this.
CASMINST-3602
Tested locally and on Fanta, verified that passwords weren't generated with any illegal characters. 
Made the change and ran `secrets-seed-customizations.sh` a bunch.
Should be no risk.
> Made the generated password for the crayvcs user URL safe by default.

- rpm/cray/csm/sle-15sp2/index.yaml
Use the latest signed csm-1.0 goss-servers RPM.  When we fixed the signing issue for 1.0.1 we did not update the CSM manifest.  This was due to the fact that 1.0.1 was created by hand and not the pipeline.
> CASMINST-3732: Use latest csm-1.0 RPM that is signed

- vendor/stash.us.cray.com/scm/shasta-cfg/stable/docs/NEW-SYSTEM.md
- vendor/stash.us.cray.com/scm/shasta-cfg/stable/docs/UPDATE-SYSTEM.md
- vendor/stash.us.cray.com/scm/shasta-cfg/stable/meta/init.sh
The [prepare_site_init.md](https://github.com/Cray-HPE/docs-csm/blob/release/1.0/install/prepare_site_init.md#2-create-and-initialize-site-init-directory) procedure has the user run `meta/init.sh` to create a new shasta-cfg directory structure for the install.
The output of `init.sh` immediately invites the user to review and edit customizations.yaml and then run the `secrets-reencrypt.sh` and `secrets-seed-customizations.sh` scripts however it is not appropriate to do so until the remainder of the steps in prepare_site_init.md have been followed.
This PR removes the prompt to run these two commands from the `init.sh` script output and updates the shasta-cfg documentation to reflect the new output.
* Resolves [CASMINST-3094](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3094)
* …
> CASMINST-3094 - Remove secret generation commands from meta/init.sh output so it isn't run prematurely

- CHANGELOG.md
- docker/index.yaml
Remove unused craycli docker image from docker manifest
This change is backward compatible as it removes a docker image that has never been used and is no longer built.
* Resolves [CASMCLOUD-1202](https://jira-pro.its.hpecorp.net:8443/browse/CASMCLOUD-1202)
N/A
- Were new tests (or test issues/Jiras) created for this change? N/A
There are no known risks or issues with this change.
- [ N/A ] Version number(s) incremented, if applicable
- [ N/A ] Copyrights updated
- [ N/A ] Testing is appropriate and complete, if applicable
- [ N/A ] [HPC Product …
> CASMCLOUD-1202 Remove unused craycli docker image from manifest

- CHANGELOG.md
- manifests/platform.yaml
This updates the Strimzi operator to 0.27.0, which fixes a number of CVEs including CVE-2021-44228.
* Resolves [CASMPET-5217](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5217) 
Validated that the strimzi operator worked properly and that the shared Kafka cluster started as expected.
- Were continuous integration tests run? If not, why? N, no tests available.
- Was upgrade tested? If not, why? N, needs further testing on bare metal to validate that Kafka can deal properly with upgrades.
- Was downgrade tested? If not, why? N, needs further testing on bare metal to validate that Kafka can deal properly with downgrades.
- Were new tests (or test issues/Jiras) created …
> CASMPET-5217 Update kafka charts to 1.0.0

- install.sh
- tds_cpu_requests.yaml
- upgrade.sh
Edit customizations.yaml during fresh install and upgrade (1.0.10) to apply lower CPU requests for some services requests larger than needed on TDS/3 worker systems.
* Partially Resolves [CASMINST-3688](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3688)
Validated the merge of yaml looks correct (craystack)
* `craystack`
Yaml looks good, will need to validate final chart impacts on a fresh install 1.2 system (with SMA installed)
None
> Changes to reduce CPU requests for TDS systems

- manifests/sysmgmt.yaml
Alpine target being used had several CVEs. Updated which artifactory the docker file was pulling from and included an apk upgrade to help resolve current and future CVE  issues.
* Resolves [CASMHMS-5302](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5302)
No additional testing required.
Verified snyk tests did not find anymore vulnerabilities.
[Snyk run from build with CVEs](https://jenkins.algol60.net/job/Cray-HPE/job/hms-capmc/job/v1.31.0/3/artifact/2022-01-05T15-22-54-093531Z_snyk_report.html)
[Snyk run for this change](https://jenkins.algol60.net/job/Cray-HPE/job/hms-capmc/job/fix-cve/5/artifact/2022-01-07T17-22-52-287318Z_snyk_report.html)
No known risks
> Update CAPMC for CVE fix

- CHANGELOG.md
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
Update craycli to 0.40.20 in RPM manifests to match what is installed in node images.
This change is backward complatible.
* Resolves [CASMINST-3741](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3741)
N/A
N/A
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_ N/A
- Were new tests (or test issues/Jiras) created for this change? N/A
There are no known risks associated with this change.
- [  N/A ] Version number(s) incremented, if applicable
- [ …
> CASMINST-3741 update craycli to 0.40.20 in RPM manifests

- manifests/platform.yaml
Use the recent rebuilt external-dns image for CVE remediation (31 critical & high -> 13)
* Resolves [CASMPET-5212]
* Change will also be needed in `master`
* `wasp`
Chris re-installed powerdns and re-deployed the externaldns chart, and verified that powerdns records were repopulated correctly.
Low. Can always revert back to the original chart if unexpected issues arise.
> CASMPET-5212: use the recent rebuilt external-dns image

- manifests/sysmgmt.yaml
See original PR for details:
https://github.com/Cray-HPE/gitea/pull/13
> CASMCMS-7754: gitea: Do not pin alpine patch version; Use patched and signed alpine image

- manifests/sysmgmt.yaml
This updates spire to 2.1.0, which fixes an issue where it was requesting the wrong pgbouncer image.
* Resolves [CASMINST-3770](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3770)
Validated spire worked and used the correct image
None
> CASMINST-3770 Update spire to 2.1.0

- manifests/platform.yaml
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-94
https://github.com/Cray-HPE/cray-sysmgmt-health/pull/46
https://github.com/Cray-HPE/cray-sysmgmt-health/releases/tag/v1.2.15
> Casmmon 94 bumping the sysmgmt-health version.

- rpm/cray/csm/sle-15sp2/index.yaml
CANU has been updated to feature complete as of the 1.0.0 release and needs to be included in CSM 1.2 build.
* Resolves CASMNET-1059
* Merge with `https://github.com/Cray-HPE/csm-rpms/pull/149`
* `wasp`
* Tested upgrade from 0.0.5 and 0.0.6 to 1.0.0.
* On system testing of SHCD validate, configuration generation and validation and cabling checks.
- Were continuous integration tests run? **YES**
- Was upgrade tested? **YES**
- Was downgrade tested? **NO** as downgrade to 0.0.6 or lower will not be useful on CSM 1.2 systems.
None
> CASMNET-1059: Bump CANU version to 1.0.0

- manifests/sysmgmt.yaml
Update CSM Barebones to v1.4.7. This moves the CSM Barebones recipe and image to be based off of SLES15SP3 instead of SLES15SP2
Yes
* Resolves [CASMCMS-7758](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7758)
* `Hela`
Installed new helm …
> CASMCMS-7758 Update CSM Barebones to v1.4.7

- manifests/platform.yaml
Fix a couple of precache image references that were wrong or have recently changed.
* Resolves [CASMINST-3784](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3784)
surtur
* `surtur`
Edited the configmap and test now passes:
```
ncn-m002:/opt/cray/tests/install/ncn/tests # export GOSS_BASE=/opt/cray/tests/install/ncn; goss -g /opt/cray/tests/install/ncn/tests/goss-k8s-precache-images-health.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate
..
Total Duration: 0.169s
```
Low
> Fix an opa an nexus precache image reference issue

- manifests/sysmgmt.yaml
Pull in fix for [CASMCMS-7753](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7753) into csm-1.2
See original PR for details:
https://github.com/Cray-HPE/bos/pull/26
> CASMCMS-7760: BOS needs to use BOA >= v1.2.80

- lib/setup-nexus.sh
Updated line 21 of nexus_check_pod to include a | grep -v Completed. This is necessary to ignore the nexus-init pods that stay in a Completed state.
_Summarize what has changed. This is a critical bug fix. I added a grep -v Completed to the nexus_check_pod variable in the script. This is needed to ignore the init pods that stay in a Completed state.
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_ Not Applicable
* Resolves CASMINST-3762 https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3762
* Change will also be needed in yapl automation as well, separate PR for that coming.
* Future work required by N/A
* Documentation …
> CASMINST-3762 updated nexus_check_pod to exclude init pods in completed state

- docker/index.yaml
- manifests/platform.yaml
cray-kiali was using upstream kiali repo, but we should use algol60 repo and the rebuilt kiali images.
* Resolves [CASMINST-3775]
* `wasp`
Redeployed the new cray-kiali chart, and verified the images were pulled from algol60 repo, and kiali pods were restarted successfully with no errors from pod logs.
Low. Only image repo path changes.
> CASMINST-3775: fix kiali image repo path

- manifests/sysmgmt.yaml
Fixes:
CASMINST-3792: BREAK/FIX: cronjob-kicker is missing
CASMINST-3757: FIX/BREAK: master node - missing dir for rebuild automation
* Resolves [CASMINST-3757](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3757)
* Resolves [CASMINST-3792](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3792)
Limited testing of new ansible code in isolation
* `craystack`
Low
> New version of csm-config chart

- docker/index.yaml
Unable to find any charts that use this image on a csm 1.0 or 1.2 system.
Reviewed with PET team members as well. 
Removing the bitnami/minideb:bullseye image from the docker index.
* Resolves [CASMPET-5254](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5254)
Low
> CASMPET-5254 main : SECURITY: fix vulnerabilities in bitnami/minideb (no references found)

- docker/index.yaml
Unable to find any charts that use this image on a csm 1.0 or 1.2 system.
Reviewed with PET team members as well. 
Removing the bitnami/minideb:bullseye image from the docker index.
* Resolves [CASMPET-5254](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5254)
Low
> CASMPET-5254 : SECURITY: fix vulnerabilities in bitnami/minideb (no references found)

- manifests/platform.yaml
The current node-discovery chart was based on an old alpine image 3.12.6, with many critical and high CVEs. This PR changes the chart to use a new rebuilt image based on alpine image 3.14.3, which shows no known CVEs.
* Resolves [CASMPET-5225]
* `hela`
Re-deployed the new node-discovery chart, and verified that the new pods successfully pulled the new image with no errors in log. I also ran the node-discovery smoke tests and verified that the tests completed successfully.
- Were new tests (or test issues/Jiras) created for …
> CASMPET-5225: fix vulnerabilities in node-discovery

- rpm/cray/csm/sle-15sp2/index.yaml
This change updates the path to the hms-pytest image in Nexus since images are no longer being uploaded to the old location.
* Resolves CASMHMS-5312.
This change was tested on Mug running csm-1.2.0-alpha.43 by pulling the hms-pytest image from the new location and verifying that the previously failing CT tests began to pass. Also verified with Zach C. that the new path is correct and that the previous location is no longer supported.
Low risk that fixes an out-of-date image path.
> CASMHMS-5312 Update hms-pytest image location for Nexus main

- rpm/cray/csm/sle-15sp2/index.yaml
This change updates the path to the hms-pytest image in Nexus since images are no longer being uploaded to the old location.
* Resolves CASMHMS-5312.
This change was tested on Mug running csm-1.2.0-alpha.43 by pulling the hms-pytest image from the new location and verifying that the previously failing CT tests began to pass. Also verified with Zach C. that the new path is correct and that the previous location is no longer supported.
Low risk that fixes an out-of-date image path.
> CASMHMS-5312 Update hms-pytest image location for Nexus csm-1.2

- rpm/cray/csm/sle-15sp2/index.yaml
New version of csm-testing to fix goss test to remove blank lines from file system cert before comparing to the one in metadata
* Resolves [CASMINST-3796](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3796)
Tested this in place on mug:
```
ncn-m002:~ # export GOSS_BASE=/opt/cray/tests/install/ncn; goss -g /opt/cray/tests/install/ncn/tests/goss-platform-ca-certs-match-cloud-init.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate
.
Total Duration: 0.061s
Count: 1, Failed: 0, Skipped: 0
```
* `mug`
Tested in place.
Low
> New version of csm-testing

- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
The FQDNs that are on NMN or HMN are on a separate load-balancer subnet than the actually NMN/HMN subnets so they need to have a different subdomain:  nmnlb and hmnlb.
This adds those subdomains to the domain filter and the ingressgateway cert.  It also fixes some of the FQDNs specified in customizations for auth, api, hmcollector, etc.
* Resolves CASMINST-3727
* Merge with https://github.com/Cray-HPE/docs-csm/pull/757
* `drax`
Ran the update-customizations.sh and verified that the FQDNs are added/changed correctly.
No risks.  It is broken the way that it is now.
> CASMINST-3727: Fix nmn/hmn subdomains that should be nmnlb/hmnlb

- rpm/cray/csm/sle-15sp2/index.yaml
Update the loftsman RPM for 1.0.10 in the RPM manifest.
* Resolves CASMTRIAGE-2900
This was tested indirectly through CASMINST-3664. There is no way to test the packaging of this rpm that I know of.
Low
> CASMTRIAGE-2900: Add loftsman-1.2.0-1 RPM for CSM 1.0.10

- CHANGELOG.md
- docker/index.yaml
Image created and used only by analytics and not part of any CASM chart.
HAL-2498 opened for any needed work by analytics.
Removing the reference from CASM docker manifest.
* Resolves [CASMPET-5234](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5234)
Low
> CASMPET-5234 1.2 : SECURITY: fix vulnerabilities in pvc-migrator

- manifests/sysmgmt.yaml
Backport CASMINST-3664's addition of loftsman to the csm-config list of RPMs to install from CSM 1.0.10.
* Resolves CASMINST-3811
See https://github.com/Cray-HPE/csm-config/pull/36.
None
> CASMINST-3811: update csm-config to v1.9.14

- rpm/cray/csm/sle-15sp2/index.yaml
This change updates the FAS actions and snapshots CT tests with new expected "error" field placeholders for the API responses. Without this change the FAS tests don't expect the new empty "error" fields in the API responses and flag them as failures.
* Resolves CASMHMS-5317.
This change was tested by deploying the updated FAS CT tests onto Mug running 1.2.0-alpha.43, executing them, and verifying that the previously failing test cases began to pass.
Low risk.
> CASMHMS-5317 Add new error field placeholders to FAS actions and snapshots CT tests

- rpm/cray/csm/sle-15sp2/index.yaml
This change updates the FAS actions and snapshots CT tests with new expected "error" field placeholders for the API responses. Without this change the FAS tests don't expect the new empty "error" fields in the API responses and flag them as failures.
* Resolves CASMHMS-5317.
This change was tested by deploying the updated FAS CT tests onto Mug running 1.2.0-alpha.43, executing them, and verifying that the previously failing test cases began to pass.
Low risk.
> CASMHMS-5317 Add new error field placeholders to FAS actions and snapshots CT tests csm-1.2

- rpm/cray/csm/sle-15sp2/index.yaml
This change removes a duplicated code block from verify_hsm_discovery.py which stops it from running and printing the checks for CabinetPDUControllers twice instead of once. The extra output was causing confusion during installs while troubleshooting discovery failures.
* Resolves CASMHMS-5310.
This change was tested on Mug running csm-1.2.0-alpha.43 by copying the new version of the script onto the NCN, running it, and verifying that the duplicated output from the original script was no longer present in the updated version.
Previous (two identical "CabinetPDUControllers" entries per cabinet):
```
<snip>
River Cabinet Checks
====================
x3000
Nodes: PASS
NodeBMCs: WARNING
- x3000c0s1b0 - Not found in HSM Components; No mgmt port connection; BMC of mgmt node ncn-m001.
RouterBMCs: …
```
> CASMHMS-5310 Remove duplicate CabinetPDUController output from verify_hsm_discovery csm-1.2

- rpm/cray/csm/sle-15sp2/index.yaml
This change removes a duplicated code block from verify_hsm_discovery.py which stops it from running and printing the checks for CabinetPDUControllers twice instead of once. The extra output was causing confusion during installs while troubleshooting discovery failures.
* Resolves CASMHMS-5310.
This change was tested on Mug running csm-1.2.0-alpha.43 by copying the new version of the script onto the NCN, running it, and verifying that the duplicated output from the original script was no longer present in the updated version.
Previous (two identical "CabinetPDUControllers" entries per cabinet):
```
<snip>
River Cabinet Checks
====================
x3000
Nodes: PASS
NodeBMCs: WARNING
- x3000c0s1b0 - Not found in HSM Components; No mgmt port connection; BMC of mgmt node ncn-m001.
RouterBMCs: …
```
> CASMHMS-5310 Remove duplicate CabinetPDUController output from verify_hsm_discovery

- manifests/sysmgmt.yaml
resolves CASMINST-3771 and CASMINST-3772 which updates the version to be pointed to 2.0.1 for HBTD and HMNFD.
> fix hmnfd hbtd version

- CHANGELOG.md
- manifests/platform.yaml
Clean up license header changes.
* Remove {{ /* \<LICENSE\> */ }} that existed prior to license-check fix
* Change {{- \/* ... \*\/ -}} to {{\/\* ... \*\/}} in existing code where this resulted in the next line being commented out (e.g. #apiVersion, #kind)
* Keep the license header added by the license-check (which uses # to start the line)
* Update the chart version to prepare to release the cray-sysmgmt-health chart for this change
* Resolves [CASMINST-3833](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3833)
vshasta
* …
> CASMINST-3833 1.2 : BREAK/FIX: apiVersion not set chart=cray-sysmgmt-health

- CHANGELOG.md
- manifests/platform.yaml
Clean up license header changes.
* Remove {{ /* \<LICENSE\> */ }} that existed prior to license-check fix
* Change {{- \/* ... \*\/ -}} to {{\/\* ... \*\/}} in existing code where this resulted in the next line being commented out (e.g. #apiVersion, #kind)
* Keep the license header added by the license-check (which uses # to start the line)
* Update the chart version to prepare to release the cray-sysmgmt-health chart for this change
* Resolves [CASMINST-3833](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3833)
vshasta
* …
> CASMINST-3833 main : BREAK/FIX: apiVersion not set chart=cray-sysmgmt-health

- docker/index.yaml
- manifests/platform.yaml
Picks up the changes for cray-istio release "CSM 1.2 Release 9" and "CSM 1.2 Release 10".
https://github.com/Cray-HPE/cray-istio/releases/tag/v1.2.9
\https://github.com/Cray-HPE/cray-istio/releases/tag/v1.2.10
This includes the change for:
* CASMPET-5231: Switch to 1.8.6-cray2 images
* CASMINST-3852: Fix hmn istio label to allow for seamless upgrades from older versions of the chart
Note that these charts have the images annotation set so the
images are no longer needed in the docker index.
> CASMPET-5231: Update cray-istio to CSM 1.2 Release 9

- manifests/platform.yaml
This updates cray-opa to 1.7.0, which adds cfs-state-reporter access for storage nodes.
* Resolves [CASMPET-3855](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-3855)
* surtur
Validated that cfs-state-reporter ran successfully after chart was updated
- Was downgrade tested? If not, why? N, change didn't require downgrade testing
> CASMPET-3855 Bump cray-opa to 1.7.0

- manifests/platform.yaml
This release includes the following change:
* CASMINST-3848: Add kiali image to annotation
> CASMINST-3848: Update cray-kiali to 0.2.2

- manifests/nexus.yaml
- manifests/platform.yaml
- upgrade.sh
- vendor/github.hpe.com/hpe/hpc-shastarelm-release/lib/install.sh
- vendor/github.hpe.com/hpe/hpc-shastarelm-release/lib/release.sh
- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
* Adds `nexus-admin-credential` sealed secret to customizations.yaml, which will randomize the Nexus admin password.
* Upgrade script ensures required pre-cached images are pulled on each NCN worker prior to deploying Nexus, otherwise required images might be unavailable causing Nexus not to start.
Changes manually tested on wasp.
> CASMPET-5117: Update to cray-nexus 0.10.0

- manifests/platform.yaml
cray-istio-deploy recently changed to use a new tag for the
proxyv2 image but the reference to the image in the precached
images config wasn't updated. This updates the reference.
> CASMPET-5231: Update cray-precache-images with new proxyv2 image tag

- docker/index.yaml
- manifests/platform.yaml
Cherry-picked the changes from main for:
* https://github.com/Cray-HPE/csm/pull/384
* https://github.com/Cray-HPE/csm/pull/386
* https://github.com/Cray-HPE/csm/pull/380
Includes the changes for:
* CASMPET-5231: Switch to 1.8.6-cray2 images
* CASMINST-3852: Fix hmn istio label to allow for seamless upgrades from older versions of the chart
* CASMINST-3848: Add kiali image to annotation
> Casmpet 5231 1.2

- docker/index.yaml
The following images are part of build/release framework. Therefore we don;t need them in `docker/index.yaml` and, consequently, on Nexus target environments.
* Resolves [CASMPET-5265](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5265)
* Resolves [CASMPET-5267](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5267)
* Jenkins
Should be tested as part of Jenkins build. There's no way to test this on a target environment, because these images are not used on target environments.
In case if there's some undocumented usage of these images, we'll have to rollback this commit.
> Remove rpm-tools and packaging-tools images from manifests and nexus (1.2)

- rpm/cray/csm/sle-15sp2/index.yaml
Removed hardcoded passwords from variables-livecd.yaml, and require user to provide the password for the admin user on the management switches via the SW_ADMIN_PASSWORD environment variable when running the LiveCD preflight checks and ncn-healthcheck test suites.
Removed unused/deprecated Goss tests that depended on switch_aruba.password and switch_mellanox.password Goss variables.
* Resolves …
> (CSM 1.2) CASMPET-3996: New versions of goss-servers and csm-testing

- rpm/cray/csm/sle-15sp2/index.yaml
Removed hardcoded passwords from variables-livecd.yaml, and require user to provide the password for the admin user on the management switches via the SW_ADMIN_PASSWORD environment variable when running the LiveCD preflight checks and ncn-healthcheck test suites.
Removed unused/deprecated Goss tests that depended on switch_aruba.password and switch_mellanox.password Goss variables.
* Resolves …
> (main) CASMPET-3996: New versions of goss-servers and csm-testing

- CHANGELOG.md
- manifests/sysmgmt.yaml
This updates the cfs-operator to pull in a fix for an issue triggering IMS to finish image customization. 
* Resolves CASMTRIAGE-2909
* Hela
The changes were deployed and CFS was successfully run against both live nodes and images.
None
> CASMTRIAGE-2909: Update cfs-operator to pull in fix for image teardown

- manifests/sysmgmt.yaml
Updates the versions of the slurm RPM and munge docker image. The former is to match the slurm version the WLM team is using for this release. The latter is to fix a security issue. No changes to CRUS itself are made.
See the original PR for details:
https://github.com/Cray-HPE/cray-crus/pull/12
> CASMCMS-7785/CASMCMS-7655: cray-crus: Update slurm and munge versions

- rpm/cray/csm/sle-15sp2/index.yaml
Canu version bump
- Adds canu testing feature
- Fixed canu validate BGP for csm 1.2
CASMINST-3485
Drax, Hela, vritualEnv
successfully ran CANU on the systems above.
> 1.2: CASMINST-3485

- rpm/cray/csm/sle-15sp2/index.yaml
Canu version bump
- Adds canu testing feature
- Fixed canu validate BGP for csm 1.2
CASMINST-3485
Drax, Hela, vritualEnv
successfully ran CANU on the systems above.
> Main: CASMINST-3485

- manifests/sysmgmt.yaml
The post-upgrade hook was setting a permission level that didn't work with the ssh key for mountain console connections. The ssh key needs to be private to the current user or the ssh connection will fail. This level of permission works for all files on the /var/log mount, so I just changed the hook to set this same permission on all log files. They will all be read/write accessible for the user the container is started under.
* Resolves [CASMTRIAGE-2915](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-2915)
* Hela
The file permissions had manually been changed to '700' to make the ssh connections work. I restored the permissions to '766' and verified the ssh connections were not working. I manually changed all the file permissions under '/var/log' to '700' and restarted the …
> CASMTRIAGE-2915 - fix console ssh key permissions in helm post-upgrade hook.

- rpm/cray/csm/sle-15sp2/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
Also pulls in fix for CASMINST-3485
> CASMINST-3859: Move cfs-state-reporter check from cmsdev tool into goss NCN healthcheck suite

- docker/index.yaml
- manifests/platform.yaml
added node-exporter-smartmon path for Casmpet 5237
added graftterm image path CASMPET-5269
https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5237
https://github.com/Cray-HPE/cray-sysmgmt-health/pull/52
Cray-HPE/container-images#384
https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5269
https://github.com/Cray-HPE/container-images/pull/383
https://github.com/Cray-HPE/cray-grafterm/pull/2
https://github.com/Cray-HPE/cray-sysmgmt-health/releases/tag/v1.2.19
> Casmpet 5237 and CASMPET-5269 image version change

- assets.sh
NCN images with the implementation of CASMINST-1850 (https://github.com/Cray-HPE/node-image-build/pull/166)
> CASMINST-1850: new NCN images

- rpm/cray/csm/sle-15sp2/index.yaml
When copying the node images csi does not verify the existence of the target directory resulting in a somewhat confusing error message should it not exist.
* Resolves [CASMINST-3866](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3866)
* Merge with 
[https://github.com/Cray-HPE/csm-rpms/pull/225] 
[https://github.com/Cray-HPE/docs-csm/pull/797]
* `hela`
Old behaviour
```
ncn-m001:~ # csi pit populate pitdata "${CSM_RELEASE}/images/kubernetes/" /mnt/pitdata/data/k8s/ -kiK
5.3.18-59.34-default-0.2.43.kernel----------------> /mnt/pitdata/data/k8s/...Failed "open /mnt/pitdata/data/k8s/5.3.18-59.34-default-0.2.43.kernel: no such file or directory"
initrd.img-0.2.43.xz------------------------------> /mnt/pitdata/data/k8s/...Failed "open …
```
> CASMINST-3866 - Check target directory exists before attempting to copy image artifacts

- manifests/sysmgmt.yaml
The spire-server pods need to be able to talk to each other on port
54440. If they can't then the script that setups spire on storage nodes
will fail 2 out of 3 requests.
* Resolves [CASMINST-3916](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3916)
* surtur
Verified that spire-token requests from the spire-registration-server container always succeeded after the upgrade was pushed and that no side effects occurred from the upgrade.
- Was downgrade tested? If not, why? N, not needed.
> CASMINST-3916 Upgrade spire to 2.2.0

- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
Resolves CASMSMF-6685
https://github.hpe.com/hpe/hpc-car-sma-rsyslog/pull/133
updated customizations.yaml can to cmn
> Casmsmf 6685 move rsyslog-aggregator-can services to CMN

- manifests/sysmgmt.yaml
Updates cray-console-node and cray-console-operator to pull in the following fixes:
[CASMTRIAGE-2915](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-2915) Fix console ssh key permissions
[CASMCMS-7786](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7786) CVEs in cray-console-node
[CASM-2794](https://jira-pro.its.hpecorp.net:8443/browse/CASM-2794) / [CASMCMS-7787](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7787) CVE in cray-console-node
> CASMCMS-7786/CASMTRIAGE-2915: Fix console ssh key permissions and CVEs

- rpm/cray/csm/sle-15sp2/index.yaml
Regenerate the the BSS host_records metadata using data from SLS during CSM 1.2 upgrade
https://github.com/Cray-HPE/cray-site-init/pull/117
* Resolves CASMINST-3831
For Testing see: https://github.com/Cray-HPE/cray-site-init/pull/117
Requires additional end to end testing on Baremetal during a CSM 1.2 upgrade. But all of the changes made to a system are contained within the Global boot parameters …
> (CSM 1.2) CASMINST-3831: Bump CSI version

- rpm/cray/csm/sle-15sp2/index.yaml
Regenerate the the BSS host_records metadata using data from SLS during CSM 1.2 upgrade
https://github.com/Cray-HPE/cray-site-init/pull/117
* Resolves CASMINST-3831
For Testing see: https://github.com/Cray-HPE/cray-site-init/pull/117
Requires additional end to end testing on Baremetal during a CSM 1.2 upgrade. But all of the changes made to a system are contained within the Global boot parameters …
> (main) CASMINST-3831: Bump CSI version

- assets.sh
LiveCD:
* CASMINST-3929 (new csi)
* CASMINST-3928 (new canu)
NCNs:
* CASMINST-3928 (new canu)
* CASMINST-3860 (ceph change)
* CASMINST-3799 (ceph change)
> CASMREL-872: NCN and PIT assets for 1.2.0-alpha.57

- manifests/sysmgmt.yaml
The following service charts have been modified to add pod anti-affinity:
BSS
CAPMC
HBTD
HMNFD
SCSD
HMCollector
DOES THIS CHANGE INVOLVE ANY SCHEME CHANGES? N
REMINDER: HAVE YOU INCREMENTED VERSION NUMBERS? E.G., .spec, Chart.yaml Y
REMINDER 2: HAVE YOU UPDATED THE COPYRIGHT PER hpe GUIDELINES: © Copyright 2014-2020 Hewlett Packard Enterprise Development LP ? N/A
* Resolves CASMINST-3910 (BSS)
* Resolves CASMINST-3918 (CAPMC)
* Resolves CASMINST-3920 (HBTD)
* Resolves CASMINST-3921 (HMNFD)
* Resolves CASMINST-3922 (HMCollector)
* Resolves CASMINST-3923 (SCSD)
Tested on:
* wasp
Was a fresh Install tested? N Not needed
Was a Downgrade tested? Y
Was a CT test run? Y
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing? …
> Pod anti-affinity for HMS services

- docker/index.yaml
- manifests/platform.yaml
Use locally built K8S images that match what's being populated in nexus.
- Fixes https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3799
Brings alignment between K8S images in nexus and what's being used at bootstrap time.
```
ncn-m003:/etc/cray/kubernetes # ls -l join*
-rwx------ 1 root root 318 Jan 26 21:37 join.sh
```
```
ncn-m002:/etc/cray/kubernetes # ls -l join*
-rwx------ 1 root root 177 Jan 26 21:37 join-command
-rwx------ 1 root root 276 Jan 26 21:37 join-command-control-plane
```
```
ncn-m002:~ # kubectl get pods --all-namespaces -o jsonpath="{..image}" |tr -s '[[:space:]]' '\n' |sort |uniq
artifactory.algol60.net/csm-docker/stable/docker.io/nfvpe/multus:v3.7
artifactory.algol60.net/csm-docker/stable/docker.io/weaveworks/weave-kube:2.8.1 …
```
> Load images baked into the NCN images into distribution

- CHANGELOG.md
- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
Adds a parameter to CFS to allow sessions to be created with arbitrary arguments passed to Ansible
* Resolves CASMCMS-7784
* Wasp
Ran CFS sessions without passthrough parameters, and with different combinations of parameters.
None
> CASMCMS-7784: Update CFS to add Ansible passthrough

- assets.sh
Kubernetes node image comes pre-populated with Kubernetes (and some supplementary) container images. Sometimes during install/upgrade, these images need to be re-downloaded from Nexus. For this purpose, Nexus should also be populated with the same versions of images. This change adds a validation step to assets.sh script, which ensures that same version are being shipped with node image and installed in Nexus.
This change is dependent on https://github.com/Cray-HPE/node-image-build/pull/155. Node image needs to expose component versions. Change is backwards compatible: if https://github.com/Cray-HPE/node-image-build/pull/155 is not yet merged, validation in `assets.sh` script is not performed. However, with current state of manifest and latest node image, validation will fail (as manifest …
> CASMINST-3803 Validate node image component versions against Nexus (1.2)

- assets.sh
This is a backport of https://github.com/Cray-HPE/csm/pull/369 into `main`.
Kubernetes node image comes pre-populated with Kubernetes (and some supplementary) container images. Sometimes during install/upgrade, these images need to be re-downloaded from Nexus. For this purpose, Nexus should also be populated with the same versions of images. This change adds a validation step to assets.sh script, which ensures that same version are being shipped with node image and installed in Nexus.
This change is dependent on https://github.com/Cray-HPE/node-image-build/pull/155. Node image needs to expose component versions. Change is backwards compatible: if https://github.com/Cray-HPE/node-image-build/pull/155 is not yet merged, validation in `assets.sh` script is not performed. However, with …
> CASMINST-3803 Validate node image component versions against Nexus (main)

- assets.sh
Bump kernel to 5.3.18-150300.59.43.1 for CVE.
https://www.suse.com/security/cve/CVE-2022-0185.html
PIT & NCNs
* MTL-1606
> MTL-1606: bump kernel version for CVE-2022-0185

- CHANGELOG.md
- manifests/sysmgmt.yaml
Move cray-uas-mgr to 1.18.0 to resolve CAST-27468.
This change is backward compatible.
* Resolves [CASMUSER-2938](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-2938)
* Relates to [CAST-27468](https://jira-pro.its.hpecorp.net:8443/browse/CAST-27468)
Deployed this version of the chart to Virtual Shasta and verified that it solves the problem described in CAST-27468.
- Was downgrade tested? If not, why? y
- Were new tests (or test issues/Jiras) created for this change? n
There are no known risks or issues known to be associated with this change.
- [ N/A ] Copyrights updated …
> CASMUSER-2938 move cray-uas-mgr to 1.18.0: CAST-27468

- manifests/sysmgmt.yaml
Remove the 'polkit' package from the published image. This package is installed as part of the 'vi' zypper install but is not required by any of the basic functions of the services. Furthermore it frequently has CVE vulnerabilities that require patching. In an effort to improve the long term security of this service, this package is being deliberately removed from the image. As it is not required, it has no impact on the running of this service.
Code PR:
https://github.com/Cray-HPE/console-node/pull/37
* Resolves [CASMCMS-7793](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7793)
* Mug
I did a Helm install/upgrade of the new image on Mug. When the new version was up and running I confirmed the basic operations of the service (interactive console access and logging) was working …
> CASMCMS-7793 - remove polkit from console-node image.

- CHANGELOG.md
- manifests/sysmgmt.yaml
Updates the cfs-api chart to add pod antiaffinity
* Resolves CASMINST-3913
* Hela
- Scaled multiple pods and confirmed they were on different nodes
None
> CASMINST-3913: Update cfs-api to add pod antiaffinity

- manifests/core-services.yaml
Update HSM manifest version for CASMHMS-5348 - Fixed NULL value issue with POST /v2/Inventory/EthernetInterfaces
* Resolves [CASMHMS-5348](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5348)
For testing see https://github.com/Cray-HPE/hms-smd/pull/67
none
> Update HSM manifest version for CASMHMS-5348

- manifests/core-services.yaml
Update HSM manifest version for CASMHMS-5348 - Fixed NULL value issue with POST /v2/Inventory/EthernetInterfaces
* Resolves [CASMHMS-5348](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5348)
For testing see https://github.com/Cray-HPE/hms-smd/pull/67
none
> Update HSM manifest version for CASMHMS-5348 main

- manifests/platform.yaml
This picks up keycloak-installer release v1.2.9:
https://github.com/Cray-HPE/keycloak-installer/releases/tag/v1.2.9
This includes the following change:
* CASMPET-5260: Update constraints to pick up security fixes
(cherry picked from commit 9d6aeffce294faef25ccb0649f3033840405131d)
> CASMPET-5260: Pick up keycloak-installer release v1.2.9

- CHANGELOG.md
- manifests/sysmgmt.yaml
Updates the cfs-api to add validation to several api fields to prevent code injection. This also removes the deprecated v1 api to avoid any security vulnerabilities in that api.
* Resolves CASMCMS-7806
* Resolves CASMCMS-7287
* Hela
Tested several valid and invalid configurations, as well as session creation to validate code affected by the v1 api removal.
None
> CASMCMS-7806: Update cfs-api for api validation

- CHANGELOG.md
- manifests/platform.yaml
- manifests/storage.yaml
- upgrade.sh
The current ceph-csi charts do not allow for a modification to the rolling update
strategy.  This causes upgrades on 3 node systems to not complete as the deployment
assumes the default of allowing 25% unavailability which will only work with a min of 4
nodes.
This also requires an outage of the provisioners to remove the deployments and move them
into separate namespaces.  This means that we will not be able to provision or re-map
PVCs until the upgrade is complete.  All previously created/mapped PVCs will function normally
during the provisioner outage.
* Resolves CASMINST-3857
* Documentation changes required in CASMINST-3857
* this change needs tested on metal.  all other components tested on vshasta …
>    CASMINST-3857 - upgrade to ceph csi 3.5.1 to support rolling ugprades

- CHANGELOG.md
- manifests/platform.yaml
- manifests/storage.yaml
The current ceph-csi charts do not allow for a modification to the rolling update
strategy.  This causes upgrades on 3 node systems to not complete as the deployment
assumes the default of allowing 25% unavailability which will only work with a min of 4
nodes.
* Resolves CASMINST-3857
* Documentation changes required in CASMINST-3857
* this change needs tested on metal.  all other components tested on vshasta
- Was upgrade tested? If not, why? 
- Was downgrade tested? If not, why? 
> CASMINST-3857 - upgrade to ceph csi 3.5.1 to support rolling ugprades

- hack/gen-rpm-index.sh
- rpm/cray/csm/sle-15sp2/index.yaml
Removed references to car.dev.cray.com artifactory RPM repositories from CSM scripts and Nexus manifest.
> remove references to car.dev.cray.com

- manifests/platform.yaml
Use new cray-opa chart to upgrade XDS v2 to v3 API in EnvoyFilter in preparation for istio upgrade.
* Resolves [CASMPET-5296]
Deployed the new cray-opa chart with upgraded EnvoyFilter XDS, and verified that we can still call capmc api get_node_rules with the new EnvoyFilter.
Low. The upgrade simply replaces v2 with equivalent v3 phrases with no functionality changes, and we can also easily back off the changes if unexpected things happen.
> CASMPET-5296: upgrade XDS v2 to v3 API in EnvoyFilter

- manifests/platform.yaml
This release[0] contains the following fix:
* CASMPET-5182: sonar-jobs-watcher restarts when containerd restarted
[0] https://github.com/Cray-HPE/cray-drydock/releases/tag/v1.2.4
> CASMPET-5182: cray-drydock release v1.2.4

- CHANGELOG.md
- docker/index.yaml
- docker/transform.sh
Update the Broker UAI to a version that works. The security fix (removing cpio from the image) that produced v1.2.3 of the Broker UAI image caused openssh to be uninstalled because of a dependency in the build.  The result was a Broker UAI with no SSH server in it.  Version 1.2.4 restored the SSH server.
This change is a backward compatible bugfix.
* Resolves [CASMUSER-2949](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-2949)
* Resolves [CAST-28881](https://jira-pro.its.hpecorp.net:8443/browse/CAST-28881)
Deployed and used the Version 1.2.4 Broker UAI image on vshasta and verified that it functioned as expected.
- Were continuous integration tests run? If not, …
> CASMUSER-2949 Update Broker UAI Image to 1.2.4 (CAST-28881)

- rpm/cray/csm/sle-15sp2/index.yaml
This change updates the HSM CT tests to allow custom component roles and subroles. Previously these were expected to be one of the pre-defined roles but now we've added support and documentation for setting custom roles. Sites using custom roles or subroles (as seen on Pawsey, for example) will encounter HMS validation test failures without this update.
* Resolves [CASMHMS-5365](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5365).
This change was tested on Mug by deploying the updated tests, executing them after setting a custom node SubRole in HSM, and verifying that the previously failing test cases began to pass.
Very low risk, great benefit to stop false test failures from being reported.
> CASMHMS-5365 Update HSM CT tests for custom component roles and subroles.

- rpm/cray/csm/sle-15sp2/index.yaml
Update hpe-csm-scripts repo version for CASMHMS-5346 - Change lock_management_nodes.py to lock nodeBMCs of management nodes
* Resolves [CASMHMS-5346](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5346)
For testing, see https://github.com/Cray-HPE/hpe-csm-scripts/pull/9
none
> Update hpe-csm-scripts repo version

- rpm/cray/csm/sle-15sp2/index.yaml
Changed default BGP CMN ASN to 65532, and BGP NMN ASN to 65531. The CMN ASN was perviously set to a value that was reserved for documentation usage.
https://github.com/Cray-HPE/cray-site-init/pull/120
* Resolves [CASMINST-3804](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3804)
For testing see: https://github.com/Cray-HPE/cray-site-init/pull/120
_Are there known …
> CASMINST-3804: Update cray-site-init RPM to 1.14.9.

- assets.sh
MTL-1607: SECURITY: CVE-2022-0185: Linux kernel buffer overflow/container escape
* Resolves [MTL-1607](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1607)
> MTL-1607: New livecd and ncn images to fix CVE-2022-0185 (release/1.0)

- assets.sh
MTL-1604: CSM 1.0.x: CVE-2021-4034: pwnkit: Local Privilege Escalation in polkit's pkexec
* Resolves [MTL-1604](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1604)
> MTL-1604: new assets providing updated polkit for CVE-2021-4034 fix

- assets.sh
- rpm/cray/csm/sle-15sp3/index.yaml
- Fixes CASMINST-3789 MTL-1613
- Relates to CASMTRIAGE-2793
This reverts commit 5303a8bea5fb7160936043b17da2171e448eeada, ceasing DHCPing on every NIC. Instead the xname issue from CASMINST-3789 by removing an ambiguous variable in the iPXE script.
Prior to CASMTRIAGE-2793 the netX variable was reliably relaying the current, active DHCP interface. This behavior broke after CASMTRIAGE-2793, the netX variable actually refers to the current open interface which is _all_ of them. Thus we have to specifically select the interface that truly succeed DHCP, instead of relying on the short-cut variable.
This change removes the null setting, to prevent retries from erasing the xname as well.
> redbull 
- All NCNs reported xnames in their `/proc/cmdline` files.
What is less …
> MTL-1613 new metal ipxe

- assets.sh
This overrides https://github.com/Cray-HPE/csm/pull/467/, which introduced LiveCD build which fialed and was never uploaded.
* Resolves [MTL-1613](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1613)
> MTL-1613: install metal-ipxe-2.1.2-1 into LiveCD

- manifests/sysmgmt.yaml
This rebuilds the cray-crus service to resolve vulnerabilities in the base image at to use a fixed version of munge-munge in wlm-slurm.
The fixed version of munge-munge is not an official release version, but that will not be available until early March according to David Gloe.  In this fix I have changed the version of munge-munge used to point to a patched (but pre-release) version.  See the code PR for details on the munge-munge version:
https://github.com/Cray-HPE/cray-crus/pull/14
See details on munge-munge patch in:
https://jira-pro.its.hpecorp.net:8443/browse/PE-39542
* Resolves [CASMCMS-7814](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7814)
* Resolves [CASMCMS-7818](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7818)
Rebuilt the …
> CASMCMS-7814 - resolve CVE vulnerabilities in cray-crus.

- CHANGELOG.md
- docker/index.yaml
- manifests/platform.yaml
CASMPET-5301: Updating shared-kafka chart version and kafka tag version
Updated shared-kafka chart version to 0.7.0 under manifests/platform.yaml
Updated new docker tag under docker/index.yaml
Related PR would be from cray-shared-kafka. Soon it will be up.
CASMPET-5301: https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5301
Once CSM 1.0.11 build is out, full testing needs to be done by the appropriate stake holders
NA
> CASMPET-5301: Updating shared-kafka chart version and kafka tag version

- docker/index.yaml
This addresses multiple Ceph CVEs and also utilizes a supported
base image of centos:stream8.  The older image were centos:8 based which
is EOL.
* Resolves CASMPET-5331
* Hela
* craystack
Ran a fresh install on craystack utilizing on the v15.2.15 container image from algol60.  
Upgraded hela utilizing the v15.2.15 container image from algol60
This is an in-family upgrade.
> CASMPET-5331 - add ceph container image v15.2.15

- manifests/platform.yaml
- manifests/storage.yaml
Remove ceph-csi 3.4.0 images from pre-cache since we will not be using them
* Resolves CASMINST-4029
> CASMINST-4029 - Remove ceph csi 3.4.0 from pre-cached images

- rpm/cray/csm/sle-15sp2/index.yaml
This adds tests that are run on workers and storage nodes after the nodes have been deployed in fresh install (csi pit validate --ceph and csi pit validate --k8s) and after they are upgraded.
* Resolves CASMINST-4001
* Related to CASMINST-3828
* `fanta`
Ran `csi pit validate --ceph` and `csi pit validate --k8s` to test fresh install
Ran `ncn-upgrade-tests-storage.yaml` and `ncn-upgrade-tests-storage.yaml` to test upgrades.
Verified that the new test shows up in the output and passes.
> CASMINST-4001: Update goss-server package to 1.11.0

- rpm/cray/csm/sle-15sp2/index.yaml
During the csm 1.2 upgrade, cronjobs may get re-created because of too many failed attempts to start.
Postgresql cronjob based backup are expected to exist 24hr after the cluster is created. This window needs to be based on when the cronjobs were created (or re-created in the case of the upgrade) and not when the cluster was created.
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix? Yes
* Resolves [CASMINST-4030](issue link)
* Change will also be needed in `master`
vshasta
drax 
Verified on drax that the script passes as expected.  Some of the postgresql cronjobs had been re-created as part of the upgrade (but not all)
```
ncn-m001:~ # …
```
> CASMINST-4030 1.2 : TESTS - Kubernetes Postgresql Check that Automated Backup are Working

- manifests/sysmgmt.yaml
The gitea initialization job was using an old version of keycloak that contained CVE vulnerabilities. This updates to use the latest version of cray-keycloak-setup.
Code PR:
https://github.com/Cray-HPE/gitea/pull/14
* Resolves [CASMCMS-7824](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7824)
* Resolves [CASMCMS-7825](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7825)
* `Mug`
Installed the new version of gitea chart on Mug through a helm upgrade. We watched the initialization job run and verified it was able to connect to keycloak and check / update the required users in keycloak. As this image is only used during an initialization job, a downgrade test was not required.
- …
> CASMCSM-7825/7824 - update gitea to use new keycloak version.

- manifests/sysmgmt.yaml
Update the database image from redis:5.0-alpine3.12 to redis:5.0-alpine. This less specific tag allows use of more recent alpine base images that are still being patched for security vulnerabilities. The current version uses alpine:3.15 and has the security issues resolved.
Code PRs:
https://github.com/Cray-HPE/bos/pull/30
https://github.com/Cray-HPE/config-framework-service/pull/36
* Resolves [CASMCMS-7823](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7823)
* `Mug`
I verified the new image is clean using the SNYK scanner. After building a new version of cray-cfs-api and cray-bos using the new database image, I updated the deployment on Mug, verified the db was working correctly, then rolled back to the original version …
> CASMCMS-7823 - update bos and cfs-api to remediate redis CVE vulnerability.

- rpm/cray/csm/sle-15sp2/index.yaml
Need more than ten seconds for this test -- bumped to 60 seconds to give plenty of headroom.
* Resolves [CASMINST-4055](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4055)
```
ncn-w001:~ # export GOSS_BASE=/opt/cray/tests/install/ncn; goss -g /opt/cray/tests/install/ncn/tests/goss-k8s-console-services.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate
.
Total Duration: 6.203s
Count: 1, Failed: 0, Skipped: 0
```
* `hela`
Changed the timeout, ran fine (but finished in 6 seconds on hela)
Low
> New csm-testing for goss console pods test timeout fix

- manifests/platform.yaml
This adds a wait-for job that will pause loftsman until all the cray-precache-images are running.
* Resolves [CASMINST-4007](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4007) 
Validated that images were cached and that the wait-for pod waited until all pods were up and caused the helm install pause until they were.
Due to how the pre-cache image pod is run, this doesn't wait for the images to be fully cached. It only waits until the cache pods are up.
> CASMINST-4007 Fix pre-cache upgrade issue

- rpm/cray/csm/sle-15sp2/index.yaml
The introduction of the `cray-oauth2-proxies-customer-high-speed-ingress` causes the "LoadBalancer Services Have External IP" test to fail if CHN isn't configured as the LoadBalancer will always be in a `<pending>` state in this case.
Filtered this LoadBalancer out of the check similar to how `istio-ingressgateway-chn` is already excluded if CHN isn't configured.
Also fixed an issue where an update to the MetalLB chart meant that the test script was looking at the wrong ConfigMap.
* Resolves [CASMINST-3992](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3992)
* `starlord` - CHN is not configured, test was failing now passes.
*  `hela` - CHN is configured, test should and does pass.
Installed new csm-testing rpm on all NCNs and ran the `ncn-kubernetes-checks` test suite.
> CASMINST-3992 - ncn-kubernetes-check failed for LoadBalancer Services Have External IP testcase

- manifests/platform.yaml
This change allows us to choose whether to use required or preferred anti affinity. Preferred is needed on vshasta. On systems with 4 or more worker nodes, required should be used.
* Resolves [CASMINST-4007](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4007) 
Validated anti affinity rules worked with both toggles and that they functioned correctly.
- Were continuous integration tests run? Y
- Was upgrade tested? Y
- Was downgrade tested? Y
> CASMINST-4007 Add anti-affinity toggle to cray-opa

- rpm/cray/csm/sle-15sp2/index.yaml
This adds the capability to specify edge routers in switch_metadata.csv to get them added to SLS with xnames and get them added as CHN peers to the metallb config map.
See https://github.com/Cray-HPE/cray-site-init/pull/121
* Resolves CASMNET-1157
I have tested this by running `csi config init` with hela seed files using various combinations of inputs.
* With two edge switches specified and bgp-peer-types set to [spine, edge]
* Without edge switches specified in switch_metadata.csv
* With two edge switches specified but bgp-peer-types set to [spine]
* With no edge switches specified but bgp-peer-types set to [spine, edge]
* With only one edge switch specified
* With and without CHN defined in CSI inputs
- [N/A] Version number(s) incremented, if applicable
- [N/A] [HPC Product …
> CASMNET-1157: Add edge switches to MetalLB config for CHN

- manifests/sysmgmt.yaml
When CASMCMS-7825/7824 was checked in I missed updating this one image tag override value in the csm manifest file.  This completes getting gitea to point to the correct (updated) version of cray-keycloak-setup.
* Resolves [CASMINST-4074](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4074)
None - update missed version tag in csm manifest update.
Very low risk - just fixing mistake in previous update.
> CASMINST-4074 - update keycloak image tag to resolve CVE.

- rpm/cray/csm/sle-15sp2/index.yaml
This change updates the HSM /State/Components tests for the new expected Management roles of BMCs. A recent change was made for [CASMHMS-5346](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5346) to set the Management role in HSM for BMCs of NCNs for the purposes of locking. The test was not updated in accordance with that change, so adding the new expected roles to the test schema now.
* Resolves CASMINST-4069.
This change was tested on Surtur by deploying the updated version of the test, executing it with Management BMC roles set in HSM, and verifying that the previously failing test cases began to pass.
Low risk, fixes a problem that will cause HMS test failures.
> CASMINST-4069 Update HSM components test for new expected BMC management roles csm-1.2

- rpm/cray/csm/sle-15sp2/index.yaml
This change updates the HSM /State/Components tests for the new expected Management roles of BMCs. A recent change was made for [CASMHMS-5346](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5346) to set the Management role in HSM for BMCs of NCNs for the purposes of locking. The test was not updated in accordance with that change, so adding the new expected roles to the test schema now.
* Resolves CASMINST-4069.
This change was tested on Surtur by deploying the updated version of the test, executing it with Management BMC roles set in HSM, and verifying that the previously failing test cases began to pass.
Low risk, fixes a problem that will cause HMS test failures.
> CASMINST-4069 Update HSM components test for new expected BMC management roles

- manifests/sysmgmt.yaml
The munge-munge image used in cray-crus was provided by PE, however there were CVE vulnerabilities and they were not creating a new stable version until the next complete release of their software. Since munge is open source, we started with their Dockerfile and used it to build our own version of the image with the security patches supplied.
PR to build munge-munge image:
https://github.com/Cray-HPE/container-images/pull/393
Code PR's:
https://github.com/Cray-HPE/cray-crus/pull/15
* Resolves [CASMCMS-7831](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7831)
After all needed images were built, I used snyk to locally verify that all security vulnerabilities are resolved.
Due to the need for a 1.2 system with a complete PE install and available compute …
> CASMCMS-7831 - update cray-crus for CVE remediations.

- CHANGELOG.md
- manifests/platform.yaml
Use the updated image path for cray-externaldns to be consistent with other images.
* Resolves [CASMINST-4085]
* `mug`
Upgraded the external-dns chart and restarted cray-dns-powerdns and cray-powerdns-manager deployments, and verified that no errors in pod logs and powerdns records are correct:
ncn-m001:~/bquan # kubectl -n services exec -it cray-dns-powerdns-84dd665566-qd8r8 -- sh -c 'pdnsutil list-zone nmn.mug.dev.cray.com' | head
Defaulting container name to cray-dns-powerdns.
Use 'kubectl describe pod/cray-dns-powerdns-84dd665566-qd8r8 -n services' to see all of the containers in this pod.
$ORIGIN .
kubeapi-vip.nmn.mug.dev.cray.com 3600 IN A 10.252.1.2
ncn-m001.nmn.mug.dev.cray.com 3600 IN CNAME x3000c0s1b0n0.nmn.mug.dev.cray.com. …
> CASMINST-4085: use updated image path for cray-externaldns

- CHANGELOG.md
- manifests/platform.yaml
Change the image path of externaldns to the one consistent with other image paths.
* Resolves [CASMINST-4085]
* `mug`
Upgraded the external-dns chart and restarted cray-dns-powerdns and cray-powerdns-manager deployments, and verified that no errors in pod logs and powerdns records are correct:
ncn-m001:~/bquan # kubectl -n services exec -it cray-dns-powerdns-84dd665566-qd8r8 -- sh -c 'pdnsutil list-zone nmn.mug.dev.cray.com' | head
Defaulting container name to cray-dns-powerdns.
Use 'kubectl describe pod/cray-dns-powerdns-84dd665566-qd8r8 -n services' to see all of the containers in this pod.
$ORIGIN .
kubeapi-vip.nmn.mug.dev.cray.com 3600 IN A 10.252.1.2
ncn-m001.nmn.mug.dev.cray.com 3600 IN CNAME x3000c0s1b0n0.nmn.mug.dev.cray.com. …
> CASMINST-4085: update cray-externaldns to use the updated image path

- CHANGELOG.md
- manifests/platform.yaml
Rebuilding the cray-node-discovery image to take advantage of container-image for alpine 3.14
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_Yes
* Resolves [CASMINST-4075](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4075)
* Change will also be needed in master
vshasta
* Daemonset pods restarted (one per worker node)
```
$ kubectl get pods -A -o wide | grep node-disc
services            cray-node-discovery-8xslf                                         1/1     Running     0          8m22s   10.1.0.7     ncn-w002-afbdd1f9   <none>           <none>
services            cray-node-discovery-gslgw …
```
> CASMINST-4075 1.2 : High/Critical CVE Container use in platform->csm-algol60/cray-node-discovery:1.2.0

- CHANGELOG.md
- manifests/platform.yaml
Rebuilding the cray-node-discovery image to take advantage of container-image for alpine 3.14
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_Yes
* Resolves [CASMINST-4075](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4075)
* Change will also be needed in release/1.2
vshasta
* Daemonset pods restarted (one per worker node)
```
$ kubectl get pods -A -o wide | grep node-disc
services            cray-node-discovery-8xslf                                         1/1     Running     0          8m22s   10.1.0.7     ncn-w002-afbdd1f9   <none>           <none>
services            cray-node-discovery-gslgw …
```
> CASMINST-4075 main : High/Critical CVE Container use in platform->csm-algol60/cray-node-discovery:1.2.0

- CHANGELOG.md
- manifests/platform.yaml
Updating image in oauth2-proxy to address High/Critical CVE in container
* Resolves [CASMINST-4080](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4080)
* Change will also be needed in [main](https://github.com/Cray-HPE/csm/pull/518)
vshasta
Deployed this new version and made sure I could get to grafana through oauth2-proxy.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? NA
- Were continuous integration tests run? If not, why? NA
- Were new tests (or test issues/Jiras) created for this change? NA
Low
> CASMINST-4080: release/1.2 High/Critical CVE Container use in platform->csm-algol60/cray-oauth2-proxies:0.1.1

- CHANGELOG.md
- manifests/platform.yaml
Updating image in oauth2-proxy to address High/Critical CVE in container
* Resolves [CASMINST-4080](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4080)
* Change will also be needed in [release/1.2](https://github.com/Cray-HPE/csm/pull/519)
vshasta
Deployed this new version and made sure I could get to grafana through oauth2-proxy.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? NA
- Were continuous integration tests run? If not, why? NA
- Were new tests (or test issues/Jiras) created for this change? NA
Low
> CASMINST-4080: main High/Critical CVE Container use in platform->csm-algol60/cray-oauth2-proxies:0.1.1

- manifests/platform.yaml
Update to the latest OPA gatekeeper chart to resolve CVEs:
https://github.com/Cray-HPE/cray-opa-gatekeeper/pull/11
> CASMINST-4081 Update Gatekeeper's curlimage.

- docker/index.yaml
- manifests/sysmgmt.yaml
Use cray-spire chart 2.3.1 to pull in the latest pgbouncer image master-21 for CVE remediation.
* Resolves [CASMINST-4082]
* `mug`
Deployed the new spire chart on mug, and verified that the latest pgbouncer image was pulled. The pod log shows no error after running for 15 minutes.
Low. It's a minor patch version upgrade.
> CASMINST-4082: use cray-spire version 2.3.1

- rpm/cray/csm/sle-15sp2/index.yaml
This set of changes fixes both CASMINST-4089 and CASMNET-1173
CASMINST-4089 - A valid configuration can have either CAN, CHN, or both. This fixes the case where setting the host records with either CAN or CHN are not specified caused a failure. I also added unit tests for the use cases of: only CAN is defined, only CHN is defined, neither CAN nor CHN are defined. The last case is expected to cause a failure and the unit test checks for that.
CASMNET-1173 - The prefix-length for CAN and CMN interaces in the ipam settings of BSS should come from the CAN/CMN supernet and not from the bootstrap subnet. This fixes those settings. It also fixed the unit tests to ensure that they are set appropriately. This was not caught previously in unit tests because the SLS test data was not as it would be …
> CASMINST-4089-CASMINST-1173:  Update cray-site-init RPM to 1.16.1

- manifests/platform.yaml
This updates the base image that trusted cert operator uses in order to resolve a number of CVEs.
* Resolves [CASMPET-5268](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5268)
Validated snyk scans passed and that the updated image and helm chart worked correctly in vshasta.
- Was upgrade tested? If not, why? Y 
> CASMPET-5268 Update trustedcerts-operator to 0.5.0

- manifests/platform.yaml
This updates the base image that trusted cert operator uses in order to resolve a number of CVEs.
* Resolves [CASMPET-5268](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5268)
Validated snyk scans passed and that the updated image and helm chart worked correctly in vshasta.
- Was upgrade tested? If not, why? Y 
> CASMPET-5268 Bump trustedcerts-operator to 0.5.0

- assets.sh
`zsh` is popular and people seem to like to switch to it.  `chsh`
lets you change your shell even if the desired shell is not
installed.
Install `zsh` to avoid getting locked out of nodes.
* Resolves CASMTRIAGE-3036
Tested on redbull
> CASMTRIAGE-3036: Add zsh to NCNs & LiveCD

- docker/index.yaml
Removed vulnerable container image not used in distribution.
* Resolves [CASMINST-4084](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4084)
* Change will also be needed in `main` (https://github.com/Cray-HPE/csm/pull/534)
Not tested. Teams were polled via Slack and no one claimed a need to ship this image. CSM Docs was additionally searched with no reference indicated. Git blame also suggested the image may not be needed. 
Risk if image is actually used, but not documented.
> Remove container image (openapi-generator-cli:v5.1.0)

- rpm/cray/csm/sle-15sp2/index.yaml
- Fixes #CASMINST-4116
The HPE master and storage nodes have two NICs with two ports each.  In 1.0, these devices were named mgmt0, mgmt1, mgmt2, and mgmt3 and we would specify on the kernel cmdline which of those two devices made up bond0.  In 1.2, the device naming has changes to mgmt0, mgmt1, sun0, and sun1 and we presume that bond0 is always mgmt0 and mgmt1.   However the device that is named mgmt1 is different in 1.2 than it was in 1.0.   Because of all of this we need to make sure that `csi upgrade metadata` changes the ifnames to be what is expected for 1.2.    Master and storage nodes with only 1 NIC (on GB and Intel) can be left as they are.
I added several unit tests to check both 1 NIC and 2 NIC cases for Master and Storage as well as for the Worker nodes. …
> CASMINST-4116: Update cray-site-init RPM to 1.16.2

- rpm/cray/csm/sle-15sp2/index.yaml
A change was put in about a week ago to add `set -e` to the top of the livecd-preflight-check script.  When `/usr/bin/goss validate -f json` is run in that script to execute all of the goss tests in that suite, it will return non-zero if any of the tests fail.  The `set -e` causes the script to then stop execution immediately without giving any output indicating which tests failed.   We need to run `/usr/bin/goss validate -f json` without the `set -e`.
* Resolves CASMINST-4142
* `wasp`
I ran `/opt/cray/tests/install/livecd/automated/livecd-preflight-checks` on wasp with this fix and I was able to see the test results include the one test that was failing.
> CASMINST-4142:  Update goss-servers and csm-testing RPMs to 1.12.10

- docker/index.yaml
- manifests/platform.yaml
This updates the operator to spin up kafka using the noJSM-chainsaw-kafka images that resolve a number of log4j CVEs. 
The cray-shared-kafka chart is being reverted so that it doesn't override the image set via the operator.
* Resolves [CASMPET-5363](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5363) 
Validated the operator came up properly and that all the kafka pods were recreated with the new image.
> CASMPET-5363 Update kafka charts

- manifests/platform.yaml
Update the strimzi operator to 0.27.1. This is the last version that supports Kafka 2.X
* Resolves [CASMPET-5362](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5362)
Validated the operator worked and that kafka clusters came up properly.
- Were continuous integration tests run? If not, why?  Y
> CASMPET-5362 Bump cray-kafka-operator to 1.1.0

- rpm/cray/csm/sle-15sp2/index.yaml
Running livecd-preflight-check always ended with the terminal session messed up requiring a reset.
I isolated the problem down to the goss-dhcp-router-ip-distinct test.   This test runs an `nmap` command for all of each of 5 interfaces specified in the variables file.  The problem happens when these tests run in parallel.
To fix this, I changed the test so it passes ALL interface name as a list into the test script and then the script does the work of running through each interface serially.   This avoids goss running each individual interface test in parallel.
* Resolves CASMINST-1673
* `wasp`
I ran the goss-dhcp-router-ip-distinct individually and ran the livecd-preflight-check suite.   I ran both cases such that the test succeeds and I also caused a failure condition to see the results …
> CASMINST-1673:  Update goss-servers and csm-testing RPMs to 1.12.11

- manifests/sysmgmt.yaml
We needed to update the version of alpine that cf-gitea-import was using to resolve CVE vulnerabilities. This rebuild pulls in the new base image.
Code PR's:
https://github.com/Cray-HPE/csm-config/pull/45
https://github.com/Cray-HPE/cf-gitea-import/pull/26
* Resolves [CASMINST-4145](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4145)
* `Drax`
After the new image was built, I used snyk to insure the updated image was free of vulnerabilities. We installed the new image on Drax and insured that the gitea import worked correctly. …
> CASMINST-4145 - update csm-config to resolve CVE vulnerabilities.

- install.sh
Add step to ensure etcd cluster have three healthy members before proceeding with install
* Resolves [CASMINST-4136](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4136)
Tested script changes:
```
ncn-m002:~/bklein # ./foo.sh
validated etcd cluster: cray-bos-etcd has three running members...
validated etcd cluster: cray-bss-etcd has three running members...
validated etcd cluster: cray-crus-etcd has three running members...
validated etcd cluster: cray-externaldns-etcd has three running members...
validated etcd cluster: cray-fas-etcd has three running members...
validated etcd cluster: cray-hbtd-etcd has three running members...
validated etcd cluster: cray-hmnfd-etcd has three running members...
validated etcd cluster: cray-reds-etcd has three running members...
validated etcd …
```
> Add check during install.sh to ensure etcd clusters have three members

- docker/index.yaml
- manifests/platform.yaml
Upgrade the golang base os version in the cray-grafterm image to fix the vulnerability issue.
To resolve this we are using the golang:1.17.3-alpine3.15 version for the grafterm.
https://github.com/Cray-HPE/container-images/pull/406 (merged)
https://github.com/Cray-HPE/cray-grafterm/pull/3 (merged)
https://github.com/Cray-HPE/cray-sysmgmt-health/pull/56 (merged)
* Resolves 
[CASMINST-4144](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4144)
* Future work required:
None
* Documentation changes required
None
* Merge with/before/after
None
Done
gamora
Able to get the Grafterm graphs
None
> Bump the cray-grafterm image as part of CASMINST-4144

- docker/index.yaml
Remove vulnerable and unclaimed centos:7 image. 
Image is not present on main.
* Resolves [CASMINST-4169](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4169)
> Remove centos:7 from docker index

- manifests/platform.yaml
- manifests/sysmgmt.yaml
Disabled exposing spire-jwks externally and switched the jwks endpoint opa uses to the internal URL.
* Resolves [CASMINST-3979](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3979) 
Validated that spire tokens kept working after the upgrade and failed if the spire-jwks service was scaled down to 0.
If cray-opa gets downgraded to 1.9.0, spire also needs to be downgraded to 2.3.1 in order to create the spire-jwks VirtualService.
> CASMINST-3979 Disable external spire-jwks access

- manifests/core-services.yaml
- manifests/platform.yaml
target down alert in prometheus for the DNS unbound exporter
* Resolves 
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-117
https://github.com/Cray-HPE/cray-dns-unbound/pull/46
Tested on Mug
> Casmmon 117 target down alert in prometheus for the DNS unbound exporter

- hack/load-container-image.sh
Now that podman config is configured for overlay out of the box in 1.2, the load-container-images.sh script needs to change to not specify the overlay driver.
* Resolves [CASMTRIAGE-3092](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3092)
* `surtur`
Ran the prerequisites.sh script with this change, and it worked.
Low
> Change nexus load script to not specify overlay now that podman config does

- rpm/cray/csm/sle-15sp2/index.yaml
Update csm-testing/goss-servers RPMs to 1.12.14 to pull in:
* CASMINST-4091
* CASMINST-4095
* CASMINST-4157
* CASMINST-4161
* CASMINST-4176
* CASMINST-4183
* CASMINST-4186
* CASMINST-4195
* CASMINST-4196
* CASMINST-4197
* CASMINST-4222
> Update csm-testing/goss-servers to 1.12.14

- rpm/cray/csm/sle-15sp2/index.yaml
Pull in:
* Move interface MAC check into script file
* CASMINST-4157: Increase some test timeouts to avoid false failures
* Appease the license checker
* Remove needless comment from livecd preflight script
* Replace hard-coded paths with GOSS_BASE variable; protect string variables with quotes
* Make script hash-bang lines consistent
* Correct grep command regular expressions
* CASMINST-4157: Remove unnecessary -it arguments to kubectl exec commands in scripts
> Update csm-testing/goss-servers to v1.6.51

- CHANGELOG.md
- manifests/sysmgmt.yaml
Olympus power capping is disabled by default. When power cap requests are sent to Olympus nodes include enabling the power capping. Also had to change how power capping is disabled for Olympus nodes.
* Resolves [CASMHMS-5399](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5399)
Tested on:
* `hela`
Were the install/upgrade based validation checks/tests run? no
Power capped and verified settings with CAPMC. Disabled power capping and verified settings via curl.
HAS A SECURITY AUDIT BEEN RUN? Y
No known issues.
> Fixes for Olympus power capping

- rpm/cray/csm/sle-15sp2/index.yaml
Pull in:
* CASMINST-4223: Enable logging for bmc-check, podman-basecamp, podmap-nexus
* CASMINST-4224: Move tests to scripts and enable logging for bond-members-have-correct-mtu, switch-bgp-neighbor-aruba-or-mellanox
> Update csm-testing/goss-servers to v1.12.15

- manifests/sysmgmt.yaml
Update FAS to chart version 2.1.1 (FAS version 1.19.0) for CASMHMS-5368
> FAS to chart version 2.1.1 FAS version 1.19.0

- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
CSM 1.2 changed how network interfaces are named on the NCNs e.g. `vlan002` -> `bond0.nmn0`.
The WLM helm charts need to incorporate the new interface name in order to generate the correct `macvlan` network attachment definition.
* Resolves [CASMINST-3930](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3930)
* Upgrade story will be addressed in [CASMINST-3927](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3927)
* `hela`
<UPDATE ME> To be tested on the next install of hela.
> CASMINST-3930 - Update WLM network attachment definitions to use new CSM 1.2 naming convention

- manifests/core-services.yaml
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
This change adds support for the 'GET' operation to the HSM /v2/locks/status API which will list the lock status of all components in HSM. Optional query parameters may be supplied to filter the results based on component Type, State, Role, SubRole, and Locked, Reserved, ReservationDisabled status. Several corrections to the HSM Swagger specification and a few minor CT test updates are also included.
* Resolves CASMHMS-4974.
This change was tested by:
- Implementing unit tests for the new /v2/locks/status 'GET' operation
- Spinning up a local instance of HSM in a docker-compose environment, manually populating it with components and setting locks, and executing calls with various query parameters specified
- Upgrading the running HSM service on Mug using Helm to deploy the new version and …
> CASMHMS-4974 Add support for HSM /v2/locks/status 'GET' operation for listing all locks

- CHANGELOG.md
- manifests/sysmgmt.yaml
Update csm-config to bring in new cf-gitea-import (v1.6.0) image which fixes an issue where a new csm-config chart is installed, but with no material changes still updates git commit IDs in Gitea.
* Resolves CASMCMS-7890
* `mug`
See https://github.com/Cray-HPE/cf-gitea-import/pull/34 and https://github.com/Cray-HPE/csm-config/pull/48 for testing.
Low
> Update csm-config to 1.9.24 for CASMCMS-7890

- manifests/sysmgmt.yaml
The certificate handling of the postgres pods was not working on an upgrade from csm-1.0.x -> csm-1.2. This fixes the chart setting to allow the upgraded pod to read the needed k8s secrets during the upgrade operation.
See https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5404 for details.
Code PR:
https://github.com/Cray-HPE/console-data/pull/18
* Resolves [CASMCMS-7900](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7900)
* `Drax`
Drax has csm-1.0.10 installed. I used helm to upgrade to the new version without issues. I then used helm rollback to revert to the original version.
- Was …
> CASMCMS-7900 - fix for postgres upgrade issue.

- CHANGELOG.md
- manifests/sysmgmt.yaml
Enables tls in the gitea chart for postgres to fix an upgrade issue from 1.0 to 1.2
* Resolves CASMCMS-7901
* Hela
Deployed the chart and validated the postgres cluster was up and running
None
> CASMCMS-7901: Update gitea chart for tls upgrade issue

- rpm/cray/csm/sle-15sp2/index.yaml
Call load balancer test after pit is rebooted, and services are fully deployed.
* Resolves [CASMINST-4250](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4250)
N/A -- no change to test, just moving to different suite
N/A
N/A
Low
> Move loadbalancer test to suite after pit reboot

- Jenkinsfile.github
- hack/gen-rpm-index.sh
- hack/verify-helm-index.sh
- release.sh
These changes look for private repository credentials present in the Jenkins pipeline environment, and make them available for use in the rpm-index and rpm-sync processes when needing to access private repository resources during CSM packaging.
RELATED PRs: 
https://github.hpe.com/hpe/hpc-shastarelm-packaging-tools/pull/2
https://github.hpe.com/hpe/hpc-shastarelm-release/pull/9/files
> Casminst 3955

- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
It was found that the way externaldns domain filters were configured could result in records being created in the wrong zone (e.g. `cmn.hela.dev.cray.com` records could be created in the `hela.dev.cray.com` zone) if externaldns performed an update before powerdns-manager had completed its first pass and created all the zones.
Reconfigured externaldns to prohibit updates to the TLD.
* Resolves [CASMTRIAGE-3123](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3123)
* Merge with https://github.com/Cray-HPE/docs-csm/pull/1107
* `surtur`
* `hela`
Redeployed cray-externaldns, cray-dns-powerdns, and cray-powerdns-manager on `surtur` and `hela` a number of times verifying the goss test passes as expected.
```
ncn-m001:~ # GOSS_BASE=/opt/cray/tests/install/ncn …
```
> CASMTRIAGE-3123 - Update externaldns domain filters to only permit subdomain updates

- CHANGELOG.md
- manifests/platform.yaml
The default istio alert rules have some unit errors (e.g., milliseconds vs seconds) and need adjustments in other cases. This PR will address false alarms caused by the default istio alert rules.
* Resolves [CASMPET-5374]
* `mug`
The istio alert rules were changed and verified on mug.
Low.
> CASMPET-5374: adjust istio alert rules

- hack/load-container-image.sh
Change load image script to be more flexible to handle running on systems with and without mount program specified for overlay.
* Resolves [CASMINST-4280](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4280)
Tested both environments (vshasta and drax).
* `drax`
Tested both with and without mount program configured for podman, the options were set correctly in both contexts.
Low
> Dynamically specify overlay in skopeo opts depending on podman config

- manifests/nexus.yaml
- manifests/platform.yaml
Update cray-nexus to 0.10.1 and cray-nexus-setup to 0.6.1
Merge after:
https://github.com/Cray-HPE/cray-nexus/pull/11
> CASMTRIAGE-3126 update cray-nexus to 0.10.1 and cray-nexus-setup to 0.6.1

- manifests/nexus.yaml
- manifests/platform.yaml
This change will update the cray-nexus chart to 0.10.1 and cray-nexus-setup image precache to 0.6.1
* Merge after https://github.com/Cray-HPE/cray-nexus/pull/11
> CASMTRIAGE-3126 Update the cray-nexus chart to 0.10.1 and cray-nexus-setup image precache to 0.6.1

- manifests/sysmgmt.yaml
There is a CVE vulnerability in the base image. A rebuild of the image is required to pick up a patched base image.
Code PR:
https://github.com/Cray-HPE/cray-crus/pull/19
* Resolves [CASMINST-4261](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4261)
Rebuilt the docker image and locally ran snyk to verify the vulnerability is resolved.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc) N
- Was upgrade tested? If not, why? N - needs system with slurm installed - none present for testing
- Was downgrade tested? If not, why? N - needs system with slurm installed - none present for testing …
> CASMINST-4261 - update cray-crus base image for security patches.

- rpm/cray/csm/sle-15sp2/index.yaml
This adds the goss-switch-bgp-neighbor-aruba-or-mellanox.yaml test to ncn-upgrade-preflight-tests.yaml suite.  This allows us to check the BGP peering sessions before we attempt to boot nodes.
* Resolves CASMINST-4265
* `drax`
I manually added this test to the ncn-upgrade-preflight-tests.yaml suite and ran the suite as it is done in prerequisites.sh.   I verified that the test ran and checked the logs for the test in /opt/cray/tests/install/logs/bgp_neighbors_established.
```
GOSS_BASE=/opt/cray/tests/install/ncn goss -g /opt/cray/tests/install/ncn/suites/ncn-upgrade-preflight-tests.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate
```
> CASMINST-4265: Bump csm-testing and goss-servers to 1.12.19

- CHANGELOG.md
- docker/index.yaml
- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
This change releases the Shared Broker UAI Credential Storage feature implemented in:
- cray-uas-mgr v1.19.1
- update-uas v1.4.0 (and its related UAI images)
- switchboard v2.1.0
This change is a backwards compatible feature.
* Resolves [CASMUSER-2720](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-2720)
Broker UAIs were deployed on Virtual Shasta using all combinations of old and new Broker UAI image versions, cray-uas-mgr versions, and update-uas versions.  Backward compatibility (i.e. preserver old Broker UAI behavior) and new functionality were tested manually.  Unit tests were written to cover new UAS functionality and are run during builds.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? yes …
> CASMUSER-2720 Shared Broker UAI Credential Storage

- rpm/cray/csm/sle-15sp2/index.yaml
A change was put in to add `set -e` to the top of the livecd-preflight-check script.  When `/usr/bin/goss validate -f json` is run in that script to execute all of the goss tests in that suite, it will return non-zero if any of the tests fail.  The `set -e` causes the script to then stop execution immediately without giving any output indicating which tests failed.   We need to run `/usr/bin/goss validate -f json` without the `set -e`.
* Resolves CASMINST-4142
* `drax`
I ran `/opt/cray/tests/install/livecd/automated/livecd-preflight-checks` on drax with this fix and injected a test failure I was able to see the test results include the one test that was failing.
> CASMINST-4142: Update csm-testing/goss-servers to v1.6.52

- assets.sh
- ncn-image-modification.sh
Image code change: https://github.com/Cray-HPE/node-image-build/pull/215
Script usage:
```
redbull-ncn-m001-pit:~ # ncn-passwd-ssh-keygen.sh -h
Usage: ncn-passwd-ssh-keygen.sh [-d dir] [-k kubernetes-squashfs-file] [-s storage-squashfs-file] [ssh-keygen arguments]
This script semi-automates the process of changing the root password and
adding new ssh keys for the root user to the NCN squashfs image(s).
The script will immediately prompt for a new passphrase for ssh-keygen.
The script will then proceed to unsquash the supplied squash files and
then prompt for a password. Once the password of the last squash has been
provided, the script will continue to completion without interruption.
The process can be fully automated by using the SQUASHFS_ROOT_PW_HASH
environment variable (see below) …
```
> MTL-1647: NCN assets and CI/automation script for adding keys/password

- manifests/platform.yaml
This adds support for checking to see if the existing spire intermediate CA certificate has less than a month left before expiration, and if it does it'll replace the secret with a new intermediate CA.
* Resolves [CASMPET-5082](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5082) 
Validated that the certificate was updated properly when the conditions were met. Also validated that the cert was created correctly when it didn't already exist and that it wasn't touched when it wasn't ready to be updated.
- Were new tests (or test …
> CASMPET-5082 Bump spire-intermediate to 0.5.0

- lib/setup-nexus.sh
Supports upgrade to latest hpc-shastarelm-release vendor update.
Resolves [CASMINST-4353](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4363)
> CASMINST-4363: skopeo-sync updates images from docker/dtr.dev.cray.com directory

- rpm/cray/csm/sle-15sp2/index.yaml
Re-did this csm-testing release to pull out changes that were previously done in 1.6.51.
A change was put in to add `set -e` to the top of the livecd-preflight-check script.  When `/usr/bin/goss validate -f json` is run in that script to execute all of the goss tests in that suite, it will return non-zero if any of the tests fail.  The `set -e` causes the script to then stop execution immediately without giving any output indicating which tests failed.   We need to run `/usr/bin/goss validate -f json` without the `set -e`.
* Resolves CASMINST-4142
* `drax`
I ran `/opt/cray/tests/install/livecd/automated/livecd-preflight-checks` on drax with this fix and injected a test failure I was able to see the test results include the one test that was failing.
> CASMINST-4142: Update csm-testing/goss-servers to v1.6.53

- manifests/core-services.yaml
- manifests/platform.yaml
cray-powerdns-manager was computing the reverse zone by eliminating zeroes from the IP address.
The same `GetReverseZoneName` function was used to generate the zone contents which resulted in truncated PTR records.
```
x1000c5s0b0n1h2.hsn.hela.dev.cray.com	3600	IN	A	10.253.0.69
69.253.10.in-addr.arpa	3600	IN	PTR	x1000c5s0b0n1h2.hsn.hela.dev.cray.com
```
* Resolves [CASMNET-1151](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1151)
* `hela` and `mug`
Deployed the new version of cray-powerdns-manager and validated the generated records are now correct
```
/ $ pdnsutil list-zone 253.10.in-addr.arpa
$ORIGIN .
100.0.253.10.in-addr.arpa	3600	IN	PTR	x1000c5s7b0n1h3.hsn.vshasta.io
1.0.253.10.in-addr.arpa	3600	IN	PTR …
```
> CASMNET-1151 - powerdns-manager creating PTR records with missing zeroes

- release.sh
The script was among those included in the release directory that gets tarred and shipped.
> CASMINST-4369: copy ncn modification script into the release dir

- ncn-image-modification.sh
We do not need to create a new initrd or kernel when changing the squashfs for the purposes of adding a new root password, keys, or timezone.  Cease doing so.  The dracut code to create a new initrd has problems running on an overly filesystem.  By not creating an initrd we are avoiding this problem.
* Resolves CASMINST-4370
* `redbull`, `surtur`
I was able to create a new squashfs on both redbull and surtur while being on an overlayfs.
> CASMINST-4370: minor cleanup and cease creating new initrd/kernel files

- ncn-image-modification.sh
The `passwd --root` command does not recognize an alternate root
path unless it starts with a `/` - use `realpath` to provide the
full path to `passwd`.
Tested on redbull by providing relative paths to  the squashfs files.
> CASMINST-4381: use the full path for the passwd command

- CHANGELOG.md
- rpm/cray/csm/sle-15sp2/index.yaml
Cray Site Init generated CHN reservations with xname rather than common name. This created two xname records in DNS and played havoc with SAT and DVS.  Additionally UANs were missing from the CHN.  This change remediates these two issues for new/fresh installs of CSM 1.2 where the system has a CHN.
* Resolves CASMINST-4372
* Hela data (has a CHN)
* Surtur data (does not have a CHN)
Ensured common names were generated in CHN SLS reservations and that UAN entries were generated in the CHN SLS structured.
None
> CASMINST-4372 CSI fix for CHN reservations

- ncn-image-modification.sh
Host keys change during upgrade to a new image.  Don't propagate
the known_hosts file as this will cause key conflicts post-upgrade
and make ssh mad.
> CASMINST-4392: don't propagate known_hosts

- rpm/cray/csm/sle-15sp2/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
Canu: Release 1.3.2 
**Quick summary:**
New feature: Customer custom config injection.
Both code and switch configuration bug fixes and updates.
**Detailed change log since last official release.**
```
Fix aruba banner output during canu validate
shutdown unused ports by default on aruba 6300+dell+mellanox
Removed the override feature
Add feature to inject custom configs into generated switch configs
Change Aruba banner from motd to exec
Reordered the configuration output so that vlans are defined before being applied to ports.
Fix Leaf-bmc naming corner case: leaf-bmc-bmc to leaf-bmc
Fix OSPF CAN vlan for 1.2 in full/tds
Fixed bug to allow canu to exit gracefully with sys.exit(1)
Add network test cases
Add network test cases for DNS and site connectivity
Fixed missing DNS from Aruba …
```
> Canu: Release 1.3.2 - CASMNET-1348_1_2

- manifests/sysmgmt.yaml
Update hmcollector helm version to 2.15.4 for CASMHMS-5479 - Slingshot data prefix has 'CrayFabricCriticalTelemetry' instead of 'CrayFabricCritTelemetry'
* Resolves [CASMHMS-5479](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5479)
For testing see https://github.com/Cray-HPE/hms-hmcollector/pull/36
Low risk
> Update hmcollector helm version

- manifests/sysmgmt.yaml
Update hmcollector helm version to 2.15.4 for CASMHMS-5479 - Slingshot data prefix has 'CrayFabricCriticalTelemetry' instead of 'CrayFabricCritTelemetry'
* Resolves [CASMHMS-5479](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5479)
For testing see https://github.com/Cray-HPE/hms-hmcollector/pull/36
Low risk
> Update hmcollector helm version Main

- manifests/sysmgmt.yaml
Update hmcollector helm version to 2.15.4 for CASMHMS-5479 - Slingshot data prefix has 'CrayFabricCriticalTelemetry' instead of 'CrayFabricCritTelemetry'
* Resolves [CASMHMS-5479](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5479)
For testing see https://github.com/Cray-HPE/hms-hmcollector/pull/36
Low risk
> Update hmcollector helm version 1.2.5

- assets.sh
Bring 1.2.5 assets in line with 1.2 assets.  They should be the same up until we decide there will be new images in 1.2.5.
> Sync up 1.2.5 with latest 1.2 assets

- CHANGELOG.md
- manifests/platform.yaml
- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
Upgrade istio to 1.9.9, OPA envoy plugin to 0.26.0-envoy-6, kiali to 1.33.1.
* Resolves [CASMPET-5303]
* `mug`
After upgrading to istio 1.9.9, OPA envoy plugin, as well as kiali, I validated that the keycloak token still works, as well as kiali, grafana, keycloak, and prometheus UIs.
Medium. The upgrade was tested in both vshasta and bare metal systems, with success. Since we get into 1.2.5 early, any unexpected failures can be resolved or we can …
> CASMPET-5303: upgrade istio to 1.9.9

- manifests/core-services.yaml
- manifests/platform.yaml
- update container baseos to be rolling versions of alpine3
- resolve powerdns CVE-2022-27227 https://github.com/advisories/GHSA-67fj-vc46-4xmv by bumping powerdns version 
Resolves:
CASMINST-4262
CASMINST-4400
CASMINST-4399
CASMNET-1390
hela
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your …
> version bumps for kea,unbound,pdns,pdsn-mgr for security fixes

- assets.sh
The ISO build was including repos containing compute-node artifacts.
This was confusing the kernel install. This ISO build was done with
those repos removed.
> CASMINST-4435: liveCD correct kernel artifacts

- manifests/platform.yaml
Pull in new etcd operator image pinning to specific version of curl.
* Resolves [CASMTRIAGE-3194](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3194)
```
Normal   Pulling           16s                kubelet            Pulling image "curlimages/curl:7.73.0"
Normal   Pulled            15s                kubelet            Successfully pulled image "curlimages/curl:7.73.0" in 903.549441ms
```
* `vshasta`
Used the updated operator image with pinned version, was able to pull the image during restore.
Low
> New etcd-operator chart to pin curl image to specific version

- rpm/cray/csm/sle-15sp2/index.yaml
We need prevent UAIs from getting to CMN like we do with NMNLB.   The way this is being accomplished with NMNLB is that a route exists on the UAI that goes to a gateway that it cannot get to.   We are doing the same thing for CMN by adding the CMN subnet to macvlan routes defined in customizations.yaml.  This causes it to be added to the relevant network attachment definitions.
- Fixes #CASMINST-4283
I did a local build of CSI.  I ran "csi config init" with the resulting binary using the seed files from hela.   I verified that the correct CMN route (10.103.0.0./25) was added to the customizations.yaml generated by CSI.
```
macvlansetup:
nmn_subnet: 10.252.2.0/23
nmn_supernet: 10.252.0.0/17
nmn_supernet_gateway: 10.252.0.1
nmn_vlan: bond0.nmn0
nmn_reservation_start: 10.252.2.10 …
```
> CASMINST-4283:  Bump CSI version to 1.16.11

- rpm/cray/csm/sle-15sp2/index.yaml
See main code PR for details:
https://github.com/Cray-HPE/csm-testing/pull/269
> CASMINST-4442: Extend timeout on goss-command-available test (1.0)

- rpm/cray/csm/sle-15sp2/index.yaml
See main code PR for details:
https://github.com/Cray-HPE/csm-testing/pull/269
> CASMINST-4442: Extend timeout on goss-command-available test (1.2)

- rpm/cray/csm/sle-15sp2/index.yaml
See main code PR for details:
https://github.com/Cray-HPE/csm-testing/pull/269
> CASMINST-4442: Extend timeout on goss-command-available test (1.2.5)

- assets.sh
- Fixes MTL-1660
- Relates to MTL-1513
This moves some of the Ansible init out of storage-ceph and into NCN common, making Ansible available on every NCN.
A CSM Ansible virtualenv will exist at `/etc/ansible/csm_ansible`.
Yes.
* Resolves [MTL-1660](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1660)
* `redbull`
_How were the …
> MTL-1660 Include Ansible in all NCN Images

- CHANGELOG.md
- manifests/platform.yaml
Use latest alpine 3 base image from algol60 to reduce the need for engineering efforts to bump the alpine version string for CVE remediation.
* Resolves [CASMPET-5485]
* `mug`
Upgraded trustedcerts-operator, and made sure no errors are seen from pod logs.
Low.
> CASMPET-5485: update trustedcerts-operator to use latest alpine 3 image

- CHANGELOG.md
- docker/index.yaml
- manifests/sysmgmt.yaml
Update `update-uas` in the sysmgmt manifest to 1.4.0 from 1.3.3 to fix the DBUS error displayed on login to the Basic UAI.  At the same time, remove the unnecessary and out-of-sync basic and broker UAI images from the list in `docker/index.yaml` after verifying that the correct image is being discovered in the `update-uas` chart and shipped.  This removes two obsolete docker images from the final released blob and eliminates a double (frequently out of sync) source of truth in building CSM.
This is a backward compatible bugfix
* Resolves [CASMUSER-2992](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-2992)
Reproduced the original problem with update-uas 1.3.3 on vshasta, then verified that the problem is fixed in update-uas 1.4.0. …
> CASMUSER-2992 update-uas to 1.4.0 to fix basic UAI dbus complaint

- CHANGELOG.md
- manifests/sysmgmt.yaml
Update update-uas chart version to 1.5.0 to fix missing `awk` in the Basic UAI image which was causing
the Basic UAI entry-point script to fail to set up the user correctly before first login.
Backwards compatible bugfix.
* Resolves [CASMUSER-2994](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-2994)
Reproduced problem and verified fix on vshasta.  Upgraded to this version of update-uas and verified that the correct configuration was installed.  Verified that the Basic UAI worked correctly with the new UAI image installed by update-uas.  Downgraded back to update-uas 1.4.0 and verified that the correct config was installed for that version and that the problem returned with the unfixed Basic UAI image. …
> CASMUSER-2994 update update-uas to 1.5.0 fix missing awk in UAI

- manifests/platform.yaml
Finally refactor the etcd operator code such that we can pass in the curl docker image from our chart, eliminating the hard-coding of the image in the operator.
* Resolves [CASMINST-4465](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4465)
Controller startup/restore logs:
```
time="2022-04-18T20:13:25Z" level=info msg="Go Version: go1.15.7"
time="2022-04-18T20:13:25Z" level=info msg="Go OS/Arch: linux/amd64"
time="2022-04-18T20:13:25Z" level=info msg="etcd-restore-operator Version: 0.12.6-cray"
time="2022-04-18T20:13:25Z" level=info msg="Git SHA: 0f4c7639"
time="2022-04-18T20:13:25Z" level=info msg="Curl image version: artifactory.algol60.net/csm-docker/stable/docker.io/curlimages/curl:7.73.0"
.
.
time="2022-04-18T20:15:13Z" level=info msg="serving backup for restore CR …
```
> Pass curl image to etcd operator via values.yaml

- manifests/sysmgmt.yaml
Change the chart annotations to match the actual redis image used. This impacts the images that are packaged in a release and what is scanned for CVE vulnerabilities. It does not impact the actual use of the service.
* Resolves [CASMCMS-7965](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7965)
* `Wasp`
Installed the new version with loftsman, ran the ct tests (successfully), reverted back to the original install, then re-ran the ct tests to insure everything is still working correctly. …
> CASMCMS-7965 - fix cray-cfs-api annoataion information to correct image packaging.

- manifests/sysmgmt.yaml
A previous mod implemented support for emulating restarts when the
hardware does not directly support it. It ended up causing every power
off to wait for the hardware to be off. This caused problems due to the
behavior change and a short timeout. Bumped the timeout from 1 minute to
15 minutes. This timeout is still site dependent.
* Resolves CASMHMS-5480 for csm 1.2
Tested on:
* `hela`
Upgraded CAPMC to fixed version, verified CAPMC returns immediately after sending power Off to target node. There were no checks by CAPMC to see if the node was off. Issues a reinit to a node and verified CAPMC waited for the …
> Modify which docker container capmc uses for power off fixes.

- CHANGELOG.md
- manifests/sysmgmt.yaml
This adds a new cray-uai-gateway-test image.   This image includes the API gateway tests and will be used for executing those tests at various times to ensure the gateways are isolated/accessible on the proper networks.
There was discussion of bringing the ADMIN_CLIENT_SECRET and other configuration items like the SYSTEM_DOMAIN and USER_NETWORK into the container using secrets and volumes so the test could be run automatically in the entrypoint.sh.   For now, I opted to instead inject those values into a vars.sh file via kubectl exec commands and then execute the test.  That is all driven by a bash script which makes it easy to run the tests from an NCN.  We may choose later to take the next step of running the tests in the entrypoint but this seems to work well for now and takes care of …
> CASMINST-4246:  Update update-uas to v1.6.0 - Adding cray-uai-gateway-test image

- ncn-image-modification.sh
Clean up the squashfs-root and the embedded mount point on error.
> CASMINST-4480: cleanup mounts and squshfs-root on interrupt/error

- CHANGELOG.md
- manifests/platform.yaml
This PR changes the cray-oauth2-proxies chart v0.2.0 to use CSM built container image. 
* Resolves [CASMPET-5534]
* `wasp`
Deployed the new helm chart, and verified the following test script still PASS:
tests/install/livecd/scripts/monitoring_check.sh
Low.
> CASMPET-5534: Update cray-oauth2-proxy to use CSM built container image

- docker/index.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
- added cray-canu container image
- bumped canu-1.5.6 rpm
- Feature: LAG preserve to help in adopting CANU
- Feature: Send arbitrary read-only commands to switches.
- Many switch configuration template fixes.
- Many docs updates and changes.
- yes
- CASMNET-1518
Release notes https://github.com/Cray-HPE/canu/releases/1.5.6
- local
- hela
- local
- gamora
- jolt1
- wasp
_How were the changes tested and success verified? If schema changes were part of this …
> adding cray-canu image and bumping canu rpm version

- manifests/platform.yaml
This change will wait to apply pod priorities to the metallb controller/speaker pods until the initial chart deployment has completed spinning up the pods.
* Resolves [CASMINST-4510](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4510)
```
ncn-m001-fec36008:/home/bklein # kubectl -n metallb-system logs cray-metallb-patch-pod-priority-1-mgkb9 -f
Waiting for deployment "metallb-controller" rollout to finish: 0 of 1 updated replicas are available...
deployment "metallb-controller" successfully rolled out
Waiting for daemon set "metallb-speaker" rollout to finish: 6 of 9 updated pods are available...
Waiting for daemon set "metallb-speaker" rollout to finish: 7 of 9 updated pods are available...
Waiting for daemon set "metallb-speaker" rollout to finish: 8 of 9 updated pods are …
```
> Metallb chart change to wait for deployment/daemonsets to rollout before applying pod priority

- manifests/core-services.yaml
- manifests/platform.yaml
- Background
- a place holder dhcp lease is a dhcp reservation added via the kea api that the hardware is not renewed their lease yet or has stopped renewing their lease(like the rosetta management port, see https://jira-pro.its.hpecorp.net:8443/browse/SSHOTPLAT-1151?focusedCommentId=3404829&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-3404829)
- place holder dhcp leases helps speed up DNS record generation for unbound-manager 3 way check.
- Problem 
- a race condition can occur when you want to remove an IP in SMD EthernetInterfaces that is set for a dhcp reservation.  the placeholder lease can put back the IP into SMD …
> bug/CASMNET-1385 - csm-1.2cray-dhcp-kea version bump for CASMNET-1385

- CHANGELOG.md
- manifests/platform.yaml
Use node-discovery 1.2.4 for CVE remediation. The older 1.2.1 version has not been rebuilt for a few months.
* Resolves [CASMPET-5566]
* `wasp`
Deployed the new node-discovery chart, deleted a label from one of the worker nodes and verified that it gets added back shortly.
Low.
> CASMPET-5566: add image annotations to node-discovery

- docker/index.yaml
Updates TRS Worker to v1.6.1 to fix integration tests in build - no code changes.
> TRS Worker to v1.6.1

- docker/index.yaml
Updates TRS Worker to v1.6.1 to fix integration tests in build - no code changes.
> Updated trs worker to v1.6.1

- assets.sh
Code: https://github.com/Cray-HPE/node-image-build/pull/251
> CASMTRIAGE-3263: Improve kube-api haproxy failover using http instead of tcp check

- manifests/core-services.yaml
- manifests/platform.yaml
- during vendor lookup, skip none network devices with the bmc xname
CASMTRIAGE-3269
Surtur
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?na
- Were continuous integration tests run? If not, …
> casmtriage-3269-csm-1.2 - during vendor lookup, skip none network devices with the bmc xname

- assets.sh
- rpm/cray/csm/sle-15sp2/index.yaml
This includes the `yq` package, and a small tweak from pit-init 1.2.19. If `/usr/bin/yq` exists, it'll be a symlink not a file. The current -f test fails to find it if it exists. This change tests for its existence with command.
This also sets up the need for `CSM_PATH` only when `/usr/bin/yq` is not present.
No.
* Resolves [CASMINST-4533](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4533)
* **This change is already in `main`**
> CASMINST-4533 Add pit-init 1.2.19

- assets.sh
- rpm/cray/csm/sle-15sp3/index.yaml
- Fixes CASMINST-4547
There was a case not covered with the DHCP loop where if nothing configures the IP dumping call would fail on an unknown interface.
This change ensures that the existence of the IP property exists before dumping.
This changes the failure to print this instead before starting the loop again:
```
No interfaces were configured
```
What is less risky, or more risky now - or if your mod fails is there a new risk?
> CASMINST-4547

- CHANGELOG.md
- manifests/platform.yaml
Release cray-postgres-operator 0.14.0 to trigger image auto rebuild of underlying images (e.g., postgres-operator) for CVE remediation.
* Resolves [CASMPET-5567]
* `wasp`
Deployed this to wasp and made sure that the right postgres-operator 2.3.0 image was used. Made sure I could run patronictl list. Made sure that restarting the keycloak postgres pods worked. Made sure I could still get a token and use it.
Low.
> CASMPET-5567: release cray-postgres-operator 0.14.0

- rpm/cray/csm/sle-15sp2/index.yaml
Add service restart for patroni service in lagging members before validating lag (required when bouncing masters due to backoff in postgres pods that's not tunable), as well as correct lag check to exec into the leader.
* Resolves [CASMINST-4544](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4544)
Ran many times on surter when rebuilding master node.
* `surtur`
Ran many times
Low
> Add patroni service restarts for lagging PG members before checking lag

- assets.sh
- rpm/cray/csm/sle-15sp2/index.yaml
- Fixes #CASMTRIAGE-3253
Renames the uai_macvlan_bridge reservation in the uai_macvlan subnet to uai_nmn_blackhole.   uai_macvlan_bridge is no longer being used.  We are repurposing that reservation to be used as the gw for the NMNLB route in UAIs.  This will block access to the NMNLB from the UAI.
While in the same same section of code, I also made the allocation of IPs to the uai_macvlan reservations consistent.  This solves the issue with running CSI multiple times and ending up with different IPs for these reservations.
Built CSI locally and ran the `csi config init` with seed files from hela.   Checked the generated sls_input_file.json and customizations.yaml.
> CASMTRIAGE-3253:  Bump CSI version to 1.16.16

- CHANGELOG.md
- manifests/nexus.yaml
- manifests/platform.yaml
This changes the location of the nexus3 image. It is in a process to move the location of the image build from the nexus3 repository to the container-images repository. The image being pulled adds no new or changing function only rebuild location as the nexus3 repository no longer can rebuild the image properly.
* Resolves [CASMPET-5591](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5591)
* Future work required by [CASMPET-5592](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5592)
Tested by running on vshasta by logging into nexus via the keycloak integration.
- Was upgrade …
> CASMPET-5591: Bump cray-nexus to 0.10.2

- rpm/cray/csm/sle-15sp2/index.yaml
Pull in two Goss test improvements:
* [CASMINST-4538](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4538) - artifacts-in-place preflight check also validate that squashfs is customized. (For details see [source PR](https://github.com/Cray-HPE/csm-testing/pull/297))
This allows us to remove a manual step from the install procedure.
* [CASMINST-4548](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4548) - Correct issues with Goss Weave test; fold Weave test from Deploy Management Nodes into it. (For details see [source PR](https://github.com/Cray-HPE/csm-testing/pull/299))
> CASMINST-4538 & CASMINST-4548 Goss test improvements (csm-1.2)

- rpm/cray/csm/sle-15sp2/index.yaml
Pull in two Goss test improvements:
* [CASMINST-4538](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4538) - artifacts-in-place preflight check also validate that squashfs is customized. (For details see [source PR](https://github.com/Cray-HPE/csm-testing/pull/297))
This allows us to remove a manual step from the install procedure.
* [CASMINST-4548](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4548) - Correct issues with Goss Weave test; fold Weave test from Deploy Management Nodes into it. (For details see [source PR](https://github.com/Cray-HPE/csm-testing/pull/299))
> CASMINST-4538 & CASMINST-4548 Goss test improvements (main)

- assets.sh
New 0.3.1 images including MTL-1660.
This also includes the following commits to the node-image-build repo:
- 65fde2499 (HEAD -> develop, tag: 0.3.1-4, origin/develop, origin/cleanup_workflow, origin/HEAD, cleanup_workflow) Handle all lts branches
- 17e32bbaf Quote Secret and Fix Missing Quote
- c6890a8df Remove duplicate file; rename main file
- 3a0a571e1 (tag: 0.3.1-3, origin/build-against-latest-main, build-against-latest-main) Update "csm-rpms" from "git@github.com:Cray-HPE/csm-rpms.git@main"
- a23107ffc Squashed 'vendor/github.com/Cray-HPE/csm-rpms/' changes from 2399afe4..4c172ed7
- 2db8d2c6f (tag: 0.3.1-2, origin/CASMTRIAGE-3193-develop) fixup labeler workflow
- 3d5692759 CASMTRIAGE-3193 fix kdump not working
- be00e5308 (origin/MTL-1591) MTL-1591: Remove kernel debug RPMs
- …
> Include latest 1.3 images

- manifests/core-services.yaml
Update the cray-hms-smd chart to 2.0.8 for Fixing an issue causing FRU data to get improperly populated for empty locations.
* Resolves [CASMHMS-5511](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5511)
For testing, see https://github.com/Cray-HPE/hms-smd/pull/74
none
> Update cray-hms-smd chart to 2.0.8 CSM 1.2

- manifests/core-services.yaml
Update the cray-hms-smd chart to 2.0.8 for Fixing an issue causing FRU data to get improperly populated for empty locations.
* Resolves [CASMHMS-5511](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5511)
For testing, see https://github.com/Cray-HPE/hms-smd/pull/74
none
> Update cray-hms-smd chart to 2.0.8

- manifests/platform.yaml
Fix alpine image for cray-precache-images chart, force pod restarts on upgrade, and fix wait-for job.
* Resolves [CASMINST-4568](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4568)
```
ncn-m001-fec36008:/home/bklein # kubectl logs -n nexus pod/wait-for-cray-precache-images-pods-m898g -f
Waiting for daemon set "cray-precache-images" rollout to finish: 0 out of 6 new pods have been updated...
Waiting for daemon set "cray-precache-images" rollout to finish: 0 out of 6 new pods have been updated...
Waiting for daemon set "cray-precache-images" rollout to finish: 1 out of 6 new pods have been updated...
Waiting for daemon set "cray-precache-images" rollout to finish: 1 out of 6 new pods have been updated...
Waiting for daemon set "cray-precache-images" rollout to finish: 1 out of 6 new …
```
> Point to locally built alpine image, fix upgrade issue for configmap for cray-precache-images

- rpm/cray/csm/sle-15sp2/index.yaml
- In order to have interoperability between the HMN-SHCD parser and CANU we need to be able to have 0 as a destination port number on the HMN tab of the SHCD.
- This change allows SLS to accept 0 as a port number.  This is the same behavior as leaving it blank.
- Fixes # CASMINST-4549
Tested locally.  All tests passed.
Generated SLS file has no differences with a "" or "0" as port destination.
> CASMINST-4549 main

- rpm/cray/csm/sle-15sp2/index.yaml
- In order to have interoperability between the HMN-SHCD parser and CANU we need to be able to have 0 as a destination port number on the HMN tab of the SHCD.
- This change allows SLS to accept 0 as a port number.  This is the same behavior as leaving it blank.
- Fixes # CASMINST-4549
Tested locally.  All tests passed.
Generated SLS file has no differences with a "" or "0" as port destination.
> Casminst 4549 1.2

- CHANGELOG.md
- manifests/sysmgmt.yaml
Made some enhancements to the gateway-test.py script to better handle failure conditions when getting tokens.   We don't want to fail immediately that case.   We want to move on to the other networks to test those before failing.  
This also adds support for additional node types.   Trying to keep this copy in the gateway-test image in sync with the one in docs-csm for other nodes.
* Relates to CASMNET-1240
* `drax`, `surtur`, and `hela`
Launched a UAI with the gateway-test image, copied the updated gateway-test.py into the image and ran `run-test.sh`.   Verified that the test runs across all networks on systems with and without the fix to block the NMN network.
> CASMNET-1240:  Update update-uas to v1.6.1 - Updated test cray-uai-gateway-test image

- CHANGELOG.md
- manifests/sysmgmt.yaml
Release spire 2.5.0 to use newly built images for CVE remediation and image auto rebuild.
* Resolves [CASMINST-4505](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4505)
Validated that new images are used in spire pods, and ncn-join-tokens are generated correctly.
Low.
> CASMINST-4505: use spire 2.5.0 for CVE remediation

- rpm/cray/csm/sle-15sp2/index.yaml
[CASMINST-4565](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4565) Enhance kube-system Goss test to remove need for manual test during Deploy Management Nodes install procedure.
[CASMINST-4576](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4576) Validate that ceph -s works where and when it ought to. This would have caught a problem on the gamora install much earlier and saved hours of time.
See source PRs for full details:
https://github.com/Cray-HPE/csm-testing/pull/301
https://github.com/Cray-HPE/csm-testing/pull/304
> CASMINST-4565/CASMINST-4576: Goss test improvements

- rpm/cray/csm/sle-15sp2/index.yaml
This test will always check to see if the bond0.can0 interface exists on the worker and master nodes.   However, this interface not exist if the system was configured with CHN instead of CAN.   This changes the test into a script that checks the BICAN network configuration in SLS to determine if it is CAN or CHN.   It will only check for the bond0.can0 interface if it is configured for CAN.
* Resolves CASMINST-4446
* `surtur` and `wasp`
I ran this goss test on wasp where it is configured for CHN and previous failed.  It now passes there.
I also ran this goss test on surtur where it was configured for CAN to make sure it still passes there.
Wasp:
```
ncn-m001:~ # GOSS_BASE=/opt/cray/tests/install/ncn goss -g /opt/cray/tests/install/ncn/tests/goss-network-interfaces.yaml …
```
> CASMINST-4446: Bump csm-testing and goss-servers to 1.14.16

- rpm/cray/csm/sle-15sp2/index.yaml
This test will always check to see if the bond0.can0 interface exists on the worker and master nodes.   However, this interface not exist if the system was configured with CHN instead of CAN.   This changes the test into a script that checks the BICAN network configuration in SLS to determine if it is CAN or CHN.   It will only check for the bond0.can0 interface if it is configured for CAN.
* Resolves CASMINST-4446
* `surtur` and `wasp`
I ran this goss test on wasp where it is configured for CHN and previous failed.  It now passes there.
I also ran this goss test on surtur where it was configured for CAN to make sure it still passes there.
Wasp:
```
ncn-m001:~ # GOSS_BASE=/opt/cray/tests/install/ncn goss -g /opt/cray/tests/install/ncn/tests/goss-network-interfaces.yaml …
```
> CASMINST-4446: Bump csm-testing and goss-servers to 1.12.32

- assets.sh
- Fixes # CASMTRIAGE-3280
We tracked down the root cause of weave split-brain on gamora.  The issue was caused by weave pods starting up before enough of the nodes have joined the cluster.   More details in https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3280.   To fix this, we are waiting for a quorum of nodes to join the cluster before applying the network manifests.   We tried this process manually on gamora and we were able to see the expected results in the weave logs showing that they had a enough peers in the peer list to avoid splitting the two masters into two separate seed groups.
- [N/A] I have included documentation in my PR (or it is not required)
This code will be smoke tested on gamora to mitigate risk.
> CASMTRIAGE-3280 1.2

- CHANGELOG.md
- manifests/platform.yaml
This PR use sealed-secrets 0.3.0 for updated image location, as it was moved from quay.io to docker.io.
* Resolves[CASMPET-5602](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5602)
Upgraded the sealed-secrets chart, and made sure that the secrets were unsealed successfully.
Low.
> CASMPET-5602: release sealed-secrets 0.3.0 to use new image location

- rpm/cray/csm/sle-15sp2/index.yaml
The check_network_interface.sh fails when it is run during livecd preflight checks because the k8s cluster has not been created yet.   Therefore, it could not run kubectl to get the admin client secret.
It also fails on all of the storage nodes except for s001.   Only s001 has the k8s admin credentials to be able to run kubectl.
The fix here is to check if kubectl can be run.   If it cannot, then we will skip checking the can0 interface on the node.  Without being able to get the admin client secret, we cannot get to SLS to determine which user network is configured.
Also added a check for the argument to the script in case it is run independently of the goss test.
* Resolves CASMINST-4618
* `fanta`, `wasp`, and `redbull`
Ran check_network_interface.sh on EVERY NODE on fanta (master, …
> CASMINST-4618: Bump csm-testing and goss-servers to 1.12.33

- manifests/sysmgmt.yaml
Update uas-mgr and UAI images to use a different base layer. The new layer is kept more up to date to get timely security fixes.
* Updates [CASMINST-4148](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4148)
* vshasta
- Was upgrade tested? If not, why? N, fresh install with vshasta
- Were new tests (or test issues/Jiras) created for this change? N, covered by existing tests
No
> CASMINST-4148: Change UAS to rolling update base images

- rpm/cray/csm/sle-15sp2/index.yaml
The check_network_interface.sh fails when it is run during livecd preflight checks because the k8s cluster has not been created yet.   Therefore, it could not run kubectl to get the admin client secret.
It also fails on all of the storage nodes except for s001.   Only s001 has the k8s admin credentials to be able to run kubectl.
The fix here is to check if kubectl can be run.   If it cannot, then we will skip checking the can0 interface on the node.  Without being able to get the admin client secret, we cannot get to SLS to determine which user network is configured.
Also added a check for the argument to the script in case it is run independently of the goss test.
* Resolves CASMINST-4618
* `fanta`, `wasp`, and `redbull`
Ran check_network_interface.sh on EVERY NODE on fanta (master, …
> CASMINST-4618: Bump csm-testing and goss-servers to 1.14.17

- assets.sh
- rpm/cray/csm/sle-15sp2/index.yaml
Includes a signed ilorest RPM and a version bump.
```bash
rpm -qi https://artifactory.algol60.net/artifactory/csm-rpms/hpe/stable/sle-15sp2/metal-ilorest/x86_64/ilorest-3.5.0-1.x86_64.rpm
Name        : ilorest
Version     : 3.5.0
Release     : 1
Architecture: x86_64
Install Date: (not installed)
Group       : System/Configuration/Packaging
Size        : 15865347
License     : Copyright 2016-2021 Hewlett Packard Enterprise Development LP
Signature   : RSA/SHA256, Sat 14 May 2022 05:23:21 AM UTC, Key ID d4dae1e39da39f44
Source RPM  : ilorest-3.5.0-1.src.rpm
Build Date  : Sat 14 May 2022 05:21:49 AM UTC
Build Host  : a403a49170af
Relocations : (not relocatable) …
```
> MTL-1530 signed ilorest

- manifests/sysmgmt.yaml
This includes a fix where the bos-reporter-spire-agent was incorrectly named, preventing the bos reporter from getting a spire token.
> CASMPET-5635 Bump spire to 2.6.0

- manifests/platform.yaml
This removes the istio-injection: enabled label from the kyverno namespace. This is not needed per Jeremy Duckworth
> CASMPET-5595 Bump cray-drydock to 2.13.0

- CHANGELOG.md
- manifests/sysmgmt.yaml
Ansible role to determine whether the bifurcated CAN is configured to use CAN or CHN by reading the systemDefaultRoute property from the BICAN SLS network. In the case that CHN is defined configure the CHN IP addresses on the worker HSN interfaces.
* Resolves [CASMNET-1528](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1528)
* Documentation will be addressed via [CASMINST-4135](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4135)
* `hela` - systemDefaultRoute = CHN
* `wasp` - systemDefaultRoute = CAN
wasp - Verified that this role does nothing beyond query SLS on a system configured to use CAN.
hela - Verified the following scenarios
* CHN IP address is applied successfully if HSN interface is configured
```
TASK [csm.ncn.enable_chn : Check that the hsn0 interface has the …
```
> CASMNET-1528 - BI-CAN: Create CFS play that will setup CHN IP on NCNs after HSN install

- rpm/cray/csm/sle-15sp2/index.yaml
Change scripts that support getting files from S3 when restoring bare-metal backup to not depend on kubernetes to get creds (use radosgw-admin instead).
* Resolves [CASMPET-5626](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5626)
```
ncn-m001-fec36008:/opt/cray/platform-utils/s3 # ./list-objects.py --bucket-name boot-images
foo.txt
foo2.txt
```
```
ncn-m001-fec36008:/opt/cray/platform-utils/s3 # ./download-file.py --bucket-name boot-images --key-name foo2.txt --file-name /var/tmp/foo2.txt
```
```
ncn-m001-fec36008:/opt/cray/platform-utils/s3 # ls -lh /var/tmp/foo2.txt
-rw-r--r-- 1 root root 8 May 16 22:08 /var/tmp/foo2.txt
```
Ran several lists/downloads
Low
> Change etcd backup support scripts to not rely on k8s

- manifests/platform.yaml
Also remove externaldns backup -- no longer there, and fix benign but confusing shell error when creating manual backup.
* Resolves [CASMPET-5638](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5638)
```
ncn-m001-fec36008:/opt/cray/platform-utils/s3 # ./list-objects.py --bucket-name etcd-backup | grep uas
cray-uas-mgr/etcd.backup_v10_2022-05-17-16:14:09
cray-uas-mgr/etcd.backup_v10_2022-05-17-16:15:09
cray-uas-mgr/etcd.backup_v10_2022-05-17-16:16:09
cray-uas-mgr/etcd.backup_v10_2022-05-17-16:17:09
cray-uas-mgr/etcd.backup_v10_2022-05-17-16:18:09
cray-uas-mgr/etcd.backup_v10_2022-05-17-16:19:09
cray-uas-mgr/etcd.backup_v10_2022-05-17-16:20:09
```
```
ncn-m001-fec36008:/home/bklein # kubectl exec -it -n operators $(kubectl get pod -n operators | grep etcd-backup-restore | head -1 | …
```
> Add cray-uas-mgr to etcd backup list

- chrony/csm_ntp.py
- chrony/requirements.txt
- chrony/templates/cray.conf.j2
- release.sh
Adds our existing `csm_ntp.py` script here so it can be used during upgrades from 1.0 to 1.2 where the script does not yet exist in 1.0.
* Resolves CASMINST-4645
* Merge with https://github.com/Cray-HPE/docs-csm/pull/1649
* `#surtur`
Tested upgrading a node via the standard procedure.
Checked the logs and validated the output looked good.
```
ncn-m001:~ # /usr/share/doc/csm/upgrade/1.2/scripts/upgrade/ncn-upgrade-ceph-nodes.sh ncn-s001
************
*** NOTE ***
************
LOG_FILE is not specified; use default location: /root/output.log
====> CEPH_NODES_SET_NO_WIPE has been completed
====> BACKUP_CEPH_DATA has been completed
====> CSI_VALIDATE_BSS_NTP has been completed
====> ELIMINATE_NTP_CLOCK_SKEW ...
====> WIPE_NODE_DISK has been completed
====> SET_PXE_BOOT has been completed
====> …
```
> CASMINST-4645 add chrony script so it is available for upgrade scenarios

- assets.sh
- rpm/cray/csm/sle-15sp3/index.yaml
Presently the distribution and git information is missing from the RPM metadata.
Additionally RPMs are being published to sle-15sp2 after the vendor change. Currently CSM picks up metal-ipxe from sle-15sp3 repos, this change will restore publishing RPMs to sle-15sp3.
Currently:
```bash
Name        : metal-ipxe
Version     : 2.2.7
Release     : 1
Architecture: noarch
Install Date: (not installed)
Group       : Unspecified
Size        : 737008
License     : GPLv2
Signature   : RSA/SHA256, Tue 17 May 2022 05:48:23 PM UTC, Key ID d4dae1e39da39f44
Source RPM  : metal-ipxe-2.2.7-1.src.rpm
Build Date  : Tue 17 May 2022 05:46:42 PM UTC
Build Host  : …
```
> MTL-1744 Fix RPM Metadata

- CHANGELOG.md
- manifests/platform.yaml
Release cray-node-problem-detector 1.9.0 to use a newer image. 
* Resolves [CASMPET-5555](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5555)
* `mug`
Upgraded the cray-node-problem-detector chart, and verified that events were correctly received by following the smoke test procedures in https://connect.us.cray.com/confluence/pages/viewpage.action?spaceKey=CASMPET&title=Platform+Component+Smoketests
Low.
> CASMPET-5555: use a newer node-problem-detector image

- manifests/platform.yaml
- manifests/sysmgmt.yaml
Create new keycloak client for k8s api OIDC integration for multi-tenancy
* Resolves [CASMINST-4294](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4294)
```
ncn-m001-fec36008:/home/bklein # kubectl logs -n services $pod keycloak-setup | grep oidc
2022-05-19 22:26:59,151 - INFO    - keycloak_setup - Create Keycloak client kubernetes-api-oidc-client
2022-05-19 22:26:59,267 - INFO    - keycloak_setup - Created client kubernetes-api-oidc-client
2022-05-19 22:26:59,267 - INFO    - keycloak_setup - Fetching 'kubernetes-api-oidc-client' client URL from keycloak...
2022-05-19 22:26:59,304 - INFO    - keycloak_setup - Client 'kubernetes-api-oidc-client' has URL 'http://keycloak.services:8080/keycloak/admin/realms/shasta/clients/21711e54-96d4-4acf-9ff0-127cb4f8db2c'.
2022-05-19 22:26:59,304 …
```
> Add oidc client and mappers for multi-tenancy

- rpm/cray/csm/sle-15sp2/index.yaml
Signed-off-by: Jacob Salmela <jacob.salmela@hpe.com>
Includes the new bios/firmware test.
* Resolves CASMTRIAGE-3363
* Merge with https://github.com/Cray-HPE/csm-testing/pull/319
Results in https://github.com/Cray-HPE/csm-testing/pull/319
Low
> CASMTRIAGE-3363 add updated bios/firmware test

- assets.sh
- rpm/cray/csm/sle-15sp2/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
LiveCD:
- [CASMNET-1541](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1541) (canu)
- [CASMNET-1548](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1548) (canu)
- [CASMNET-1549](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1549) (sshd)
NCN:
- [CASMNET-1541](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1541) (canu)
- [CASMNET-1548](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1548) (canu)
- [CASMNET-1549](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1549) (sshd)
Includes some ancillary updates
- cray-nexus is deprecated and replaced by pit-nexus
- manifestgen is currently at 1.3.4 not 1.3.3
> CASMREL-972

- release.sh
Signed-off-by: Jacob Salmela <jacob.salmela@hpe.com>
Adjusted the `rysync` command to make the chrony dir instead of putting the files in the root of the tarball.
* Resolves CASMINST-4668
* Merge with main https://github.com/Cray-HPE/csm/pull/852
* `#drax`
Tested an `rsync` command from a source to the tarball directory.
```
ncn-m001:~ # ls -l /root/chrony
ls: cannot access '/root/chrony': No such file or directory
ncn-m001:~ # rsync -aq /etc/cray/upgrade/csm/csm-1.2.0-beta.127/tarball/csm-1.2.0-beta.127/chrony/ /root/chrony/
ncn-m001:~ # ls -l /root/chrony/
total 8
-rwxr-xr-x 1 root root 7256 May 23 09:45 csm_ntp.py
drwxr-xr-x 2 root root   26 May 23 09:50 templates
ncn-m001:~ #
```
Low.
> CASMINST-4668 adjust rsync path to create chrony dir

- manifests/core-services.yaml
- manifests/platform.yaml
- cray-dhcp-kea version bump to fix type-o in chart
CASMINST-4706 
surtur
- Was upgrade …
> bug/CASMINST-4706 - cray-dhcp-kea version bump to fix type-o in chart

- rpm/cray/csm/sle-15sp2/index.yaml
Adds more logic around checking if a leader exists.
* Resolves [CASMINST-4683](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4683)
* Change will also be needed in master and release/csm-1.2
drax and vshasta
o Verified in vshasta where a cluster had no leader (no patroni services were running on any members)
```
$ ./postgres_replication_lag.sh -p
PostgreSQL cluster checks may take several minutes, depending on the number of attempts per cluster.
Checking to see if any cluster members need a patroni …
```
> CASMINST-4683 main : worker node upgrade failed - cray-console-data-postgres

- CHANGELOG.md
- manifests/platform.yaml
- manifests/sysmgmt.yaml
Add a read-only monitoring role in keycloak in shasta public client, per request from some customers.
* Resolves [CASMPET-5660](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5660)
* Change will also be needed in `1.2.6`
After deploying it in vshasta, validated that a read-only monitoring role "monitor-ro" had been added to the shasta public client (in addition to existing "admin" and "user" roles.)
Low.
> CASMPET-5660: add a read-only monitoring role

- manifests/platform.yaml
Switch anti-affinity from required to preferred so that opa pods don't get stuck redeploying on 3 worker node clusters.
* Resolves [CASMINST-4757](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4757)
* https://github.com/Cray-HPE/cray-opa/pull/42
> Bump cray-opa to 1.10.5

- manifests/sysmgmt.yaml
CASMHMS-5578: Update RTS version to 2.0.2
CASMHMS-5578: Bump application image version to 1.17.0 to pick up fix to only create redfish endpoints in HSM if they do not exist.
• CASMHMS-5579: Updated the service name for the collector, as it was changed in CSM 1.2 to cray-hms-hmcollector-ingress.
* Documentation …
> CASMHMS-5578 csm1.2

- manifests/core-services.yaml
Updates the HSM image version for CASMTRIAGE-3430
ChassisBMC discovery is complete, it should check that all child components are correctly marked as Mountain components. The filtering for identifying the child components was incorrect. This mod fixes the issue.
This also changes HSM to get class from SLS for node components.
* Resolves [CASMTRIAGE-3430](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3430)
For testing see https://github.com/Cray-HPE/hms-smd/pull/76
Low
> Update HSM chart version for CASMTRIAGE-3430

- assets.sh
- docker/index.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
Upgrading Canu from 1.5.7 to 1.6.1.
Disable load balancing configuration for Dell CDU/Leaf.
Add canu report network version feature.
Fix Errors in the output of canu test
Add route-map and prefixes to allow connection to UAI's from CAN network.
Fix Dell4148 template to include correct port count
https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3322
https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1572
Nox, surtur, drax
> canu release 1.6.1 (release/1.2)

- rpm/cray/csm/sle-15sp2/index.yaml
This is a corner case that is being addressed in 1.3
Once the etcd cluster is created, it can take up to hour for the etcd backup crd to get created.
Once the etcd backup crd is created, the etcd backup occur every 24 hours
Thus it can actually take 25 hours after the cluster is created for the backup to exist.
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_ Yes
* Resolves [CASMTRIAGE-3386](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3386)
Tested on drax
* Local …
> CASMTRIAGE-3386-1.3 : TESTS: CSM etcd cluster backups silently failing

- manifests/core-services.yaml
- manifests/platform.yaml
SLS contains a "dummy" BICAN network which serves as the source of the bifurcated CAN systemDefaultRoute setting.
Unfortunately this network also has a CIDR of `0.0.0.0/0` which causes powerdns-manger to create `bican` and `0.in-addr.arpa` zones. Due to the bogus subnet records have erroneously been added to this zone.
This change implements the capability to exclude SLS networks from zone generation and excludes the SLS BICAN network by default.
* Resolves [CASMNET-1063](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1063)
* `mug`
Deployed new chart and image, verified that the `bican` and `0.in-addr.arpa` zones are no longer created.
```
ncn-m001:~ # kubectl -n services exec -it cray-dns-powerdns-86c9685d78-8fdsq -- sh
Defaulting container name to …
```
> CASMNET-1063 - Add ability to exclude SLS networks from zone creation

- rpm/cray/csm/sle-15sp2/index.yaml
The newer version of K8s in CSM changed the output of some `kubectl get nodes` output. This broke some parsing that was attempting to get a list of all worker nodes in the script make_node_groups. As a result, master nodes were included in the list.
Use a more deterministic method of filtering the output to exclude the master nodes fixes the issue. 
* Resolves [CASMTRIAGE-3475](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3475)
mug
* `mug`
The modified script created an HSM group that did not include the master nodes. Before the change master nodes were included in the HSM group `uai`.
Low risk, small change that excludes master nodes
> CASMTRIAGE-3475: Update hpe-csm-scripts to 0.0.34

- assets.sh
The canu rpm was in the sp3 repo in nexus. However, cloud-init was
only looking for rpms in the sp2 repo. This commit links the NCN
images contain a code change to check both repos.
Tested on rebull.
> CASMINST-4791: scan both sp2 and sp3 repos for rpms

- rpm/cray/csm/sle-15sp2/index.yaml
New test to replace manual install steps. See source PR for [CASMINST-4640](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4640) for details:
https://github.com/Cray-HPE/csm-testing/pull/314
This will also implicitly pull in this PR for [CASMINST-4774](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4774) which adds logging to more tests:
https://github.com/Cray-HPE/csm-testing/pull/330
> CASMINST-4640/CASMINST-4774: Goss test improvements

- CHANGELOG.md
- docker/index.yaml
container image version bumps for ceph and k8s
* Resolves CASMPET-5719
* craystack
* redbull
fresh install of vshasta/craystack/redbull with the new images
> Ceph and k8s version bumps

- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
Also brings in the same manifestgen but with fixed RPM metadata, and a
stable RPM name.
> CASMCMS-7876 craycli

- manifests/platform.yaml
Adds UUID and pod disruption policies to allow us to use requiredDuringSchedulingIgnoredDuringExecution pod anti affinity policies without causing upgrade issues on clusters with 3 workers.
* Resolves [CASMINST-4742](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4742)
* Resolves [CASMINST-4757](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4757)
* https://github.com/Cray-HPE/cray-opa/pull/43
* https://github.com/Cray-HPE/cray-istio/pull/32
> CASMINST-4742/4757 Update pod antiaffinity

- manifests/sysmgmt.yaml
The munge container needs to run as the 'munge' user to successfully start the munged process - running as the default 'nobody' user does not work in this context. This is still a non-root user so the security concerns are met while running as the munge user.
NOTE: there was also a change to the munge-munge image that must be picked up for this change to fix the issue.
https://github.com/Cray-HPE/container-images/pull/443
* Resolves [CASMTRIAGE-3526](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3526)
* `Hela`
I used helm to deploy the new cray-crus version and updated the munge-munge image already on the system.  The cray-crus pods all started up correctly and ended in a 'ready' state.  I then exec'd into the munge container and tested that munge is working as expected.
There …
> CASMTRIAGE-3526 - update cray-crus to run munge container with correct user.

- CHANGELOG.md
- manifests/platform.yaml
Release cray-opa 1.17.0 to add OPA rules for read-only monitoring role. This PR allows the added read-only monitoring role to access telemetry APIs and access SMH and SMA Grafana and Kibana UIs.
* Resolves [CASMPET-5664](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5664)
* `mug`
Made sure that a user with read-only monitoring role can log into Grafana UI and have access to telemetry API.
Low.
> CASMPET-5664: Add OPA rules for read-only monitoring role

- manifests/sysmgmt.yaml
he munge container needs to run as the 'munge' user to successfully start the munged process - running as the default 'nobody' user does not work in this context. This is still a non-root user so the security concerns are met while running as the munge user.
NOTE: there was also a change to the munge-munge image that must be picked up for this change to fix the issue.
https://github.com/Cray-HPE/container-images/pull/443
Code PR:
https://github.com/Cray-HPE/cray-crus/pull/23
PR to csm-1.2.6:
https://github.com/Cray-HPE/csm/pull/918
* Resolves [CASMTRIAGE-3526](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3526)
* `Hela`
I used helm to deploy the new cray-crus version and updated the munge-munge image already on the system. The cray-crus pods all started up correctly and ended in …
> CASMTRIAGE-3526: update cray-crus to run munge container with correct user.

- manifests/core-services.yaml
This updates the HSM chart version for:
CASMHMS-5591 - Add indexes to the FRU history table in HSM's database
CASMHMS-4972 - Ignore Baseboard when discovering GPUs
CASMHMS-4973 - ignore NV Switch when discovering GPUs
* Resolves [CASMHMS-5591](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5591)
* Resolves [CASMHMS-4972](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-4972)
* Resolves [CASMHMS-4973](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-4973)
For testing see:
https://github.com/Cray-HPE/hms-smd/pull/78
https://github.com/Cray-HPE/hms-smd/pull/77
Low
> Update HSM manifest version

- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
- rpm/cray/csm/sle-15sp3-compute/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
This is an update to the cfs-trust deployment that changes its certificate population behavior from a PUT to a PATCH operation; this is desirable because it does not remove any existing content and thereby makes it safer to deploy during an upgrade scenario.
Additionally, this service now periodically heals BSS metadata service of missing certificate information, should it go missing for whatever reason.
* Resolves CASMCMS-7783 (https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7783)
* Changes already promoted to corresponding master branch.
* wasp
Tested by modifying existing running cfs-trust on odin with updated functions, first by backing up existing bss metadata.
Low risk.
> CASMCMS-7783

- CHANGELOG.md
- manifests/platform.yaml
The postgres operator in 1.3 is restarting all postgres pods due to changes in the container structure that was introduced by istio changes. This does not effect 1.0, 1.2 or 1.2.6. 
This change modifies the postgres operator image to not assume Containers[0] is the postgres container in the statefulset or pod, but instead find the correct index for the postgres container.
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix? bugfix
* Resolves [CASMPET-5725](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5725)
* Merge …
> CASMPET-5725 1.3 : postgres operator in 1.3 restarting all postgres pods

- assets.sh
- rpm/cray/csm/sle-15sp2/index.yaml
This brings in an SP2 compatible ilorest RPM, this RPM is needed by `prerequisites.sh`.
This also includes a new LiveCD which has the newly created RPM inside.
> CASMTRIAGE-3600 ilorest RPM and LiveCD

- release.sh
Prepare to revoking anonymous access from following RPM repositories:
* https://artifactory.algol60.net/artifactory/csm-rpms/
* https://artifactory.algol60.net/artifactory/hpe-mirror-mlnx_ofed_cx4plus/
* https://artifactory.algol60.net/artifactory/hpe-mirror-hexane/
* Resolves [CASMINST-4829](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4829)
* Locally
Tested by running `gen-rpm-index.sh` script locally with updated credentials JSON file
Low - build pipeline only
> CASMINST-4829 Remove public access from artifactory.algol60.net

- manifests/core-services.yaml
- manifests/platform.yaml
`cray-dns-unbound` does not configure anti-affinity so all pods and end up on the same worker.
```
ncn-m001:~ # kubectl get pods -o wide -A | grep dns-unbound
services            cray-dns-unbound-6d7cdf6cdb-qcz9l                                 2/2     Running     0          34d     10.36.0.31     ncn-w009   <none>           <none>
services            cray-dns-unbound-6d7cdf6cdb-r2gtk                                 2/2     Running     0          53d     10.36.0.13     ncn-w009   <none>           <none>
services            cray-dns-unbound-6d7cdf6cdb-s2vwr                                 2/2     Running     0          3d22h   10.36.0.50     ncn-w009   <none>           <none>
```
Configured pod AntiAffinity to distribute the pods over the workers.
* Resolves …
> CASMNET-1671 - all cray-dns-unbound pods on same worker node preventing clean rolling reboot

- manifests/platform.yaml
Kubernetes 1.21+ updated the kubernetes serviceaccount JWT ISS, breaking kubernetes token access to vault. This updates the issuer in vault, which fixes the issue.
* Resolves [CASMPET-5745](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5745)
* https://github.com/Cray-HPE/cray-vault/pull/7
Validated that spire-intermediate was able to talk to vault after the update. …
> CASMPET-5745 Bump cray-vault to 1.3.0

- chrony/csm_ntp.py
Instead of returning the actual response from bss, this
code was returning an undefined variable.
* Resolves [CASMTRIAGE-3637](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3637)
* `rocket`
Fixed the code, ran the script, success.
> CASMTRIAGE-3637: fix use of undefined variable

- manifests/core-services.yaml
- manifests/sysmgmt.yaml
This PR includes the following changes:
- Update HMS CT tests to stable hms-test:3.1.0 image (upgrades pytest and tavern to work around python issue43798)
- Pull Alpine base image from correct location in algol60 artifactory
- CT test cleanup
* Partially resolves CASMHMS-5458.
This change was tested by deploying the updated version of the services and charts onto Mug, executing the Helm CT tests, and verifying that they passed.
Low risk, test updates.
> CASMHMS-5458 Coordination for HMS CT Helm tests

- CHANGELOG.md
- manifests/platform.yaml
- manifests/velero-1.7-upgrade.yaml
This will upgrade to 1.6.3 via the platform manifest, then we will need to apply another manifest to do the second upgrade.  this will get us within a  release of current upstream
* Resolves CASMPET-5332
- Was downgrade tested? If not, why? y
> update to manifest for velero double upgrade in 1.3

- chrony/csm_ntp.py
This script requires python3. While python2 has long been deprecated,
python2 is still required by the Mellanox software stack and may
be configured as the default python on the system.
* Resolves [CASMTRIAGE-3657](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3657)
* Change will also be needed in `release/1.2`, `main`
* `shandy`
> CASMTRIAGE-3657: change shebang to explicitly specify python3

- CHANGELOG.md
- manifests/storage.yaml
image feature layering was missing when upgrade from 1.0.x and earlier versions
* Resolves CASMTRIAGE-3674
* shandy
> Casmtriage 3674 1.2

- manifests/nexus.yaml
- manifests/platform.yaml
This change will update the nexus image to a much more recent version released. The change is not easily downgraded however documentation updates will allow for ability to rollback. The only change in this nexus update is to bring the image up to a version that is much newer. The impact is low and there has been much testing to ensure update works well as well as upgrade.
* Resolves [CASMPET-5397](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5397)
* Drax - Full backup upgrade and restore
* Surtur - Just backup and restore
- Was downgrade tested? If not, why? y
- Were new tests (or test issues/Jiras) created for this change? y
The only risk is with a rollback to old versions. That is solved by using the export/restore procedure …
> CASMPET-5397: Upgrade the image version of nexus

- manifests/sysmgmt.yaml
IPXE Binary Name Randomization for Added Security. This is the change needed to csm-ipxe service.
Code change was in this PR:
https://github.com/Cray-HPE/cms-ipxe/pull/38
v1.2.6 manifest PR:
https://github.com/Cray-HPE/csm/pull/967
* Resolves [CASMCMS-2930](https://jira-pro.its.hpecorp.net:8443/browse/CASM-2930)
Described in above code PR.
Described in above code PR.
> CASM-2930 - merge to v1.3.0 manifest.

- manifests/sysmgmt.yaml
Pick up changes from the csm-1.2.6 manifest that were missed in moving to csm-1.3 manifests.
The services with updated versions are:
cray-cfs-api
cfs-trust
cray-console-node
These were tested as part of inclusion in csm-1.2.6.
The risk is in not keeping the versions up to date - if not included fixes in csm-1.2.6 will regress in csm-1.3.0.
> CASMCMS-8065 - update csm-1.3 manifest with csm-1.2.6 changes.

- CHANGELOG.md
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
Update craycli to 0.56.0
This brings the BOS comands up to date (0.54.0), removes the obsolete `cray network` subcommand from the CLI (0.55.0), and finishes the BOS changes (0.56.0).
These changes are backward compatible.
* Resolves CASMCMS-8064 (0.56.0)
* Resolves [CASMCLOUD-1208](https://jira-pro.its.hpecorp.net:8443/browse/CASMCLOUD-1208) (0.55.0)
* Resolves CASMCMS-7876/CASMCMS-7848 (0.54.0)
The changes for 0.55.0 were tested by linting the code and running unit tests, then running the `cray network --help` command and verifying that there was no `network` sub-command supported.
The changes for 0.54.0 and 0.56.0 (per the description provided …
> CASMCLOUD-1208 Update craycli to 0.56.0

- lib/install-goss-tests.sh
I don't have a Jira open for this, because Jira is not happy at the moment. 
This corrects one problem found so far in the surtur install attempt of csm-1.3.0:
It updates the Goss server install script to make use of the correct PIT variables to find the RPMs. It was making some assumptions which were no longer true.
I tested the updated Goss script on surtur and it worked as expected.
Install is broken without these fixes.
> Fixes from ongoing attempt to install surtur with csm-1.3.0

- rpm/cray/csm/sle-15sp2/index.yaml
This will bring in a 1.3 version of the ceph service check with the fix for osd service name changes
* Resolves CASMTRIAGE-3686
* surtur
live debugging on surtur
> bump testing and utils versions

- manifests/platform.yaml
Bumping velero to 1.6.3-2 to fix a sub chart image location
This is to fix the sub chart image reference 
* Resolves CASMINST-4952
> Release cray-velero-1.6.3-2

- CHANGELOG.md
- manifests/platform.yaml
Increased istiod replica count from 1 to 3, and adjusted its hpa autoscale range to be 3 (min) to 8 (max) to better handle up pod bring-up surge.
* Resolves [CASMPET-5621](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5621)
Upgraded the cray-istio charts, and verified istiod with 3 pods by default, and hpa setting is now set to the range of 3 to 8. …
> CASMPET-5621: adjust istiod replicaCount and hpa setting

- manifests/platform.yaml
Some images that got version bumps need updates in the pre-cache image chart (goss test properly flagged these).
* Resolves [CASMINST-4962](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4962)
Applied on surtur -- no failures now:
```
surtur-ncn-m001-pit:~ # kubectl -n nexus logs -l app.kubernetes.io/name=cray-precache-images --tail=100 | grep failed
```
* `surtur`
Updated the cm on surtur and restarted the pods -- they pulled the newer images.
Low
> Update pre-cache config map with correct 1.3 image versions

- CHANGELOG.md
- manifests/sysmgmt.yaml
Update the alpine base image version and shift to the ones on algol60 that are being rebuilt nightly for better automatic CVE remediation and fix instances of using arti.dev.cray.com which will be inactive at the end of August.
This also picks up the anti-affinity settings in cray-console-node to keep multiple pods from residing on the same worker.
* Resolves [CASMCMS-7830](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7830)
* Resolves [CASMCMS-8055](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8055)
* `Drax`
Installed via helm on Drax with the other console services. Did complete test with flushing cached data and made sure all new services came up and operated as expected, including connecting to live console sessions on compute nodes. Rolled back to previous installed …
> CASMCMS-7830 - update base images for CVE remediation.

- CHANGELOG.md
- manifests/sysmgmt.yaml
The hsm v1 interface is being removed from the service, so we needed to switch to using the v2 interface. The endpoints that we are using are identical in both versions so this was a minimal change.
NOTE: this will conflict with the following manifest PR.  Make sure to merge the below PR first, then this one:
https://github.com/Cray-HPE/csm/pull/999
Code PR's:
https://github.com/Cray-HPE/console-operator/pull/30
https://github.com/Cray-HPE/console-node/pull/52
* Resolves [CASMCMS-8016](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8016)
* `Mug`
I used helm to upgrade the existing deployments of console-operator and console-node, forced a complete regeneration of the console connections, and verified the information needed is being pulled correctly from the new hsm interface and the …
> CASMCMS-8016 - update the console services to use HSM v2 api.

- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp3-compute/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
This manifest change adds the BOS v2 service to the 1.3 release. Contained in this helm chart change are both versions of BOS (v1 and v2). This manifest change represents the culmination of work accomplished under the CASM-2270 epic.
* Promotes [CASM-2270](https://jira-pro.its.hpecorp.net:8443/browse/CASM-2270) to the 1.3 release (when its cut).
* Depending on when release/1.3 is made, It will also require promotion to this release.
Installed on groot for testing; because groot is a 1.1/1.2 system, additional manual changes to the deployed manifest were also required.
* groot (install and functional boot testing)
* wasp ( historical functional testing against an older …
> Add BOS v2 feature work to 1.3 installs

- manifests/sysmgmt.yaml
This updates the request-ncn-join-tokens to support the new spire paths in CSM 1.3. It also adds a toggle to allow vshasta to work properly (default is off). 
* Resolves [CASMTRIAGE-3714](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3714)
* https://github.com/Cray-HPE/cray-spire/pull/45
* https://github.com/Cray-HPE/container-images/pull/449
Validated that requests-ncn-join-token worked properly after upgrading the helm chart.
- Was downgrade tested? If not, …
> CASMTRIAGE-3714 Bump spire to 2.8.0

- manifests/sysmgmt.yaml
This is pulling in a fix that's in the 1.2.0 build into release/1.2. This fixes an anti-affinity issue with the postgres-pooler and an issue where the connections between opa and spire-jwks could be exhausted when a large number of computes are running.
* Resolves [CASMPET-5785](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5785)
This is pulling in a fix that's in the 1.2.0 build into release/1.2.
> CASMPET-5785 Bump spire to 2.6.5

- manifests/core-services.yaml
- manifests/sysmgmt.yaml
This updates:
hms-smd - v2.1.6
hms-bss - v2.1.2
hms-hmnfd - v2.1.3
hms-rts - v2.0.3
hms-scsd - v2.1.3
hms-hbtd - v2.1.3
hms-capmc - v3.0.4
hms-meds - v2.0.2
hms-discovery - v2.0.3
hms-hmcollector - v2.15.7
* Resolves [CASMHMS-5616](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5616)
> Update chart versions for HMS charts affected by removing the HSM v1 API

- CHANGELOG.md
- manifests/platform.yaml
Update cray-oauth2-proxies chart to use the new oauth2-proxy v7.3.0 image for CVE remediation.
* Resolves [CASMPET-5697](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5697)
* `mug`
Deployed the new helm chart, and verified the following test script still PASS as it uses oauth2-proxy:
tests/install/livecd/scripts/monitoring_check.sh …
> CASMPET-5697: Updated cray-oauth2-proxies for CVE remediation

- ncn-image-modification.sh
For some reason, create-kis-artifacts.sh is unable to unmount a
bind mount within an NCN chroot environment, but *is* able to do
so in the PIT environment. This needs further investigation. The
change in this commit allows it to compensate for the error on
NCNs, while being a no-op on the PIT.
* Resolves [CASMINST-4968](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4968)
* Future work required by [CASMINST-4974](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4974)
Tested on drax on an NCN during an upgrade from 1.2 to 1.3.
Tested on the redbull PIT.
N/A
> CASMINST-4968: ignore errors from create-kis-artifacts.sh for now

- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
Move to updated cmstools and cray-crus that stop using the deprecated v1 HSM API and use v2 instead.
Both of these things will be broken without this change, since v1 is gone in csm v1.3.
> CASMCMS-8073/CASMCMS-8074: cray-crus, cmstools stop using deprecated HSMv1 API

- manifests/core-services.yaml
This updates the HSM and SLS chart versions for:
CASMHMS-5610 - Fixed POST /Inventory/RedfishEndpoints returning 500 instead of 409 for conflicts.
CASMHMS-5463 - Fixed smd-init job permissions issues
CASMHMS-5475 - Fixed sls-init job permissions issues
* Resolves [CASMHMS-5610](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5610)
* Resolves [CASMHMS-5463](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5463)
* Resolves [CASMHMS-5475](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5475)
For testing see:
https://github.com/Cray-HPE/hms-smd-charts/pull/22
https://github.com/Cray-HPE/hms-sls-charts/pull/13
none.
> Update HSM and SLS chart versions

- manifests/sysmgmt.yaml
Switches cfs-hwsync-agent from the v1 hsm endpoints to the v2 endpoints
* Resolves CASMCMS-8014
* Hela
Deleted a component and allowed it to be recreated.  Also compared the data from all used endpoints to confirm that there were no changes.
None
> CASMCMS-8014: Update cfs-hwsync-agent to use hsm v2

- CHANGELOG.md
- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
We will be adding the fabric-manager service to the hmn API gateway. This is the first REST API to be available on that gateway. Therefore, we will now need to have the name api.hmnlb.SYSTEM_DOMAIN on that gateway. 
This handles the addition of that annotation for 1.3 fresh installs.   There will be a separate Jira for upgrades.
* Resolves CASMPET-5795
* `mug`
Added api.hmnlb.mug.dev.cray.com annotation to the istio-ingressgateway-hmn service.  Verified that the name was created in powerdns and I was able to access the fabric-manager service via api.hmnlb.mug.dev.cray.com after manually adding the hmn-gateway to the slingshot-fabric-manager virtual service.
Very low risk.  This is an addition.   Will not disrupt the other gateways.
> CASMPET-5795: Add api.hmnlb.SYSTEM_DOMAIN to the annotations for istio-ingressgateway-hmn

- manifests/platform.yaml
Refactor namespaces controlled by hnc controller, create specific namespaces for tapms and slurm.
* Resolves [CASMINST-4841](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4841)
* Resolves [CASMINST-4843](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4843)
```
multi-tenancy
├── slurm-operator
├── tapms-operator
└── tenants
├── [s] vcluster-coke
│   └── [s] vcluster-coke-user
└── [s] vcluster-pepsi
└── [s] vcluster-pepsi-user
[s] indicates subnamespaces
```
```
ncn-m001-48d9c509:/home/bklein # kubectl get secrets -n slurm-operator
NAME                  TYPE                                  DATA   AGE
default-token-vt5br   kubernetes.io/service-account-token   3      4m2s
wlm-s3-credentials    Opaque                                7      2m23s
``` …
> Add hnc/tapms charts, update others for namespace configuration

- manifests/sysmgmt.yaml
Update pause image to 3.4.1. This fixes an issue where the pause container fails to start due to Kyverno modifying its security context to run as nonroot.
* Resolves [CASMTRIAGE-3754](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3754)
* https://github.com/Cray-HPE/cray-spire/pull/46
* surtur
Validated that the request-ncn-join-token pods came up correctly after the updated spire chart was applied.
- Was downgrade tested? If not, why? N, not needed.
- Were new tests (or test …
> CASMTRIAGE-3754 Bump spire to 2.8.1

- manifests/platform.yaml
- Update opa-envoy to 0.42.1
- Add opa rego strict check to validate opa code is written correctly for the current version
- Fix opa code that failed the strict check
* Resolves [CASMPET-5793](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5793)
* https://github.com/Cray-HPE/cray-opa/pull/50
Validated pods started and didn't error. 
Further testing is needed on bare metal with all products installed.
This is a major version bump and needs to be tested on a bare metal 1.3.0 …
> CASMPET-5793 Update cray-opa to 1.18.0

- CHANGELOG.md
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
Taken from the CLI PR that created this new version:
This change updates the scsd docs in the cray cli. It brings in the changes to scsd to support getting and setting TPM State in the bios. We plan to include these changes in CSM 1.3
Examples:
```
cray scsd bmc bios tpmstate list x3000c0s27b0n0
cray scsd bmc bios tpmstate update x3000c0s27b0n0 --future Disabled
cray scsd bmc bios tpmstate update x3000c0s27b0n0 --future Enabled
```
This change is backward compatible in the following way
* The existing command lines will continue to work as they did before
* The new command line `cray scsd bios tpmstate` will show up in the usage statements, but will fail when the new scsd is not present.
* Resolves CASMHMS-5606
* mug (1.2)
* groot (1.0)
Tested on mug and groot with the latest SCSD.
Added …
> CASMHMS-5606 Bump CLI RPM version to 0.57.0

- manifests/core-services.yaml
- manifests/platform.yaml
Resolves the following issues
* An SLS alias consisting of the node xname resulted in a bad CNAME record which was in conflict with the A record.
```
x3000c0s3b0n0.nmn.drax.dev.cray.com	3600	IN	CNAME	x3000c0s3b0n0.nmn.drax.dev.cray.com.
```
* Matching SLS static and HSM dynamic data could result in the same record being generated twice causing the PowerDNS API patch request to fail as the API does not permit duplicate records.
* Change chart `imagePullPolicy` to `IfNotPresent` to avoid negating the benefit of pre-caching the image on the NCNs.
* Resolves [CASMNET-1674](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1674), [CASMNET-1143](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1143), and [CASMNET-1724](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1724).
* `fanta` …
> CASMNET-1143/CASMNET-1674 - Record generation fixes

- CHANGELOG.md
- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
We will be adding the fabric-manager service to the HMN API gateway. This is the first REST API to be available on that gateway. That API will need to be authenticated by keycloak so we will need to add allowed-issuers to the cray-opa service in customizations.yaml like we have for the other ingress gateways.
While adding this, I also realized that we need to add the auth.hmnlb name to the istio-ingressgateway-hmn service.
Adding these items on upgrade will be handed by CASMPET-5811.
* Resolves CASMPET-5817
There is not much testing that can be done until CASMPET-5812 and CASMPET-5813 are done.  The allowed-issuers for istio-ingressgateway-hmn will not be used until the template for the HMN opa policy is completed in CASMPET-5813.
> CASMPET-5817:  Add allowed-issues to customizations.yaml for istio-ingressgateway-hmn

- rpm/cray/csm/sle-15sp2/index.yaml
The new spire-agent rpm uses /var/lib/spire instead of /root/spire. This
fixes the path issues.
* Resolves [CASMINST-5051](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5051)
* https://github.com/Cray-HPE/utils/pull/53
* https://github.com/Cray-HPE/csm-rpms/pull/506
* drax
Validated script ran successfully and storage nodes joined to spire.
- Was downgrade tested? If not, why? N, not applictable
> CASMINST-5051 Bump platform-utils to 1.3.1

- manifests/core-services.yaml
This re-adds the HSM v1 APIs to CSM and adds the bugfixes that came after the HSM v1 APIs had been removed.
* Resolves [CASMHMS-5625](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5625)
For testing, see https://github.com/Cray-HPE/hms-smd/pull/82
> Re-add HSM v1 APIs

- CHANGELOG.md
- manifests/core-services.yaml
Changed the hardware and network search APIs to build the sql requests with parameters.
* Resolves CASMHMS-5488
* mug
Was a Downgrade tested? Y
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing? NA
Compared the results of these queries with and without this PRs changes:
/v1/search/hardware?parent=s0
/v1/search/hardware?xname=x3000c0h42s1
/v1/search/hardware?type=comptype_node
/v1/search/hardware?class=River
/v1/search/hardware?extra_properties.NID=100007
/v1/search/hardware?extra_properties.VendorName=ethernet1/1/23
/v1/search/hardware?node_nics=x3000c0s7b0
/v1/search/hardware?networks=ncn …
> CASMHMS-5488 Changed how sls search API generates SQL

- manifests/platform.yaml
Add validation for xnames by type and refactor lib package so webhook can access
* Resolves [CASMINST-4792](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4792)
Validated create/update blocked when specifying a non-compute xname:
```
ncn-m001-48d9c509:/home/bklein/demo # kubectl -n tenants -f pepsi/tenant.yaml apply
Error from server (the following xname(s) do not have type Node and role Compute: [x0c3s2b0]): error when creating "pepsi/tenant.yaml": admission webhook "vtenant.kb.io" denied the request: the following xname(s) do not have type Node and role Compute: [x0c3s2b0]
```
Multiple iterations of create/modify/delete
Low
> Add validation for xnames by type and refactor lib package so webhook can access

- manifests/platform.yaml
Switches will be talking to the fabric manager through the hmn gateway via a keycloak JWT. This requires a new hmn opa policy to be added for this to work properly.
* Resolves [CASMPET-5813](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5813)
* https://github.com/Cray-HPE/cray-opa/pull/52
Validated that the hmn opa pods and envoyfilter was created properly. This needs additional testing on a bare metal system.
- Was downgrade tested? If not, why? YB
- Were new …
> CASMPET-5813 Bump cray-opa to 1.19.0

- manifests/sysmgmt.yaml
The URL being used to test communication with CAPMC was removed. Changed it to the health CAPMC health URL.
* Resolves [CASMINST-5031](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5031)
* `surtur`
Validated similar test for gateway testing with new CAPMC health URL on surtur.
PASS - [cray-capmc]: https://api.cmn.surtur.hpc.amslabs.hpecorp.net/apis/capmc/capmc/v1/health - 200
Overall Gateway Test Status: PASS
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? goss test passed
- Was upgrade tested? If not, why? N - N/A
- Was downgrade tested? If not, why? N - N/A
No known risks.
> Change CAPMC URL for uai-images

- CHANGELOG.md
- manifests/sysmgmt.yaml
Adds better handling for cases where Kafka is unavailable when the cfs-operator starts up.  Previously the client setup would never be retried, but this has been moved into the retry loop.
* Resolves CASMCMS-7941
- Tested startup of the cfs-operator and connection to Kafka.
None
> CASMCMS-7941: Update cfs-operator for kafka client init stability

- CHANGELOG.md
- manifests/platform.yaml
Add keycloak service to hmn-gateway for fabric_manager.
* Resolves [CASMPET-5812](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5812)
Verified that the cray-keycloak service is now exposed to hmn-gateway in addition to other gateways after upgrading.
$ kubectl get vs -A | grep keycloak
services keycloak ["services-gateway","customer-admin-gateway","customer-user-gateway","hmn-gateway"] ["*"] …
> CASMPET-5812: add keycloak service to hmn-gateway

- manifests/platform.yaml
Add validation check for xname in two hsm exclusive groups
* Resolves [CASMINST-5086](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5086)
```
ncn-m001-48d9c509:/home/bklein/demo # kubectl -n tenants -f coke/tenant.yaml apply
Error from server (the following xname(s): '[x0c3s3b0n0]' already exist in an exclusive hsm group): error when creating "coke/tenant.yaml": admission webhook "vtenant.kb.io" denied the request: the following xname(s): '[x0c3s3b0n0]' already exist in an exclusive hsm group
```
Ran through create/modify/update
Low
> Add validation check for xname in two hsm exclusive groups

- rpm/cray/csm/sle-15sp2/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
This addresses a large number of problems related to the Goss tests. Without this fix, there are a number of failures we can expect to see.
I tested the changes on surtur.
This also switches us over to using the SP3 build of the RPM, since the NCNs are installed with SP3.
See the source PR for details:
https://github.com/Cray-HPE/csm-testing/pull/345
I tested the changes on surtur.
Moderate risk in that there are a number of changes, but low risk in that without this there will be a lot of problems.
> CASMINST-5025: Numerous Goss testing fixes

- manifests/sysmgmt.yaml
CASMCMS-8104: Modify the CSM configuration play to define the csm-sle-sp15sp3 zypper repository on the NCNs, so that they can install RPMs from them.
CASMINST-5090: Remove the no-longer-existent HMS CT test RPMs from NCN personalization
Resolves:
* https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8104
* https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5090
CASMCMS-8104: Tested updated config on drax.
CASMCMS-8104+CASMINST-5090: Tested hotfix for both combined on tyr.
Low risk, and necessary.
> CASMCMS-8104: Create SP3 zypper repo in NCN personalization; CASMINST-5090: Remove HMS CT test RPMs from csm config

- manifests/core-services.yaml
- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
This PR includes the following changes for the Helm CT tests:
- kill the istio sidecar after the tests run to save wait time
- remove build dependencies from final test image that aren't needed to run the tests
- revert the test base image to alpine:3.15 to resolve CVEs
- improve log file readability
It also updates the cray-smd-init and cray-reds-vault-loader jobs to respect the global appVersion for overrides.
* Resolves CASMHMS-5612.
* Resolves CASMHMS-5593.
Merge with:
- https://github.com/Cray-HPE/hpe-csm-scripts/pull/22
- https://github.com/Cray-HPE/csm-rpms/pull/510
This change was tested by deploying a new version of an HMS service on Mug which pulled in the latest version of the hms-test image, executing its Helm CT tests, and verifying that they passed. Also verified that the …
> CASMHMS-5612/CASMHMS-5593 HMS Helm CT test enhancements, CVE remediation, chart global.appVersion standardization

- manifests/platform.yaml
Fix for https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5107 -- bump chart timeout for pre-cache images daemonset.
```
apiVersion: manifests/v1beta1
metadata:
name: brad
spec:
charts:
- name: cray-precache-images
namespace: nexus
version: 0.5.6
timeout: 20m0s  <-----
values:
cacheImages:
- artifactory.algol60.net/csm-docker/stable/docker.io/weaveworks/weave-kube:2.8.1
- artifactory.algol60.net/csm-docker/stable/docker.io/weaveworks/weave-npc:2.8.1
- artifactory.algol60.net/csm-docker/stable/docker.io/nfvpe/multus:v3.7
. 
. 
. 
```
```
bash-5.1# /tmp/loftsman  ship --manifest-path /workspace/.cache/manifest.yaml --charts-path /workspace/.cache/charts --json-log-path /workspace/.cache/loftsman.json.log
2022-07-25T18:45:33Z INF Initializing the connection to the Kubernetes cluster …
```
> Increase loftsman timeout for precache images chart

- rpm/cray/csm/sle-15sp3/index.yaml
Changes the size required for Nexus during an upgrade. This was gotten from information about the size of releases.
* Resolves [CASMPET-5756](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5756)
* mug
I ran the goss test with varying required sizes to check. 
- Was downgrade tested? If not, why? y
No new risks added with this change
> CASMPET-5756: Update Space Required for Nexus

- manifests/platform.yaml
- manifests/sysmgmt.yaml
heartbeat is now using spire tokens by default. This disabled the spire authentication bypass for heartbeats and fixes issues with heartbeat spire access.
* Resolves [CASMPET-5835](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5835)
* https://github.com/Cray-HPE/cray-opa/pull/53
* https://github.com/Cray-HPE/cray-spire/pull/47
* `fanta`
Validated that storage nodes started heartbeating properly.
heartbeats with xname filtering enabled needs to be tested to validate the API URLs are …
> CASMPET-5835 Enable heartbeat spire auth

- manifests/sysmgmt.yaml
Pick up newer version of RTS that utilized cert-manager for its default certificate, and is no longer use a hard coded default cert.
* Resolves [CASMHMS-5607](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5607)
* Mug
_How were the changes tested and success verified? If schema changes were part of this change, how were …
> CASMHMS-5607: Pick up newer version of RTS that utilized cert-manager for its certificate, and is no longer hard coded.

- manifests/platform.yaml
Adding UUID to status section will allow us to differentiate between two tenants with the same name (one already deleted).
* Resolves [CASMINST-4907](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4907)
```
{
"vcluster-coke-user",
"vcluster-coke-slurm"
],
"state": "Deployed",
{
"hsmgrouplabel": "coke",
"xnames": [
"x0c3s5b0n0",
"x0c3s6b0n0"
]
}
],
"uuid": "d6ffdf70-5ef0-4ed1-9f06-3059a30839a0"
}
```
Ran several chart updates -- created/modified/deleted tenants...
Low
> Add UUID to tenant status section (CASMINST-4907)

- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp3-compute/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4-compute/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Updated BOA is compatible with CAPMC versioned endpoint changes.
It was discovered that the previous version of BOS was launching a BOA image that was targetting capmc endpoints that no longer exist. These endpoints were deprecated in favor of their versioned endpoint compatible pieces (/v1/). Unfortunately, BOA changes that reflect this were not included with BOS because they were not published to a release branch.
This change adds that compatibility back, as well, adds RPMs that went missing from the manifest as a function of a perceived build issue.
* Resolves [CASMINST-5096](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5096)
Built the associated helm chart and …
> Bump cray-bos chart and associated RPMs to include a chart manifest

- rpm/cray/csm/sle-15sp2/index.yaml
Add the postgres container to the kubectl exec commands for the ncnPostgresHealth script.
Related goss test and doc changes were done as part of [CASMPET-5786](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5786) and [CASMTRIAGE-3727](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3727)
* Resolves [CASMPET-5837](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5837)
Ran the script to verify the fix to add the container to `kubectl exec`
```
.
.
.
PASSED. All postgresql checks passed.
```
surtur
Low
> CASMPET-5837 1.3 : Break/Fix: Unable to determine a leader for the cray-console-data-postgres cluster

- rpm/cray/csm/sle-15sp3/index.yaml
Adds the option for users to specify the image used in the barebones boot test. In some cases, the default of picking the first image with "barebones" in its name does not work. This allows a way to handle that, if it occurs.
Source PR: https://github.com/Cray-HPE/cms-tools/pull/44
csm-rpms PR: https://github.com/Cray-HPE/csm-rpms/pull/518
Doc PR: https://github.com/Cray-HPE/docs-csm/pull/2134
I tested this on rocket, both with and without an ID being specified, to make sure that both cases still work correctly. I also tested to make sure it behaved appropriately if an invalid ID is specified.
Low risk -- the default behavior of the test is not changed. This only adds a new option. And this new option allows some people to be able to run the test who otherwise would not be able to.
> CASMCMS-8068: Allow user to specify image used in barebones test

- CHANGELOG.md
- manifests/platform.yaml
Upgrade to istio 1.10.6.
* Resolves [CASMPET-5796](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5796)
* `mug`
In both vshasta and mug systems, upgraded the istio charts to use the new v1.10.6 images (as well as latest opa envoy plugin & kiali v1.36.7)and validated the following:
* capmc api call still works with an admin token
* kiali & grafana UIs still work and show the correct component versions
* can still log into keycloak UIs (after restarting keycloak-postgres & cray-keycloak statefulsets to run the new envoy sidecar for them) and create clients & users …
> CASMPET-5796: cray-istio and cray-kiali versions for istio 1.10.6

- rpm/cray/csm/sle-15sp3/index.yaml
See source PRs for details:
https://github.com/Cray-HPE/csm-testing/pull/348
https://github.com/Cray-HPE/csm-testing/pull/347
Fixes: [CASMINST-5124](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5124)
Fixes: [CASMINST-5129](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5129)
Tested changes on surtur.
Without these changes, one of the goss test scripts does not work, and the goss-servers RPM cannot be updated to a new version in the NCN images.
> CASMINST-5124/CASMINST-5129: Fix NCN image build issue, Fix typo in ncn-healthcheck-master script

- manifests/core-services.yaml
* Add SLS Migrator to deal with malformed data from older CSM releases.
* When malformed liquid-cooled Chassis data is encountered a corresponding ChassisBMC will be created.
* When malformed xname derived fields (Parent, Type, TypeString) are encountered the object will be PUT back into SLS to recalculate the fields.
* Added CDUMgmtSwitch as an acceptable type to the SLS CT functional tests.
* Resolves …
> CASMINST-3788: Bump SLS version

- manifests/sysmgmt.yaml
Fix the import of the barebones image and recipe.  There was a change the base image that we use to build the barebones image from the recipe that resulted in file permissions that didn't allow the 'nobody' user to access the resulting boot image file.  This fixes the file permissions so the boot image can be transferred to the install image and installed on the system. 
Code PR's:
https://github.com/Cray-HPE/image-recipes/pull/25
https://github.com/Cray-HPE/ims-load-artifacts/pull/19
* Resolves [CASMTRIAGE-3756](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3756)
* `Surtur`
I uploaded new versions of the images and helm charts, then used helm/loftsman to uninstall/re-install the package. This is not a running service, it just kicks off an import job that completes and exits. …
> CASMTRIAGE-3756 - fix import of barebones image.

- manifests/core-services.yaml
This mod updates the HSM chart version to 2.1.8 for:
- CASMHMS-5355 - Changes the `/hsm/v2/locks/reservations/check` API to return failures for reservations that don't exist.
- CASMHMS-5387 - Enhances discovery to properly discover power URLs and control info for Intel nodes.
* Resolves [CASMHMS-5355](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5355)
* Resolves [CASMHMS-5387](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5387)
For testing, see https://github.com/Cray-HPE/hms-smd/pull/86
Low
> HSM Locking and Discovery Improvements

- manifests/sysmgmt.yaml
Fixes two bugs introduced in BOS v2.  One was a regression that made listing v1 sessiontemplates sometimes fail.  The other was a race condition where rebooting a node with the same CFS configuration could result in the BOS session completing before configuration was complete.
* Resolves CASMCMS-8085
* Resolves CASMCMS-8103
* Fanta
Tested know failure cases before and after the update.  See original PRs for more detail.
No
> CASMCMS-8085/8103: Fix BOS v2 bugs

- CHANGELOG.md
- manifests/platform.yaml
Allow keycloak token to be retrieved for hmn in order to support fabric manager.
* Resolves [CASMPET-5840](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5840)
* `surtur`
Verified that keycloak token can now be retrieved within hmn, after the chart is upgraded.
Low.
> CASMPET-5840: whitelist keycloak for hmn

- CHANGELOG.md
- manifests/sysmgmt.yaml
Adding HMNLB network to the gateway tests now that the hmn-gateway has authN and authZ.
I added the cray-nls (argo) service to the set of tested services since that was added in 1.3.
I also changed the use-api-gw-override to false so the test is no longer using api-gw-service-nmn.local.   We are starting to move away from that name.
The HMNLB network is not accessible on the UAI so it only ends up trying to get a token and then moving on when it finds that it cannot get the token (as expected).
* Resolves CASMNET-1741
* `surtur`
Ran the gateway tests on both NCN and UAI on surtur.   All UAI tests passed. 
I also ran the tests on an earlier install of surtur where the UAI did not have the HMN and HMNLB blocked.  The test caught …
> CASMNET-1741:  Update gateways tests to include HMN gateway

- manifests/sysmgmt.yaml
Olympus hardware doesn't allow multiple power cap controls to be modified at the same time but there is something called a deep patch that is available. Converted CAPMC to use the deep patch mechanism for Olympus nodes.
* Resolves [CASMHMS-5436](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5436)
Tested on:
* `loki`
Upgraded to test CAPMC and verified power cap setting can be applied with the newer CAPMC using the deep patch.
HAS A SECURITY AUDIT BEEN RUN? (./runSnyk.sh) Y
ARE THERE KNOWN ISSUES WITH THESE CHANGES? N
ANY OTHER SPECIAL CONSIDERATIONS? N
> Use Controls.Deep PATCH for Olympus power capping

- manifests/platform.yaml
Expand kyverno policy to include more BOS V2 pods.
CASMPET-5501
Yes. See https://github.com/Cray-HPE/cray-kyverno-policies/pull/2.
Low.
> CASMPET-5501: Pulling in latest kyverno-policy

- CHANGELOG.md
- rpm/cray/csm/sle-15sp2/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
Adding the container (-c etcd) when exec'ing into the etcd pods.
This covers changes needed for:
** ncnHealthCHecks.sh (utils)
** goss tests (csm-testing)
** md docs (docs-csm)
This change is not needed for csm 1.0 or 1.2.
Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix? bug fix
* Resolves [CASMPET-5838](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5838)
* Change will also be needed in NA (only needed for CSM 1.3 and beyond)
drax
* `drax`
Ran ncnHealthChecks and goss test to verify no regressions in the fix. …
> CASMPET-5838-1.3 : Break/Fix: Etcd health checks failing - need to specificy etcd container

- manifests/core-services.yaml
This PR updates hms-discovery to use the hms-mountain-discovery:0.7.0 image which includes the following changes:
- Updated hms-mountain-discovery to build using GitHub Actions instead of Jenkins.
- Pull images from artifactory.algol60.net instead of arti.dev.cray.com.
- Updated Alpine base image version.
- Updated and fixed runUnitTest.sh.
* Resolves CASMHMS-5631.
This change was tested by verifying that the new hms-mountain-discovery version was built successfully using GitHub Actions and the resulting image was pushed to the expected location in Algol60 Artifactory. The newly built hms-mountain-discovery was also spun up locally in a docker-compose environment. No integration or CT tests to run for hms-mountain-discovery or hms-discovery.
Was an Upgrade …
> CASMHMS-5631 Update hms-mountain-discovery image to v0.7.0 built with GitHub Actions

- CHANGELOG.md
- docker/index.yaml
- manifests/sysmgmt.yaml
Most of the changes here are related to the upcoming retirement of the dev.cray.com domain - artifacts still used in that domain needed to have server addresses updated to the new location in the hpe network.
This also pulls in a dependency update for ims-utils that was causing problems with python modules.
There is also a small change to the default ims job size to handle larger images.
* Resolves [CASMCMS-7970](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7970)
* Resolves [CASMCMS-8093](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8093)
* Resolves [CASMCMS-8015](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8015)
* `Fanta`
I put the entire final package of changes together and upgraded the IMS installation on fanta via helm.  I then ran a recipe build job and an …
> CASMCMS-7970 - build automation updates.

- manifests/sysmgmt.yaml
Update the csm-config version. Adds the csm.ncn.ca_cert role for CFS.
https://jira-pro.its.hpecorp.net:8443/browse/MTL-1864
https://github.com/Cray-HPE/csm-config/pull/66
https://github.com/Cray-HPE/docs-csm/pull/2163
* Hermod
Created a new CFS configuration on Hermod and added the role. The play ran successfully and included the desired changes.
Low risk.
> MTL-1864 add ca-cert role to csm-config

- manifests/platform.yaml
Use mutating webhook to publish correct state for dependent operators, as well as adding new state.  This change moves the 'state' field form the status section to spec.
* Resolves [CASMINST-4908](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4908)
```
"spec": {
"user",
"slurm"
],
"state": "Deployed",    <----------- moved from 'status' section
"tenantname": "vcluster-pepsi",
{
"hsmgrouplabel": "pepsi",
"xnames": [
"x0c3s2b0n0",
"x0c3s3b0n0"
]
}
]
},
```
Ran through CRUD operations, observed good state for appropriate deployment status.
Low
> Add New state and fix erroneus Deploying state for tapms

- manifests/sysmgmt.yaml
A few CMS deployments that use the PET provided postgres operator to provision SQL clusters was impacted by a recent change to istio. This change impacted the ability to communicate between pods without an additional SSL/TLS layer, and both of these deployments expect a "no-ssl" configuration (for reasons of performance). The use of the updated base chart provides istio with the necessary configuration options to allow these deployments to function once again.
* Resolves [CASMINST-5145]
* Resolves [CASMINST-5147]
Dev built branches with this code were applied to the system, however the system did not have an updated istio controller. These tests that were performed showed that existing integration with older istio functioned to ensure backwards compatibility. For 8.2.0 specific changes, …
> Casminst 5145

- manifests/platform.yaml
This allows the heartbeat spire JWT to have access to `/apis/hbtd/hmi/v1/params`. This is used in the cray-heartbeat.sh script to request the heartbeat warning wait timeout.
* Resolves [CASMPET-5856](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5856)
* https://github.com/Cray-HPE/cray-opa/pull/56
* shandy
Validated that the cray-heartbeat script could successfully request the warning timeout from `/apis/hbtd/hmi/v1/params`.
- Was downgrade tested? If not, why? N, not needed for this change.
> CASMPET-5856 Bump cray-opa to 1.23.0

- manifests/sysmgmt.yaml
This PR updates FAS to the v1.23.0 image which includes the following changes:
- Removed unused integration test Pipfile and Dockerfiles (contained reference to arti.dev.cray.com)
- Updated to stable, nightly algol60 images.
- Updated Alpine base image version.
* Resolves [CASMHMS-5646](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5646).
This change was tested by building and running the FAS unit, integration, and CT tests and verifying that they continued to pass.
Low risk.
> CASMHMS-5646 Update FAS for arti.dev.cray.com domain retirement

- CHANGELOG.md
- manifests/platform.yaml
This solves the issue with the keycloak-localize job failing to copy all the keycloak users to the local systems. It solves the issue seen by ensuring that all the users keycloak has are received for processing extending the loop if a less than full page is returned by keycloak.
* Resolves [CASMPET-5743](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5743)
* vale
* rocket
- Were continuous integration tests run? If not, why?y
- Was upgrade tested? If not, why?y
- Was downgrade tested? If not, why?no there is no downgrade for the job
- …
> CASMPET-5743: Update keycloak-localize

- manifests/sysmgmt.yaml
In csm-1.2, hsm changed so that the 'node class' can be either 'Mountain', 'River', or 'Hill'.  The 'hill' types were not getting picked up by console services.  This set of changes looks for records containing 'Hill' and treats them correctly.
Code PR's:
https://github.com/Cray-HPE/console-data/pull/27
https://github.com/Cray-HPE/console-node/pull/55
https://github.com/Cray-HPE/console-operator/pull/33
* Resolves [CASMCMS-8140](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8140)
* `Loki`
I installed the new version via helm and observed that Hill nodes were correctly picked up by console services and connections and logging were established.
- Were continuous integration tests run? …
> CASMCMS-8140 csm-1.2.1 - correctly handle Hill nodes.

- CHANGELOG.md
- manifests/sysmgmt.yaml
Fixes two CFS issues found by NERSC around using additional inventory with image customization.
* Resolves CASMCMS-8120
* Resolves CASMCMS-8121
* Fanta
Ran image customization with and without additional inventory
The CHANGELOG doesn't appear to have been updated for the 1.2 release.  I'm not sure if the comment needs to go in a new 1.2.1 section.
> CASMCMS-8120: Update cfs-operator for additional inventory bug fixes

- manifests/core-services.yaml
- manifests/platform.yaml
The External DNS service that creates DNS records for Kubernetes services does not support the generation of PTR records, only A records. Several customers require that PTR records exist for services for security purposes.
This PR introduces a new cray-externaldns-manager container that runs within the cray-powerdns-manager pod that scans PowerDNS for TXT records with an external-dns signature, if any are found the associated A record is identified and a PTR record is generated. An externaldns-manager TXT record is also generated to aid identification and removal of stale records.
* Resolves [CASMNET-1069](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1069)
* Documentation changes required in [CASMNET-1753](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1753)
* Merge with …
> CASMNET-1069 - Create PTR records that are not created by externaldns

- manifests/core-services.yaml
- manifests/platform.yaml
- adjust cray-dns-unbound max unavailable from 0 to 1
CASMINST-4452
- Was upgrade tested? If …
> CASMINST-4452 - adjust cray-dns-unbound max unavailable

- manifests/sysmgmt.yaml
In csm-1.2, hsm changed so that the 'node class' can be either 'Mountain', 'River', or 'Hill'. The 'hill' types were not getting picked up by console services. This set of changes looks for records containing 'Hill' and treats them correctly.
Code PR's:
https://github.com/Cray-HPE/console-data/pull/28
https://github.com/Cray-HPE/console-node/pull/56
https://github.com/Cray-HPE/console-operator/pull/34
* Resolves [CASMCMS-8140](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8140)
* `Loki`
I installed the new version via helm and observed that Hill nodes were correctly picked up by console services and connections and logging were established. …
> CASMCMS-8140 - correctly handle Hill nodes.

- manifests/sysmgmt.yaml
Provide references to versions of the following software that can and
should be used in CSM-1.3. This is in addition to the versions for the
CSM-1.2 release, which are being retained in case software has not
switched to the newer verions.
Repositories:
cray-import-config
cray-import-kiwi-recipe-image
cray-product-catalog
None.
Slight.
> Provide CSM-1.3 compatible versions

- manifests/sysmgmt.yaml
added conditional to csm.ncn.ca_cert to check for the existence of **certificate_authority.crt** before proceeding.
ncn-personalization halted because the cert didn't exist on disk. Fixes ncn-personalization.
* Resolves https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5187
* surtur
ncn-personalization executed successfully on surtur with this change
Not aware of any risks.
> CASMINST-5187

- manifests/sysmgmt.yaml
Reverts Cray-HPE/csm#1119 until it can be tested for chart functionality.
> Revert "Provide CSM-1.3 compatible versions"

- manifests/core-services.yaml
- manifests/platform.yaml
* Fixed an issue where `cray-powerdns-manager` could intermittently crash on startup when trying to read existing TSIG keys via the PowerDNS API.
* Fixed an issue where `cray-powerdns-manager` did not retry the attempt to add the TSIG key.
* Fixed an issue where `cray-externaldns-manager` could panic on startup if the PowerDNS API connection couldn't be established.
* Applies consistent `go fmt` formatting to source files.
* Resolves [CASMNET-1710](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1710)
* Resolves [CASMNET-1711](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1711)
* Resolves [CASMNET-1758](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1758)
* `mug`
Deployed new artifacts on `mug`
`cray-powerdns-manager` no longer crashes and also retries the attempt to add …
> CASMNET-1710/CASMNET-1711/CASMNET-1758 - PowerDNS Manager bugfixes

- manifests/platform.yaml
CASMPET-5197 - This fixes an issue where the opa xname url was incorrectly set to /apis/hmnfd/hmi/v2/subscriptions/%v/agents$ instead of /apis/hmnfd/hmi/v2/subscriptions/%v.
CASMPET-5827 - hmcollector access should only be available on the hmn gateway. In addition to this, source restrictions aren't possible due to our double SNAT issue and are being removed.
* Resolves [CASMPET-5197](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5197)
* Resolves [CASMPET-5827 ](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5827 )
* https://github.com/Cray-HPE/cray-opa/pull/57
* https://github.com/Cray-HPE/cray-opa/pull/58
- Were the …
> CASMPET-5197 Bump cray-opa to 1.25.0

- rpm/cray/csm/sle-15sp3/index.yaml
Modify automated Goss scripts so that they only print failure information to screen, and successes to a log file.
https://github.com/Cray-HPE/csm-rpms/pull/537
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5161
See source PR for testing details: https://github.com/Cray-HPE/csm-testing/pull/355
Minor risk, but big payoff to usability.
> CASMINST-5161: Reduce excessive Goss script output

- CHANGELOG.md
- manifests/platform.yaml
During some upgrade scenarios, istio pods failed to pull images from Nexus. Adding them to precache will prevent it from happening.
* Resolves [CASMPET-5888](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5888) …
> CASMPET-5888: add all istio images to precache

- manifests/platform.yaml
Adds a new daemonset that will mostly do nothing unless a user turns encryption on. The daemonset simply reads/mounts /etc/cray/kubernetes/encryption and reads the current.yaml file to know if/when data, in this case secrets need to be rewritten with a new encryption key.
It will work anywhere technically, even non cray systems, just isn't very useful without the appropriate data.
* Resolves [CASMPET-5845
* Documentation changes required in TBD Will doc this once in and get to validate/test.
Tested in vshasta, on mug with …
> initialize cray-k8s-encryption daemonset at 0.0.3

- manifests/platform.yaml
CASMMON-188: create switch state prometheus alerts
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-188
CASMMON-158:  create Prometheus Network Exporter grafana dashboard
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-158
CASMMON-187: Prometheus Network Exporter grafana dashboard bug 
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-187
CASMMON-189:Update Snmp stats dash board as hpcm dashboard which supports multiple switches
CASMMON-159:temperature hardware monitoring dashboards for NCNS in SHS
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-159
https://github.com/Cray-HPE/cray-sysmgmt-health/pull/73
https://github.com/Cray-HPE/cray-sysmgmt-health/pull/72
https://github.com/Cray-HPE/cray-sysmgmt-health/pull/74
https://github.com/Cray-HPE/cray-sysmgmt-health/pull/75 …
> bump version

- assets.sh
- docker/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
Overview
BUGFIX: Fix UAN configuration templates producing None VLAN when CHN is enabled.
BUGFIX: Enable 1.3 configuration templates in the pyinstaller binary.
Details
Update docs generated from code.
Change exception-handling in canu validate shcd and from network_modeling.
Provide better next steps from errors reported while validating SHCDs.
Add canu test to ping Kea DHCP.
Update to release process doc
- Fixes: CASMNET-1757
- Bugfix [Release 1.6.13](https://github.com/Cray-HPE/canu/pull/196)
> CASMNET-1757: CANU bugfixes including UAN VLAN as None

- manifests/core-services.yaml
- manifests/platform.yaml
Certain services have aliases defined in SLS and ExternalDNS annotations.
```
ncn-m001:~ # cray sls search networks list --name NMNLB --format json | jq '.[].ExtraProperties.Subnets[].IPReservations[] | select(.IPAddress=="10.92.100.71")'
{
"Aliases": [
"api-gw-service",
"api-gw-service-nmn.local",
"packages",
"registry",
"spire.local",
"api_gw_service",
"registry.local",
"packages",
"packages.local",
"spire"
],
"Comment": "api-gw-service,api-gw-service-nmn.local,packages,registry,spire.local,api_gw_service,registry.local,packages,packages.local,spire",
"IPAddress": "10.92.100.71",
"Name": "istio-ingressgateway"
}
```
```
ncn-m001:~ # kubectl -n istio-system get svc istio-ingressgateway -o json | jq '.metadata.annotations,.status'
{
"external-dns.alpha.kubernetes.io/hostname": …
```
> CASMNET-1761 - powerdns-manger and externaldns-manager are updating the same record.

- CHANGELOG.md
- manifests/core-services.yaml
- manifests/platform.yaml
Bump cray-powerdns-manager to 0.6.9 to include the following fixes.
[CASMNET-1631](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1631) - PTR records for the CAN subnet are missing
[CASMNET-1550](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1550) - powerdns-manager support for HSM v2 API
[CASMNET-1143](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1143) - BREAK/FIX: cray-powerdns-manager stuck updating the nmn zone.
[CASMNET-1674](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1674) - BREAK/FIX: PowerDNS - Missing A records before final NCN deployment
This release is 100% backwards compatible as it does not include the ExternalDNS PTR generation code.
* Resolves [CASMNET-1779](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1779)
* Various CSM 1.3 installs …
> CASMNET-1779 - PowerDNS record generation bugfixes

- CHANGELOG.md
- manifests/sysmgmt.yaml
The last fix to incorporate Hill nodes into console services had a bug when it was concatenating node lists together which resulted in malformed sql queries.  This prevented the console services from acquiring nodes when there were mixed types in the same acquisition call. This fixes the node lists.
Code PR:
https://github.com/Cray-HPE/console-data/pull/31
* Resolves [CASMCMS-8156](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8156)
* `Loki`
I installed the new console-data service via helm, then cleared all console connections and information from the system.  I then watched as the mixed node types were acquired at the same time and successfully interacted with the database updates. …
> CASMCMS-8156 - fix handling of Hill nodes with console services.

- CHANGELOG.md
- manifests/sysmgmt.yaml
The last fix to incorporate Hill nodes into console services had a bug when it was concatenating node lists together which resulted in malformed sql queries.  This prevented the console services from acquiring nodes when there were mixed types in the same acquisition call. This fixes the node lists.
Code PR:
https://github.com/Cray-HPE/console-data/pull/31
* Resolves [CASMCMS-8156](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8156)
* `Loki`
I installed the new console-data service via helm, then cleared all console connections and information from the system.  I then watched as the mixed node types were acquired at the same time and successfully interacted with the database updates. …
> CASMCMS-8156 - fix problem with handling hill nodes in console services.

- manifests/sysmgmt.yaml
Fixes an issues were an old debug binary won't get cleaned up when upgrading from cms-ipxe 1.9.  Also includes build changes to switch from dev.cray.com
* Resolves CASMCMS-8149
* Resolves CASMCMS-8141
* Mug
Deployed new image and allowed the cleanup to run with and without the old binary present.
None
> CASMCMS-8149: Update cms-ipxe for build changes and binary cleanup

- docker/index.yaml
- lib/setup-nexus.sh
- vendor/github.hpe.com/hpe/hpc-shastarelm-release/lib/install.sh
* Add SAT image to CSM
* When installing SAT, use `skopeo-copy` function to tag it as `csm-latest`.
* Update vendor library to include `skopeo-copy` function.
* Resolves [CRAYSAT-1509](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1509)
* Resolves [CRAYSAT-1508](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1508)
* Relates to https://github.com/Cray-HPE/csm-rpms/pull/542
Testing currently in progress
This change should pose little risk as it is simply adding a container image to the install.
- [TODO] Testing is appropriate and complete, if applicable
> Add SAT 3.18.0 image to CSM

- CHANGELOG.md
- manifests/sysmgmt.yaml
Update the barebones image/recipe to use sles 15sp4 - also migrate to using the algol60 sles zypper repos.
* Resolves [CASMCMS-8075](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8075)
* `Surtur`
Most of the changes were with building the image that is packaged up and contained in the install image - getting that building correctly with the new recipe and sp4 repos was most of the work.  I did use Surtur, removed the old barebones image and recipe, used the new package to install the updated one, then successfully ran the barebones image boot test using the new image.
- Was downgrade tested? …
> CASMCMS-8075 - update barebones image to use sles15sp4.

- manifests/core-services.yaml
HSM will now discover HSN NICs under `/redfish/v1/Chassis/<sysid>/Devices` instead of `/redfish/v1/Chassis/<sysid>/NetworkAdapters` for Proliant iLO redfish implementations and ignore non-HSN NICs.
* Resolves [CASMHMS-5675](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5675)
For testing, see https://github.com/Cray-HPE/hms-smd/pull/88
none
> Fix HSN NIC discovery in HSM for Proliant iLO redfish implementations

- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp3-compute/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4-compute/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
This PR updates the BOS v1 BOA component to become compatible with changes made in CAPMC endpoint deprecation. Without this, BOA will fail preflight checks while attempting to resolve health of the capmc service before continuing.
Additionally, this contains a small fix to BOS v2 that effectively zeros component errors during new session instantiation. As a result, previous attempts on hardware that have failed to be provisioned for any reason are re-attempted on new session creation. Without this fix, hardware components will be skipped until the error field is manually zero'd out.
* Resolves [CASMCMS-8102](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8102)
* Resolves …
> CASMCMS-8102, CASMCMS-7551

- rpm/cray/csm/sle-15sp3/index.yaml
Cut execution time of some of our automated Goss tests in half by running tests on multiple nodes in parallel.
See source PR for details on changes and testing of those changes:
https://github.com/Cray-HPE/csm-testing/pull/363
Fixes: [CASMINST-5162](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5162)
Also pulled in the fixes for [CASMINST-5218](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5218). See its
source PR for the details on those small bug fixes:
https://github.com/Cray-HPE/csm-testing/pull/364
csm-rpms manifest PR: https://github.com/Cray-HPE/csm-rpms/pull/551
See source PRs for details on changes and testing of those changes:
https://github.com/Cray-HPE/csm-testing/pull/363
https://github.com/Cray-HPE/csm-testing/pull/364
Reduces the risk that we will not live …
> CASMINST-5162: Parallelize execution of remote Goss tests

- manifests/sysmgmt.yaml
This will correct the problem seen trying to deploy the unstable csm-config chart. 
I deployed this on drax and verified that it corrected the problem.
Without this, the chart cannot be deployed.
> CASMTRIAGE-3922: Use stable csm-config artifact

- docker/index.yaml
On a previous manifest change, this location for cray-ims-load-artifacts was missed, so the nightly CVE rebuild was rebuilding the previous version instead of the currently used version.  This captures the correct version that is being used with cray-csm-barebones-recipe-install.
* Resolves [CASMCMS-8162](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8162)
* Build system and local environment
I checked the image cray-ims-load-artifacts and confirmed 1.6.0 was not being rebuilt nightly, manually triggered a rebuild, and verified the rebuilt image does not contain CVE vulnerabilities.  This change to the manifest will insure the correct version is getting built from now on.
- Were …
> CASMCMS-8162 - correct missed update to cray-ims-load-artifacts version.

- manifests/platform.yaml
Increase hnc webhook timeouts to avoid retries
* Resolves [CASMINST-4897](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4897)
```
ncn-m001-22703c05:/home/bklein # kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io hnc-validating-webhook-configuration -o yaml | grep timeout
timeoutSeconds: 30
timeoutSeconds: 30
timeoutSeconds: 30
timeoutSeconds: 30
timeoutSeconds: 30
```
Updated the chart, saw the new timeouts, ran CRUD operations, no timeouts.
Low
> Increase hnc webhook timeouts to avoid retries (CASMINST-4897)

- manifests/sysmgmt.yaml
The base image for the final layer may or may not have security patches applied, so each time this is built, apply any security patches directly to it here.  This does not rely on the base image being updated to get all patches at the time of the build.
Code PR:
https://github.com/Cray-HPE/csm-config/pull/70
* Resolves [CASMCMS-8099](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8099)
* Build system
The image built with the Jenkins pipeline failed the CVE scan before the changes, and passes after the changes.  There are no code changes, just a base image update so no need to test on-system.
- …
> CASMCMS-8099 - enable automatic updates to csm-config base image.

- manifests/platform.yaml
CASMINST-5243:BREAK/FIX: csm-1.3-beta.41 : install csm service failed
[
](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5243)
installation working fine
loftsman ship --charts-path . --manifest-path  shs-cust.yaml_snmp_bug
2022-08-17T16:00:44Z INF Initializing the connection to the Kubernetes cluster using KUBECONFIG (system default), and context (current-context) …
> CASMINST-5243:bump version

- CHANGELOG.md
- rpm/cray/csm/sle-15sp3/index.yaml
See https://github.com/Cray-HPE/csm-testing/pull/366 for details.
* Resolves https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5239
> CASMINST-5239: Fix occasional failure in goss_check_static_routes test

- manifests/platform.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
CASMINST-5243:BREAK/FIX: csm-1.3-beta.41 : install csm service failed
[
List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies.
Resolves [issue id](issue link)
Change will also be needed in <insert branch name here>
Future work required by [issue id](issue link)
Documentation changes required in [issue id](issue link)
Merge with/before/after <insert PR URL here>
](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5243)
Testing
List the environments in which these changes were tested.
Tested on: mug and starloard
installation working fine
loftsman ship --charts-path . --manifest-path shs-cust.yaml_snmp_bug
2022-08-17T16:00:44Z INF Initializing the connection to the Kubernetes cluster using …
> Casminst 5243

- CHANGELOG.md
- manifests/sysmgmt.yaml
Updates cfs-api, operator and trust for pod priority escalation
* Resolves CASMTRIAGE-3835
* Mug
Deployed and ran basic tests for updated images/charts
None
> CASMTRIAGE-3835: Update cfs api, operator and trust for pod priority escalation

- CHANGELOG.md
- manifests/sysmgmt.yaml
Updates cfs-api, operator and trust for pod priority escalation
* Resolves CASMTRIAGE-3835
* Mug
Deployed and ran basic tests for updated images/charts
None
> CASMTRIAGE-3835: Update cfs api, operator and trust for pod priority escalation (1.3)

- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
- Fixes: https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5428
Cephexporter only reports data on the first three storage nodes (running mon/mgr).
```
C02YT3JRLVCJ:cray-site-init bklein$ cat foo/foo/customizations.yaml  | grep -A3 nmn_ncn_storage_mons
nmn_ncn_storage_mons:
- 10.252.1.4
- 10.252.1.5
- 10.252.1.6
```
Good
Low
> Add separate list of storage nodes for cephExporter endpoints

- rpm/cray/csm/sle-15sp3/index.yaml
Incorrect csm-testing,goss-servers version was implemented by CASMPET-5324. This fixes the version for csm-testing and goss-servers.
* Resolves CASMINST-5268
> CASMINST-5268: Resolves issue from CASMPET-5324. Fix manifest versions for csm-testing, goss-servers that were incorrect

- docker/index.yaml
- lib/setup-nexus.sh
Update the version of the cray-sat container image included in CSM from 3.18.0 to 3.19.0. This version includes important `sat bootprep` functionality implemented in [CRAYSAT-1385](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1385).
(cherry picked from commit cc49c9eea6e42667543ae9cb1c33426fdd361726)
* Resolves [CRAYSAT-1526](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1526)
* Pulls in changes from the epic [CRAYSAT-1385](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1385)
* Jenkins
If the Jenkins build succeeds, then that means it could find the new container image.
The container image itself was tested through a test installation of SAT product version 2.4.8 on hermod.
Not much risk is introduced here. We are just upgrading the version of the sat container image.
> CRAYSAT-1526: Add SAT version 3.19 to CSM

- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp3-compute/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4-compute/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
This mod corrects the behavior documented in CASMCMS-8163 with respect to making the used schema backwards compatible with the v1 healthz openapi generated structure.
* Resolves [CASMCMS-8163](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8163)
* `groot`
Applied the change to groot and verified that the health endpoints for v1 and v2 were appropriately populating.
> CASMCMS-8163: Adjust healthz payload to be v1/v2 agnostic

- manifests/sysmgmt.yaml
This includes two changes to BSS
* BSS v2.1.5: Include type information when getting the spire token which fixes CASMHMS-5682 "cray-spire bos xname workloads incorrectly named"
* BSS v2.1.4: Convert metal.server boot parameter to a signed, time limited, s3 http url when the boot parameter is set to s3://bucket/path. There will be other changes, to other products, in CSM that will make use of this BSS change. This change is backwards compatible.
* Resolves [CASMHMS-5682](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5682)
* Resolves [CASMHMS-5656](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5656)
The fix for CASMHMS-5682 is in BSS 2.1.5 and the fix for CASMHMS-5656 is in BSS 2.1.4
The change for CASMHMS-5656 is backward compatible.
* For CASMHMS-5682 see …
> Changed cray-hms-bss version to 2.1.5

- rpm/cray/csm/sle-15sp3/index.yaml
fix ceph-service-check.sh to allow for version specific output
Output from the same command has changed in 16.2.x from the output the script was
written for in 15.2.x. This will allow for the correct format depending on the version.
* Resolves CASMINST-5271
* Drax ceph vers 15.2.15
* Craystack ceph vers 16.2.x
_How were the changes tested and success verified? If schema changes were part of this …
> CASMINST-5273 - fix to ceph service check for osd unit name issue

- rpm/cray/csm/sle-15sp3/index.yaml
fix ceph-service-check.sh to allow for version specific output
Output from the same command has changed in 16.2.x from the output the script was
written for in 15.2.x. This will allow for the correct format depending on the version.
* Resolves CASMINST-5271
* Drax ceph vers 15.2.15
* Craystack ceph vers 16.2.x
_How were the changes tested and success verified? If schema changes were part of this …
> CASMINST-5273 - fix for ceph service check osd unit name issue

- manifests/core-services.yaml
- manifests/platform.yaml
- cray-dhcp-kea - add variable reset to prevent wrong data on being used
yes
CASMTRIAGE-3966
Shandy …
> bug/CASMTRIAGE-3966 - cray-dhcp-kea - add variable reset to prevent wrong data on being used

- assets.sh
- docker/index.yaml
- manifests/platform.yaml
This change is a step towards resolving CVEs in multus -- we're switching to the current upstream repo in anticipation of a fix to update the base docker image (https://github.com/k8snetworkplumbingwg/multus-cni/issues/898).
- Fixes: https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5821
Prep work for finally fixing multus CVEs
craystack:
```
ncn-m001:~ # kubectl get po -n kube-system | grep multus
kube-multus-ds-4s25j               1/1     Running   0          84s
kube-multus-ds-d65lk               1/1     Running   0          84s
kube-multus-ds-fs67s               1/1     Running   0          84s
kube-multus-ds-g65tn               1/1     Running   0          84s
kube-multus-ds-nl29k               1/1     Running   0          84s
kube-multus-ds-wn28v …
```
> Update multus to v3.9.1 from k8snetworkplumbingwg/multus-cni repo (CASMPET-5821)

- CHANGELOG.md
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
When no version string is specified for the `cray bos` command, then
default the version to `v1`.
This should merge at the same time as the following PRs:
https://github.com/Cray-HPE/csm-rpms/pull/583
https://github.com/Cray-HPE/csm-rpms/pull/588
https://github.com/Cray-HPE/csm/pull/1224
See https://github.com/Cray-HPE/craycli/pull/59.
> CASMCMS-8192: Default the Cray CLI to v1 for BOS

- rpm/cray/csm/sle-15sp3/index.yaml
Updates the cmsdev test to reflect the change of the BOS default CLI version to v1.
This should merge at the same time as these PRs:
https://github.com/Cray-HPE/csm-rpms/pull/582
https://github.com/Cray-HPE/csm/pull/1225
https://github.com/Cray-HPE/csm-rpms/pull/589
This should merge when the manifest PRs for [CASMCMS-8192](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8192) merge. Otherwise the tests and the CLI will be mismatched.
csm-rpms: https://github.com/Cray-HPE/csm-rpms/pull/582
See source PR for details:
https://github.com/Cray-HPE/cms-tools/pull/53
If the CLI change goes in without this, there will be test failures.
> CASMCMS-8193: cmsdev test: Update BOS CLI test to reflect default version back to v1

- manifests/sysmgmt.yaml
Change dev.cray.com addresses to new HPC domains as previous domain is being deprecated.
As of next month no.
* Resolves [issue id](issue link) [CASMCMS-8144](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8144)
Testing was done on the mug machine.
Modified the crus deployment to contain new container image. Initialized new version of crus and made an authcurl 
call to verify sessions.
None that I know of.
> Casmcms 8144

- docker/index.yaml
Add hardware-topology-assistant to docker.index. This is a docker image that will help facilitate adding of river cabinets to a system.
Backwards compatible. New docker image.
* Resolves CASMINST-3902
* Mug
- Were …
> CASMINST-3902: Add hardware-topology-assistant to docker.index

- docker/index.yaml
- lib/setup-nexus.sh
See CHANGELOG.md in sat repo for full description of changes.
This updates the version of the cray-sat container image from 3.19.0 to 3.19.1 to include several release-critical bugfixes.
See [sat CHANGELOG.md](https://github.com/Cray-HPE/sat/blob/release/3.19/CHANGELOG.md) for a full description of the changes.
* Resolves [CRAYSAT-1550](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1550)
* loki
Installed this version of cray-sat container image on loki through installation of SAT product stream version 2.4.10, which includes this same version of the container image.
None.
> CRAYSAT-1550: Update cray-sat container image to 3.19.1

- rpm/cray/csm/sle-15sp2/index.yaml
Release updated version of platform utils.
This update creates a symbolic link for utils/ceph-service-status.sh to point to updated version of script in opt/cray/tests/install/ncn/scripts/ceph-service-status.sh
> CASMPET-5918 release platform-utils v1.3.6

- rpm/cray/csm/sle-15sp3/index.yaml
release a new version of csm-rpms
> MTL-1927: new csm-testing rpm with BIOS version updates

- rpm/cray/csm/sle-15sp2/index.yaml
platform-utils spec file is changed to create ceph-service-status.sh sym-link on rpm upgrade and rpm install.
* Resolves [CASMPET-5922](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5922)
* Related to [CASMPET-5918](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5918)
Tested install and upgrade of platform-utils rpm and verified creation of symbolic link.
_Are …
> CASMPET-5922 edit platform-utils spec file to create ceph-service-status.sh sym-link on rpm upgrade

- manifests/sysmgmt.yaml
The cray-cfs-api chart does not have overrides for the PVC storage class so the override was added. This is a bug fix
Can helm rollback.
* Resolves [issue id](issue link) https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7863
Mug
Ran helm deploy with updated image and template
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled …
> increment cray-cfs-api version

- manifests/platform.yaml
- Splits OPA policies up by type instead of by gateway
- Adds ability for customers to add their own policies without modifying the charts
- Adds TPM Provisioner access
* Resolves [CASMPET-5898](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5898)
* Resolves [CASMPET-5673](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5673) 
* Resolves [CASMPET-5024](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5024)
* https://github.com/Cray-HPE/cray-opa/pull/59
* https://github.com/Cray-HPE/cray-opa/pull/60
* https://github.com/Cray-HPE/cray-opa/pull/61 …
> CASMPET-5024 Bump cray-opa to 1.28.0

- manifests/core-services.yaml
SLS changes to do the following:
* CASMHMS-5696 - Disallow networks with an empty name.
* CASMHMS-4267 - Added validation to loadstate.
* CASMHMS-5691 - Added the slignshot11 network type.
* Resolves [CASMHMS-5696](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5696)
* Resolves [CASMHMS-4267](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-4267)
* Resolves [CASMHMS-5691](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5691)
see: 
* https://github.com/Cray-HPE/hms-sls/pull/57
* https://github.com/Cray-HPE/hms-sls/pull/56
* https://github.com/Cray-HPE/hms-sls/pull/55
* mug
- Were continuous integration tests run? Y
- Was upgrade tested? Y
- Was …
> Changed cray-hms-sls version to 2.1.7

- docker/index.yaml
- lib/setup-nexus.sh
This updates the version of the cray-sat container image from 3.19.1 to 3.19.2 to include the fix for [CRAYSAT-1552](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1552).
See [sat CHANGELOG.md](https://github.com/Cray-HPE/sat/blob/release/3.19/CHANGELOG.md) for a full description of the changes.
(cherry picked from commit 861956ae9932f7292300df4eb4c66f8636d1470f)
* Part of [CRAYSAT-1559](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1559)
* Resolves [CRAYSAT-1552](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1552)
* surtur
Installed this version of cray-sat container image on surtur through installation of SAT product stream version 2.4.11, which includes this same version of the container image.
None.
> CRAYSAT-1559: Update cray-sat container image to 3.19.2

- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp3-compute/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4-compute/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
This mod updates the BOS Staging behavior to be more in line with the customer requirement to be able to reprovision nodes repeatedly. This mod adds a new API level option to BOSv2 that allows staged session information to be preserved between applystaged options. As a result, WLMs may request the same staged provision action repeatedly, and there is no longer a reason for re-staging thereafter.
* Resolves [CASMCMS-8158](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8158)
Tested both on and off on system while booting a COS "staged" node, representing the full lifecycle of the changed operation.
* `mug`
I created a new BOS v2 session with staging options set; then configured BOSv2 options for staging to preserve …
> Allow BOS to optionally preserve staged boot artifacts between operations

- assets.sh
These images are the same as 0.3.46 but also have Vagrant boxes available in Artifactory. By aligning the tag this means we have recognized Vagrant boxes that are associated with our release.
> CASMREL-1100

- rpm/cray/csm/sle-15sp3/index.yaml
Update nexus test to pull correct pause image.
* Resolves [CASMTRIAGE-4057](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4057)
Tested fix on fanta:
```
ncn-m001:~ # export GOSS_BASE=/opt/cray/tests/install/ncn; goss -g /opt/cray/tests/install/ncn/tests/goss-k8s-nexus-can-pull.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml v
Total Duration: 0.153s
Count: 1, Failed: 0, Skipped: 0
```
* `fanta`
Tested on fanta
Low
> Update pause version for nexus test

- CHANGELOG.md
- rpm/cray/csm/sle-15sp2/index.yaml
manifest change to update platform-utils version
This removes duplicate copy of ceph-service-status.sh from platform-utils. Existing copy of this script is located in csm-testing.
* Resolves [CASMPET-5920](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5920)
> CASMPET-5920: manifest change to update platform-utils version

- CHANGELOG.md
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
Update craycli to 0.63.0 to fix python 6.3 deprecation warning
Backward compatible bugfix
* Resolves [CASMCLOUD-1212](https://jira-pro.its.hpecorp.net:8443/browse/CASMCLOUD-1212)
* `surtur`
Ran the offending command from the ticket, verified that it no longer produces a deprecation warning.  Unit tests and lint run at build on craycli code.
- Was downgrade tested? If not, why? Yes …
> Update craycli to 0.63.0; clean up python 6.3 deprecation warning

- CHANGELOG.md
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
Update craycli to 0.63.0 to fix python 6.3 deprecation warning
Backward compatible bugfix
* Resolves [CASMCLOUD-1212](https://jira-pro.its.hpecorp.net:8443/browse/CASMCLOUD-1212)
* Change will also be needed in `release/1.3`
* `surtur`
Ran the offending command from the ticket, verified that it no longer produces a deprecation warning.  Unit tests and lint run at build on craycli code.
- Was downgrade tested? If not, why? Yes …
> Update craycli to 0.63.0 to fix python 6.3 deprecation warning

- rpm/cray/csm/sle-15sp3/index.yaml
- Fixes: [CASMCMS-8203](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8203)
- Relates to: [CASMTRIAGE-4074](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4074)
The cmsdev test crashes in a couple of error paths when it dereferences null pointers. The fix is very simple.
Tested on starlord, where the problem was discovered. See source PR for details: https://github.com/Cray-HPE/cms-tools/pull/57
Very low risk to include. Fix is extremely simple.
> CASMCMS-8203: Stop failing git commands from crashing cmsdev

- rpm/cray/csm/sle-15sp3/index.yaml
- Fixes: [CASMINST-5311](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5311)
- Add clock skew test to storage and worker health check test suites
- Fixes: [CASMINST-5312](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5312)
- Enable logging of 6 additional Goss tests
- Fixes: [CASMINST-5316](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5316)
- Fix typo in k8s_kyverno_pods_running.sh
See source PRs for details: 
- https://github.com/Cray-HPE/csm-testing/pull/388
- https://github.com/Cray-HPE/csm-testing/pull/391
- https://github.com/Cray-HPE/csm-testing/pull/392
Updated tests and test suites executed successfully on starlord.
Very low risk -- adding 1 existing test to 2 existing test suites, enabling an existing logging feature in 6 existing …
> CASMINST-5311/CASMINST-5312/CASMINST-5316: Goss testing improvements

- rpm/cray/csm/sle-15sp3/index.yaml
Fix for https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4095 -- point to cray bss command if wipe flag test fails.
* Resolves [CASMTRIAGE-4095](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4095)
Not a functional change
N/A
N/A
Low
> Point to cray bss as alternative to setting wipe flag w/out csi (CASMTRIAGE-4095)

- CHANGELOG.md
- manifests/sysmgmt.yaml
There were timeouts configured for connections and read times, but the overall application was timing out when an s3 file operation was taking over 30 seconds. This caused the gunicorn application that is running inside the ims pod to restart, dropping the operation that was in progress.
This change adds the timeout configuration value to the gunicorn application and makes it configurable through the helm charts and ims-config k8s configmap.
There is also a change to the readiness/liveness probes to increase their timing as well. The way they were configured, when an operation took long enough, the liveness probe would fail and the container would be restarted mid-operation. There should be a better solution for this put into place at some point. Currently the http server is …
> CASMTRIAGE-4091 - add configurable timeout to IMS to handle large images.

- manifests/sysmgmt.yaml
Update the CSM CFS layer so that it configures the CSM SLES15 SP4 RPM repository.
- Source PR: https://github.com/Cray-HPE/csm-config/pull/78
- Resolves [CASMCMS-8209](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8209)
- Combined with [CASMINST-5314](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5314), resolves [CASMTRIAGE-4094](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4094)
Tested the fix (in WAR format) on surtur.
Low risk. Just adding one stanza to the yaml file to define the repository, following the same pattern as is used for the other SP versions.
> CASMCMS-8209: Add csm-sle15sp4 repo in NCN personalization

- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
The override in customizations.yaml was not updated to the correct access-pool for the ims service.  This prevents the networking to be set up correctly.
* Resolves [CASMTRIAGE-4098](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4098)
No testing - needs to be incorporated into an install.
Low risk as this override will not impact anything outside of the ims service and will only resolve the networking for the service.
> CASMTRIAGE-4098 - update ims override to the correct access pool.

- assets.sh
- rpm/cray/csm/sle-15sp3/index.yaml
Fixes usage for `csi-setup-lan0.sh`. Also fixes the `PITDATA` variable in `pit-init.sh` for systems running in memory (e.g. for recovery where no partition can be provided).
- https://github.com/Cray-HPE/pit-init/pull/53
- https://github.com/Cray-HPE/pit-init/pull/52
> MTL-1952 MTL-1953 Fixes for `pit-init`

- CHANGELOG.md
- manifests/sysmgmt.yaml
Updates console-node, cray-crus and csm-config to use sp4 base images
* Resolves CASMCMS-8076
Everything was tested/run on Mug
No
> CASMCMS-8076: Update csm services for sp4 base images

- CHANGELOG.md
- manifests/platform.yaml
Updated cray-keycloak to 3.6.1 to fix postgres sql version incompatibility issue causing restore to fail.
* Resolves [CASMPET-5936](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5936)
* Future work required by [CASMPET-5936](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5936)
Verified that …
> CASMPET-5936: fix postgres database restore issue

- manifests/platform.yaml
Fix for slurm-operator writing munge keys to vault from slurm-operator namespace -- add issuer for slurm-operator namespace.
* Resolves [CASMPET-5953](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5953)
```
ncn-m001-cdd6e862:/home/bklein/demo # kubectl get vault -n vault -o yaml | grep -C6 slurm
bound_service_account_namespaces:
- ceph-rgw
- services
- istio-system
- sma
- tapms-operator
- slurm-operator
- spire
name: pki-common
policies:
- pki-common
ttl: 1h
- bound_service_account_names:
--
name: uas
policies:
- allow_secrets
- allow_transit
ttl: 72h
- bound_service_account_names:
- slurm-operator
bound_service_account_namespaces:
- slurm-operator
name: slurm-operator
policies:
- allow_secrets
- allow_transit
ttl: 72h
type: kubernetes
policies:
```
``` …
```
> Add slurm-operator namespace role/cert for vault calls

- manifests/platform.yaml
tapms chart is referring to stale docker image
* Resolves [CASMINST-5325](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5325)
Updated tapms deployment on fanta, not hanging with latest bits..
* `fanta`
Now able to create tenant:
```
{
"vcluster-blue-user",
"vcluster-blue-slurm"
],
{
"hsmgrouplabel": "blue",
"xnames": [
"x3000c0s21b1n0",
"x3000c0s21b2n0"
]
}
],
"uuid": "aa8eb552-2e51-4ca9-8ade-2653a01a6d12"
}
tenants
└── [s] vcluster-blue
├── [s] vcluster-blue-slurm
└── [s] vcluster-blue-user
[s] indicates subnamespaces
```
- Was upgrade …
> Bump chart and docker versions to match (CASMINST-5325)

- rpm/cray/csm/sle-15sp3/index.yaml
- Fixes: [CASMCMS-8210](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8210)
- Adds 3 overlooked BOS CLI tests to the cmsdev test tool. See source PR for full details: https://github.com/Cray-HPE/cms-tools/pull/58
- Fixed [CASMCMS-8212](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8212)
- Updated Golang version and dependent modules to [resolve High severity CVE](https://github.com/Cray-HPE/cms-tools/security/dependabot/1). See source PR for full details: https://github.com/Cray-HPE/cms-tools/pull/60
New subtests were run successfully on surtur. See source PR for full details:
https://github.com/Cray-HPE/cms-tools/pull/58
Rebuilt binary with CVE remediations was tested on fanta. See source PR for full details: https://github.com/Cray-HPE/cms-tools/pull/60 …
> CASMCMS-8210/CASMCMS-8212: cmsdev: Add BOS CLI tests, resolve CVE

- rpm/cray/csm/sle-15sp2/index.yaml
This change updates the hpe-csm-scripts version to v0.0.39 which fixes Keycloak authentication token leaks in the hsm_discovery_status_test.sh script. Previously the test output and logs would contain previously used tokens, now these tokens are redacted.
Example output:
```
ncn-m001:~/schooler # ./hsm_discovery_status_test.sh
Running hsm_discovery_status_test...
(17:29:51) Getting client secret...
(17:29:51) Retrieving authentication token...
(17:29:51) Testing 'curl -s -k -H "Authorization: Bearer <REDACTED>" https://api-gw-service-nmn.local/apis/smd/hsm/v2/Inventory/RedfishEndpoints'...
(17:29:51) Processing response with: 'jq '.RedfishEndpoints[] | { ID: .ID, LastDiscoveryStatus: .DiscoveryInfo.LastDiscoveryStatus}' -c | sort -V | jq -c'...
(17:29:52) Verifying endpoint discovery …
```
> CASMHMS-5743 Fix token leaks in HMS test script

- CHANGELOG.md
- manifests/sysmgmt.yaml
Rebuilds spire to pickup base chart cray-service:8.2.3
Bugfix
* Resolves [CASMPET-5961](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5961)
vshasta
```
$ kubectl get cronjob spire-postgresql-db-backup -n spire -o yaml | grep cray-service
helm.sh/base-chart: cray-service-8.2.3
$ kubectl get cronjob spire-postgresql-db-backup -n spire -o yaml | grep backup | grep image
image: …
```
> CASMPET-5961-main : BREAK/FIX: Spire needs to pick up the cray base chart version 8.2.3 to fix postgres restore incompatibility issue

- CHANGELOG.md
- manifests/sysmgmt.yaml
Rebuilds spire to pickup base chart cray-service:8.2.3
Bugfix
* Resolves [CASMPET-5961](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5961)
vshasta
```
$ kubectl get cronjob spire-postgresql-db-backup -n spire -o yaml | grep cray-service
helm.sh/base-chart: cray-service-8.2.3
$ kubectl get cronjob spire-postgresql-db-backup -n spire -o yaml | grep backup | grep image
image: …
```
> CASMPET-5961-1.3 : BREAK/FIX: Spire needs to pick up the cray base chart version 8.2.3 to fix postgres restore incompatibility issue

- build/images/extract.sh
Improve chart related error handling in extract.sh script by adding "--halt-on-error" parameter to parallel options.
* Resolves CASMINST-5176
Tested in the build pipeline
No known risks
> added halt-on-error parameter to parallel opts

- manifests/core-services.yaml
Changed the cray-service chart version to 8.2.3 for SLS. With this change the following changes are brought in.
* CASMHMS-5696 - Disallow Networks with empty names
* CASMHMS-4267 - Changed loadstate to validate
* CASMHMS-5691: Added the slingshot11 network type
* CASMINST-3902: Expanded the SLS client to perform dumpstate and PUT to networks.
* Resolves [CASMHMS-5753](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5753)
* Resolves [CASMHMS-5696](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5696)
* Resolves [CASMHMS-4267](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-4267)
* Resolves [CASMHMS-5691](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5691)
* Resolves [CASMINST-3902](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3902)
See the PRs:
* …
> Changed cray-hms-sls version to 3.0.0

- manifests/platform.yaml
Update manifest to pull in 0.0.4 of the cray-k8s-encryption chart.
Bugfix to ensure placement only on masters.
* Resolves CASMPET-5968
Validated on starlord and mug that we get placement only on master/control plane nodes.
* starlord/mug
On a system with the node label having a different value than what I tested with, manually edited the changes into place to ensure we still only get placement on master nodes. While worker nodes also technically …
> Casmpet 5968 1.3
