Cray-HPE/csm

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
Release the latest version of CSI
MTL-1549 - Routes to undefined networks go through the CMN
CASMHMS-5185 - Interactively generate application_node_config.yaml
MTL-1483 - auto-generate hmn_connections and switch_metadata
=> update to latest csi

assets.sh
CASMPET-5121
CASMINST-3535
MTL-1512
MTL-1524
=> CASMREL-819 - NCN assets update

CHANGELOG.md, manifests/platform.yaml
Moved cray-s3 metallb pool from customer-access to new Bi-CAN customer-management (CMN)
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?
This is backward incompatible with releases prior to csm-1.2
Resolves CASMPET-5152
Change will also be needed in NA
Future work required by [issue id](issue link) NA
Documentation changes required in [issue id](issue link) NA
Merge with/before/after <insert PR URL here> NA
wasp 1.2 install
wasp
How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?
Verified on wasp that the cray-s3 service IP changed from 10.101.10.0/24 to 10.101.8.0/24
```
wasp-ncn-m001-pit:~ # kubectl get cm config -n metallb-system -o yaml
... …
```
=> CASMPET-5152 1.2 : cray-s3 service needs to move to CMN

rpm/cray/csm/sle-15sp2/index.yaml
- add yapl rpm (automation framework) to csm build
- fix/merge duplicated key in rpm/cray/csm/sle-15sp2/index.yaml
* Resolves [CASMPET-4886](https://connect.us.cray.com/jira/browse/CASMPET-4886)
* Future work required by [CASMPET-5161](https://connect.us.cray.com/jira/browse/CASMPET-5161)
* `wasp`
- Were the install/upgrade-based validation …
=> Casmpet 4886

rpm/cray/csm/sle-15sp2/index.yaml
Release csm-testing with the fix for CASMINST-3411
=> CASMINST-3411: manifest update

assets.sh
New NCN images with the fix for CASMTRIAGE-2734, smoke-tested on redbull
=> Release NCN images with fix for CASMTRIAGE-2734

CHANGELOG.md, manifests/nexus.yaml
Bi-CAN : Update the virtual service ingress cray-nexus gateways to also include customer-admin-gateway and customer-user-gateway.
backward compatible since the service-gateway still remains as an ingress gateway.
* Resolves [CASMPET-4951](https://connect.us.cray.com/jira/browse/CASMPET-4951)
* Future work required NA
* Documentation changes required NA
wasp (1.2.0-alpha.20)
before
```
ncn-m001:~ # kubectl get vs -n nexus
NAME    GATEWAYS                        HOSTS                                                               AGE
nexus   ["services/services-gateway"]   ["packages.local","registry.local","nexus.cmn.wasp.dev.cray.com"]   26h
```
after - additional gateways are present
```
ncn-m001:/tmp/kimj # kubectl get vs -n …
```
=> CASMPET-4951-1.2 : BI-CAN: Update nexus to use the new API Gateways

manifests/platform.yaml
https://connect.us.cray.com/jira/browse/CASMMON-103
https://github.com/Cray-HPE/cray-sysmgmt-health/pull/39
https://github.com/Cray-HPE/cray-sysmgmt-health/releases/tag/v1.3.0
=> CASMMON-103:NodeFilesystemAlmostOutOfSpace bug

assets.sh
* livecd: MTL-1558
* NCNs: CASMINST-3568, CASMINST-3564
=> CASMREL-824: assets update

assets.sh
LiveCD:
* CASMPET-4873
* CASMHMS-5273
NCNs:
* MTL-1462
* MTL-1559
* MTL-1553
* CASMHMS-5273
=> CASMREL-826: image assets

docker/index.yaml, manifests/core-services.yaml
Pulling new SLS helm chart with CASM-2670 changes. Also pull in a fix for CASMINST-3446.
* Resolves CASMHMS-5197
* Wasp
- Were continuous integration tests run? If not, why? 
- Was downgrade tested? If not, why? Yes
- Were new tests (or test issues/Jiras) created for this change? No
For testing see: …
=> CASMHMS-5197: Pulling new SLS helm chart with CASM-2670 changes. Also

CHANGELOG.md, docker/index.yaml, rpm/cray/csm/sle-15sp2-compute/index.yaml, rpm/cray/csm/sle-15sp2/index.yaml
Support for SCSD new subcommand
Resolves CASMHMS-5273.
=> Support for SCSD new subcommand

vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
https://stash.us.cray.com/projects/CAR/repos/sma-rsyslog/pull-requests/131/overview
updated customizations.yaml pointing both udp and tcp pointing same ip
=> CASMSMF-6605:rsyslog-aggregator udp listens to wrong IP address

assets.sh
LiveCD: CASMINST-3611
NCNs: CASMINST-3573, MTL-1566
=> CASMREL-828: csm-1.2 images

assets.sh
Updated NCN images with fix for:
* CASMINST-3614
=> CASMREL-830: updated NCN images

assets.sh
=> CASMREL-831: NCN assets for csm-1.2

assets.sh
* CASMTRIAGE-2764 - Delay s3fs bucket mounting until ceph is really done with rgw config
* CASMTRIAGE-2732
* CASMHMS-5183
=> CASMREL-832: csm-1.2 NCN assets update

docker/index.yaml, manifests/sysmgmt.yaml
Includes changes for IMS, BOS and csm-ssh-keys using updated basecharts consistent with CASM-2670.
Related Issues:
- [CASMCMS-7622](https://connect.us.cray.com/jira/browse/CASMCMS-7622)
- [CASMCMS-7611](https://connect.us.cray.com/jira/browse/CASMCMS-7611)
- [CASMCMS-7617](https://connect.us.cray.com/jira/browse/CASMCMS-7617)
=> CASMCMS CASM-2670 PR Request 2 (Electric Boogaloo)

assets.sh
* Fixes CASMCMS-7691: Fix broken IMS signing keys test
=> CASMREL-833: new NCN images

docker/index.yaml, manifests/core-services.yaml, manifests/sysmgmt.yaml
CAPMC v1.30.0
SMD v1.37.0
Discovery v1.10.0
FAS v1.14.0
CASMHMS-4994
CASMHMS-5001
CASMHMS-5137
CASMHMS-5238
=> CAPMC 1.30.0 SMD 1.37.0 Discover 1.10.0 FAS 1.14.0

assets.sh
PIT:
* New CSI: https://github.com/Cray-HPE/csm/pull/208
* CASMINST-3639
NCNS:
* CASMINST-3626
=> CASMREL-835: NCN & PIT artifacts for csm-1.2

CHANGELOG.md, rpm/cray/csm/sle-15sp2/index.yaml
* Fixed race condition in restore script that was caused by deleting of the crd before the pods were restarted after restore. A delete of the crd is already being done before the restore starts and thus is not also needed after the restore completes.
* Fixed get_latest_backup to set the most_recent_backup_sec for first backup_instance.
This change is backward compatible
* Resolves [CASMINST-3621](https://connect.us.cray.com/jira/browse/CASMINST-3621)
* Documentation changes required NA
Verified restore succeeds
drax and vshasta
```
ncn-m001: # ./etcd_restore_rebuild.sh -s cray-bss-etcd
The following etcd clusters will be restored/rebuilt:
cray-bss-etcd
You will be accepting responsibility for any …
```
=> CASMINST-3621 1.2 : BREAK/FIX: Etcd backup restore failed

assets.sh
Includes:
- CASMINST-3653
PR for NCN Stable was here: https://github.com/Cray-HPE/node-image-build/pull/117
=> New NCN Images

assets.sh
* CASMTRIAGE-2648
* CASMINST-3633
* MTL-1576
=> CASMREL-837: CSM-1.2 LiveCD

rpm/cray/csm/sle-15sp2/index.yaml
ceph service check manifest change
* Resolves CASMINST-3469
*mug/fanta
manually ran script and verified results
n/a
=> 1.2 ceph service check manifest change

docker/index.yaml, manifests/sysmgmt.yaml
FAS to version 1.15.0 / FAS chart to 2.0.3
CASMHMS-5258
=> FAS to ver 1.15.0 / FAS chart to 2.0.3

assets.sh
* CASMTRIAGE-2801
* MTL-1578
* MTL-1492
=> CASMREL-839: NCN assets for csm-1.2

assets.sh
* CASMINST-2549: Add openssh packages to prevent dependency conflict
* CASMINST-3647
* CRAYSAT-1241: Add prodmgr RPM to CSM k8s image
* MTL-1582
=> CASMREL-840: NCN assets

assets.sh
* CASMTRIAGE-2702
* MTL-1568
* CASMINST-3410
* CASMNET-1061
=> LiveCD containing latest CSI

rpm/cray/csm/sle-15sp3/index.yaml
Update metal-ipxe to match what's included in the LiveCD.
=> CASMREL-843

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
CSI with the fix for CASMINST-3699
=> CASMINST-3699: release latest CSI

rpm/cray/csm/sle-15sp2/index.yaml
When downloading from S3, use the correct credentials for the specified bucket.
* Resolves [CASMINST-3700](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3700)
```
ncn-m001:~/bklein #./download-file.py --bucket-name velero --key-name backups/vault-daily-backup-20211215020056/velero-backup.json --file-name velero-backup.json
ncn-m001:~/bklein # ls -l velero-backup.json
-rw-r--r-- 1 root root 2451 Dec 15 19:34 velero-backup.json
```
```
ncn-m001:~/bklein # ./download-file.py --bucket-name boot-images --key-name 836f55cd-34c0-4b48-bbcb-e4a0df678287/manifest.json --file-name manifest.json
ncn-m001:~/bklein # ls -l manifest.json
-rw-r--r-- 1 root root 1148 Dec 15 19:35 manifest.json
```
```
ncn-m001:~/bklein # ./download-file.py --bucket-name etcd-backup --key-name …
```
=> New platform-utils rpm with fix for etcd restore helper script

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
Release the latest version of csi
=> MTL-1429: csi with 1.0 to 1.2 Upgrade Logic

manifests/sysmgmt.yaml
Update IMS to version v3.4.7
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_ Yes
* Resolves [CASMCMS-7722](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7722)
* Resolves [CASMCMS-7728](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7728)
* 
* `Hela`
- Were continuous integration tests run? If not, why? No
- …
=> CASMCMS-7722 Update IMS to version v3.4.7

assets.sh
Get the 1.0 branch caught up with the 1.0.1 changes for ceph/storage.
=> Align 1.0.10 assets.sh with 1.0.1 assets.sh

assets.sh
* CASMINST-3725
* CASMPET-4660
=> CASMREL-846: NCN assets

rpm/cray/csm/sle-15sp2/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml
See original PR for details:
https://github.com/Cray-HPE/cms-tools/pull/23
Related manifest PR:
=> CASMINST-3725: Fix typos in barebones boot test

manifests/sysmgmt.yaml
Fixing a BOS bug CASMCMS-7753. See related PRs.
=> CASMCMS-7753: Pull in new BOS/BOA

manifests/sysmgmt.yaml
Changed BSS to respond faster to requests to get the boot parameters.
* Resolves CASMHMS-4540
For testing see:
https://github.com/Cray-HPE/hms-bss/pull/42
Lots of testing was done to mitigate the risks.
=> CASMHMS-4540 Performance improvements in bss

install.sh, tds_cpu_requests.yaml
Edit customizations.yaml during fresh install to apply lower CPU requests for some services requests larger than needed on TDS/3 worker systems.
* Partially Resolves [CASMINST-3688](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3688)
Validated the merge of yaml looks correct (craystack)
* `craystack`
Yaml looks good, will need to validate final chart impacts on a fresh install 1.2 system (with SMA installed)
None
=> Changes to reduce CPU requests for TDS systems

assets.sh
LiveCD:
* CASMTRIAGE-2793
NCNs:
* MTL-1587
=> CASMREL-853: image assets for 1.2.0-alpha.43

install.sh, release.sh
Add path to yq included in distribution when modifying customizations for TDS systems.
* Resolves [CASMINST-3744](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3744)
surtur
* `surtur`
Ran the new code, which finds yq
Low
=> Add path to yq when modifying customizations for tds systems

manifests/sysmgmt.yaml
Rebuild the barebones container to pull in fixes for synk vulnerabilities. 
Yes
* Resolves [CASMCMS-7751](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7751)
Not tested. Simple rebuild of the barebones container.
=> CASMCMS-7751 Update barebones container for synk

rpm/cray/csm/sle-15sp2/index.yaml
Debug logic is preventing full run and has far too much output.
CASMINST-3751
Tested on Drax
Installed new RPM, ran upgrade, saw updated entries.
No risk.
- [X ] Version number(s) incremented, if applicable
- [X ] Copyrights updated
- [X ] License file intact
- [X ] Target branch correct
- [X ] CHANGELOG.md updated
- [X ] Testing is appropriate and complete, if applicable
- [X ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable
=> Removed debug logging and break from CSI

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
Latest CSI with fix for CASMISNT-3751
=> CASMINST-3751: release latest CSI

rpm/cray/csm/sle-15sp2/index.yaml
Canu upgrade to 1.1.1
* Resolves 
CASMNET-1088
CASMNET-1089
CASMNET-1090
CASMNET-1099
CASMNET-1092
CASMNET-1098
CASMNET-1077
Hela
Ran CANU on Hela successfully. 
No
=> Casmnet 1089,1088,1090,1099

assets.sh
LiveCD:
- [canu] CASMNET-1099 spanning-tree forward-delay 4
- [rpm] MTL-1598 Remove hexane
- [csi] CASMINST-3751 clean-up debug logic
NCN:
- [rpm] MTL-1598 Remove hexane
- [rpm] CRAYSAT-1246 new prodmgr
* `redbull` …
=> CASMREL-857 New LiveCD and NCN Images

CHANGELOG.md, docker/index.yaml, manifests/platform.yaml
Updates prometheus operator ghostunnel image based on recently created container-images for ghostunnel v1.6.0
* Resolves [CASMPET-5224](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5224)
* Change will also be needed in release/1.2
* Documentation changes required NA
vshasta
```
C02YP47BLVCG:my_workspace kim.jensen$ kubectl get pods -A | grep promet-oper
sysmgmt-health      cray-sysmgmt-health-promet-operator-7df8c5bc49-rjhmt              2/2     Running            0          4m38s
C02YP47BLVCG:my_workspace kim.jensen$ kubectl describe pod cray-sysmgmt-health-promet-operator-7df8c5bc49-rjhmt -n sysmgmt-health | grep "Image:" | grep ghost
Image: …
```
=> CASMPET-5224 main : SECURITY : update ghostunnel for sec vulnerabilities

assets.sh
PIT:
* CASMINST-3780
NCNs:
* CASMINST-3780
* CASMPET-5183
* CASMINST-3629
=> CASMREL-859: PIT & NCN assets for 1.2.0-alpha-47

assets.sh
NCNs:
* CASMINST-3800
* CASMINST-3801
* CASMHMS-5312
=> CASMREL-860: 1.2.0-alpha.48 NCN assets

manifests/platform.yaml
https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5098
https://github.com/Cray-HPE/cray-sysmgmt-health/pull/49
https://github.com/Cray-HPE/cray-sysmgmt-health/releases/tag/v1.2.17
=> bump version

CHANGELOG.md, docker/index.yaml
Image created and used only by analytics and not part of any CASM chart.
HAL-2498 opened for any needed work by analytics.
Removing the reference from CASM docker manifest.
* Resolves [CASMPET-5234](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5234)
Low
=> CASMPET-5234 main : SECURITY: fix vulnerabilities in pvc-migrator

rpm/cray/csm/sle-15sp2/index.yaml
removed the no longer necessary entry or car.cray and added the  loftsman-1.2.0-1.x86_64 line.
* Resolves [CASM-3830](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3830)
* …
=> CASMINST-3830 - update lofstman package to 1.2.0-1 for csm 1.2

assets.sh
LiveCD:
* CASINST-3830
NCNS:
* CASMISNT-3830
* CASMINST-3803
* CASMINST-3669
* CASMHMS-5310
* CASMHMS-5317
=> CASMREL-864: New NCN and LiveCD images for CSM 1.2 alpha.50

assets.sh
NCNs:
* CASMINST-3827
* CASMINST-3825
=> CASMREL-866: NCN assets for CSM 1.2 alpha.51

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml
LiveCD:
* CASMINST-3789
NCNs:
* CASMINST-3789
* CASMINST-3838
=> CASMREL-867: CSM 1.2 image assets for 1.2.0-alpha.52

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
New version of cray-site-init, updated in both LiveCD image and RPM manifest.
* Resolves [CASMPET-5279](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5279)
=> CASMPET-5279: update version of csi

manifests/sysmgmt.yaml, rpm/cray/csm/sle-15sp2/index.yaml
=> CASMPET-5281

assets.sh
Version bump for NCN assets related to CASMINST-3485
=> CASMINST-3485: Update NCN assets

assets.sh
=> CASMINST-3866: liveCD with cray-site-init=1.14.4-1

rpm/cray/csm/sle-15sp2/index.yaml
=> CASMINST-3929

assets.sh
=> CASMINST-3831: new liveCD with CSI 1.14.6

assets.sh
PIT:
* CASMCMS-7784
NCNs:
* CASMCMS-7784
* CASMCMS-7783
* CASMINST-3857
=> CASMREL-873: NCN and PIT assets for CSM 1.2.0-alpha.58

manifests/core-services.yaml, manifests/platform.yaml, rpm/cray/csm/sle-15sp2/index.yaml
CASMNET-1103 - HELA: dhcp-helper.py crash
CASMNET-1104 - BREAK/FIX UPGRADE: dhcp-helper is putting IPs on the wrong interface
CASMNET-1108 - BREAK/FIX: NCN bond interface dhcp'ing and getting dhcp reservation
CASMNET-1118 - Alpine BaseOS version update to tackle some CVEs
CASMNET-1113 - improve kea api check in dhcp-helper
CASMINST-3274 - TESTS: Check for duplicate Kea reservations for NCNs during upgrade
CASMNET-1103 - HELA: dhcp-helper.py crash - add error handling
CASMNET-1104 - BREAK/FIX UPGRADE: dhcp-helper is putting IPs on the wrong interface - removed logic and assume mgmt0
CASMNET-1108 - BREAK/FIX: NCN bond interface dhcp'ing and getting dhcp reservation …
=> bugfixCASMNET-1103,CASMNET-1104,CASMNET-1108,CASMNET-1118,CASMNET-1113,CASMINST-3274 for csm-1.2

manifests/core-services.yaml, manifests/platform.yaml, rpm/cray/csm/sle-15sp2/index.yaml
CASMNET-1103 - HELA: dhcp-helper.py crash
CASMNET-1104 - BREAK/FIX UPGRADE: dhcp-helper is putting IPs on the wrong interface
CASMNET-1108 - BREAK/FIX: NCN bond interface dhcp'ing and getting dhcp reservation
CASMNET-1118 - Alpine BaseOS version update to tackle some CVEs
CASMNET-1113 - improve kea api check in dhcp-helper
CASMINST-3274 - TESTS: Check for duplicate Kea reservations for NCNs during upgrade
CASMNET-1103 - HELA: dhcp-helper.py crash - add error handling
CASMNET-1104 - BREAK/FIX UPGRADE: dhcp-helper is putting IPs on the wrong interface - removed logic and assume mgmt0
CASMNET-1108 - BREAK/FIX: NCN bond interface dhcp'ing and getting dhcp reservation …
=> CASMNET-1103,CASMNET-1104,CASMNET-1108,CASMNET-1118,CASMNET-1113,CASMINST-3274 for main

assets.sh
LiveCD:
* CASMINST-3935
NCNs:
* MTL-1609
=> CASMREL-876: assets for CSM-1.2-alpha.60

rpm/cray/csm/sle-15sp2/index.yaml
See individual tickets for details.
=> Pull in goss RPMs with fixes for CASMINST-3274, CASMINST-3945, and CASMINST-3949

rpm/cray/csm/sle-15sp2/index.yaml
=> CASMINST-3935

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
The MTL-1600 changes in CSI updates the syntax for the storage/ceph parameter.
PR here: https://github.com/Cray-HPE/cray-site-init/pull/119
* Resolves [MTL-1600](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1600)
* Merge with https://github.com/Cray-HPE/cray-site-init/pull/119
* `drax`
* `fanta`
_How were the changes tested and success verified? If schema …
=> MTL-1600 New CSI & LiveCD

assets.sh
NCNs:
* MTL-1614
* CASMNET-1132
=> CASMREL-877: NCN images for CSM-1.2-alpha.61

hack/gen-rpm-index.sh
Remove an extra new line that was unintentionally introduced with
https://github.com/Cray-HPE/csm/pull/451
=> Remove an extra newline character

manifests/sysmgmt.yaml
Fixing a BOS RPM build issue.
CASMCMS-7794
CASMCMS-7802
Build and Hela
* It builds.
* Also, tested the installation of the rpm on a compute node on Hela.
Low
=> Casmcms 7794 1.2

assets.sh
NCNs:
* CASMHMS-5346
* CASMHMS-5365
* MTL-1492
=> CASMREL-883: NCN assets for CSM 1.2-alpha.66

manifests/sysmgmt.yaml
Fix CVE vulnerabilities in multiple services.
Code PR's:
https://github.com/Cray-HPE/image-recipes/pull/16
https://github.com/Cray-HPE/cfs-operator/pull/36
https://github.com/Cray-HPE/container-images/pull/390
* Resolves [CASMCMS-7816](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7816)
* Resolves [CASMCMS-7817](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7817)
* Multiple ways
See individual code PR's for testings.  All were verified by manual snyk test that vulnerabilities were resolved.  The individual services were tested as needed based on the amount of change introduced.
Low risks - there were no code changes, just switching to different (updated) base images.
=> CASMCMS - CVE fixes for multiple services.

upgrade.sh
Fix typo in the undeploy - 1.2 only
* Resolves CASMPET-4010
=> CASMPET-4010_1.2 - fix typo in undeploy.

assets.sh
LiveCD with new CSI containing the fix for CASMINST-3828
=> CASMINST-3828: new CSI

assets.sh
Assets bump for MTL-1495: RAID wait circumvention code fix
=> MTL-1495: Assets update for dracut-metal-mdsquash fix

manifests/sysmgmt.yaml
To resolve CVE vulnerabilities, this needed to incorporate a new base image and a new security patched version of cf-gitea-import. There are no code changes, just a triggered rebuild to incorporate the patched dependent images.
Code PR:
https://github.com/Cray-HPE/csm-config/pull/43
* Resolves [CASMCMS-7819](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7819)
I verified the new images are free of known vulnerabilities using the snyk tool on the Jenkins built images. As there are no code changes I did not test on a machine. …
=> CASMCMS-7819 - update csm-config for CVE vulnerabilities.

assets.sh
=> CASMPET-5328: updated NCN images

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
LiveCD:
* CASMINST-3874 (metal-ipxe, csi)
NCNs:
* CASMINST-3874
=> CASMINST-3874: LiveCD and NCNs

rpm/cray/csm/sle-15sp2/index.yaml
=> CASMINST-4061 change wicked update version

assets.sh
PIT:
* CASMNET-1157
* CASMINST-4061
* CASMINST-3986
NCNs:
* CASMINST-3986
* CASMINST-4069
=> CASMREL-896: NCN and LiveCD assets for CSM-1.2-alpha.72

rpm/cray/csm/sle-15sp2/index.yaml
Bump Canu version
CASMINST-3986
Hela, Drax, VirtualEnv
=> CASMINST-3986

rpm/cray/csm/sle-15sp2/index.yaml
Bump Canu version
CASMINST-3986
Hela, Drax, VirtualEnv
=> CASMINST-3986 main

rpm/cray/csm/sle-15sp2/index.yaml
See PR for details: https://github.com/Cray-HPE/csm-testing/pull/200
=> CASMINST-4072: goss test improvements

assets.sh
PIT:
* MTL-1623
* CASMISNT-4040
=> CASMREL-898: new PIT iso for csm-1.2

rpm/cray/csm/sle-15sp2/index.yaml
See code PR for details:
https://github.com/Cray-HPE/pit-init/pull/19
=> CASMINST-4040: bios-baseline.sh --check no longer changes BMC ipmitool settings

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml
Resolves MTL-1624
* https://github.com/Cray-HPE/metal-ipxe/pull/34
=> MTL-1624: release new liveCD

rpm/cray/csm/sle-15sp2/index.yaml
CASMINST-4000 
BGP test fix.
Goss rpm version bump.
=> CASMINST-4000 1.2

rpm/cray/csm/sle-15sp2/index.yaml
CASMINST-4000 
BGP test fix.
Goss rpm version bump.
=> CASMINST-4000 main

assets.sh
NCNs:
* CASMTRIAGE-3006
* CASMINST-3780
* CASMINST-4052
=> CASMREL-900: NCN images for 1.2.0-alpha-75

docker/index.yaml, manifests/sysmgmt.yaml
Update base container versions to alpine v3.15
Yes
* Resolves [CASMCMS-7829](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7829)
* `hela` …
=> CASMCMS-7829 Update base containers to alpine v3.15

rpm/cray/csm/sle-15sp2/index.yaml
Bump CANU Version
CASMNET-1163
CASMNET-4051
CASMNET-1159
CASMNET-1160
CASMNET-998
Virtual Env
Hela
=> CASMNET-1163

manifests/core-services.yaml, manifests/platform.yaml
- added creation of empty /etc/unbound/records.conf to add stability to pod startup
- added logic in initialize.py to regenerate empty files for /etc/unbound/records.conf and /etc/unbound/unbound.conf
- yes
* Resolves 
- CASMINST-3031
- 
Loki
```
bash-5.1$ rm -rf /etc/unbound/config_loaded ;rm -rf /etc/unbound/records.conf ;rm -rf /etc/unbound/unbound.conf; ./test-1.2.py 
2022-Mar-01 15:02 …
```
=> CASMTRIAGE-3031 - fix for unbound startup

assets.sh
PIT:
* CASMNET-1163
* CASMNET-4051
* CASMNET-1159
* CASMNET-1160
* CASMNET-998
* CASMINST-4116
NCNs:
* CASMNET-1163
* CASMNET-4051
* CASMNET-1159
* CASMNET-1160
* CASMNET-998
=> CASMREL-904: NCN and PIT assets for CSM-1.2.0-alpha.79

rpm/cray/csm/sle-15sp2/index.yaml
- Fixes #CASMINST-1172
The switches have been locked down in 1.2 to disallow ssh to the switches via the NMN.   However, the host records we create for the switches use the NMN IPs.  This changes both the fresh install and upgrade paths of CSI to use the HMN IPs for the switches in their host records.
Kind of tested on hela.  I used the hela seed files to run `csi config init` and verified that the host records in the generated data.json have the HMN IPs for the switches.
```
{
"ip": "10.254.0.2",
"aliases": [
"sw-spine-001"
]
},
{
"ip": "10.254.0.3",
"aliases": [
"sw-spine-002"
]
},
{
"ip": "10.254.0.4",
"aliases": [
"sw-leaf-001"
]
},
{
"ip": "10.254.0.5",
"aliases": [
"sw-leaf-002"
]
},
{
"ip": "10.254.0.6",
"aliases": [
"sw-leaf-003"
]
},
{
"ip": "10.254.0.7", …
```
=> CASMNET-1172: Update cray-site-init RPM to 1.16.3

assets.sh
See: https://github.com/Cray-HPE/node-image-build/pull/201
=> MTL-1616: fixup broken services

install.sh
=> Revert "Add check during install.sh to ensure etcd clusters have three members"

assets.sh
NCN images containing fix for CASMTRIAGE-3068.
See: https://github.com/Cray-HPE/node-image-build/pull/202
=> CASMTRIAGE-3068: Point token cert refresh script at kube config file

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
Release LiveCD with latest CSI.  Release latest CSI.
=> CASMINST-3670 CASMNET-1165 - release latest LiveCD and CSI rpm

assets.sh
PIT:
* CASMINST-4117
NCNs:
* CASMTRIAGE-3076
=> CASMREL-909: images for 1.2.0-beta.83

manifests/sysmgmt.yaml
See code PRs for details:
https://github.com/Cray-HPE/gitea/pull/16
https://github.com/Cray-HPE/gitea/pull/17
=> Pull in fix for CASMCMS-7891

manifests/core-services.yaml, manifests/platform.yaml
Done the code changes for missed dhcp exporter changes in values.yaml startup scripts and updated latest dhcp grafana dashboards 
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-115
https://github.com/Cray-HPE/cray-dhcp-kea/pull/25
https://github.com/Cray-HPE/csm/pull/574
Tested on mug
=> CASMMON-115:  dhcp exporter issues

rpm/cray/csm/sle-15sp2/index.yaml
=> CASMINST-4117 cray-site-init version bump

assets.sh
LiveCD:
* CASMINST-4249
NCNs:
* CASMINST-4260
=> CASMREL-916: LiveCD and NCN images

assets.sh
NCN images with goss-servers=1.12.17-1
=> CASMINST-4250: NCN images

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
See here for code change: https://github.com/Cray-HPE/cray-site-init/pull/133
=> CASMINST-4285: update manifest and LiveCD with latest csi

manifests/core-services.yaml, manifests/platform.yaml
- create bare hostname entries of HSN NCN and UAN xnames
yes
- CASMNET-1274
- hela
- Was …
=> bugfix/CASMNET-1274-csm-1.2 - fix for missing HSN dns entries

manifests/sysmgmt.yaml
CASMHMS-5461: scsd chart to 2.0.2
=> CASMHMS-5461: scsd chart to 2.0.2 for main

manifests/sysmgmt.yaml
SCSD chart to 2.0.2 for CASMHMS-5461
=> CASMHMS-5461: scsd chart to 2.0.2

manifests/sysmgmt.yaml
SCSD chart to 2.0.2 for CASMHMS-5461
=> SCSD chart to 2.0.2 for CASMHMS-5461 release 1.2.5

assets.sh
PIT:
* CASMNET-1348
* CASMNET-974
NCNs:
* CASMNET-1348
* CASMNET-974
=> CASMNET-1348 CASMNET-974: release canu-1.3.2

ncn-image-modification.sh
Do a basic sanity check on any private ssh keys that exist in
the provided ssh key directory.
* `redbull`
Created a bad key in ~/.ssh/ by removing some lines from the existing private key.  Ran the script, which flagged the bad private key:
```
ncn-m002:~ # ./ncn-image-modification.sh -p -d /root/.ssh/ -k /dev/null -s /dev/null
Load key "/root/.ssh//id_rsa": invalid format
ERROR: unable to verify private key: /root/.ssh//id_rsa
ncn-m002:~ #
```
Restored the good key:
```
ncn-m002:~ # mv .ssh/id_rsa.good .ssh/id_rsa
```
Re-ran the script:
```
ncn-m002:~ # ./ncn-image-modification.sh -p -d /root/.ssh/ -k /dev/null -s /dev/null
Signing file /tmp/ncn-ssh-keygen.cl9fXKXKDj/empty-file
Write signature to /tmp/ncn-ssh-keygen.cl9fXKXKDj/empty-file.sig
ERROR: …
```
=> CASMINST-4405: verify ssh key before adding it to the image

assets.sh
Code: https://github.com/Cray-HPE/node-image-build/pull/222
=> CASMINST-4310: update containerd config for arti hostname change

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml
This change fixes some echo statements and removes calls to `nstat`, which doesn't print anything.
Yes.
* Resolves [MTL-1658](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1658)
None.
=> MTL-1658 Updated echos and removal of nstat

rpm/cray/csm/sle-15sp2/index.yaml
CASMINST-4419
- Were continuous integration …
=> CASMINST-4419

CHANGELOG.md, manifests/platform.yaml, vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
Upgrade istio to 1.9.9, OPA envoy plugin to 0.26.0-envoy-6, kiali to 1.33.1. …
=> CASMPET-5303: upgrade istio to 1.9.9

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml
PIT:
* MTL-1658
* CASMINST-4432
* CASMINST-4435
=> CASMREL-931: PIT ISO

assets.sh
PIT:
* CASMINST-4283
* CASMINST-4421
* MTL-1655
NCNs:
* MTL-1664
=> CASMREL-932: assets for 1.2.0-beta.102

rpm/cray/csm/sle-15sp2/index.yaml
See code PR for details:
https://github.com/Cray-HPE/csm-testing/pull/279
=> CASMINST-4451: Correct retry loop logic in clock skew test

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
This adds a function that will disable DHCP over the Shared NIC on HPE servers equipped with iLO5.
The new function checks the current DHCP setting and toggles it to False if it is not already set to that value.
Output shows that DHCP is enabled, so the tool will disable DHCP:
```bash
The running host [ncn-m001-mgmt] will have settings applied last.
Verifying 10 iLO/BMCs (non-compute nodes) match BIOS baseline spec.
================================
Checking ncn-s002-mgmt ... differs from spec
ipmitool usage: enabled
BMC Shared NIC DHCP: enabled
```
A re-run shows that DHCP is disabled:
```bash
The running host [ncn-m001-mgmt] will have settings applied last. …
```
=> CASMINST-4430 Disable Shared NIC DHCP Requests

CHANGELOG.md, manifests/platform.yaml
Addition of kyverno namespace
* Resolves CASMPET-5498
- vshasta
=> CASMPET-5498 - release cray-drydock 2.12.2

manifests/platform.yaml
Fixed Grafana Istio performance dashboard data not found issues.
* Resolves: CASMPET-5438
=> Bump the chart version

manifests/sysmgmt.yaml
hms-hmnfd chart to version 2.0.3 to fix build action
=> hms-hmnfd to version 2.0.3

manifests/sysmgmt.yaml
hms-hmnfd chart to version 2.0.3 to fix build action
=> hms-hmnfd to 2.0.3

ncn-image-modification.sh
Reverts Cray-HPE/csm#728
Waiting until next week
=> Revert "CASMINST-4480: cleanup mounts and squshfs-root on interrupt/error"

rpm/cray/csm/sle-15sp2/index.yaml
=> update csi version

assets.sh
=> CASMINST-4478: new CSI

assets.sh
=> CASMTRIAGE-3193: NCN image tag with the fix

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
In addition to the following verbiage for CAMINST-4485... this PR contains NCN images and a new LiveCD containing the fix(es) for CASMNET-1518/CASMNET-1519.
A subset of the generated data from `csi config init` needs to be merged into the site-init/customizations.yaml file. PIT Init calls `csi config init` before copying the generated files into place, but it fails to handle the merge into customizations.yaml. This changes fixes that gap by invoking yq to merge that newly generated data into customizatons.yaml. PIT Init will do this before patching the CA certificate. All that needs to happen now from a pit-init perspective is the CSI files must be in place, and …
=> CASMINST-4485 CASMNET-1518 CASMNET-1519 1.2

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
A subset of the generated data from `csi config init` needs to be merged into the site-init/customizations.yaml file. PIT Init calls `csi config init` before copying the generated files into place, but it fails to handle the merge into customizations.yaml. This changes fixes that gap by invoking yq to merge that newly generated data into customizatons.yaml. PIT Init will do this before patching the CA certificate. All that needs to happen now from a pit-init perspective is the CSI files must be in place, and site-init must be created.
The docs will still entail calling `csi config init`, and then creating site-init before calling pit-init. However this change …
=> CASMINST-4485 CASMINST-4471 New pit-init, pit-nexus, and metal-basecamp with a new LiveCD

ncn-image-modification.sh
=> Revert "Revert "CASMINST-4480: cleanup mounts and squshfs-root on interrupt/error""

manifests/sysmgmt.yaml
Log rotation was failing due to two problems.
The first is that log rotation needs the target file and the backup directory to be on the same device due to the way it handles the file rotations. The log aggregation file was set to backup to a different device, so the log rotation call was failing. When it failed it didn't rotate any of the files despite the error with only one entry in the config file.
The second problem is that with the change to user 'nobody' the process no longer had permission to modify the log rotation configuration file as the default location is owned by root. I changed this to use a custom configuration file that is owned by the 'nobody' user. This should be safer as this is the only process that will call logrotate using this configuration file.
Code change PR: …
=> CASMCMS-7989 - fix log rotation in cray-console-node

manifests/sysmgmt.yaml
See source PR for details:
https://github.com/Cray-HPE/csm-config/pull/51
=> CASMCMS-7990: Automatically append newlines to SSH key files during NCN personalization play

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
Tested and works with podman 3.4.4.
=> CASMINST-4471 fix for making sure basecamp and nexus startup

manifests/platform.yaml
CPS and NMD OPA update for least privilege access model.
* Resolves [SKERN-4961](https://jira-pro.its.hpecorp.net:8443/browse/SKERN-4961) [SKERN-4998](https://jira-pro.its.hpecorp.net:8443/browse/SKERN-4998)
* Change will also be needed in `NA`
This mod is tested on hela by running the new OPA setup and tested all CPS and NMD API access to verify the API access.
* `Hela`
New OPA setup for CPS and NMD is applied to Hela, then verified all API accesses. …
=> SKERN-4961 and SKERN-4998

rpm/cray/csm/sle-15sp2/index.yaml
csm-1.3 version of this PR:
https://github.com/Cray-HPE/csm/pull/766
=> CASMINST-4532/CASMINST-4457: Create xname test, fix clock skew test

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
=> CASMPET-5563 update manifest

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
=> CASMREL-950: NCN & PIT assets, manifest bump for pit-init

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
=> CASMREL-914: PIT asset and manifest bump for pit-init

assets.sh
LiveCD:
- CASMINST-4425
Also needs a docs-csm merge: https://github.com/Cray-HPE/docs-csm/pull/1534
=> CASMREL-914

assets.sh
LiveCD:
- CASMINST-4425
NCN:
- CASMINST-4425
Also needs a docs-csm merge: https://github.com/Cray-HPE/docs-csm/pull/1535
=> CASMREL-960

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
Update the `dns_records.py` script to use the NMN API gateway URL so the API call doesn't fail.
* Resolves [CASMNET-1539](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1539) and [CAST-29864](https://jira-pro.its.hpecorp.net:8443/browse/CAST-29864)
* `wasp`
=> CASMNET-1539 - Update dns_records.py API call to use the correct API gateway.

assets.sh
#812 did not actually have the assets for MTL-1688 and MTL-1687.  This does.
=> MTL-1688-and-MTL-1687 redux

manifests/core-services.yaml, manifests/platform.yaml
…e name
- add feature to dynamically update boot file name from cray-ipxe in cray-dhcp-kea dhcp-helper.py
casminst-4526
- hela
- testing was done by testing cray-dhcp-kea and cray-ipxe upgrades together and independantly 
- Were the …
=> CASMINST-4526 - dynamic boot file name for cray-dhcp-kea

manifests/platform.yaml
Add tenants and hnc-system namespaces in support of multi-tenancy.
* Resolves [CASMINST-4296](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4296)
```
ncn-m001-fec36008:/home/bklein # kubectl get namespace tenants -o yaml
apiVersion: v1
kind: Namespace
metadata:
annotations:
meta.helm.sh/release-name: cray-drydock
meta.helm.sh/release-namespace: loftsman
creationTimestamp: "2022-04-25T20:10:30Z"
labels:
app.kubernetes.io/managed-by: Helm
helm.sh/chart: cray-drydock-2.13.1
hnc.x-k8s.io/included-namespace: "true"
istio-injection: enabled
name: tenants
tenants.tree.hnc.x-k8s.io/depth: "0"
managedFields:
- apiVersion: v1
fieldsType: FieldsV1
fieldsV1:
f:metadata:
f:annotations:
.: {}
f:meta.helm.sh/release-name: {}
f:meta.helm.sh/release-namespace: {}
f:labels:
.: {} …
```
=> Add tenants and hnc-system namespaces

manifests/platform.yaml
Add psp for cray-tapms-operator
* Resolves [CASMINST-4647](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4647)
```
ncn-m001-fec36008:/home/bklein # helm ls -n services | grep psp
cray-psp                    	services 	2       	2022-05-18 14:19:15.811451062 +0000 UTC	deployed	cray-psp-0.4.0
```
```
ncn-m001-fec36008:/home/bklein # kubectl get clusterrolebindings.rbac.authorization.k8s.io cray-tapms-operator-psp -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
annotations:
meta.helm.sh/release-name: cray-psp
meta.helm.sh/release-namespace: services
creationTimestamp: "2022-05-18T14:19:17Z"
labels:
app.kubernetes.io/managed-by: Helm
managedFields:
- apiVersion: rbac.authorization.k8s.io/v1
fieldsType: FieldsV1
fieldsV1:
f:metadata:
f:annotations:
.: …
```
=> Add psp for cray-tapms-operator

rpm/cray/csm/sle-15sp2/index.yaml
Signed-off-by: Jacob Salmela <jacob.salmela@hpe.com>
Includes the new bios/firmware test.
* Resolves CASMTRIAGE-3363
* Merge with https://github.com/Cray-HPE/csm-testing/pull/320
Results in https://github.com/Cray-HPE/csm-testing/pull/319
Low
=> CASMTRIAGE-3363 add updated bios/firmware test

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml
LiveCD:
- [MTL-1747](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1747) (canu & csi)
- [MTL-1749](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1749) (metal-basecamp)
- [CASMNET-1519](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1519) (canu)
- [CASMNET-1541](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1541) (canu)
- [CASMNET-1548](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1548) (canu)
NCN:
- [MTL-1682](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1682) (new kernel)
- [MTL-1747](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1747) (canu & csi)
- [MTL-1748](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1748) (NVME support)
- [CASMTRIAGE-3280](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3280) (weave)
- …
=> CASMREL-970

docker/index.yaml
Cray-canu is missing from the manifest.
=> CASMREL-970 Include cray-canu

assets.sh, docker/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml
LiveCD:
- [CASMINST-4667](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4667)
NCN Images:
- [CASMINST-4667](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4667)
- [CASMNET-1568](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1568)
=> CASMREL-973

manifests/platform.yaml
set holdApplicationUntilProxyStarts true as default
* Resolves [CASMPET-5642](issue link) …
=> CASMPET-5642 set holdApplicationUntilProxyStarts true as default

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
LiveCD:
- [CASMINST-4671](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4671)
- [MTL-1762](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1762)
- [MTL-1768](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1768)
NCN:
- [CASMINST-4659](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4659)
- [CASMPET-5442](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5442)
- [CASMPET-5580](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5580)
- [VSHA-399](https://jira-pro.its.hpecorp.net:8443/browse/VSHA-399)
=> CASMREL-976

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
LiveCD:
- [CASMINST-4671](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4671)
NCN:
- [CASMINST-4682](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4682)
=> CASMREL-975

rpm/cray/csm/sle-15sp2/index.yaml
There was an issue that was fixed in 1.2 but not in 1.0 where the goss_platform_ca_certs_match_cloud_init can fail if the ca-certs in the local file are not ordered the same as in the BSS meta-data
The test requires that the data be sorted and then diff'ed.
This was hit during a 1.0.11 fresh install of SS611 TDS
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_ Yes
* Resolves [CASMPET-5684](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5684)
groot and drax
* Local …
=> CASMPET-5684 1.0 : TESTS : Add sort fix to goss_platform_ca_certs_match_cloud_init

assets.sh
NCN images with fixes for CASMNET-1549 and  CASMTRIAGE-3391
=> CASMNET-1549 CASMTRIAGE-3391: new NCN images

manifests/core-services.yaml, manifests/platform.yaml
…s are loaded
- fix duplicate xname A records when compute node CHN IPs are loaded
- 
CSMNET-1577
hela …
=> bug/CASMNET-1577 - fix duplicate xname A records when compute node CHN IPs are loaded

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml
LiveCD:
- [CASMINST-925](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-925)
- [MTL-1771](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1771)
- [MTL-1773](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1773)
- [MTL-1774](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1774)
- [MTL-1775](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1775)
=> Casmrel 978 livecd

assets.sh
NCNs:
* CASMTRIAGE-3391
* CASMNET-1549
* MTL-1704
* CASMINST-4301
=> CASMREL-984: NCN assets

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml
New PIT iso with a new pit-init rpm
=> CASMINST-4745 MTL-1787: PIT ISO with a new pit-init rpm

manifests/sysmgmt.yaml
CASMHMS-5578: Bump application image version to 1.17.0 to pick up fix to only create redfish endpoints in HSM if they do not exist.
• CASMHMS-5579: Updated the service name for the collector, as it was changed in CSM 1.2 to cray-hms-hmcollector-ingress.
* …
=> CASMHMS-5578: Update RTS version to 2.0.2

lib/install-goss-tests.sh
Add canu to the list of rpms installed from the tarball
Pairs with https://github.com/Cray-HPE/node-images/pull/332
* Relates to CASMNET-1591
Tested on redbull.
=> CASMNET-1591: add canu to the list of rpms installed from the tarball

assets.sh
LiveCD:
* CASMNET-1591
* CASMTRIAGE-3475
NCNs:
* CASMTRIAGE-3475
* CASMNET-1591 (remove canu from NCNs - added by cloud-init/install script now)
=> CASMREL-989: assets

docker/index.yaml
Update HMS chart versions for github action conversion for all cray-hms-* charts.
* Resolves [CASMHMS-5559](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5559)
N/A
Build only changes
=> CASMHMS-5559 Update manifests for HMS GitHub Actions build conversions pt. 2

assets.sh, docker/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml
=> CASMTRIAGE-3402

rpm/cray/csm/sle-15sp3/index.yaml
Fixes to CSI tool. See source PR for more info:
https://github.com/Cray-HPE/cray-site-init/pull/188
=> CASMINST-4794: CSI: Correct misspellings and one other error

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml
LiveCD:
- [MTL-1750](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1750) (note: CSI was included yesterday with #908 )
NCN:
- [CASMPET-5586](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5586)
- [CASMPET-5682](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5682)
- [CASMINST-4742](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4742)
- [MTL-1798](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1798)
- [VSHA-402](https://jira-pro.its.hpecorp.net:8443/browse/VSHA-402)
=> CASMREL-990

lib/install-goss-tests.sh
Add canu to the list of RPMs installed by this script.
Pairs with https://github.com/Cray-HPE/node-images/pull/334
Related to CASMNET-1591
=> CASMNET-1591: add canu to the list of RPMs installed by this script

rpm/cray/csm/sle-15sp2/index.yaml
We've seen a few cases this week where if the preflight fails on SyncFailed, the test does not give link for remediation. This adds that info to the test.
* Resolves [CASMINST-4764](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4764)
- Were the …
=> CASMINST-4764 1.3 : Still seeing the check for SynFailed failing - automated remediation is next step?

docker/index.yaml, manifests/platform.yaml, vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
backport argo deployment from 1.3 to 1.2.6
- …
=> argo deployment in 1.2.6

docker/index.yaml, manifests/platform.yaml, vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
=> CASMPET-5680 update customizations

manifests/platform.yaml, vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
=> backport - Casmpet 5735 

manifests/platform.yaml
Adding new admission controller kyverno to CSM main branch
CASMPET-5433:  https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5433
Chart PR https://github.com/Cray-HPE/cray-kyverno/pull/5
Tested the chart on vshasta
NA
No dependencies.
=> Adding cray-kyverno chart

assets.sh
LiveCD:
- [MTL-1708](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1708)
- [MTL-1808](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1808)
NCN:
- [CASMINST-4814](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4814)
- [MTL-1708](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1708)
- [MTL-1808](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1808)
- [MTL-1811](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1811)
=> CASMREL-997

manifests/platform.yaml
update nls chart
* Resolves CASMPET-5455,5456,5457,5740 …
=> update nls chart version

assets.sh
Code change: https://github.com/Cray-HPE/node-images/pull/355
=> MTL-1812: assets

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
LiveCD and manifest update for new CSI
=> CASMUSER-3028: LiveCD and manifest update for new CSI

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
This brings in an SP2 compatible ilorest RPM, this RPM is needed by `prerequisites.sh`.
This also includes a new LiveCD which has the newly created RPM inside.
This change for main includes some very minor upstream updates as well.
=> CASMTRIAGE-3600 New ilorest

assets.sh, ncn-image-modification.sh, rpm/cray/csm/sle-15sp3/index.yaml
LiveCD:
- [MTL-1799](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1799)
- [MTL-1806](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1806)
- [MTL-1818](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1818)
- [MTL-1820](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1820)
NCNs:
- [MTL-1761](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1761)
- [MTL-1799](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1799)
- [MTL-1819](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1819)
- [MTL-1827](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1827)
`ncn-image-modification.sh`:
- [MTL-1761](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1761)
=> CASMREL-1000

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
LiveCD:
- [CASMTRIAGE-3640](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3640)
=> CASMREL-1007

manifests/platform.yaml
Add kyverno and kyverno-policy to CSM main branch
CASMPET-5433: https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5433
[vshasta-platform_changes.txt](https://github.com/Cray-HPE/csm/files/9017306/vshasta-platform_changes.txt)
- We have covered Installation scenario on vshasta. All the policies were installed successfully and were applied on the respective workloads.(PFA logs for reference)
- We have tested upgrade scenario by upgrading the kyverno chart. We could see that it didn't have any impact on the already installed policies.
- Also, when we delete the kyverno chart all the policies were deleted as expected
CASMINST-4864: https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4864
PR: https://github.com/Cray-HPE/csm/pull/952 (must be merged before this PR)
=> CASMPET-5433 Add kyverno and kyverno-policy to platform.yaml

docker/index.yaml, manifests/platform.yaml
=> Port back to main branch

rpm/cray/csm/sle-15sp2/index.yaml
csm-testing rpm with fix for clock skew test
=> CASMINST-4868: csm-testing rpm with fix for clock skew test

assets.sh
NCNs:
- [CASMPET-5748](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5748)
- [CASMTRIAGE-3637](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3637)
=> CASMREL-1008

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml
New LiveCD and manifest bump for CSI.
Code: https://github.com/Cray-HPE/cray-site-init/pull/201
=> CASMTRIAGE-3640: new CSI

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml
New LiveCD with:
- cray-site-init: https://github.com/Cray-HPE/cray-site-init/pull/202
- pit-init: https://github.com/Cray-HPE/pit-init/pull/46
=> CASMINST-4909 & MTL-1836 New LiveCD

manifests/sysmgmt.yaml
Updates the csm-config chart to pull in the new playbook that will install csm packages including the cfs-state-reporter
* Resolves CASMCMS-6989
* Playbook tested on groot
None
=> CASMCMS-6989: Update csm-config for new csm packages playbook

docker/index.yaml, manifests/sysmgmt.yaml
Add the ability to use template arguments in ims recipes
Code PR's:
https://github.com/Cray-HPE/ims-load-artifacts/pull/16
https://github.com/Cray-HPE/ims-utils/pull/21
https://github.com/Cray-HPE/ims/pull/29
https://github.com/Cray-HPE/ims-python-helper/pull/11
https://github.com/Cray-HPE/docs-csm/pull/974
https://github.com/Cray-HPE/cray-product-install-charts/pull/5
* Resolves [CASMCMS-7676](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7676)
* `Mug`
The tests are described in the code PR's listed above.
The risks are described in the code PR's listed above.
=> CASMCMS-7676 - add recipe template arguments to IMS.

manifests/sysmgmt.yaml
* Resolves [CASMSMF-6743](https://jira-pro.its.hpecorp.net:8443/browse/CASMSMF-6743)
See: https://github.hpe.com/hpe/hpc-car-sma-strimzi-kafka/pull/53 or 
No
=> CASMSMF-6743

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml
LiveCD:
- craycli [CASMCLOUD-1208](https://jira-pro.its.hpecorp.net:8443/browse/CASMCLOUD-1208)
- manifestgen [CASMCLOUD-1209](https://jira-pro.its.hpecorp.net:8443/browse/CASMCLOUD-1209)
NCNs:
- craycli [CASMCLOUD-1208](https://jira-pro.its.hpecorp.net:8443/browse/CASMCLOUD-1208)
- manifestgen [CASMCLOUD-1209](https://jira-pro.its.hpecorp.net:8443/browse/CASMCLOUD-1209)
- [CASMINST-4920](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4920)
- [CASMPET-5774](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5774)
- [VSHA-403](https://jira-pro.its.hpecorp.net:8443/browse/VSHA-403)
=> CASMREL-1018

docker/index.yaml, manifests/sysmgmt.yaml
=> Revert "CASMCMS-7676 - add recipe template arguments to IMS."

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml
See: https://github.com/Cray-HPE/pit-nexus/pull/13
=> CASMTRIAGE-3697 New pit-nexus

assets.sh
NCNs:
- [CASMTRIAGE-3697](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3697)
- [MTL-1839](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1839)
- [MTL-1842](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1842)
=> CASMREL-1019

rpm/cray/csm/sle-15sp2/index.yaml
Specifies postgres container in postgres goss test scripts
* Resolves [CASMTRIAGE-3727](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3727)
surtur
Verified that the tests that were failing now pass.
- Were new tests (or test issues/Jiras) …
=> CASMTRIAGE-3727-1.3 : INSTALL: Postgres test needs to specify a container

assets.sh, manifests/core-services.yaml, rpm/cray/csm/sle-15sp3/index.yaml
[CASMINST-3671](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3671) and [CASMINST-3788](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3788) CSI: Pull in newer CSI version that supports EX2500 cabinets. Also CSI is no longer generating bad Chassis data in SLS.
[CASMHMS-5291](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5291) SLS: Pull in newer SLS Add Model field to the cabinet extra properties structure
[CASMHMS-5567](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5567) MEDS: Pull in newer MEDS to allow MEDS to support variable number of Chassis in a Cabinet
_Is this change backwards incompatible, backwards compatible, or a backwards …
=> CASMINST-3671/CASMHMS-5291/CASMHMS-5567: EX2500 cabinet support in CSI/SLS/MEDS

hack/snyk-scan.sh
Introduce retry logic, in case if snyk scan errors out (exit code 2 or higher). This often happens due to internal error at snyk.io or connection timeout. Change is dackwards compatible.
* Resolves [CASMINST-4966](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4966)
* Locally
* Testing in Jenkins is currently blocked due to issues with OpenSUSE mirror
* Tested that retry logic succeeds on the first try with good image
* Tested that retry logic performs additional attempts and fails after 5 retries, by overriding snyk.io record in `/etc/hosts`
Low - build pipeline change only, can be easily rolled back.
=> CASMINST-4966 Introduce retry logic in snyk-scan.sh

assets.sh
PIT:
* CASMHMS-5562
* CASMHMS-5603
* CASMHMS-5617
* MTL-1845
NCNs:
* CASMHMS-5562
* CASMHMS-5603
* CASMHMS-5617
* MTL-1845
* MTL-1846
=> CASMREL-1021: image assets

manifests/sysmgmt.yaml
Pull in a new BOS version that correctly references an unstable build
on purpose.
- Was upgrade tested? If …
=> CASMCMS-8081: BOS V2 Now with Instability!

manifests/platform.yaml
Set oidc token timeout to four hours instead of one year
* Resolves [CASMINST-4957](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4957)
```
"id": "c445c659-00fa-426d-92c9-55fb490f5e25",
"clientId": "kubernetes-api-oidc-client",
"surrogateAuthRequired": false,
"enabled": true,
"alwaysDisplayInConsole": false,
"clientAuthenticatorType": "client-secret",
"secret": "**********",
"redirectUris": [],
"webOrigins": [],
"notBefore": 0,
"bearerOnly": false,
"consentRequired": false,
"standardFlowEnabled": true,
"implicitFlowEnabled": false,
"directAccessGrantsEnabled": true,
"serviceAccountsEnabled": false,
"publicClient": true,
"frontchannelLogout": false,
"protocol": "openid-connect",
"attributes": {
"access.token.lifespan": "14400"  <=======
},
```
```
{
"jti": …
```
=> Set oidc token timeout to four hours instead of one year

manifests/platform.yaml
=> CASMINST-5010 update manifest

assets.sh
LiveCD:
- [MTL-1612](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1612)
NCNs:
- [CASMPET-5814](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5814)
- [MTL-1612](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1612)
- [MTL-1852](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1852)
=> CASMREL-1029 New LiveCD and NCN Images

assets.sh
Includes MTL-1612 and CASMHMS-5606.
=> CASMREL-1029 LiveCD Amendment

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml
LiveCD:
- [CASMINST-5026](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5026)
- [CASMINST-4932](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4932)
NCNs:
- [CASMHMS-5606](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5606)
- [CASMINST-5026](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5026)
- [CASMINST-5034](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5034)
- [CASMINST-5037](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5037)
- [MTL-1853](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1853)
=> CASMREL-1030

manifests/core-services.yaml, manifests/platform.yaml
- index error during auto repair logic
y
CASMNET-1727
mug
- Was upgrade tested? If not, …
=> bug/CASMNET-1727 - index error during auto repair logic

manifests/platform.yaml
Update cray-nls versions so that cray-nls now include storage node functionality.
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in …
=> CASMINST-5004 update manifest for Cray-nls

assets.sh, docker/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml
New canu Docker image and RPM, with a LiveCD to match.
LiveCD:
- [CASMNET-1635](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1635)
- [CASMTRIAGE-3780](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3780)
=> CASMREL-1032

assets.sh, rpm/cray/csm/sle-15sp2-compute/index.yaml, rpm/cray/csm/sle-15sp2/index.yaml
LiveCD:
- [CASMUSER-3047](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-3047)
NCN:
- [CASMHMS-5628](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5628)
- [CASMINST-4783](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4783)
- [CASMINST-5025](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5025)
- [CASMINST-5051](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5051)
- [CASMINST-5055](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5055)
- [CASMINST-5095](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5095)
- [CASMNET-1635](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1635)
- [CASMPET-5756](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5756)
=> CASMREL-1034

rpm/cray/csm/sle-15sp3/index.yaml
See source PR for details:
https://github.com/Cray-HPE/cms-tools/pull/42
https://github.com/Cray-HPE/csm-rpms/pull/513
https://github.com/Cray-HPE/docs-csm/pull/2108
See source PR for details:
https://github.com/Cray-HPE/cms-tools/pull/42
Low risk. Small change.
=> CASMCMS-8069: Barebones boot test should not disobey --xname argument

assets.sh
NCNs:
* CASMINST-5122
* CASMHMS-5612
* CASMCMS-8069
=> CASMREL-1037: NCN assets

manifests/platform.yaml
update manifest with latest cray-nls version
- …
=> CASMINST-5117 update manifest with latest cray-nls version

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml
PIT:
* CASMUSER-3050
* CASMINST-4940
NCNs:
* MTL-1855
* CASMINST-5119
* CASMTRIAGE-3784
* CASMCMS-8068
=> CASMREL-1038: NCN/PIT assets

assets.sh
NCNs:
- [CASMPET-5829](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5829)
=> CASMREL-1039

manifests/platform.yaml, vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
=> CASMINST-5140 update manifest

manifests/core-services.yaml
Remove the hardcode of the HSM, SLS, and CAPMC endpoints for the mountain discovery script. This allows greater flexibility for the hms-discovery container image to work in environments outside of a installed CSM system, such as for use with the hms-simulation-environment.
* Resolves https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5613
* `Mug`
* hms-simulation-environment
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled …
=> CASMHMS-5613: Pull in newer hms-discovery chart

assets.sh
NCNs:
- [MTL-1830](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1830)
- [MTL-1841](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1841)
- [CASMINST-5124](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5124)
- [CASMINST-5129](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5129)
***NOTE*** Both CASMINST-5124 and CASMINST-5129 were already in the CSM tarball, they're just now also included in the NCN images.
=> CASMREL-1040

rpm/cray/csm/sle-15sp3/index.yaml
Minor enhancements to Goss test service and shared library, in support of upcoming improvements.
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5169
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5171
https://github.com/Cray-HPE/csm-rpms/pull/529
Tested on drax. See source PRs for full details:
https://github.com/Cray-HPE/csm-testing/pull/351
https://github.com/Cray-HPE/csm-testing/pull/352
Low risk.
=> CASMINST-5169/CASMINST-5171: Goss test server improvements

assets.sh
LiveCD:
- [MTL-1858](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1858)
- [MTL-1868](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1868)
NCNs:
- [CASMINST-5159](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5159)
- [MTL-1858](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1858)
- [MTL-1863](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1863)
- [MTL-1867](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1867)
=> CASMREL-1043

manifests/platform.yaml
Update hnc to final v1.0.0 build
* Resolves [CASMINST-4896](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4896)
Updated chart, ran CRUD operations on tenants, new version looks good.
Updated chart, ran CRUD operations on tenants, new version looks good.
Low
=> Update hnc with final v1.0.0 release (from rc2)

manifests/core-services.yaml, manifests/platform.yaml
-  fix missing variable assignment for repair_data
CASMINST05182
tyr 
surtur
- Was upgrade …
=> bug/CASMINST-5182 - fix missing variable assignment for repair_data

manifests/platform.yaml
=> CASMPET-5880 update manifest

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml
PIT:
* MTL-1870
* CASMINST-4903
* MTL-1869
NCNs:
* CASMPET-5851
=> CASMREL-1045: NCN assets

manifests/platform.yaml
=> CASMPET-5883 bump version

assets.sh
NCNs:
- [CASMINST-5137](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5137)
- [MTL-1872](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1872)
=> CASMREL-1047

rpm/cray/csm/sle-15sp3/index.yaml
The current version of velero has a bug which causes a backup to be created when the backup schedule is created.
On installs, this causes the backup to be run before the service is fully healthy and thus the backup ends up PartiallyFailed.
This removes any such PartiallyFailed backup that were created within 10m of the backup schedule creation time. The test then continues to check for any remaining *Failed backups. Those would still need to be investigated, but the initial PartiallyFailed backup will not longer cause the test to fail and need to be remediated since that particular PartiallyFailed backup(s) will be deleted.
This fix will reduce the install time given it automatically remediates those PartiallyFailed backups that are a result of a velero bug before the test to check for …
=> CASMINST-4278-1.3 : AUTOMATION: Find a solution/automated remediation/re-execute failed velero backups

assets.sh
NCNs:
- [CASMINST-4278](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4278)
- [CASMINST-5103](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5103)
- [CASMINST-5161](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5161)
- [CASMINST-5191](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5191)
- [MTL-1699](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1699)
=> CASMREL-1051

manifests/platform.yaml
Add propagation of resource quota and limit ranges in HNC tree.
* Resolves [CASMINST-4842](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4842)
```
1.6601692423951287e+09	INFO	controllers.Tenants	Successful update of resources for propogation: '[{ limitrange Propagate} { resourcequota Propagate} { roles Propagate} { rolebindings Propagate}]'
```
```
Synchronized resources:
* Propagating: limitrange (/v1)
* Propagating: resourcequota (/v1)
* Propagating: rolebindings (/v1)
* Propagating: roles (/v1)
Conditions:
```
Applied the, hnc configuration properly modified.
Low
=> Add propagation for additional objects (limitrange and resource quota)

rpm/cray/csm/sle-15sp3/index.yaml
See source PRs for details:
https://github.com/Cray-HPE/csm-testing/pull/353
https://github.com/Cray-HPE/csm-testing/pull/360
https://github.com/Cray-HPE/csm-testing/pull/358
https://github.com/Cray-HPE/csm-testing/pull/357
Fixes: [CASMINST-5195](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5195)
Fixes: [CASMPET-5559](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5559)
Fixes: [CASMPET-5620](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5620)
Fixes: [MTL-1646](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1646)
Fixes: [MTL-1847](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1847)
Fixes: [CASMINST-4281](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4281)
csm-rpms PR:
https://github.com/Cray-HPE/csm-rpms/pull/544
I tested my PR on surtur. I am including …
=> Update csm-testing/goss-servers to pull in CASMINST-5195, CASMPET-5559, CASMPET-5620, MTL-1646, MTL-1847, CASMINST-4281

assets.sh, manifests/sysmgmt.yaml, rpm/cray/csm/sle-15sp2-compute/index.yaml, rpm/cray/csm/sle-15sp2/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml, rpm/cray/csm/sle-15sp4-compute/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
LiveCD:
- [CASMINST-5026](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5026) (old, but missed)
- [CASMINST-5209](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5209)
- [CASMCMS-8090](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8090)
NCNs:
- [CASMCMS-7971](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7971)
- [CASMCMS-7991](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7991)
- [CASMCMS-8090](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8090)
- [CASMINST-4884](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4884)
- [CASMINST-5130](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5130)
- [CRAYSAT-1509](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1509)
- [HPCCHT3-3379](https://jira-pro.its.hpecorp.net:8443/browse/HPCCHT3-3379) …
=> CASMREL-1053

manifests/sysmgmt.yaml
Pulls in CASMCMS-8157. Look there for details: https://github.com/Cray-HPE/bos/pull/65
=> CASMCMS-8157: Pull this in

assets.sh
LiveCD:
- [MTL-1907](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1907)
NCNs:
- [CASMPET-5893](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5893)
- [MTL-1905](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1905)
- [MTL-1907](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1907)
=> CASMREL-1054

assets.sh, docker/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml
Overview
BUGFIX: Fix UAN configuration templates producing None VLAN when CHN is enabled.
BUGFIX: Enable 1.3 configuration templates in the pyinstaller binary.
Details
Update docs generated from code.
Change exception-handling in canu validate shcd and from network_modeling.
Provide better next steps from errors reported while validating SHCDs.
Add canu test to ping Kea DHCP.
Update to release process doc
- Fixes: CASMNET-1757
- Bugfix [Release 1.6.13](https://github.com/Cray-HPE/canu/pull/196)
Overview
BUGFIX: Fix UAN configuration templates producing None VLAN when CHN is enabled.
BUGFIX: Enable 1.3 configuration templates in the pyinstaller binary.
Details …
=> CASMNET-1757 canu uan vlan fix and 1.6.13 release 1.2 stable

manifests/sysmgmt.yaml
See https://github.com/Cray-HPE/bos/pull/66.
* Resolves CASMCMS-8101
=> CASMCMS-8101: Pull in new BOS

rpm/cray/csm/sle-15sp2-compute/index.yaml, rpm/cray/csm/sle-15sp2/index.yaml
Fixed loadstate and dumpstate for sls in the cray cli.
* Resolves [CASMHMS-5351](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5351)
* mug
* Local docker compose environment
Example tests:
```
openssl genpkey -out private.pem -algorithm RSA -pkeyopt rsa_keygen_bits:2048
openssl rsa -in private.pem -outform PEM -pubout -out public.pem
cray sls dumpstate create --public-key public.pem --format json > dumpstate.json
cray sls loadstate create --private-key private.pem dumpstate.json
cray sls loadstate create dumpstate.json
```
```
cray sls dumpstate list --format json > dumpstate.json
cray sls loadstate create dumpstate.json
cray sls loadstate create --private-key private.pem dumpstate.json
```
When loading on hardware, I …
=> CASMHMS-5351: Fixed sls loadstate and dumpstate in the cray cli

CHANGELOG.md, manifests/platform.yaml, manifests/sysmgmt.yaml
Released spire 2.10.0 and cray-nls 1.3.8 for security fixes.
* Resolves [CASMPET-5873](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5873) …
=> CASMPET-5873: spire 2.10.0 and cray-nls 1.3.8 for security fixes

rpm/cray/csm/sle-15sp2-compute/index.yaml, rpm/cray/csm/sle-15sp2/index.yaml
=> Revert "CASMHMS-5351: Fixed sls loadstate and dumpstate in the cray cli"

assets.sh, rpm/cray/csm/sle-15sp2-compute/index.yaml, rpm/cray/csm/sle-15sp2/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml
LiveCD:
- [CASMHMS-5351](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5351)
- [CASMINST-5240](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5240)
NCNs:
- [CASMHMS-5351](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5351)
- [CASMINST-5240](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5240)
=> CASMREL-1058

manifests/platform.yaml
Changes:
* Add PVC for first etcd cluster member when restored from backup
* Add automatic restoration from backup when quorum is lost (if available)
* Update golang and package versions to properly interact with k8s APIs (lots of non-functional changes)
* Resolves [CASMPET-5716](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5716)
Before:
```
persistentvolumeclaim/cray-bss-etcd-b2x8gnk7d6             Bound    pvc-b82b016a-3976-4a61-8c04-3562ef43f9e7   3Gi        RWO            k8s-block-replicated   17m
persistentvolumeclaim/cray-bss-etcd-lf5489zqqs             Bound    pvc-a4cfeb72-5824-4b05-a02a-a459edc393ae   3Gi        RWO            k8s-block-replicated   18m
persistentvolumeclaim/cray-bss-etcd-pfqpw9lzr8             Bound    pvc-f7a257eb-7fbb-49d9-909b-f3a3100fc649   3Gi …
```
=> Add support for PVCs for restored etcd clusters and auto-restore from backup

manifests/sysmgmt.yaml
There were 2 fixes in the release/csm-1.2 branch that didn't make it to the master branch, so were missing from the csm-1.3 version.  This picks up those fixes as well as updating the keycloak-setup version to resolve a CVE issue.  The missed fixes were for:
CASMCMS-7901 - postgres cluster setting fixes to resolve upgrade issue
CASMCMS-7891 - failure to create gitea user when password starts with a '-'
This also includes an update to the keycloak-setup version to pick up some CVE remediations.
Code PR:
https://github.com/Cray-HPE/gitea/pull/28
* Resolves [CASMCMS-7901](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7901)
* Resolves [CASMCMS-7891](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7891)
* Resolves [CASMINST-5250](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST …
=> CASMINST-5250 - Fix password issue and pick up CVE fixes.

assets.sh
Code change: https://github.com/Cray-HPE/node-images/pull/458
=> MTL-1906: ensure kata and containerd tarball unpack with root ownership

assets.sh
=> MTL-1909: NCN images with disk boot fix

manifests/storage.yaml
manifest change for ceph-csi upgrade
_How were the changes tested and …
=> CASMPET-5780 csm-1.3 manifest change for ceph-csi upgrade

manifests/storage.yaml
manifest change for ceph-csi upgrade
- Were …
=> CASMPET-5780 manifest change for ceph-csi upgrade

CHANGELOG.md, rpm/cray/csm/sle-15sp3/index.yaml
Release csm-testing for ceph goss test failure output fix. Output now points to documentation for remediation steps.
- Were the …
=> CASMPET-5324 release csm-testing 

manifests/platform.yaml
update configmap for ceph-csi upgrade
- Were …
=> CASMINST-5266 update configmap for ceph-csi upgrade

manifests/platform.yaml
update configmap for ceph-csi upgrade
- Were …
=> CASMINST-5266-main update configmap for ceph-csi upgrade

rpm/cray/csm/sle-15sp3/index.yaml
Backport CASMPET-5324 to csm-1.3
This is a change to goss output messages for ceph goss testsin csm-testing …
=> CASMPET-5911

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml
LiveCD:
- [CASMPET-5428](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5428)
NCNs:
- [CASMCMS-8087](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8087)
- [CASMPET-5911](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5911) (already merged via #1204, this just brings the NCN build in which is irrelevant bot logged here for bookkeeping).
- [MTL-1923](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1923)
- [MTL-1924](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1924)
- [MTL-1925](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1925)
=> CASMREL-1080

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml
LiveCD:
- [CASMPET-5428](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5428)
NCNs:
- [CRAYSAT-1476](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1476)
- [CASMCMS-8087](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8087)
- [CASMINST-5213](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5213)
- [CASMINST-5240](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5240)
- [MTL-1906](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1906)
- [MTL-1923](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1923)
- [MTL-1924](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1924)
- [MTL-1925](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1925)
=> CASMREL-1057

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml
LiveCD:
- [MTL-1876](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1876)
NCNs:
- [MTL-1876](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1876)
- [MTL-1926](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1926)
=> CASMREL-1083

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml
> The original PR for 1057 merged before it was ready, this includes
follow-up assets. #1208 
LiveCD:
- [MTL-1876](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1876)
NCNs:
- [MTL-1876](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1876)
- [MTL-1926](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1926)
=> CASMREL-1057 Follow-up

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml
LiveCD:
- [MTL-1876](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1926) (follow-up)
NCNs:
- [MTL-1926](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1926)
- [MTL-1930](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1930)
=> CASMREL-1084

assets.sh
=> CASMREL-1084: NCN images

assets.sh
=> CASMREL-1057: NCN assets

manifests/core-services.yaml, manifests/platform.yaml
- cray-dns-unbound - pod affinity configs
yes
CASMNET-1671
version is running on release/1.2 …
=> break/fix/CASMNET-1276/CASMNET-1671 - cray-dns-unbound - pod affinity configs

manifests/sysmgmt.yaml
Added PVC override for cray bos chart
Yes
* Resolves [issue id](issue link) https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7862
Mug
Trialed a helm deployment  …
=> increment bos release version

manifests/sysmgmt.yaml
The cray-cfs-api chart does not have overrides for the PVC storage class so the override was added. This is a bug fix
Can helm rollback.
* Resolves [issue id](issue link) https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7863
Mug
Ran helm deploy with updated image and template
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled …
=> increment cray-cfs-api version

rpm/cray/csm/sle-15sp3/index.yaml
Add Kyverno check scripts. See source PR for details:
https://github.com/Cray-HPE/csm-testing/pull/376
=> CASMINST-5088: Add Kyverno check scripts

assets.sh
LiveCD:
- [MTL-1903](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1903)
NCNs:
- [MTL-1903](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1903)
=> CASMREL-1094

rpm/cray/csm/sle-15sp3/index.yaml
=> MTL-1927: new csm-testing rpm with BIOS version updates

assets.sh
PIT:
* CASMINST-4637
NCNs:
* CASMINST-4637
* CASMTRIAGE-3997
=> CASMREL-1097: NCN & PIT images for 1.3 beta.50

Jenkinsfile.github, README.md, assets.sh, build/README.md, build/images/resolve.py, hack/gen-helm-index.sh, hack/gen-rpm-index.sh, hack/list-squashfs-rpms.sh, hack/verify-rpm-index.sh, manifests/platform.yaml, manifests/velero-1.7-upgrade.yaml, validate.sh
Verified hostname replacement with DST, spot tested instances locally.
=> replace arti.dev.cray.com hostname with arti.hpc.amslabs.hpecorp.net

rpm/cray/csm/sle-15sp3/index.yaml
csm-testing version change to remove user-prompt in ceph-service-status.sh …
=> CASMPET-5824 csm-testing version change to remove user-prompt in ceph-service-status.sh

rpm/cray/csm/sle-15sp3/index.yaml
csm-testing version change to remove user-prompt in ceph-service-status.sh …
=> CASMPET-5824 for csm-1.3: csm-testing version change to remove user-prompt in ceph-service-status.sh

Jenkinsfile.github, verify-docs-csm-tag.sh
=> CASMTRIAGE-4013 stable 1.2

Jenkinsfile.github, verify-docs-csm-tag.sh
=> CASMTRIAGE-4013 release 1.2

Jenkinsfile.github, verify-docs-csm-tag.sh
=> CASMTRIAGE-4013

Jenkinsfile.github, verify-docs-csm-tag.sh
=> CASMTRIAGE-4013 add/call verify-docs-csm-tag.sh

assets.sh
NCNs:
- [CASMREL-1091](https://jira-pro.its.hpecorp.net:8443/browse/CASMREL-1091)
=> CASMREL-1091 NCNs

manifests/core-services.yaml
This updates the HSM chart version for CASMHMS-5726 - Fix syntax error in migration down step 22
* Resolves [CASMHMS-5726](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5726)
For testing, see https://github.com/Cray-HPE/hms-smd/pull/89
none
=> Fix HSM CSM 1.3 database downgrade

CHANGELOG.md, manifests/platform.yaml
cray-nls-chart version bump to include change for storage workflow mount
* Resolves [CASMPET-5916](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5916)
=> CASMPET-5916 cray-nls-chart version bump to include change for storage workflow mount

manifests/sysmgmt.yaml
=> MTL-1921: csm-config version bump

manifests/sysmgmt.yaml
Release the production version of BOS v2.0.0
* Resolves everything that was ever wrong with BOS V1 (and I mean _everything_)
Yes, lots.
* Every machine would could beg, borrow, or steal.
Manual, bloody
With great change, comes great responsibility. 
You can't make an omelet without breaking a few workload managers.
=> Release BOS v2.0.0

nexus-repositories.yaml
added the sp4 repos to the nexus-repositories.yaml manifest
=> added the sp4 repos to the nexus-repositories.yaml manifest

assets.sh
PIT:
* CASMCLOUD-1212
NCNs:
* CASMINST-5311
* CASMINST-5312
* CASMINST-5316
* CASMCLOUD-1212
* CASMCMS-8203
=> CASMREL-1104: 1.3.0-beta.55 NCN and PIT assets

assets.sh
PIT:
* CASMCLOUD-1212
NCNs:
* CASMINST-5311
* CASMINST-5312
* CASMINST-5316
* CASMCLOUD-1212
* CASMCMS-8203
=> CASMREL-1101: 1.4.0-alpha.2 NCN and PIT assets

assets.sh
* CASMPET-5948
* CASMCMS-8210
* CASMCMS-8212
=> CASMREL-1115: NCN assets

assets.sh
=> CASMREL-1112: NCN assets

rpm/cray/csm/sle-15sp2/index.yaml
=> Revert "CASMHMS-5743 Fix token leaks in HMS test script"

manifests/sysmgmt.yaml
Fix build issues in `update-uas` and `uas-mgr` so that automatic security updates are applied.
`uas-mgr` was failing on some new lint errors
`update-uas` required a change to use a new Jenkins credential for publishing
* Resolves [CASMPET](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5859)
* `fanta`
CRUD testing
```
arbus:~ $ cray config use fanta
Your active configuration is: fanta
arbus:~ $ cray auth login
Username: alanm
Password:
Success!
arbus:~ $ cray uas list
[]
arbus:~ $ cray uas create --publickey ~/.ssh/id_rsa.pub
{
"uai_age": "0m",
"uai_connect_string": "ssh alanm@10.102.4.163",
"uai_host": "ncn-w003",
"uai_img": "artifactory.algol60.net/csm-docker/stable/cray-uai-sles15sp3:1.7.4",
"uai_ip": "10.102.4.163",
"uai_msg": "ContainerCreating",
"uai_name": …
```
=> Fix incremental updates to UAS components

CHANGELOG.md, manifests/platform.yaml
Rebuilds cray-nls to pickup base chart cray-service:8.2.3
Bugfix
* Resolves [CASMPET-5960](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5960)
vshasta
Verified the cray-nls chart is using the cray-service:8.2.3 base chart
Verified the cronjob to backup postgres is using the latest 0.2.3 image
Verified cronjob based backup can be restored to a freshly build v12 cluster
```
$ kubectl …
```
=> CASMPET-5960-main : BREAK/FIX: Cray-nls needs to pick up the cray base chart version 8.2.3 to fix postgres restore incompatibility issue

CHANGELOG.md, manifests/platform.yaml
Rebuilds cray-nls to pickup base chart cray-service:8.2.3
Bugfix
* Resolves [CASMPET-5960](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5960)
vshasta
Verified the cray-nls chart is using the cray-service:8.2.3 base chart
Verified the cronjob to backup postgres is using the latest 0.2.3 image
Verified cronjob based backup can be restored to a freshly build v12 cluster
```
$ kubectl …
```
=> CASMPET-5960-1.3 : BREAK/FIX: Cray-nls needs to pick up the cray base chart version 8.2.3 to fix postgres restore incompatibility issue

build/images/extract.sh
Improve chart related error handling in extract.sh script by adding "--halt-on-error" parameter to parallel options.
* Resolves CASMINST-5176
Tested in the Jenkins build pipeline
No known risks
=> Casminst 5176 1.4

manifests/core-services.yaml
Pull in new HSM helm chart to pull in a fix for the PostgreSQL backup cronjob.
The new `4.0.0` helm chart for HSM is compatible with both CSM 1.3 and 1.4. 
The major version of the helm chart was reved from `2` to `4` due to the a major version bump of the cray-service chart from `7` to `8`.  Also the `3` release of the HSM was already released but abandoned. 
* Resolves [CASMHMS-5754](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5754)
_List the …
=> CASMHMS-5754: Pull in new HSM helm chart

assets.sh
=> CASMREL-1112: NCN assets for CASMHMS-5743

assets.sh
=> CASMREL-1118: NCN images with the fix for  CASMTRIAGE-4052

rpm/cray/csm/sle-15sp2/index.yaml
=> Revert "Revert "CASMHMS-5743 Fix token leaks in HMS test script""

chrony/csm_ntp.py
Main backport PR for https://github.com/Cray-HPE/csm/pull/1333
=> CASMINST-5349: csm_ntp.py properly handle unsuccessful responses from BSS

chrony/csm_ntp.py
Currently the csm_ntp script will immediately fail in cases where its query to BSS fails. However, we have seen intermittent failures on API requests during CSM upgrades, where the request works on retry. This PR modifies the csm_ntp script so that it will wait 15 seconds and retry the BSS query if the query fails because of a 5XX status code (which could be an intermittent service problem) or an exception trying to make the request at all (which is what is seen in cases such as name resolution failures). For any other failures, the script behaves as it currently does. Additionally, it will only retry for up to 5 minutes before giving up.
I tested this on drax. I verified that the good path still works fine. For bad path, I had to artificially create some error conditions, but in all …
=> CASMINST-5353: Add limited retries to chrony/csm_ntp.py for some BSS request failures

assets.sh
LiveCD:
- None; rebuilt for good measure.
NCNs:
- [CASMINST-5332](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5332)
- [HPCCHT3-3457](https://jira-pro.its.hpecorp.net:8443/browse/HPCCHT3-3457)
=> CASMREL-1120

assets.sh
LiveCD:
- None; rebuilt for good measure.
NCNs:
- [CASMINST-5332](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5332)
- [CASMTRIAGE-4052](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4052)
- [HPCCHT3-3457](https://jira-pro.its.hpecorp.net:8443/browse/HPCCHT3-3457)
=> CASMREL-1129

manifests/platform.yaml
Since limit ranges are propagated by hnc, using the default dry-dock limit ranges causes a conflict when deploying the chart after hnc is all wired up.  Fix is to remove then and then they can be set/managed at various different places in the hnc tree and still have the propagation we want.
* Resolves [CASMTRIAGE-4204](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4204)
Reproduced current failure after hnc configured, new chart passes..
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Releasing cray-drydock v2.14.6
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-09-21T13:30:58Z INF Running helm install/upgrade with arguments: upgrade --install cray-drydock /workspace/.cache/charts/cray-drydock-2.14.6.tgz --namespace loftsman --create-namespace --set global.chart.name=cray-drydock --set …
```
=> Remove default limit ranges for hnc managed namespaces

manifests/core-services.yaml, manifests/platform.yaml
- Fix pod disruption budget and podAntiAffinity selector
- yes
CSMNET-1883
mug
- Was upgrade …
=> CASMNET-1883-stable-csm-1.2 - bugfix for disruption budget and pod affinity

manifests/core-services.yaml, manifests/platform.yaml
- Fix pod disruption budget and podAntiAffinity selector
- yes
CSMNET-1883
mug
- Was upgrade …
=> CASMNET-1883-csm-1.2 - bugfix for disruption budget and pod affinity

manifests/core-services.yaml, manifests/platform.yaml
- Fix pod disruption budget and podAntiAffinity selector
- yes
CSMNET-1883
mug
- Was upgrade …
=> Bugfix/casmnet-1883-csm-1.3 - Fix pod disruption budget and podAntiAffinity selector

manifests/core-services.yaml, manifests/platform.yaml
- Fix pod disruption budget and podAntiAffinity selector
- yes
CSMNET-1883
mug
- Was upgrade …
=> bug/CASMNET-1883 - bugfix for disruption budget and pod affinity

manifests/core-services.yaml, manifests/platform.yaml
- Fix race condition between dhcp-helper.py and MEDs
CASMNET-1880
CASMTRIAGE-4140
Loki
- Was …
=> bugfix/CASMNET-1880 - Fix race condition between dhcp-helper.py and MEDs

manifests/platform.yaml
=> Revert "CASMMON-190/196 Path change for plugins"

CHANGELOG.md, manifests/platform.yaml
Make anti-affinity required for cray-kyverno chart to spread its deployment to different nodes.
* Resolves [CASMPET-6008](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6008)
* `mug`
Indian security team did successful sanity tests on mug.
- Were the …
=> CASMPET-6008: add required anti-affinity for cray-kyverno

rpm/cray/csm/sle-15sp3/index.yaml
See: https://github.com/Cray-HPE/cray-site-init/pull/254
=> MTL-1961 New `csi`

manifests/platform.yaml
=> CASMINST-5391update mainifest

assets.sh
NCNs:
- [CASMTRIAGE-4255](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4255)
- [VSHA-468](https://jira-pro.its.hpecorp.net:8443/browse/VSHA-468)
=> CASMREL-1134

assets.sh
NCNs:
- [CASMTRIAGE-4255](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4255)
- [VSHA-468](https://jira-pro.its.hpecorp.net:8443/browse/VSHA-468)
=> CASMREL-1133

docker/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml
=> CASMNET-1876 1.3

docker/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml
=> CASMNET-1876 main

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml
PIT:
* MTL-1695
* CASMNET-1876
=> CASMREL-1135: PIT ISO and CSI manifest update

assets.sh
=> CASMREL-1134: PIT ISO

manifests/sysmgmt.yaml
See CASMTRIAGE-4246 for details.
* Resolves CASMTRIAGE-4246
* `Shandy`
Low. BOS is broken without this change.
=> CASMTRIAGE-4246: Pull in BOS 2.0.1

manifests/sysmgmt.yaml
See CASMTRIAGE-4246 for details.
* Resolves CASMTRIAGE-4246.
* `Shandy`
Low. BOS is broken without this change.
=> CASMTRIAGE-4246: Pull in new BOS V2

assets.sh
=> CASMREL-1137: NCNs with fix for CASMINST-5357

assets.sh
=> CASMREL-1139: NCN images with fix for CASMINST-5410

manifests/platform.yaml
=> CASMINST-5281 update manifest

assets.sh
=> CASMREL-1140: NCN assets

assets.sh
[CASMTRIAGE-4308](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4308).
=> CASMTRIAGE-4308 NCN Images

assets.sh
NCNs:
* CASMPET-6033
* CASMTRIAGE-4308
=> CASMREL-1138: NCN assets

manifests/platform.yaml
Changes OPA policies for BOS and fix the hmn collector service. See listed Jiras.
* Resolves CASMCMS-8269 and CASMPET-6043
Trust us, we're good.
=> CASMCMS-8269: Change OPA policy

manifests/platform.yaml
Change BOS' OPA policy and fix HMN collector
* Resolves CASMCMS-8269
=> CASMCMS-8269: Change BOS' OPA policy and fix HMN collector

CHANGELOG.md, manifests/platform.yaml
This is a bugfix that fixes an issue with keycloak localize where it can get into a state of never being able to end and gets stuck in a infinite loop.
* Resolves [CASMTRIAGE-4286](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4286)
- Was downgrade tested? …
=> CASMTRIAGE-4286: Update Keycloak-Localize

assets.sh
NCNS:
* CASMINST-5313
* HPCCHT3-3493
* CASMNET-1876
* CASMTRIAGE-4328
=> CASMREL-1145: NCN assets

assets.sh
PIT:
* CASMCMS-8245
NCNs:
* CASMCMS-8245
* CASMTRIAGE-4328
* HPCCHT3-3493
* MTL-1971
=> CASMREL-1142: NCN and PIT assets

rpm/cray/csm/sle-15sp3/index.yaml
See: https://github.com/Cray-HPE/csm-testing/pull/409
=> MTL-1954 Bootloader checks

assets.sh
=> CASMREL-1147: NCN assets

assets.sh
=> CASMREL-1146: NCN assets

manifests/sysmgmt.yaml
=> Casmcms 8275

manifests/sysmgmt.yaml
=> CASMCMS-8275: Pull in BOS V2 fix

manifests/platform.yaml
=> CASM-3511 update manifest

assets.sh
PIT:
* MTL-1978
NCNs:
* MTL-1978
=> MTL-1978: pit ISO and NCN images with CVE fixes

manifests/sysmgmt.yaml
Add read-only API for tenant status.
* Resolves [CASMINST-4836](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4836)
```
ncn-m001-cdd6e862:/home/bklein # curl -s http://10.30.210.163:2875/apis/tapms/v1/tenant/e8d5319e-dee6-4fa7-8ac4-c264fb8f1232 | jq .
{
"kind": "Tenant",
"apiVersion": "tapms.hpe.com/v1alpha1",
"metadata": {
"name": "vcluster-green",
"namespace": "tenants",
"uid": "e8d5319e-dee6-4fa7-8ac4-c264fb8f1232",
"resourceVersion": "9807277",
"generation": 3,
"creationTimestamp": "2022-10-06T17:20:53Z",
"annotations": {
"kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"tapms.hpe.com/v1alpha1\",\"kind\":\"Tenant\",\"metadata\":{\"annotations\":{},\"name\":\"vcluster-green\",\"namespace\":\"tenants\"},\"spec\":{\"childnamespaces\":[\"user\",\"slurm\"],\"ten …
```
=> Add read-only API for tenant status

CHANGELOG.md, manifests/platform.yaml
This updates the version of oauth2-proxies to include the update of oauth2-proxy which upgrades the image version to the latest version
* Resolves [CASMPET-6071](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6071)
- Were …
=> CASMPET-6071: Update oauth2-proxies

manifests/platform.yaml
=> CASM-3517 update manifest

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml
PIT:
* MTL-1975
* MTL-1986
NCNs:
* MTL-1974
* MTL-1975
=> MTL-1986 MTL-1975 MTL-1974: PIT and NCN updates

CHANGELOG.md, manifests/platform.yaml
release cray-nls v1.4.8
This adds a configmap for iuf-install-workflow-files
Tested on wasp
- Chart deployed successfully during an install.
- Were continuous integration tests run? …
=> CASMINST-5530 release cray-nls

assets.sh
PIT:
* MTL-1793
NCNs:
* CASMPET-5723
=> CASMREL-1158: NCN and PIT assets

assets.sh
=> CASMREL-1160: NCN assets

manifests/platform.yaml
Bump the chart version for CASM-3398: Need Alerts for CPU and Memory usage for NCNs 
* Resolves: CASM-3398: Need Alerts for CPU and Memory usage for NCNs 
Mug
=> CASM-3398: Bump chart version

manifests/platform.yaml
Monitor Kyverno policy metrics with Prometheus
As part of shasta monitoring, it may benefit you to have monitoring capabilities over both the state and execution of cluster-applied Kyverno policies. This includes monitoring over any applied changes to policies, any activity associated with incoming requests, and any results produced as an outcome. If enabled, monitoring will allow you to visualize and alert on applied policies, and is critical to overall cluster observability and compliance.
Kyverno exporter to get metrics from service monitor. Installation of the dashboard for the kyverno metrics through the .json file.
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-236
* Mug successfully
=> CASSMON-236 Grafana for Kyverno

assets.sh
PIT:
* CASMINST-5255 (csi)
* VSHA-505 (pit-init)
=> CASMREL-1161: new PIT ISO

assets.sh
NCNs:
- [CASMCMS-7938](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7938)
- [CASMTRIAGE-4448](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4448)
=> CASMREL-1166

manifests/sysmgmt.yaml
Pulls in a fix for the cfs-operator that addresses an issue with the new image map feature.
* Resolves CASMCMS-8313
- Successfully ran a session that was previously failing due to hitting this bug
None
=> CASMCMS-8313: Update cfs-operator for image customization fix

assets.sh
=> CASMREL-1169: NCN images with CASMPET-5759 (fresh install Cilium)

CHANGELOG.md, rpm/cray/csm/sle-15sp2/index.yaml
Release platform-utils v1.4.3 to edit output from ncnHealthChecks.sh …
=> CASMTRIAGE-4539 Release platform-utils v1.4.3 to edit output from ncnHealthChecks.sh

assets.sh
=> CASMREL-1170

docker/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml
Tested on several systems and local dev environments; CI also passes.
- surtur
- redbull
=> CASMNET-1954 `canu-1.6.27`

rpm/cray/csm/sle-15sp4/index.yaml
Adds a new "cfs-debug" tool to help users find the cause of failed sessions or other unexpected failures.
* Resolves CASMCMS-5516
* Mug
Ran through all of options for the new tool on a system with some known  and unknown problems.
None
=> CASMCMS-5516: Add CFS debugging tool

docker/index.yaml
Add iuf-containers to the manifest.
=> CASMINST-5585 CASMINST-5584: Add iuf container

build/images/Makefile, build/images/extract.sh
Apply CSM chart validation improvements to release/1.3 
* Resolves https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5624
=> update chart validation checking

CHANGELOG.md, manifests/platform.yaml
Release cray-nls 1.4.25 to update image used in iufBase.template.yaml.
_How …
=> CASMINST-5621 release cray-nls 1.4.25

manifests/platform.yaml
Modified local sub-chart was ignored due to helm dependency -- change to use the local copy which includes clusterrole changes to support auto-heal.
* Resolves [CASMPET-6121](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6121)
```
time="2022-11-22T20:53:53Z" level=info msg="Checking for existing restore that needs to be cleaned up." cluster-name=cray-bos-etcd cluster-namespace=services pkg=cluster
time="2022-11-22T20:53:53Z" level=info msg="execing into pod etcd-backup-restore-7848575c4f-4cmlc to restore" cluster-name=cray-bos-etcd cluster-namespace=services pkg=cluster
time="2022-11-22T20:53:54Z" level=info msg="attempting restore from backup : etcd.backup_v7388_2022-11-22-18:15:10" cluster-name=cray-bos-etcd cluster-namespace=services pkg=cluster
time="2022-11-22T20:53:54Z" …
```
=> Use local version of etcd operator helm chart

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml
LiveCD:
- [CASMINST-5622](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5622)
- [MTL-1657](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1657)
NCNs:
- [CASMCMS-5516](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-5516)
=> CASMREL-1203

docker/index.yaml, manifests/platform.yaml
iuf version bump
* Resolves [CASMINST-5627](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5627)
_Are …
=> CASMINST-5627: iuf version bump

rpm/cray/csm/sle-15sp2-compute/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml
Implements all current PCS APIs as pretty much a pass through. Hostlist expansion done by the CLI before calling the PCS API.
* Resolves [CASMHMS-4619](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-4619)
* Simulated Shasta environment
Manually executed all CLI options based on the unit tests that were created. Powered simulated nodes on and off, power capped simulated nodes. Verified expected interaction with PCS was working as expected.
- Were continuous integration tests run? If not, why? Yes
- Was downgrade tested? If not, why? No - nothing to downgrade to
- Were new tests (or test issues/Jiras) created for …
=> Add new CrayCLI that supports PCS

assets.sh
PIT:
* CASMHMS-4619
NCNs:
* CASMHMS-4619
=> CASMHMS-4619: updated `craycli`

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml
=> MTL-1949: bump csi version

assets.sh
NCNs with changes for CASMTRIAGE-4656
=> CASMTRIAGE-4656: NCN images

manifests/platform.yaml
Add opa policies to address keycloak vulnerabilities for request_uri
See https://github.com/Cray-HPE/cray-opa/pull/74 and https://github.com/Cray-HPE/cray-opa/pull/75 for PR details.
* `<mug>`
Helm install/upgrade/rollback logs are attached  below.
For more unit test logs looks for PR's https://github.com/Cray-HPE/cray-opa/pull/74 and https://github.com/Cray-HPE/cray-opa/pull/75
ncn-m001:/tmp/vasu/helm_test # mkdir space_test
ncn-m001:/tmp/vasu/helm_test # cd space_test/
ncn-m001:/tmp/vasu/helm_test/space_test # wget https://artifactory.algol60.net/artifactory/csm-helm-charts/stable/cray-opa/cray-opa-1.25.6.tgz
--2022-12-07 22:49:11--  https://artifactory.algol60.net/artifactory/csm-helm-charts/stable/cray-opa/cray-opa-1.25.6.tgz
Resolving artifactory.algol60.net …
=> CASMPET-6128: Add opa policies to address keycloak vulnerabilities for request_uri

manifests/core-services.yaml, manifests/platform.yaml
kea
*CASMNET-1937 - Security remediation for RFC 8357
unbound
*CAST-31331/CASMNET-1955 - Allow CoreDNS max_concurrent tuning via cray-dns-unbound chart
*CASMNET-1960 - Eliminate use of deprecated K8s APIs
*CASMNET-1964 - update unbound-telemtry to resolve dependency security concerns
*CASMNET-1969 - migrate cray-dns-unbound to use rust base image hosted in artifactory
kea
CASMNET-1937 - Security remediation for RFC 8357
unbound
CAST-31331/CASMNET-1955 - …
=> feature/casmnet-1937 - Security remediation for RFC 8357

assets.sh, rpm/cray/csm/sle-15sp4/index.yaml
PIT:
* CASMTRIAGE-4671, CASMTRIAGE-4672
=> CASMTRIAGE-4671, CASMTRIAGE-4672: new pit-init

assets.sh, rpm/cray/csm/sle-15sp4/index.yaml
CASMMON-208: Automate prometheus, grok exporter and grafana gets instantiated automatically on Combined Install Media LiveDVD
* Resolves - https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-208
Gamora-csm-pit
gamora-ncn-m001-pit: # podman ps
CONTAINER ID  IMAGE                                                                                   COMMAND               CREATED        STATUS …
=> CASMMON-208 Automate prometheus, grok exporter and grafana gets instantiated automatically on PIT node.

assets.sh
=> CASMPET-6200: NCN assets

manifests/core-services.yaml
Removed encrypted dumpstate and loadstate capabilities
Updated to run the new functional tests
* Resolves [CASMHMS-5771](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5771)
* Resolves [CASMHMS-5856](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5856)
* mug
* local docker compose environment
Low.
=> Updated SLS to version 3.0.2

assets.sh, install.sh, rpm/cray/csm/sle-15sp2-compute/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
Includes:
- CASMTRIAGE-4693
- CASMHMS-5771
- DVS-2881
=> CASMREL-1322

assets.sh, install.sh
Includes updated LiveCD and NCN images.
LiveCD:
- [CASMTRIAGE-4697](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4697)
- [MTL-2055](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2055)
- [MTL-2056](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2056)
- [MTL-2058](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2058)
NCNs:
- [CASMPET-6152](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6152)
- [CASMTRIAGE-4738](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4738)
- [CASMTRIAGE-4697](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4697)
- [MTL-2055](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2055)
- [MTL-2056](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2056)
- [MTL-2058](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2058)
This is an …
=> CASMREL-1322 Part 2

assets.sh, rpm/cray/csm/sle-15sp4/index.yaml
Rollback `pit-init`, and include a new LiveCD using the rolled back `pit-init`.
=> CASMINST-5757

assets.sh
NCNs:
- [CASMPET-6206](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6206)
- [MTL-1828](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1828)
=> CASMREL-1325

manifests/sysmgmt.yaml
CASMHMS-5857
Updated to run the new functional tests
* Resolves [CASMHMS-5857](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5857)
* mug
Low
=> Updated BSS to version 2.1.6

manifests/sysmgmt.yaml
=> Casmcms 8373

manifests/platform.yaml
Prometheus updated to the current stable version v2.41.0, alert manager to v0.25.0, and node-exporter to v1.5.0.
Backward compatible.
* Resolves - [CASMMON-244](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-244)
* `mug` successfully
Snips of the testing -
How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?
- Upgrade was tested.
prometheus_build_info{branch="HEAD", endpoint="web", goarch="amd64", goos="linux", goversion="go1.19.4", instance="10.44.0.2:9090", job="cray-sysmgmt-health-promet-prometheus", namespace="sysmgmt-health", pod="prometheus-cray-sysmgmt-health-promet-prometheus-0", revision="c0d8a56c69014279464c0e15d8bfb0e153af0dab", service="cray-sysmgmt-health-promet-prometheus" …
=> CASMMON-244: Update Prometheus to current stable release version v2.41.0

install.sh, manifests/platform.yaml
=> Nothing unique in 1.6 yet. Backporting to 1.4 for this build.

assets.sh, install.sh, rpm/cray/csm/sle-15sp3/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
LivCD:
- [MTL-2059](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2059)
- [MTL-2063](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2063)
NCNs:
- [CASMTRIAGE-4693](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4693)
- [MTL-2059](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2059)
- [MTL-2063](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2063)
Misc:
- Updated `csm-testing` and `goss-servers` for SP4 (matching meta)
=> CASMREL-1332

assets.sh, install.sh, rpm/cray/csm/sle-15sp3/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
LivCD:
- [MTL-2059](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2059)
- [MTL-2063](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2063)
NCNs:
- [CASMTRIAGE-4693](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4693)
- [MTL-2059](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2059)
- [MTL-2063](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2063)
Misc:
- Updated `csm-testing` and `goss-servers` for SP4 (matching meta)
=> CASMREL-1333

rpm/cray/csm/sle-15sp4/index.yaml
Updates the cfs-debugger to handle the new CFS session format with all Ansible logs in a single container.
* Resolves CASMCMS-8336
* Wasp
Tested log parsing against both successful and failed sessions
None
=> CASMCMS-8336: Update cfs-debugger for new cfs session format (1.4)

rpm/cray/csm/sle-15sp4/index.yaml
Updates the cfs-debugger to handle the new CFS session format with all Ansible logs in a single container.
* Resolves CASMCMS-8336
* Wasp
Tested log parsing against both successful and failed sessions
None
=> CASMCMS-8336: Update cfs-debugger to handle new cfs session format

CHANGELOG.md, rpm/cray/csm/sle-15sp4/index.yaml
Main backport of https://github.com/Cray-HPE/csm/pull/1633. See that PR for details.
See [1.4 manifest PR](https://github.com/Cray-HPE/csm/pull/1633) for details.
See [1.4 manifest PR](https://github.com/Cray-HPE/csm/pull/1633) for details.
See [1.4 manifest PR](https://github.com/Cray-HPE/csm/pull/1633) for details.
=> CASMINST-5793: csm-testing: Log test duration in decimal without scientific notation

manifests/sysmgmt.yaml
Turn beta releases into official releases.
We are basically ensuring everything that needs to be in the Alice release aka CSM-1.4 is in it. 
* Wasn't tested
We thought through what should be included.
Low-ish
=> Ensuring Alice has all needed content.

docker/index.yaml
Adding cf-gitea-update working branch VCS for IUF work into 1.4
* Resolves [CASMINST-5805](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5805)
* `Frigg, Mug`
=> CASMINST-5805: Add cf-gitea-update to release 1.4

rpm/cray/csm/sle-15sp4/index.yaml
Updates all CFS rpms to the latest for consitency.  This pulls in build changes and a bug fix for cfs-debugger.
* Resolves CASMCMS-8379
Testing was done as part of the code change PRs.  See those for more information.
None
=> CASMCMS-8379: Fix CFS rpm versions

docker/index.yaml, lib/setup-nexus.sh
=> CRAYSAT-1651: Add SAT 3.20.0 to CSM 1.6

docker/index.yaml
The following images need to be present in Nexus for IUF to be functional.
(cherry picked from commit 95bd5bd788cdce22df82cdda3ed9f60ba9457406)
See #1657
=> CASM-3758, CASM-3710: Add images needed by IUF to CSM

manifests/core-services.yaml, manifests/platform.yaml
- update kea and unbound to support multiple unbound loadbalancers.
CSAMNET-2024
CAST-31858
NERC Muller
- manual testing with proper helm labels to allow upgrades and downgrades
- Were the install/upgrade-based validation …
=> CASMNET-2024-csm-1.4 - update kea and unbound to support multiple unbound loadbalancers.

manifests/core-services.yaml, manifests/platform.yaml
- update kea and unbound to support multiple unbound loadbalancers.
CSAMNET-2024
CAST-31858
NERC Muller
- manual testing with proper helm labels to allow upgrades and downgrades
- Were the install/upgrade-based validation …
=> CASMNET-2024 - update kea and unbound to support multiple unbound loadbalancers.

manifests/sysmgmt.yaml, rpm/cray/csm/sle-15sp4-compute/index.yaml
Pulling in the right versions.
- Were the …
=> Pulling in the right versions

CHANGELOG.md, docker/index.yaml
Bumping version of cf-gitea-update due to small bug in matching logic.
* Resolves [5814](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5814)
* `Frigg`
IUF workflows via Frigg
=> CASMINST-5814: Updating version of cf-gitea-update 1.0.2

docker/index.yaml, manifests/platform.yaml
=> CASMINST-5751: manifest bumps

docker/index.yaml, manifests/platform.yaml
=> CASMINST-5751: version bumps

assets.sh, rpm/cray/csm/sle-15sp4/index.yaml
**If this is a draft then smoke-testing is in-progress and this should not merge.**
node-images:
- [CASMCMS-8379](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8379)
- [CASMPET-5081](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5081)
- [MTL-1476](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1476)
- [MTL-2035](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2035)
- [MTL-2064](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2064)
- [MTL-2067](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2067)
- [MTL-2068](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2068)
=> CASMREL-1340

assets.sh, rpm/cray/csm/sle-15sp4/index.yaml
**If this is a draft then smoke-testing is in-progress and this should not merge.**
node-images:
- [CASMCMS-8379](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8379)
- [CASMPET-5081](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5081)
- [MTL-1476](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1476)
- [MTL-2035](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2035)
- [MTL-2064](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2064)
- [MTL-2067](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2067)
- [MTL-2068](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2068)
=> CASMREL-1336

Jenkinsfile.github, build/images/inspect.sh, build/images/sync.sh, hack/verify-helm-index.sh, hack/verify-rpm-index.sh
Backport authentication changes from main to stable/1.2
Related to https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5741
* Resolves [CASMINST-5741](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5741)
No known risks
=> backport PR 1654 to stable/1.2

docker/index.yaml, manifests/platform.yaml
=> CASMINST-5827: bump version

manifests/platform.yaml
Add PCS OPA rules to CSM 1.4
* Resolves [CASMHMS-5895](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5895)
Ran unit tests
Low
=> CASMHMS-5895: Add PCS OPA Rules

manifests/platform.yaml
Add PCS OPA rules to CSM master
* Resolves [CASMHMS-5895](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5895)
Ran unit tests
Low
=> CASMHMS-5895: Add PCS OPA rules to CSM master

CHANGELOG.md, manifests/sysmgmt.yaml, rpm/cray/csm/sle-15sp2-compute/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml
Minor fixes to Cray CFS CLI formatting and language.
See source PRs for details:
* [craycli PR](https://github.com/Cray-HPE/craycli/pull/65)
* [CFS PR](https://github.com/Cray-HPE/config-framework-service/pull/58)
* Fixes: [CASMCMS-8380](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8380)
* [main backport manifest PR](https://github.com/Cray-HPE/csm/pull/1681)
* [csm-rpms 1.4 manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/712)
* [csm-rpms main backport manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/713)
See source PRs for details
Low risk -- no functional changes.
=> CASMCMS-8380: Minor language and formatting corrections to CFS Cray CLI

manifests/sysmgmt.yaml
CASMCMS-8353: Pulling in artifactory authentication  content and alphabetizing
Yes. …
=> CASMCMS-8353-release-1.4

manifests/platform.yaml
In order to prevent webhook failures in the event of a container restart, increase controller replica size to 2.
* Resolves [CASMPET-6277](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6277)
```
hnc-controller-manager-6d7d6dff65-mg9d8   2/2     Running     0          49m
hnc-controller-manager-6d7d6dff65-xhnvk   2/2     Running     0          105m
wait-for-hnc-manager-pods-bmf58           0/1     Completed   0          11m
```
```
ncn-m001-e2e75ea1:/home/bklein # kubectl get tenants.tapms.hpe.com -n tenants vcluster-coke -o yaml
apiVersion: tapms.hpe.com/v1alpha1
kind: Tenant
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"tapms.hpe.com/v1alpha1","kind":"Tenant","metadata":{"annotations":{},"name":"vcluster-coke","namespace":"tenants"},"spec …
```
=> Increase hnc controller replicas for webhook redundancy

rpm/cray/csm/sle-15sp4/index.yaml
Updates the cfs-debugger to fix an issue where a dependency was missing.
* Resolves CASMCMS-8395
* Locally/venv
Installed package in a clean venv and verified dependencies.
None
=> CASMCMS-8395: Update cfs-debug to fix install dependency (1.4)

rpm/cray/csm/sle-15sp4/index.yaml
Updates the cfs-debugger to fix an issue where a dependency was missing.
* Resolves CASMCMS-8395
* Locally/venv
Installed package in a clean venv and verified dependencies.
None
=> CASMCMS-8395: Update cfs-debug to fix install dependency

rpm/cray/csm/sle-15sp4/index.yaml
Pull in newer hpe-csm-scripts RPM to pull in an updated  verify_hsm_discovery.py script with EX2500 cabinet support
* Resolves [CASMINST-5858](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5858)
- Mug
- Surtur
- Shandy
- Baldar
- Bradi
- Hela
- Loki
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in …
=> CASMINST-5858: Pull in newer hpe-csm-scripts RPM to pull in an updated  verify_hsm_discovery.py script with EX2500 cabinet support

rpm/cray/csm/sle-15sp4/index.yaml
Pull in newer hpe-csm-scripts RPM to pull in an updated  verify_hsm_discovery.py script with EX2500 cabinet support
* Resolves [CASMINST-5858](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5858)
- Mug
- Surtur
- Shandy
- Baldar
- Bradi
- Hela
- Loki
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in …
=> (CSM 1.4) CASMINST-5858: Pull in newer hpe-csm-scripts RPM to pull in an updated verify_hsm_discovery.py script with EX2500 cabinet support #

assets.sh
- [CASMCMS-8395](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8395)
- [CASMINST-5858](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5858)
- [CASMINST-5861](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5861)
=> CASMREL-1354

assets.sh
- [CASMCMS-8395](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8395)
- [CASMINST-5858](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5858)
- [CASMINST-5861](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5861)
=> CASMREL-1355

assets.sh, rpm/cray/csm/sle-15sp4/index.yaml
- [CASMMON-250](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-250)
- [CASMTRIAGE-4870](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4870)
=> CASMREL-1357

assets.sh, rpm/cray/csm/sle-15sp4/index.yaml
- [CASMMON-250](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-250)
- [CASMTRIAGE-4870](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4870)
=> CASMREL-1356

manifests/sysmgmt.yaml
cray-uas-mgr:
```
- Language linting of API spec and other documentation (no content changes)
- Use authentication for csm-python-modules
```
update-uas:
```
- Update version for new scanning build
```
* Resolves [CASMUSER-3162](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-3162)
* Resolves [CASMUSER-3163](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-3163)
* Resolves [CASMUSER-3164](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-3164)
Local unit testing (no code changes)
Unit tests and lint pass
Low risk
=> Bump uas artifacts for security fixes

manifests/sysmgmt.yaml
cray-uas-mgr:
```
- Language linting of API spec and other documentation (no content changes)
- Use authentication for csm-python-modules
```
update-uas:
```
- Update version for new scanning build
```
* Resolves [CASMUSER-3162](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-3162)
* Resolves [CASMUSER-3163](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-3163)
* Resolves [CASMUSER-3164](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-3164)
Local unit testing (no code changes)
Unit tests and lint pass
Low risk
=> Bump uas artifacts for security fixes [CSM 1.4]

manifests/sysmgmt.yaml
cray-uas-mgr:
```
- Language linting of API spec and other documentation (no content changes)
- Use authentication for csm-python-modules
```
update-uas:
```
- Update version for new scanning build
```
* Resolves [CASMUSER-3162](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-3162)
* Resolves [CASMUSER-3163](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-3163)
* Resolves [CASMUSER-3164](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-3164)
Local unit testing (no code changes)
Unit tests and lint pass
Low risk
=> Bump uas artifacts for security fixes [CSM 1.3]

docker/index.yaml, manifests/platform.yaml
The new iuf-container has been updated to provide output used to update the product catalog.
* Resolves [CASM-3727]
* `Frigg`
Look at the other PR's associated with this.
- Were continuous integration tests run? If not, why? No
- Was upgrade tested? If not, why? No
- Was downgrade tested? If not, why? No
- Were new tests (or test issues/Jiras) created for this change? No.
Low.
=> CASM-3727: Pull in new iuf-container

assets.sh
=> CASMPET-5862 CASMCMS-8301: NCN & PIT assets

CHANGELOG.md, rpm/cray/csm/sle-15sp4/index.yaml
* Update iuf-cli for the main branch
_How were the changes tested and …
=> SCICD-578 Update iuf-cli version in main

assets.sh, rpm/cray/csm/sle-15sp4/index.yaml
node-images:
- [CASMTRIAGE-4850](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4850)
- [CASMTRIAGE-4891](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4891)
=> CASMREL-1361

assets.sh, rpm/cray/csm/sle-15sp4/index.yaml
node-images:
- [CASMTRIAGE-4850](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4850)
- [CASMTRIAGE-4891](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4891)
=> CASMREL-1359

release.sh
Files (PIT/NCN/Storage ISOs and squashfs files), downloaded during csm builds, may get corrupted in transit. This change is to:
* Compare sha256 of downloaded file with checksum declared by Artifactory
* Store sha256 of the file in `${filename}.sha256.txt` file, to allow further tracking of file downloads.
* Resolves [CASMINST-5891](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5891)
Ran `release.sh` locally and checked that checksum is verified and `sha256.txt` files generated. Also, simulated incorrect checksum and tested script behavior in this case.
=> CASMINST-5891 Compare sha256 of downloaded file with Artifactory data

CHANGELOG.md, docker/index.yaml, manifests/platform.yaml
Add changes to the versions of the cray-nls, cf-gitea-import, cf-gitea-update, and cray-ims-load-artifacts images needed for the fixes for CASMINST-5843, CASMINST-5902, and CASMINST-5876.
Resolves [CASMINST-5843](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5843)
Resolves [CASMINST-5902](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5902)
Resolves [CASMINST-5876](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5876)
Change will also be needed in main
* `frigg`
Tested IUF argo runs on Frigg using deliver-product stage with Ryan H and Jack S. …
=> CASMINST-5843: backport from release/1.4 to main

manifests/sysmgmt.yaml
This older version does not support merging content.
=> CASMINST-5910: use the newest version of cray product catalog

manifests/platform.yaml
Monitor Opensearch cluster with Prometheus and grafana
https://github.com/Cray-HPE/cray-sysmgmt-health/pull/100
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-262
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-263
=> CASMMON-263: create metrics and grafana dashboard for OpenSearch

CHANGELOG.md, manifests/platform.yaml
There is an NPE when processing outputs on failed workflows.
This breaks resume/restart functionality.
There are two Argo Workflow templates in cray-nls that were not upversioned correctly back in November. Thus, they are not updating on systems with the latest cray-nls being installed.
This breaks IUF.
* Resolves:
** [CASM-3874](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3874)
** [CASM-3873](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3873)
* Documentation …
=> CASM-3874 update cray-nls and cray-iuf versions

docker/index.yaml
=> CASMINST-5944: (IUF): Use new version of cray-nexus-setup in IUF

manifests/core-services.yaml
Pull in Helm chart 3.0.1 into CSM 1.3.2 which has a change to the /v1/hardware API to prevent SLS from deadlocking when many concurrent requests are made to it. The dead locking was occurring due to unoptimized code used for the `/v1/hardware` API endpoint. 
* Resolves [CASMHMS-5920](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5920)
* Mug
_How were the changes tested …
=> CASMHMS-5920: Pull in SLS Helm chart 3.0.1 into CSM 1.3.2

docker/index.yaml, manifests/platform.yaml
(cherry picked from commit ab23631d591188bbe287be579d83a1cdc4d4add1)
CASMINST-5939: Bring in latest version of iuf container
* Resolves CASMINST-5939: Bring in latest version of iuf container
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your …
=> CASMINST-5939: Bring in latest version of iuf container

assets.sh
New NCN images with fixed `ll` BASH alias.
=> MTL-2077 1.4

docker/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
Signed-off-by: lukebates123 <66981180+lukebates123@users.noreply.github.com>
- Fixes: CASMNET-2018
=> CASMNET-2018 main

docker/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
Signed-off-by: lukebates123 <66981180+lukebates123@users.noreply.github.com>
- Fixes: CASMNET-2018
=> CASMNET-2018 1.4

docker/index.yaml, lib/setup-nexus.sh, manifests/platform.yaml
Update SAT container image version to fix auth bug in CRAYSAT-1678.
* Resolves [CRAYSAT-1678](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1678)
* `gamora`
Run sat auth against empty config directory and test that the token files are properly created.
=> CRAYSAT-1678: Update SAT docker image version

docker/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
Signed-off-by: lukebates123 <66981180+lukebates123@users.noreply.github.com>
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5966
Bump canu version
=> Casminst 5966 1.4

docker/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
Signed-off-by: lukebates123 <66981180+lukebates123@users.noreply.github.com>
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5966
Bump canu version
=> Casminst 5966 main

manifests/sysmgmt.yaml
Reviewed fix with Ryan Sjostrand, and applied correct versions.
=> restore HMS section after reversion due to PR 1794

assets.sh
=> CASMREL-1387: NCN assets

hack/snyk-scan.sh
Add debugging on snyk scans when they fail.
=> cat output of snyk scan on failure

assets.sh, rpm/cray/csm/sle-15sp4/index.yaml
node-images:
- [CASMINST-5966](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5966)
- [MTL-2074](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2074)
- [MTL-2080](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2080)
- [MTL-2085](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2085)
- [VSHA-536](https://jira-pro.its.hpecorp.net:8443/browse/VSHA-536)
=> CASMREL-1367

assets.sh
node-images:
- [CASMINST-5999](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5999)
- [CASMTRIAGE-4917](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4917)
=> CASMREL-1390

assets.sh
node-images:
- [CASMINST-5999](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5999)
- [CASMTRIAGE-4917](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4917)
- [MTL-2087](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2087)
- [MTL-2089](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2089)
- [MTL-2090](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2090)
- [MTL-2091](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2091)
=> CASMREL-1388

CHANGELOG.md, manifests/platform.yaml
Backport of https://github.com/Cray-HPE/csm/pull/1855
=> [Backport release/1.4] CASMPET-6323 and CASMINST-5988

manifests/platform.yaml
Changed cray-kyverno chart version in accordance with PR Cray-HPE/cray-kyverno#7
=> CASMSEC-385: kyverno resources need to be adjusted

assets.sh
node-images:
- [CASMINST-6007](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6007)
- [MTL-2100](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2100)
- [MTL-2101](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2101)
=> CASMREL-1409

assets.sh
node-images:
- [MTL-2100](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2100)
- [MTL-2101](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2101)
=> CASMREL-1407

assets.sh
node-images:
- [CASMTRIAGE-4991](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4991)
- [MTL-2100 (follow-up)](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2100)
=> CASMREL-1410

upgrade.sh
Remove line to remove TRS operator as it will have been done in the CSM 1.4 upgrade/fresh install.
* Resolves [CASMHMS-5854](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5854)
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your …
=> CASMHMS-5854: Remove line to remove TRS operator as it will have been done in the CSM 1.4 upgrade/fresh install.

CHANGELOG.md, manifests/core-services.yaml, manifests/platform.yaml
- bugfix for builds with Makefile reference to helm-unittest
CASMNET-2067
jenkins
- Was …
=> bugfix/CASMNET-2067 - version bumps for cray-dhcp-kea, cray-dns-powerdns and cray-pdns-manager for CASMNET-2067

CHANGELOG.md, manifests/core-services.yaml, manifests/platform.yaml
- bugfix for builds with Makefile reference to helm-unittest
CASMNET-2067
jenkins
- Was …
=> bugfix/CASMNET-2067-csm-1.4 - version bumps for cray-dhcp-kea, cray-dns-powerdns and cray-pdns-manager for CASMNET-2067

CHANGELOG.md, manifests/core-services.yaml, manifests/platform.yaml
- bugfix for builds with Makefile reference to helm-unittest
CASMNET-2067
jenkins
- Was …
=> bugfix/CASMNET-2067-csm-1.3 - version bumps for cray-dhcp-kea, cray-dns-powerdns and cray-pdns-manager for CASMNET-2067

assets.sh
node-images:
- [MTL-2105](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2105)
=> CASMREL-1415

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
node-images:
- [CASMINST-6031](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6031)
- [MTL-2103](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2103)
- [MTL-2105](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2105)
=> CASMREL-1412

manifests/platform.yaml, rpm/cray/csm/sle-15sp2/index.yaml
Refactoring related to bitnami-etcd chart.
* Resolves [CASMPET-6184](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6184)
```
ncn-m001-e2e75ea1:/home/bklein # /opt/cray/platform-utils/etcd/etcd_restore_rebuild.sh -s cray-bos
The following etcd clusters will be restored/rebuilt:
cray-bos
You will be accepting responsibility for any missing data if there is a
restore/rebuild over a running etcd k/v. HPE assumes no responsibility.
Proceed restoring/rebuilding? (yes/no)
yes
Proceeding: restoring/rebuilding etcd clusters.
----- Restoring from cray-bos/db-2023-03-03_17-00 -----
Scaling etcd statefulset down to zero...
statefulset.apps/cray-bos-bitnami-etcd scaled
Waiting for statefulset spec update to be observed...
statefulset rolling update complete 0 pods at revision …
```
=> Pull in scripting changes for bitnami-etcd chart

CHANGELOG.md, manifests/platform.yaml
=> CASMINST-5982 abort worker rebuild on the backend

CHANGELOG.md, manifests/platform.yaml
=> CASMINST-5982 backport to release/1.4

CHANGELOG.md, rpm/cray/csm/sle-15sp4/index.yaml
Adjust the goss test skips for vshasta
* Resolves [VSHA-542](https://jira-pro.its.hpecorp.net:8443/browse/VSHA-542)
* Virtual Shasta `beau`
I ran both the preflight and healthcheck tests on beau and verified that there are no failures and only the expected tests are skipped.
=> VSHA-542:  Release csm-testing v1.16.9

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
node-images:
- [MTL-2081](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2081)
- [MTL-2097](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2097)
=> CASMREL-1422

manifests/platform.yaml
=> CASMTRIAGE-5041 update manifest

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
node-images:
- [MTL-2081](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2081)
- [MTL-2097](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2097)
=> CASMREL-1421

rpm/cray/csm/sle-15sp4/index.yaml
=> CASMINST-6076 update manifest

rpm/cray/csm/sle-15sp4/index.yaml
=> Casminst 6078 1.4

rpm/cray/csm/sle-15sp4/index.yaml
=> CASMINST-6078 update manifest

manifests/platform.yaml
Doc and utility updates for etcd bitnami chart conversion
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6185
* ashton
```
cray-bos-5df5b77796-p4bh6                                         2/2     Running     0          66m
cray-bos-5df5b77796-xdbkl                                         2/2     Running     0          68m
cray-bos-bitnami-etcd-0                                           2/2     Running     0          10m
cray-bos-bitnami-etcd-1                                           2/2     Running     0          12m
cray-bos-bitnami-etcd-2                                           2/2     Running     0          13m
cray-bos-bitnami-etcd-snapshotter-27978960-qns4t                  0/2     Completed   0          61m
```
Was an Upgrade tested? …
=> Doc updates for bitnami etcd chart (CASMPET-6185)

CHANGELOG.md, rpm/cray/csm/sle-15sp4/index.yaml
bug/casmtriage-5066 - update BGP test to be more dynamic for different versions of vault
yes
CASMTRIAGE-5066
baldar
- Were continuous integration …
=> bug/CASMTRIAGE-5066 - update bgp test have a more dynamic vault check

CHANGELOG.md, rpm/cray/csm/sle-15sp4/index.yaml
bug/casmtriage-5066 - update BGP test to be more dynamic for different versions of vault
yes
CASMTRIAGE-5066
baldar
- Were continuous integration …
=> bug/CASMTRIAGE-5066-csm-1.4 - update bgp test have a more dynamic vault check

manifests/sysmgmt.yaml, rpm/cray/csm/sle-15sp4/index.yaml
Backport of https://github.com/Cray-HPE/csm/pull/1948
=> CASMTRIAGE-5050/CASMCMS-8461/CASMCMS-8463: Update csm-config, csm-ssh-keys, and import-images

assets.sh
=> MTL-2118 CVE Revert

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
- [CASMCMS-8473](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8473)
- [CASMTRIAGE-5072](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5072)
=> CASMREL-1434

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
- [CASMCMS-8473](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8473)
- [CASMTRIAGE-5072](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5072)
=> CASMREL-1433

Jenkinsfile.github
Backport of https://github.com/Cray-HPE/csm/pull/1976 into `main`.
=> Improve pre-release valiadation - add deploy branch check, fail early

CHANGELOG.md, rpm/cray/csm/sle-15sp4/index.yaml
Augment the postgres backup goss test to check to see if the logical backup cronjobs exist.. The operator should re-create the logical backup cronjob if they are missing, but since this is fundamental to the job running and the artifact getting uploaded to s3, adding this to the initial part of the test seemed valuable.
* Resolves [CASMPET-6422](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6422)
Augment postgres backup goss test to also check for cronjob
* Virtual Shasta V2 (dorian)
* Operator has been running for >10 min, but some postgresql resource have not - so cannot guarantee the cronjob will be there (test-postgres running for 1 minute)
``` …
```
=> CASMPET-6422 1.5 : Augment postgres backup goss test to also check for cronjob

rpm/cray/csm/sle-15sp3/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
main backport of https://github.com/Cray-HPE/csm/pull/1963
=> CASMCMS-8473: Run tftp file transger subtest on workers not masters

manifests/platform.yaml
=> CASMINST-5880 update manifest

manifests/platform.yaml, rpm/cray/csm/sle-15sp4/index.yaml
Refactor etcd tests for bitnami etcd chart
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6397
* vshasta
```
ncn-m001-e2e75ea1:/home/bklein # export GOSS_BASE=/opt/cray/tests/install/ncn; goss -g /opt/cray/tests/install/ncn/tests/goss-k8s-etcd-database-health.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate
..
Total Duration: 1.455s
```
```
ncn-m001-e2e75ea1:/home/bklein # GOSS_BASE=/opt/cray/tests/install/ncn; goss -g /opt/cray/tests/install/ncn/tests/goss-k8s-etcd-cluster-balance.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate
..
Total Duration: 1.287s
```
```
ncn-m001-e2e75ea1:/home/bklein # GOSS_BASE=/opt/cray/tests/install/ncn; goss -g …
```
=> Refactor etcd tests for bitnami helm chart

rpm/cray/csm/sle-15sp3/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
To help @mtupitsyn add cmsdev to Goss, this adds a feature to cmsdev that lists the available tests it can run.
In addition, a null pointer exception is fixed (but this is only hit when using cmsdev in an unadvertised way and before CSM is deployed -- so not a critical problem).
Also pulls in CASMCMS-8482, although that makes no actual change to the RPM itself -- it's just changes to the build and repo.
See source PRs for details.
- [CASMCMS-8479 source PR](https://github.com/Cray-HPE/cms-tools/pull/76)
- [CASMCMS-8480 source PR](https://github.com/Cray-HPE/cms-tools/pull/77)
- [CASMCMS-8482 source PR](https://github.com/Cray-HPE/cms-tools/pull/80)
- Resolves [CASMCMS-8479](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8479)
- Resolves …
=> CASMCMS-8479/CASMCMS-8480: cmsdev: Add feature to list available tests; fix minor bug

rpm/cray/csm/sle-15sp4/index.yaml
This is already 1.0.20 in csm-rpms for 1.5, but csm was never updated.
=> MTL-2025 catch-up

manifests/sysmgmt.yaml, rpm/cray/csm/sle-15sp4/index.yaml
Upload spire-agent to nexus.
Include `csm-config` with `spire-agent` and `csm-node-identity` (MTL-2025).
=> MTL-2014 Add `spire-agent`

assets.sh
Pulls in the newer ipmitool back in.
=> MTL-2087 1.4

manifests/platform.yaml
Address build failure due to partial annotations on chart
=> CASMPET-6455: Fixup chart build (meta) to address build issue

assets.sh
* CASMCMS-8495
* CASMNET-2056
* CASMINST-5106
* CASMPET-6454
* CASMPET-6435
=> CASMREL-1456: NCN assets

assets.sh
* CASMCMS-8495
* CASMCMS-8485
* CASMNET-2056
* CASMINST-5106
* CASMPET-6454
* CASMPET-6435
=> CASMREL-1455: NCN assets

rpm/cray/csm/sle-15sp4/index.yaml
Small message fixes/improvements to cmsdev test tool. Because of the minor nature, and given that it is getting late in CSM 1.4, I am not planning to backport this.
- [source PR](https://github.com/Cray-HPE/cms-tools/pull/90)
- [csm-rpms manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/808)
See source PR for details.
Low risk -- only message changes.
=> CASMCMS-8498: cmsdev: Fix typo in message; improve some message details

rpm/cray/csm/sle-15sp2/index.yaml
Just fixes to typos in messages and comments in a couple NCN health check scripts. No functional changes.
- [csm-rpms main manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/812)
- [source PR](https://github.com/Cray-HPE/utils/pull/70)
Very very low risk.
=> CASMINST-6180: Fix typos in comments/messages of NCN health check scripts

CHANGELOG.md, manifests/core-services.yaml, manifests/platform.yaml
- update unbound-manager to load all aliases for NMN
CASMTRIAGE-5155
CAST-32667
mug
- manual review of dns records on test data …
=> feature/casmtriage-5155-csm-1.4 - update unboud-manager to load all aliases for NMN

CHANGELOG.md, manifests/core-services.yaml, manifests/platform.yaml
- update unbound-manager to load all aliases for NMN
CASMTRIAGE-5155
CAST-32667
mug
- manual review of dns records on test data …
=> feature/casmtriage-5155 - update unboud-manager to load all aliases for NMN

rpm/cray/csm/sle-15sp4/index.yaml
Backport of https://github.com/Cray-HPE/csm/pull/2064
=> CASMCMS-8502: cmsdev: Update dependencies to resolve CVEs

assets.sh, rpm/cray/csm/sle-15sp4/index.yaml
node-images:
- [MTL-1860](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1860)
- [MTL-2127](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2127)
=> CASMREL-1465

docker/index.yaml, manifests/sysmgmt.yaml
Move to a version of the Cray Product Catalog with the correct image path in its chart
=> CASMCMS-8521: Use updated Cray Product Catalog

assets.sh
New kernel and several user space packages.
=> MTL-2135 Package Sweep

assets.sh
node-images:
- [CASMCMS-8514](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8514)
- [MTL-2138](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2138)
=> CASMREL-1469

CHANGELOG.md, manifests/sysmgmt.yaml
Updates cray-console-data, node and operator for various stability improvements
* Resolves CASMCMS-8041
* Resolves CASMCMS-8252
* Resolves CASMCMS-7167
* Resolves CASMCMS-8416
* Resolves CASMCMS-8415
* Resolves CASMCMS-7169
See individual tickets
=> Update cray-console for stability improvements

manifests/sysmgmt.yaml
=> CASMCMS-8494: Pull in latest cray-cfs-api

rpm/cray/csm/sle-15sp3/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
=> CASMTRIAGE-5206

tds_cpu_requests.yaml, vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
New feature - As part of the migration from ElasticSearch to OpenSearch, sma-dashboards will be used to visualize OpenSearch's data. 
N/A
* …
=> added opensearch dashboards

manifests/sysmgmt.yaml
Fix filter options on BSS's endpoint-history API
* Resolves [CASMHMS-5812](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5812)
* Resolves [CASMHMS-5813](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5813)
* docker compose env
* vshasta
=> Updated bss to version 3.0.1

assets.sh
https://github.com/Cray-HPE/csm-rpms/pull/829
https://github.com/Cray-HPE/csm-rpms/pull/824
=> MTL-2144 New kernel

CHANGELOG.md, manifests/platform.yaml
* Resolves [CASMPET-6510](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6510)
* Rocket …
=> CASMPET-6510: update cray-opa for nexus keycloak connection

vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
=> Revert "CASMPET-6517 Override cray-spire server.fqdn"

CHANGELOG.md, manifests/platform.yaml
[## Summary and Scope
_How were the changes tested and success verified? If …
=> CASMPET-6514: update cray-sysmgmt-health for cmn seperation

manifests/sysmgmt.yaml, rpm/cray/csm/sle-15sp2-compute/index.yaml, rpm/cray/csm/sle-15sp3-compute/index.yaml, rpm/cray/csm/sle-15sp4-compute/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
This updates BOS to 2.1.1.
[csm-rpms manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/834) (moved to [metal-provision manifest PR](https://github.com/Cray-HPE/metal-provision/pull/93))
This resolves the following issues:
- [CASMCMS-8560](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8560): Updated API spec for GET to / to reflect that it returns a list of versions
- [CASMCMS-8570](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8570): Updated API spec for POST to /v1/sessiontemplate to reflect actual success status code (201)
- [CASMCMS-8571](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8571): Ensure that DELETE requests to /v1/sessiontemplate/{session_template_id} return a meaningful status code
- [CASMCMS-8573](https://jira-pro.its.hpecorp.net:8443/browse/CASMCM …
=> Update BOS to 2.1.1

assets.sh
Fixes:
- CASMCMS-8570: Updated API spec for POST to `/v1/sessiontemplate` to reflect actual success status code (201)
- CASMCMS-8571: Ensure that DELETE requests to `/v1/sessiontemplate/{session_template_id}` return a meaningful status code
- CASMCMS-8573: Updated API spec for POST to `/v1/session` to include possible 404 status response
- CASMCMS-8574: Updated API spec for POST to `/v1/session` to reflect actual success status code (201)
- CASMCMS-8578: Updated API spec for POST to `/v1/session/{session_id}/status` to reflect actual success status code (200) and possible failure status code (409)
- CASMCMS-8579: Updated API spec for DELETE to `/v1/session/{session_id}/status` to include possible 404 status response
- CASMCMS-8580: Updated API spec for POST to …
=> CASMREL-1488: assets

CHANGELOG.md, rpm/cray/csm/sle-15sp4/index.yaml
Create the iuf-cli 1.5 branch and update the CSM manifest.
=> SCICD-715: iuf-cli 1.5 branch and Manifest

manifests/sysmgmt.yaml
Pull in BOS include_disabled nodes option.
_How were the changes tested and success verified? If schema changes were part of this …
=> CASMTRIAGE-5255: Fix CASMTRIAGE-5255

rpm/cray/csm/sle-15sp3/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
New csm-testing and goss-servers.
Also re-syncs the SP3 repo which was lagging behind.
=> CASMINST-6306

assets.sh, rpm/cray/csm/sle-15sp3/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
Includes:
- [CASMINST-6306](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6306)
- [CASMPET-6319](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6319)
- [MTL-2113](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2113)
- [MTL-2141](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2141)
- [MTL-2151](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2151)
- [VSHA-559](https://jira-pro.its.hpecorp.net:8443/browse/VSHA-559)
=> CASMREL-1489

CHANGELOG.md, manifests/platform.yaml
Upgraded cray-nls & cray-iuf charts for CVE remediation (no critical or high CVEs).
* Resolves CASMPET-6235 and CASMPET-6563.
* `mug`
* dorian …
=> CASMPET-6235/CASMPET-6563: upgrade cray-nls & cray-iuf charts for CVE remediation

CHANGELOG.md, manifests/platform.yaml
=> CASMPET-6235: upgrade cray-iuf for CVE remediation

rpm/cray/csm/sle-15sp4/index.yaml
=> add cvt rpm to csm pit image

assets.sh, rpm/cray/csm/sle-15sp4/index.yaml
[CASMCVT-177](https://jira-pro.its.hpecorp.net:8443/browse/CASMCVT-177)
[CASMTRIAGE-5309](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5309)
=> CASMREL-1490

manifests/sysmgmt.yaml
Add support for UAN resources in tapms
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6316
```
{
"vcluster-green-user",
"vcluster-green-slurm"
],
{
"hsmgrouplabel": "green",
"type": "application",
"xnames": [
"x3000c0s32b0n0"
]
},
{
"hsmgrouplabel": "green",
"xnames": [
"x3000c0s19b1n0",
"x3000c0s19b3n0"
]
}
],
"uuid": "a81e4206-02ed-4ec8-b6fc-512bb67cfdf0"
}
Deployed
label = "green"
description = ""
exclusiveGroup = "tapms-exclusive-group-label"
tags = [ "vcluster-green",]
[members]
ids = [ "x3000c0s19b3n0", "x3000c0s32b0n0", "x3000c0s19b1n0",]
```
If …
=> Add UAN/Application node support for tapms (CASMPET-6316)

manifests/platform.yaml
=> Revert "Casmpet 6173 main"

Jenkinsfile.github, build/images/Makefile, build/images/extract.sh, build/images/pull_images.sh
Add pull images logic from PR 2197, move API Documentation stage out of parallel stages.
JIRA was down when this work was tested and PR created, so no ticket to link
* Change will also be needed in `release/1.4`
Tested in CSM Jenkins build pipeline
No known risks
=> Fix context timeout

docker/index.yaml
=> CASMINST-6352 update argoexec version

manifests/platform.yaml
Trying this a third time.
* Resolves CASMPET-6173
vshasta v2
- Was upgrade tested? If …
=> CASMPET-6173: cert-manager 0.7.2

assets.sh
=> CASMREL-1500: NCN assets

assets.sh
* CASMCMS-8517
* MTL-2156
* CASMCVT-192
=> CASMREL-1503: NCN assets

CHANGELOG.md, docker/index.yaml
Add ceph v17.2.6 to docker index.
As part of the CSM-1.4 to CSM-1.5 upgrade, we believe we will be upgrading ceph from v16.2.9 to v17.2.6.
* …
=> CASMPET-6585 add ceph v17.2.6 to docker index

CHANGELOG.md, manifests/sysmgmt.yaml
Change default runtime arm64 build runtime to utilize kata 
[CASMCMS-8566](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8566)
Tested in the mug environment
Manual testing on the helm chart
Build tests
None known of
=> increment ims to v3.9.2

Jenkinsfile.github, assets.sh, docker/index.yaml, hack/gen-rpm-index.sh, hack/snyk-scan.sh, hack/verify-helm-index.sh, hack/verify-rpm-index.sh, lib/setup-nexus.sh, manifests/platform.yaml, manifests/sysmgmt.yaml, release.sh, rpm/cray/csm/sle-15sp2-compute/index.yaml, rpm/cray/csm/sle-15sp2/index.yaml, rpm/cray/csm/sle-15sp3-compute/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml, rpm/cray/csm/sle-15sp4-compute/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml, security/snyk-aggregate-results/snyk-aggregate-results.py
CSM 1.3 backport of https://github.com/Cray-HPE/csm/pull/2215
=> BOS API spec fixes & one small BOS code fix

manifests/sysmgmt.yaml, rpm/cray/csm/sle-15sp2-compute/index.yaml, rpm/cray/csm/sle-15sp3-compute/index.yaml, rpm/cray/csm/sle-15sp4-compute/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
1.4 version of https://github.com/Cray-HPE/csm/pull/2227
=> CASMTRIAGE-5404: Update BOS to fix v1 session creation regression bug

CHANGELOG.md, assets.sh, release.sh
- add x86_64 and aarch64 compute artifacts
https://jira-pro.it.hpe.com:8443/browse/MTL-2162
https://jira-pro.its.hpecorp.net:8443/browse/CASM-4066
- local VM
Minimal, but does increase the size of the csm tarball.
=> MTL-2162: Add compute artifacts

assets.sh, rpm/cray/csm/sle-15sp2/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
- [CASMCVT-193](https://jira-pro.it.hpe.com:8443/browse/CASMCVT-193)
- [CASMINST-6379](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6379)
- [CASMPET-6542](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6542)
=> CASMREL-1506

docker/index.yaml, manifests/sysmgmt.yaml
See source PRs for full details.
* [cray-import-kiwi-recipe-image source PR](https://github.com/Cray-HPE/cray-import-kiwi-recipe-image/pull/18)
* [ims-load-artifacts source PR](https://github.com/Cray-HPE/ims-load-artifacts/pull/59)
* [image-recipes source PR](https://github.com/Cray-HPE/image-recipes/pull/56)
=> CASMCMS-7922: Use BOS v2 when importing images and creating BOS session templates

assets.sh, lib/install-goss-tests.sh
While here, make this code slightly more readable
* Resolves MTL-2163
* `redbull`
* ran a slightly-modified version of this script with a subset of the rpms normally handled by this script.
=> MTL-2163: install cmstools rpm

CHANGELOG.md, rpm/cray/csm/sle-15sp4/index.yaml
Update the iuf version to 1.5.2.
=> SCICD-733: Update IUF Version

assets.sh
- [CASMINST-6387](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6387)
- [CASMINST-6374](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6374)
=> CASMREL-1508

manifests/sysmgmt.yaml
Updates BOS to pull in fixes v2 and multi-tenancy bugs as well as an updated spec that more accurately reflects the behavior of the API. 
* Resolves CASMCMS-8612
* Resolves CASMCMS-8613
* Resolves CASMCMS-8614
* Resolves CASMCMS-8617
* Resolves CASMCMS-8630
* Resolves CASMCMS-8645
* and other spec tickets
Mostly tested on Ashton.  See individual tickets for details.
None
=> CASMCMS-8645: Update many BOS v2 and multitenancy bugs

manifests/sysmgmt.yaml
Updates the version of cfs-ara to pull in CVE fixes and the change to the new postgres basechart/operator
* Resolves CASMCMS-8627
* Resolves CASMCMS-8605
* Ashton
See individual PRs
None
=> CASMCMS-8627: Update ara for postgres chart changes and CVE fixes

assets.sh
- [CASMPET-6601](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6601)
=> CASMREL-1509

manifests/sysmgmt.yaml
Fix tapms api to use non-privileged port for read-only api
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6597
Mug -- curl w/in pod:
```
{"kind":"Tenant","apiVersion":"tapms.hpe.com/v1alpha1","metadata":{"name":"vcluster-green","namespace":"tenants","uid":"e9de42ad-6141-471c-ad5c-41611f842ca0","resourceVersion":"164165666","generation":5,"creationTimestamp":"2023-05-25T17:03:11Z","annotations":{"kopf.zalando.org/last-handled-configuration":"{\"spec\":{\"childnamespaces\":[\"slurm\"],\"state\":\"Deployed\",\"tenantname\":\"vcluster-green\",\"tenantresources\":[{\"enforceexclusivehsmgroups\":true,\"forcepoweroff\":false,\"hsmgrouplabel\":\"green\",\"type\":\"compute\",\"xnames\":[\"x3000c0s19b3n0\"]}]}}\n","kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"tapms.hpe.com …
```
=> Fix read-only api -- change pod port (CASMPET-6597)

assets.sh, lib/install-goss-tests.sh
- [CASMINST-6387](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6387)
- [MTL-2163](https://jira-pro.it.hpe.com:8443/browse/MTL-2163)
=> CASMREL-1510

CHANGELOG.md, manifests/platform.yaml, rpm/cray/csm/sle-15sp4/index.yaml
Bump cray-iuf, cray-nls, and iuf-cli versions.
This impliments all changes made for CASMINST-6208.
=> CASMINST-6208 bump cray-iuf, cray-nls, and iuf-cli versions

Jenkinsfile.github, assets.sh, nexus-repositories.yaml, release.sh, rpm/cray/csm/noos/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
- [CASMINST-3421](https://jira-pro.it.hpe.com:8443/browse/CASMINST-3421) (necessary for MTL-2016)
- [CASMTRIAGE-5477](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5477)
- [MTL-2016](https://jira-pro.it.hpe.com:8443/browse/MTL-2016)
- [MTL-2139](https://jira-pro.it.hpe.com:8443/browse/MTL-2139)
=> CASMREL-1518

Jenkinsfile.github, assets.sh, nexus-repositories.yaml, release.sh, rpm/cray/csm/noos/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
- [CASMINST-3421](https://jira-pro.it.hpe.com:8443/browse/CASMINST-3421) (necessary for MTL-2016)
- [CASMTRIAGE-5477](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5477)
- [MTL-2016](https://jira-pro.it.hpe.com:8443/browse/MTL-2016)
- [MTL-2139](https://jira-pro.it.hpe.com:8443/browse/MTL-2139)
=> CASMREL-1517

assets.sh
node-images:
- [CASMCMS-8621](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8621)
=> CASMREL-1519

assets.sh
node-images:
- [CASMCMS-8621](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8621)
=> CASMREL-1520

manifests/sysmgmt.yaml, rpm/cray/csm/sle-15sp2-compute/index.yaml, rpm/cray/csm/sle-15sp3-compute/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml, rpm/cray/csm/sle-15sp4-compute/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
1.3 backport of https://github.com/Cray-HPE/csm/pull/2323
=> CASMINST-6451: Fix bug creating BOS session templates

rpm/cray/csm/sle-15sp4/index.yaml
Moved all the postgres health checks out of the ncn-healthcheck-worker-single and into healthcheck-master-single test suite.
This is for CSM 1.5 where some postgres tests changed between CSM 1.5 and CSM 1.4. The new upgrade flow (which upgrade CSM before doing the image node upgrade) will also need to upgrade the csm-testing, goss-servers and platform-utils RPM to w001 to fully resolve this issue.
* Resolves [CASMPET-6633](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6633)
* `surtur`
The postgres tests pass when run on m001.  The remaining spire failure is a different issue (CASMPET-6618) 
``` …
```
=> CASMPET-6633 main : Move postgres health check goss tests to m001

manifests/sysmgmt.yaml, rpm/cray/csm/sle-15sp3/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
=> Revert "CASMCMS-8651/CASMCLOUD-1220: Remove ARS from Cray CLI; remove references to ARS from BSS API spec"

CHANGELOG.md, rpm/cray/csm/noos/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
(cherry picked from commit fabf2178c61a1648f82d5a61377f023feb6f6326)
=> CASMPET-6643 Update platform-utils to 1.6.0

assets.sh
=> CASMPET-6643 CASMPET-6638 CASMCMS-8651 CASMINST-6472 CASMPET-6640

assets.sh
* CASMCMS-8651
* CASMINST-6472
* CASMPET-6640
=> CASMREL-1527: NCN assets

rpm/cray/csm/sle-15sp4/index.yaml
=> CASMCVT-206

assets.sh
- [CASMCVT-206](https://jira-pro.it.hpe.com:8443/browse/CASMCVT-206)
=> CASMREL-1533

assets.sh
- [CASMCVT-206](https://jira-pro.it.hpe.com:8443/browse/CASMCVT-206)
- [CASMPET-6643](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6643)
=> CASMREL-1534

assets.sh, rpm/cray/csm/sle-15sp4/index.yaml
- [MTL-2168](https://jira-pro.it.hpe.com:8443/browse/MTL-2168)
- [MTL-2170](https://jira-pro.it.hpe.com:8443/browse/MTL-2170)
=> CASMREL-1535

docker/index.yaml
Switch base image to artifactory.algol60.net/csm-docker/stable/docker.io/library/alpine:3.15. This alpine base image gets rebuilt automatically, which should allow for updated packages to be picked up automatically when this container gets rebuilt.
* Resolves [CASMHMS-6036](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6036)
* Local System
* Mug
_How were the changes tested …
=> CASMHMS-6036: Pull in updated hms-shcd-parser image

docker/index.yaml
Switch base image to artifactory.algol60.net/csm-docker/stable/docker.io/library/alpine:3.15. This alpine base image gets rebuilt automatically, which should allow for updated packages to be picked up automatically when this container gets rebuilt.
* Resolves [CASMHMS-6036](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6036)
* Local System
* Mug
_How were the changes tested …
=> (1.5) CASMHMS-6036: Pull in updated hms-shcd-parser image

assets.sh
* CASMTRIAGE-5555
* CASMTRIAGE-5522
* MTL-2018
=> CASMREL-1540: assets

CHANGELOG.md, manifests/core-services.yaml, manifests/platform.yaml, rpm/cray/csm/noos/index.yaml
CASMNET-2095 (kea/ipxe changes)
MTL-2018 (transfer heartbeat to csm)
MTL-2019 (transfer acpid to csm)
https://jira-pro.it.hpe.com:8443/browse/CASMNET-2095
https://jira-pro.it.hpe.com:8443/browse/MTL-2018
https://jira-pro.it.hpe.com:8443/browse/MTL-2019
=> CASMNET-2095, MTL-2018, MTL-2019

manifests/sysmgmt.yaml, rpm/cray/csm/sle-15sp2-compute/index.yaml, rpm/cray/csm/sle-15sp3-compute/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml, rpm/cray/csm/sle-15sp4-compute/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
Updates BOS to include the following fixes/improvements:
* [CASMCMS-8674](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8674) - Remove long unused and broken `templateUrl` option from BOS API and CLI.
* [CASMCMS-8649](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8649) - Update API spec to include recommended limits for user-submitted fields, and give notice that these limits will be enforced in the future.
* [CASMCMS-8532](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8532) - Fix bug causing invalid schema error during some BOS operations
* [CASMCMS-8661](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8661) - Linting of BOS API spec to fix minor errors and outdated information.
* [CASMCMS-8667](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8667) - Correct erroneous information …
=> CASMCMS-8674/CASMCMS-8649/CASMCMS-8532/CASMCMS-8661/CASMCMS-8667: BOS fixes and improvements

manifests/sysmgmt.yaml, rpm/cray/csm/sle-15sp4/index.yaml
Main branch version of this PR:
* https://github.com/Cray-HPE/csm/pull/2406
The reason that this PR does not include the craycli changes is because they are pulled in by this PR by John:
https://github.com/Cray-HPE/csm/pull/2402
=> CASMCMS-8676/CASMCMS-8674/CASMCMS-8649/CASMCMS-8532/CASMCMS-8661/CASMCMS-8667: BOS fixes and improvements

docker/index.yaml
Switch base image to artifactory.algol60.net/csm-docker/stable/docker.io/library/alpine:3.15. This alpine base image gets rebuilt automatically, which should allow for updated packages to be picked up automatically when this container gets rebuilt.
* Resolves [CASMHMS-6036](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6036)
* Local System
* Mug
_How were the changes tested …
=> (1.4) CASMHMS-6036: Pull in updated hms-shcd-parser image

assets.sh
- new ilorest
- new cray-site-init
=> MTL-2156 CASMINSTS-6333: new NCN images

CHANGELOG.md, manifests/platform.yaml
upversion because of bad tag and CSM build
* Resolves [CASMTRIAGE-5568](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5568)
* Surtur
- Ran IUF
No
=> CASMTRIAGE-5568 to release/14

CHANGELOG.md, manifests/platform.yaml
upversion because of bad tag and CSM build
* Resolves [CASMTRIAGE-5568](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5568)
* Surtur
- Ran IUF
No
=> CASMTRIAGE-5568 to stable 15

manifests/core-services.yaml
* Database interaction improvements:
*  Prevent scenarios from getting deadlocked when multiple concurrent requests. 
* Pass HTTP context to database layer to cancel database queries if the HTTP request is canceled.
* Ensure that all get and set operations on SLS are performed atomically in a SQL transaction.
* Introduced a caching HTTP middleware in SLS. This feature is disabled by default, but can be enabled by overriding values in the SLS helm chart.
_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to …
=> CASMHMS-5916: Pull in newer version of SLS with database interaction improvements

manifests/sysmgmt.yaml
Update for etcd base chart
* Resolves [CASMUSER-3228](https://jira-pro.it.hpe.com:8443/browse/CASMUSER-3228)
Chart builds. Requires a 1.5 system for testing
=> CASMUSER-3228: Update uas with etcd fixes

manifests/sysmgmt.yaml
Same PR that went into main. This is multi-arch support for ARM64 builds.
* `tyr`
=> Bump cms-ipxe to latest and greatest

rpm/cray/csm/noos/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
=> Add latest noos CVT and cm-cli RPM

manifests/sysmgmt.yaml, rpm/cray/csm/sle-15sp4/index.yaml, rpm/cray/csm/sle-15sp5/index.yaml
main branch PR for https://github.com/Cray-HPE/csm/pull/2433
=> CASMTRIAGE-5575: Fix BOS session status error

assets.sh
=> CASMREL-1547

assets.sh
https://github.com/Cray-HPE/node-images/compare/5.0.13...5.0.14
=> 5.0.12 -> 5.0.14

rpm/cray/csm/sle-15sp4/index.yaml
main branch PR for https://github.com/Cray-HPE/csm/pull/2461
=> CASMTRIAGE-5598: cmsdev: Compress test artifacts using gzip on failure

manifests/sysmgmt.yaml
Updates the bos chart to include a new parameter needed for the latest etcd chart.
* Resolves CASMCMS-8684
* Mug
Deployed and ran basic commands
None
=> CASMCMS-8684: Update bos for etcd chart updates

manifests/sysmgmt.yaml
Updates the bos chart to include a new parameter needed for the latest etcd chart.
* Resolves CASMCMS-8684
* Mug
Deployed and ran basic commands
None
=> CASMCMS-8684: Update bos for etcd chart updates (stable)

manifests/sysmgmt.yaml
Pulls in the CFS changes needed to support passing the require_dkms parameter to IMS during image customization.
* Resolves CASMCMS-8679
* Mug
Tested image customization with various combinations of the parameter.
None
=> CASMCMS-8679: Update CFS to support new require_dkms parameter

manifests/sysmgmt.yaml
Pulls in the CFS changes needed to support passing the require_dkms parameter to IMS during image customization.
* Resolves CASMCMS-8679
* Mug
Tested image customization with various combinations of the parameter.
None
=> CASMCMS-8679: Update CFS to support new require_dkms parameter (stable)

rpm/cray/csm/noos/index.yaml
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASM-4366
Wasp
=> CASM-4366: Upgrade pit-observability images (Grafana and prometheus) to the latest version

.gitignore, release.sh, rpm/cloud-init.yaml, rpm/cray/csm/noos/index.yaml, rpm/cray/csm/sle-15sp3/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
=> MTL-2000 stable

rpm/cray/csm/sle-15sp4/index.yaml
bump canu version
CASMNET-2146
_How were the changes tested and success …
=> CASMNET-2146 

rpm/cray/csm/sle-15sp4/index.yaml
CASMNET-2046
_How were the changes tested and success verified? If schema …
=> CASMNET-2046 1.5

docker/index.yaml
bump canu
CASMNET-2046
_How were the changes tested and success verified? …
=> CASMNET-2046 main

docker/index.yaml
bump canu
CASMNET-2146 
_How were the changes tested and success verified? …
=> CASMNET-2146 1.5

assets.sh
- [CASMNET-2146](https://jira-pro.it.hpe.com:8443/browse/CASMNET-2146)
- [CASMPET-6650](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6650)
- [MTL-2032](https://jira-pro.it.hpe.com:8443/browse/MTL-2032)
- [MTL-2159](https://jira-pro.it.hpe.com:8443/browse/MTL-2159)
=> CASMREL-1559

assets.sh
- [CASMNET-2146](https://jira-pro.it.hpe.com:8443/browse/CASMNET-2146)
- [CASMPET-6650](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6650)
- [MTL-2032](https://jira-pro.it.hpe.com:8443/browse/MTL-2032)
- [MTL-2159](https://jira-pro.it.hpe.com:8443/browse/MTL-2159)
=> CASMREL-1560

rpm/cray/csm/noos/index.yaml, rpm/cray/csm/sle-15sp4/index.yaml
New `pit-init` and new package names for `pit-nexus` and `pit-observability.
=> CASMINST-6625 New `pit-init`

assets.sh
- [CASMINST-6525](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6525)
- [CASMTRIAGE-5632](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5632)
- [MTL-2159](https://jira-pro.it.hpe.com:8443/browse/MTL-2159)
- [MTL-2189](https://jira-pro.it.hpe.com:8443/browse/MTL-2189)
=> CASMREL-1562

assets.sh
- [CASMINST-6525](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6525)
- [CASMTRIAGE-5632](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5632)
- [MTL-2159](https://jira-pro.it.hpe.com:8443/browse/MTL-2159)
- [MTL-2189](https://jira-pro.it.hpe.com:8443/browse/MTL-2189)
=> CASMREL-1561

rpm/cray/csm/sle-15sp4/index.yaml
Fixes for istio goss testing to also include completed pods.
* Resolves [CASMTRIAGE-5580](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5580)
* `drax`
- …
=> Fixes for CSM 1.5 istio goss test (CASMTRIAGE-5580)

rpm/cray/csm/sle-15sp4/index.yaml
Fixes for istio goss testing to also include completed pods.
* Resolves [CASMTRIAGE-5580](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5580)
* `drax` …
=> CASMTRIAGE-5580: fixes for istio goss test

assets.sh
- [MTL-2191](https://jira-pro.it.hpe.com:8443/browse/MTL-2191)
=> CASMREL-1563

assets.sh
- [MTL-2191](https://jira-pro.it.hpe.com:8443/browse/MTL-2191)
=> CASMREL-1566

rpm/cray/csm/noos/index.yaml
Bug fixes to CDS have been included in CVT pkg, hence need to include the latest version  
cvt-1.5.2-20230704071632_a2da8d744eec.x86_64.rpm
https://jira-pro.it.hpe.com:8443/browse/CASMCVT-229
_List the …
=> adding latest CVT version

assets.sh
=> CASMREL-1569
