- manifests/platform.yaml
Update manifest to pull in 0.0.4 of the cray-k8s-encryption chart.
Bugfix to ensure placement only on masters.
* Resolves CASMPET-5968
Validated on starlord and mug that we get placement only on master/control plane nodes.
* starlord/mug
On a system with the node label having a different value than what I tested with, manually edited the changes into place to ensure we still only get placement on master nodes. While worker nodes also technically …
> Bump cray-k8s-encryption to 0.0.4

- manifests/platform.yaml
Fixes a build issue due to a missing default tpmProvisioner value.
* Resolves [CASMPET-5970](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5970)
* https://github.com/Cray-HPE/cray-opa/pull/62
> CASMPET-5970 Bump cray-opa to 1.28.1

- chrony/csm_ntp.py
The csm_ntp.py script has an oversight in how it attempts to handle problems with API calls to BSS. It handles the case where the request function raises an exception, but it does not handle the case where the request gets a response, but that response is not reporting success. This PR modifies the get_bss_data function so that it properly handles both error paths.
Caveats:
- I did not author the original script and don't know much about it. I have tested my changes and am confident that they do what I want, but someone with more context about the script should be sure to review them.
- I don't know if the csm repo is the (only) home of this script. I just saw that it existed here and had the same issue as I saw on surtur. On surtur I could see that the file had not been installed by an …
> CASMINST-5349: csm_ntp.py properly handle unsuccessful responses from BSS

- build/images/extract.sh
Improve chart related error handling in extract.sh script by adding "set -eo pipefail" parameter to parallel options.
Resolves casminst-5355
* Resolves CASMINST-5355
Tested in the build pipeline
No known risks
> add set -eo pipefail to inline bash script to force exit on error

- manifests/platform.yaml
- manifests/sysmgmt.yaml
Adding some distance between the hnc and tapms charts.  Wasn't able to reproduce the issue but it looked like hnc was still doing some config when tapms was installed.  It makes sense to move tapms after the hms stuff anyway, since it makes hsm calls anyway..
* Resolves [CASMTRIAGE-4209](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4209)
- …
> Move tapms chart deploy later in the install

- manifests/core-services.yaml
- manifests/platform.yaml
- Fix race condition between dhcp-helper.py and MEDs
CASMNET-1880
CASMTRIAGE-4140
Loki
- Was …
> bug/CASMNET-1880-csm-1.3 - Fix race condition between dhcp-helper.py and MEDs

- rpm/cray/csm/sle-15sp3/index.yaml
- Fixes: [CASMINST-5352](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5352)
- Relates to: [CASMTRIAGE-4198](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4198)
- csm
- https://github.com/Cray-HPE/csm/pull/1339
- csm-rpms
- https://github.com/Cray-HPE/csm-rpms/pull/614
- https://github.com/Cray-HPE/csm-rpms/pull/615
- csm-testing
- https://github.com/Cray-HPE/csm-testing/pull/398
- https://github.com/Cray-HPE/csm-testing/pull/399
- docs-csm
- https://github.com/Cray-HPE/docs-csm/pull/2498
- https://github.com/Cray-HPE/docs-csm/pull/2499
- Docs Pull Request
The description of this test (seen when it fails) includes a link to a page which no longer exists in the csm-1.3 documentation. This updates the test description text to correct that, as well as …
> CASMINST-5352: Fix broken link in unused_drives_on_storage_nodes test description

- CHANGELOG.md
- manifests/platform.yaml
In LANL tycho enviromment, the bos etcd backups had been timing out for many days.
This environment has 14 workers, 2688 compute nodes in 11 Olympus cabinets.
The default timeout is 1 min, once the timeout was increased, the backups started to succeed in tycho.
The timeout was increased to 10 min for all etcdbackups and a post-upgrade hook was added to allow for the etcdbackup resources to get re-created with the added backupPolicy.timeoutInSecond value.
This is targeted for CSM 1.3.
A troubleshooting doc change will be made for CSM 1.2.
* Resolves [CASMTRIAGE-4188](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4188)
* Change will also be needed in `<insert branch …
> CASMTRIAGE-4188 1.3 : LANL DDR5 tycho bos etcd backup has not run for 9 days

- CHANGELOG.md
- manifests/platform.yaml
In LANL tycho enviromment, the bos etcd backups had been timing out for many days.
This environment has 14 workers, 2688 compute nodes in 11 Olympus cabinets.
The default timeout is 1 min, once the timeout was increased, the backups started to succeed in tycho.
The timeout was increased to 10 min for all etcdbackups and a post-upgrade hook was added to allow for the etcdbackup resources to get re-created with the added backupPolicy.timeoutInSecond value.
This is targeted for CSM 1.3.
A troubleshooting doc change will be made for CSM 1.2.
* Resolves [CASMTRIAGE-4188](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4188)
* Change will also be needed in `<insert branch …
> CASMTRIAGE-4188 main : LANL DDR5 tycho bos etcd backup has not run for 9 days

- manifests/platform.yaml
[CASMMON-190](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-190) - Grafana piechart plugin issues in air-gapped systems
[CASMPET-4897](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-4897) - Grafana is missing the Vonage-status-panel plugin required by the Ceph - Cluster dashboard
Upgrading the pie-chart-panel plugin to the latest by creating a Grafana docker image with the build piechart plugin instead of downloading the piechart plugin while installing the chart. Grafana Upgrade and Dashboard improvements by supporting new visualizations. Setting the new path for plugins to download.
Resolves -
Adds pie chart panel to existing dashboards. Resolves the Grafana Ceph - Cluster dashboard reporting the following error - Panel plugin not found: Vonage-status-panel.
Tested on slice …
> CASMMON-190/196 Path change for plugins

- CHANGELOG.md
- rpm/cray/csm/sle-15sp2/index.yaml
This is a bugfix for platform utils etcd_restore_rebuild.sh calling a script in a local directory instead of the proper location of platform utils.
* Resolves [CASMINST-5379](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5379) …
> CASMINST-5379: Fix bad reference in platform utils

- CHANGELOG.md
- manifests/platform.yaml
Make anti-affinity required for cray-kyverno chart to spread its deployment to different nodes.
* Resolves [CASMPET-6008](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6008)
* Change will also be needed in `release/1.3`
* `mug`
Indian security team did successful sanity tests on mug.
- Were the …
> CASMPET-6008: add required anti-affinity for cray-kyverno

- CHANGELOG.md
- manifests/nexus.yaml
- manifests/platform.yaml
Updates the version of nexus-setup and the chart version
* Resolves [CASMPET-6016](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6016)
Almost no risk. The …
> CASMPET-6016: Update cray-nexus to use nexus-setup 0.7.1

- CHANGELOG.md
- manifests/sysmgmt.yaml
Updates the cfs-api, cfs-operator, cfs-batcher and cfs-hwsync-agent to pull in fixes/additions for several tickets in the CFS usability epic. 
* Resolves CASMCMS-8243
* Resolves CASMCMS-2121
* Resolves CASMCMS-5919
* Resolves CASMCMS-7114
* Resolves CASMCMS-7278
* Resolves CASMCMS-7457
* Resolves CASMCMS-7548
* Resolves CASMCMS-7639
* Resolves CASMCMS-7714
* Resolves CASMCMS-7719
* Resolves CASMCMS-7803
* Resolves CASMCMS-7802
* Resolves CASMCMS-7850
* Resolves CASMCMS-7886
* Resolves CASMCMS-8195
* Resolves CASMCMS-8208
* Resolves CASMCMS-8211
* Starlord
All changes were tested installed  and tested.
> CASM-2684: Update cfs services for several usability changes/fixes

- CHANGELOG.md
- rpm/cray/csm/sle-15sp3/index.yaml
Release csm-testing v1.14.59, fix check_for_unused_drives.py failing
* Resolves [CASMTRIAGE-4185](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4185)
* Redbull
_Are there …
> CASMTRIAGE-4185 csm-1.3 - Release csm-testing v1.14.59, fix check_for_unused_drives.py failing

- CHANGELOG.md
- rpm/cray/csm/sle-15sp3/index.yaml
release csm-testing v1.15.14, fix check_for_unused_drives.py failing
* Resolves [CASMTRIAGE-4185](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4185)
* Tested on redbull
_Are there known issues with these changes? Any other special …
> CASMTRIAGE-4185 release csm-testing v1.15.14, fix check_for_unused_drives.py failing

- manifests/sysmgmt.yaml
Updates the cfs-api chart to pull in a chart that has the correct image annotation
* Resolves CASMINST-5399
The build logs confirm that the correct annotation was generated
None
> CASMINST-5399: Fix cfs-api image annotation

- manifests/sysmgmt.yaml
Fixes the cfs-batcher chart so that it's annotation correctly references the beta build image.
* Resolves CASMCMS-8252
> CASMCMS-8252: Fix cfs-batcher chart to include correct image annotation

- CHANGELOG.md
- rpm/cray/csm/sle-15sp3/index.yaml
The BSS boot parameter test (data-validatory.py) was too strict. Instead of testing for **initrd=initrd.img.xz**, we're now just confirming that the **initrd** boot parameter exists.
https://github.com/Cray-HPE/csm-testing/pull/407
* rocket
initrd= did not exist on two nodes and the test flagged it.
None known.
> CASMTRIAGE-4269

- CHANGELOG.md
- manifests/sysmgmt.yaml
Updates the gitea chart to pull in the 1.17.2 version of the gitea image to address CVEs
* Resolves CASMCMS-8251
* Starlord
Pushed and pulled from repos with the new image deployed
None
> CASMCMS-8251: Updaate gitea chart for CVEs (1.3)

- CHANGELOG.md
- manifests/sysmgmt.yaml
Updates the gitea chart to pull in the 1.17.2 version of the gitea image to address CVEs
* Resolves CASMCMS-8251
* Starlord
Pushed and pulled from repos with the new image deployed
None
> CASMCMS-8251: Update gitea chart for CVEs

- build/images/Makefile
- build/images/extract.sh
- manifests/platform.yaml
Remove complex sub-shell logic in 'extract.sh', script as a small refactor to ~ fix 'not' failing on missing Helm charts.
Also, add logic to the extract phase of the makefile to short-circuit build failures so builds fail faster on missing charts, etc.  
* Resolves [CASMINST-5355](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5355)
Tested forced non-existent chart reference and happy path test via `make -j 8` for images.
* Ubuntu VM (Local)
> Fail on missing charts

- CHANGELOG.md
- manifests/sysmgmt.yaml
The ims service is single-threaded, so while it is performing an operation it is not able to respond to liveness/readiness queries. When the image sizes get to 5-13Gb, sometimes the liveness probe will kill the ims container in the middle of an image copy. This increases the timings to allow longer operations until we can get a better solution in place.
Code PR:
https://github.com/Cray-HPE/ims/pull/44
* Resolves [CASMTRIAGE-4288](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4288)
* Resolves [CASMTRIAGE-4268](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4268)
* Resolves [CASMTRIAGE-4091](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4091)
* `Mug`
* `Loki`
The settings were changes manually in the deployment on Loki and with these changes can successfully …
> CASMTRIAGE-4288 - IMS - increase timeouts to accommodate larger images.

- docker/index.yaml
- lib/setup-nexus.sh
See CHANGELOG.md in sat repo for full description of changes.
Increment the version of SAT included in CSM from 3.19.2 to 3.19.3
* Partially resolves [CASMTRIAGE-4288](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4288)
* Relates to #1397 and #1398
* mug
Installed this version of cray-sat container image on mug through installation of SAT product stream version 2.4.13, which includes this same version of the container image.
N/A
> CASMTRIAGE-4288: Update cray-sat container image to 3.19.3

- manifests/sysmgmt.yaml
When BOS V2 performs an upgrade, it needs to migrate data from the etcd database to a new redis database. It does this 
migration in a post-upgrade Helm hook. The Helm hook needs to wait for the pod containing the etcd database to start up before it can do its migration work. The etcd pod can take a long time to start up and this causes Helm to time out the deployment. Extending the timeout avoids this failure.
* Resolves CASMCMS-8239
* `Fanta`
I deployed BOS V2 using a manifest that had the same timeout value of 10 minutes. It was successful. I then rolled BOS back to the earlier deployment.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? No.
- Were continuous integration tests …
> CASMCMS-8239: Lengthen BOS deployment timeout to 10 minutes

- manifests/platform.yaml
When the opa policies were broken up by use the system-pxe and system-compute policies were not moved over. This creates a new policy group, keycloak-system, that's used on the main ingress.
* Resolves [CASMINST-5400](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5400)
* https://github.com/Cray-HPE/cray-opa/pull/63
* fanta
Validated that system-pxe keycloak access worked after applying and that it allowed nodes to continue booting.
- Was downgrade tested? If not, why? N, not needed
> CASMINST-5400 Bump cray-opa to 1.29.0

- CHANGELOG.md
- manifests/platform.yaml
We ran into a case that kyverno failed to pull images from Nexus because Nexus was down; at the meantime, Nexus could not be deleted for a restart because kyverno webhook blocked the Nexus pod deletion to go through.
* Resolves [CASMPET-6035](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6035)
_How were the changes tested and success verified? If …
> CASMPET-6035: add kyverno images to precache

- assets.sh
- rpm/cray/csm/sle-15sp3/index.yaml
MTL-1971
Associate `system_config.yaml` and CSI inputs to CSM 1.4.
> MTL-1971 Enable 1.4 configs

- CHANGELOG.md
- rpm/cray/csm/sle-15sp2/index.yaml
This fixes a path issue that prevents spire from being re-joined properly. It also fixes an issue where attempting to delete files that weren't there caused the script to error out.
* Resolves [CASMPET-6033](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6033)
* https://github.com/Cray-HPE/utils/pull/65
* wasp …
> casmpet-6033 bump platform-utils to 1.3.9

- CHANGELOG.md
- rpm/cray/csm/sle-15sp2/index.yaml
This fixes a path issue that prevents spire from being re-joined properly. It also fixes an issue where attempting to delete files that weren't there caused the script to error out.
* Resolves [CASMPET-6033](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6033)
* https://github.com/Cray-HPE/utils/pull/66
* wasp …
> casmpet-6033 bump platform-utils to 1.4.2

- CHANGELOG.md
- manifests/platform.yaml
Verified on many systems that the gatekeeper-audit pod (manager container) was being OOM killed frequently.
This is a backward compatible bug fix to increase the memory limit from 512Mi to 1Gi.
* Resolves [[CASMTRIAGE-4311](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4311)
Verified the pod is no longer restarting and kubectl events no longer reports OOMs for the manager container process.
Tested in shandy (1.3.0-rc.1) , hermod (1.2.0-rc.2) and tyr …
> CASMTRIAGE-4311 1.3 : gatekeeper-audit manager container is oom-killed frequently

- CHANGELOG.md
- manifests/platform.yaml
Verified on many systems that the gatekeeper-audit pod (manager container) was being OOM killed frequently.
This is a backward compatible bug fix to increase the memory limit from 512Mi to 1Gi.
* Resolves [[CASMTRIAGE-4311](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4311)
Verified the pod is no longer restarting and kubectl events no longer reports OOMs for the manager container process.
Tested in shandy (1.3.0-rc.1) , hermod (1.2.0-rc.2) and tyr …
> CASMTRIAGE-4311 main: gatekeeper-audit manager container is oom-killed frequently

- CHANGELOG.md
- manifests/platform.yaml
This is a bugfix that fixes an issue with keycloak localize where it can get into a state of never being able to end and gets stuck in a infinite loop.
* Resolves [CASMTRIAGE-4286](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4286)
- Was downgrade tested? …
> CASMTRIAGE-4286: Update keycloak-localize

- manifests/sysmgmt.yaml
Fixes BOS v2 session extended status reporting for cases with many component failures.
* Resolves CASMCMS-8270
* Changes were tested locally
Created a test case to mimic the multiple failures seen on Shandy
None
> CASMCMS-8270: Update bos to fix v2 session status reporting

- manifests/sysmgmt.yaml
Pull in newer  cray-hms-hmcollector chart. Switched over to use ping from the iputils package instead of from busybox to work around an issue where busybox ping does not have permission when running as non-root user. This was causing River telemetry to not be polled.
* Resolves [CASMHMS-5776](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5776)
* Tyr
_How were the …
> CASMHMS-5776: Pull in new collector version

- manifests/sysmgmt.yaml
Pull in newer  cray-hms-hmcollector chart. Switched over to use ping from the iputils package instead of from busybox to work around an issue where busybox ping does not have permission when running as non-root user. This was causing River telemetry to not be polled.
* Resolves [CASMHMS-5776](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5776)
* Tyr
_How were the …
> CASMHMS-5776: Pull in newer cray-hms-hmcollector chart

- docker/index.yaml
Remove unused multus v3.1 docker image from tarball in CSM 1.3
* Resolves [CASMPET-6051](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6051)
Will verify the image is no longer in the tarball.
Not yet
Not yet
Low
> Remove previous (not used) multus docker image reference (CASMPET-6051)

- manifests/platform.yaml
Change upgrade strategy to restart pods in the daemonset in parallel.  This isn't an api or db service, so they can all be restarted together.
* Resolves [CASMPET-6052](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6052)
Before:
```
ncn-m001-cdd6e862:/home/bklein # time kubectl rollout status daemonset -n nexus cray-precache-images
Waiting for daemon set "cray-precache-images" rollout to finish: 0 out of 6 new pods have been updated...
Waiting for daemon set "cray-precache-images" rollout to finish: 0 out of 6 new pods have been updated...
Waiting for daemon set "cray-precache-images" rollout to finish: 0 out of 6 new pods have been updated...
Waiting for daemon set "cray-precache-images" rollout to finish: 1 out of 6 new pods have been updated...
Waiting for daemon set …
```
> Change precache chart upgrade to restart pods in parallel

- docker/index.yaml
A linting error from an updated base image pylinter was causing the nightly builds to fail. I made a slight code change that fixes the linting error. There is no practical change to the underlying code, but it needed an updated ims-load-artifacts image to resolve.
The barebones recipe image automatically picks up the new ims-load-artifacts image (with no change to its version), but the manifests need to update to the ims-load-artifacts:1.6.1 version that is getting picked up.
Code PR:
https://github.com/Cray-HPE/ims-load-artifacts/pull/25
* Resolves [CASMCMS-8272](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8272)
* Change will also be needed in `release/1.2` and `main`
Very low risk - just a change to make the linter happy.
> CASMCMS-8272 - fix broken nightly build due to linting error.

- CHANGELOG.md
- manifests/sysmgmt.yaml
Use cray-postgres-db-backup:0.2.3 image for spire to fix postgres db restore issue that was caused by incompatible sql version in previous images.
* Resolves [CASMPET-5966](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5966)
_How were the changes tested and success verified? If schema changes were part of this change, how …
> CASMPET-5966: use cray-postgres-db-backup:0.2.3 image for spire

- manifests/sysmgmt.yaml
Changing the "hosts" from a wildcard ("*") to the specific hostname that will be used to access the hmcollector service.  In this case, the hostname is actually the HMN gateway IP (e.g. 10.94.100.71).    This will prevent requests that are using api.hmnlb.<system-domain> from being routed to this service.
This change is backwards compatible.  It just makes the virtual service more restrictive in what will be routed to it.
* Resolves CASMTRIAGE-4336
Tested on:
* `drax`
Test description:
Tested by manually changing the virtual service on drax.   
```
ncn-m001:~/johren # diff -cw orig fixed 
*** orig	2022-10-07 16:59:14.000998731 +0000
--- fixed	2022-10-07 16:59:22.061084307 +0000
***************
*** 17,23 ****
gateways:
- hmn-gateway
hosts:
!   - "*"
http:
- route:
- destination:
--- 17,23 …
```
> CASMTRIAGE-4336: Pull in cray-hms-hmcollector chart version 2.15.9

- manifests/platform.yaml
Some uan subscription matches were missing preventing uans from booting. This adds the missing policies and sorts the list so that it's easier to parse.
* Resolves [CASMTRIAGE-4338](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4338)
* https://github.com/Cray-HPE/cray-opa/pull/68
* Loki
* Rocket
> CASMTRAIGE-4338 Bump cray-opa to 1.25.3

- rpm/cray/csm/sle-15sp2/index.yaml
Increases the timeout for the etcd endpoint health test. At times it can take just over 10s to run.
_Is this change is a backwards compatible bugfix
* Resolves [CASMPET-6047](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6047)
vale
- …
> CASMPET-6047 1.2.2 : Vale ncn-healthcheck fails in etcd_database_health

- manifests/sysmgmt.yaml
Updates BOS to pull in increased default timeout values.  This is due to testing on shandy where many components were taking longer than expected to boot.
* Resolves CASMCMS-8279
* Shandy
These values were tested on Shandy, and several sessions were run with these values.
None
> CASMCMS-8279: Update BOS for increased v2 default timeouts

- rpm/cray/csm/sle-15sp2/index.yaml
The script that configures SNMP on Dell and Aruba switches expects a user to delete from the Aruba switches. Unfortunately the delete happens after the creation of the new user and if they are the same name, the new user is deleted leaving the switch as it was before the script is executed. Updated the script to not require the delete user name. This allows both a creation method and a way to delete bad user names.
Behavior will not change when the same command line from the documentation is used.
* Resolves [CASMHMS-5782](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5782)
* Documentation changes required in [CASMHMS-5782](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5782)
* `loki`
Copied a modified version of the script to loki and executed with an alternative username …
> CASMHMS-5782 Fix snmp configure script

- manifests/sysmgmt.yaml
This was a change that was merged shortly after the release/1.3 branch was created. The below manifest PR was merged to 'main', but we missed the 'release/1.3' manifest PR.
This updates internal server addresses so when the *.dev.cray.com domain is retired, the nightly builds will continue to succeed.
Manifest PR to main:
https://github.com/Cray-HPE/csm/pull/1238
Code PR:
https://github.com/Cray-HPE/cray-crus/pull/32/files
* Resolves [CASMCMS-8144](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8144)
* `Mug`
Installed on system and checked out as much as able with condition of the machine.
Low risk - only changes to build server addresses.
> CASMCMS-8144 - update dev.cray.com server addresses to allow continued builds.

- manifests/sysmgmt.yaml
Pull in newer cray-hms-hmcollector container image. Switched over to use ping from the iputils package instead of from busybox to work around an issue where busybox ping does not have permission when running as non-root user. This was causing River telemetry to not be polled.
Backwards compatible bugfix
* Resolves [CASMHMS-5776](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5776)
* Bradi - …
> CASMHMS-5776: Pull in cray-hms-hmcollector for polling river telemetry fix.

- manifests/sysmgmt.yaml
Olympus hardware doesn't allow multiple power cap controls to be modified at the same time but there is something called a deep patch that is available. Converted CAPMC to use the deep patch mechanism for Olympus nodes.
* Resolves [CASMHMS-5436](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5436)
Tested on:
* `loki`
Upgraded to test CAPMC and verified power cap setting can be applied with the newer CAPMC using the deep patch.
HAS A SECURITY AUDIT BEEN RUN? (./runSnyk.sh) Y
ARE THERE KNOWN ISSUES WITH THESE CHANGES? N
ANY OTHER SPECIAL CONSIDERATIONS? N
> CASMHMS-5786 Use CAPMC that has change for Olympus deep patch power capping

- manifests/platform.yaml
CASMSTRIAGE-4349: recreated this PR to target stable/1.2 in place of release/1.2
> update cray-sysmgmt-health to v0.25.1

- manifests/sysmgmt.yaml
Updates BOS to fix an issue with staging shutdown operations using BOS v2
* Resolves CASMCMS-8284
* Frigg
Staged a shutdown operation and confirmed the staged data was correct and that there were no errors during setup.
None
> CASMCMS-8284: Update bos to fix v2 staged shutdowns

- manifests/sysmgmt.yaml
This is a backport of the [1.3 PR](https://github.com/Cray-HPE/csm/pull/1086) for [CASMTRIAGE-3756](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3756), because the fix is needed for 1.2.2 as well.
Source PRs:
* https://github.com/Cray-HPE/ims-load-artifacts/pull/28
* https://github.com/Cray-HPE/image-recipes/pull/33
Resolves [CASMINST-5509](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5509).
I tested the fix on fanta and it resolved the problem.
Low risk, and barebones builds during install will fail without this fix.
> CASMINST-5509: Backport CASMTRIAGE-3756 - fix import of barebones image

- CHANGELOG.md
- manifests/platform.yaml
BREAK/FIX: Cray-nls needs to pick up the cray base chart version 8.1.5 to fix postgres restore incompatibility issue in CSM 1.2.2
* Resolves [CASMPET-6086](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6086)
```
$ wget https://artifactory.algol60.net/artifactory/csm-helm-charts/stable/cray-nls/cray-nls-1.2.7.tgz
$ …
```
> CASMPET-6086 CSM 1.2.2 : BREAK/FIX: Cray-nls needs to pick up the cray base chart

- manifests/core-services.yaml
Pull in newer SLS chart that contains a fix for automatic postgres backups.
backwards compatible bugfix
* Resolves [CASMHMS-5791](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5791) …
> CASMHMS-5791: Pull in newer SLS chart that contains a fix for automatic postgres backups.

- manifests/core-services.yaml
Pull in newer HSM chart that contains a fix for automatic postgres backups
* Resolves [CASMHMS-5792](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5792)
For testing, see: https://github.com/Cray-HPE/hms-smd-charts/pull/30
low
> CASMHMS-5792: Pull in newer HSM chart that contains a fix for automatic postgres backups

- manifests/core-services.yaml
- manifests/platform.yaml
- cray-dhcp-kea increase timeout on readiness check to from default value.
yes
CAST-31316
mug
- Were continuous integration tests …
> bugfix/CAST-31316 - cray-dhcp-kea increase timeout on readiness check to from default value.

- manifests/core-services.yaml
- manifests/platform.yaml
- cray-dhcp-kea increase timeout on readiness check to from default value.
yes
CAST-31316
mug
- Were continuous integration tests …
> bugfix/CAST-31316-stable-csm-1.2 - cray-dhcp-kea increase timeout on readiness check to from default value.

- manifests/core-services.yaml
- manifests/platform.yaml
- cray-dhcp-kea increase timeout on readiness check to from default value.
yes
CAST-31316
mug
- Were continuous integration tests …
> bugfix/CAST-31316-csm-1.3 - cray-dhcp-kea increase timeout on readiness check to from default value.

- CHANGELOG.md
- manifests/platform.yaml
> Revert "CASMPET-6086 CSM 1.2.2 : BREAK/FIX: Cray-nls needs to pick up the cray base chart"

- manifests/sysmgmt.yaml
This increases the helm timeout value so the console-operator and console-node post-install hooks have more time to complete on large systems where there are a lot of files that need ownership and permissions changes. 
* Partly Resolves [CAST-31309](https://jira-pro.its.hpecorp.net:8443/browse/CAST-31309)
* Resolves [CASMCMS-8302](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8302)
This is a manifest only change, so it really can't be tested outside of a system upgrade.
This should be a low risk change as it only adds an option to the manifest and this option is used in other places successfully for the same purpose.
> CASMCMS-8302 - add timeout to allow more time for post-upgrade hooks to complete.

- rpm/cray/csm/sle-15sp2/index.yaml
This adds a reference to validate_csm_health.md to the output of verify_hsm_discovery.py.
* Resolves [CASMINST-5366](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5366)
For testing, see https://github.com/Cray-HPE/hpe-csm-scripts/pull/27
none
> CASMINST-5366 Bump hpe-csm-scripts version to pickup newer verify_hsm_discovery.py script

- manifests/sysmgmt.yaml
Updates the cfs-operator image to remove the high priority from cfs session pods
* Resolves CASMTRIAGE-4452
* Shandy
Ran a full system reboot
This may impact very small systems like where the original triage ticket to increase the priority was from.
> CASMTRIAGE-4452: Update cfs-operator to remove the high priority on pods

- manifests/sysmgmt.yaml
In order for tenant specific backups to work using the current wlm backup process, the wlm secret also needs to be propagated to the user namespace (in addition to slurm-operator).
* Resolves [CASMTRIAGE-4456](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4456)
```
1.6669886235564501e+09	INFO	controllers.Tenants	Ensuring secret wlm-s3-credentials exists in user namespace
1.6669886261452048e+09	INFO	controllers.Tenants	Secret wlm-s3-credentials created in user namespace
```
Tested the new operator and saw the secret propagate to user namespace.
Low
> Include user namespace in wlm secret propagation

- manifests/sysmgmt.yaml
Updated cray-hms-hmcollector chart to pickup a change to enable slingshot health event streaming telemetry.
Backwards compatible bugfix
* Resolves https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6092
* Shandy …
> CASMPET-6092: Pull in newer version of cray-hms-hmcollector chart to support Slingshot health event streaming telemetry

- manifests/sysmgmt.yaml
Updates cfs-operator to remove the high pod priority on CFS sessions.
* Resolves CASMTRIAGE-4452
* Shandy
- Ran a full system reboot and configure
This will require followup to analyze the memory usage of CFS sessions.
> CASMTRIAGE-4452: Update cfs-operator to remove high pod priority

- rpm/cray/csm/sle-15sp2/index.yaml
This change fixes a broken HSM CLI call in the make_node_groups script.
* Resolves [CASMHMS-5784](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5784).
This change was tested by running the updated CLI call and verifying that the errors previously encountered no longer occurred.
Before fix:
```
ncn-m001:~ # cray hsm state components list --type node --role management --subrole master --format json | jq
Usage: cray hsm state components list [OPTIONS]
Try 'cray hsm state components list --help' for help.
Error: Invalid value for '--type': invalid choice: node. (choose from CDU, CabinetCDU, CabinetPDU, CabinetPDUOutlet, CabinetPDUPowerConnector, CabinetPDUController, Cabinet, Chassis, ChassisBMC, CMMRectifier, CMMFpga, CEC, ComputeModule, RouterModule, NodeBMC, NodeEnclosure, …
```
> CASMHMS-5784 Fix broken HSM CLI call in make_node_groups script Main

- manifests/platform.yaml
Include slurm-operator namespace in jobs cleanup.
* Resolves [CASMTRIAGE-4501](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4501)
(tyr)
```
Checking containers in pod mycluster-slurm-config-t4rqj
Found pod mycluster-slurm-config-t4rqj with restartPolicy 'Never' and container 'istio-proxy' with status '2022-11-02T16:39:46Z'
Found pod mycluster-slurm-config-t4rqj with restartPolicy 'Never' and container 'slurm-config' with status 'Completed'
All containers of job pod mycluster-slurm-config-t4rqj has completed. Killing istio-proxy (0a6d955ea5779a324dfa07042bf5418736a5dfae601379e6beac1b26a33fbcf8) to allow job to complete
0a6d955ea5779a324dfa07042bf5418736a5dfae601379e6beac1b26a33fbcf8
```
```
C02YT3JRLVCJ:cray-drydock bklein$ helm template . | grep -A10 command
command:
- …
```
> Add slurm-operator namespace to sonar-jobs-watcher

- manifests/platform.yaml
In addition to making sure the hnc deployment is rolled out, also ensure the validating webhook is responsive.
* Resolves [CASMPET-6098](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6098)
```
kubectl logs -n hnc-system wait-for-hnc-manager-pods-8mkkf
sleeping 10 seconds to ensure the deployment rollout has begun...
Waiting for deployment "hnc-controller-manager" rollout to finish: 0 of 1 updated replicas are available...
deployment "hnc-controller-manager" successfully rolled out
sleeping 10 seconds allowing the webhook time to start...
Webhook is now responding...
```
Multiple chart installes
Low
> Ensure hnc webhook is responsive before completing chart deployment

- manifests/core-services.yaml
- manifests/platform.yaml
The current cray-dns-unbound air-gapped configuration breaks forwarding of queries to PowerDNS, the result of this is that the new DNS names such as `api.nmnlb.<system_domain>` stop working.
* Resolves [CASMNET-1939](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1939)
* `groot`
* `mug`
Chart deployed on groot (airgapped) system and DNS functionality verified.
Chart also deployed on mug in airgapped and non-airgapped mode to ensure DNS behaves as expected.
> CASMNET-1939 - Unbound forward to PowerDNS does not work in an air-gapped configuration.

- manifests/core-services.yaml
- manifests/platform.yaml
The current cray-dns-unbound air-gapped configuration breaks forwarding of queries to PowerDNS, the result of this is that the new DNS names such as `api.nmnlb.<system_domain>` stop working.
* Resolves [CASMNET-1939](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1939)
* `groot`
* `mug`
Chart deployed on groot (airgapped) system and DNS functionality verified.
Chart also deployed on mug in airgapped and non-airgapped mode to ensure DNS behaves as expected.
> CASMNET-1939 - Unbound forward to PowerDNS does not work in an air-gapped configuration

- docker/index.yaml
This only adds the cilium docker images to prepare for installing cilium during a fresh install or upgrade in the near furture.   The install and upgrade code will still only install weave currently.
This is some of the work required for CASMPET-5759.
Pulled these docker images into nexus with podman on the cilium vshasta v2 cluster.   Successfully installed cilium with these images.
None
> CASMPET-5759: Add docker images for cilium

- manifests/platform.yaml
While testing a different issue on frigg I noticed that the spire-jwks endpoint is still internal on CSM 1.3. This is supposed to use the istio ingress gateway due to a caching issue causing port exhaustion. This fixes that problem.
* Resolves  [CASMPET-6126](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6126)
* https://github.com/Cray-HPE/cray-opa/pull/70
* frigg
Validated ingress gateway worked and that the endpoint was set to the ingress gateway.
- Were continuous integration …
> CASMPET-6126 Switch jwks endpoint back to ingress gateway

- manifests/platform.yaml
Bumping up the version as part of  CVE-2020-10770 mitigation changes
Details are in the below PR,
https://github.com/Cray-HPE/cray-opa/pull/71
> CASMPET-6127: CVE-2020-10770 mitigation change

- rpm/cray/csm/sle-15sp3/index.yaml
- contains https://github.com/Cray-HPE/csm-testing/pull/414
- contains https://github.com/Cray-HPE/csm-testing/pull/418
- required by https://github.com/Cray-HPE/livecd-gcp-infrastructure/pull/174
> VSHA-503 vshasta support for csm-tests

- rpm/cray/csm/sle-15sp2/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
- Fixes: [CASMCLOUD-1214](https://jira-pro.its.hpecorp.net:8443/browse/CASMCLOUD-1214) & [CASMINST-5473](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5473)
Built against Python3.10 to keep the code current, and built with updated dependencies.
- https://github.com/Cray-HPE/manifestgen/pull/17
- https://github.com/Cray-HPE/manifestgen/pull/18
- https://github.com/Cray-HPE/manifestgen/pull/19
- https://github.com/Cray-HPE/manifestgen/pull/20
- https://github.com/Cray-HPE/manifestgen/pull/22
***NOTE*** This also changes to pull `manifestgen` (and a collection of other packages) from the SP3 repo. I'm doing this in preperation for the SP4 RPMs so I can cleanly show them changing from SP3 to SP4. This also satisfies
`manifestgen` successfully …
> CASMCLOUD-1214 & CASMINST-5473

- manifests/platform.yaml
- Update vault to 1.12.1
- Update vault-operator to 1.16.0
* Resolves [CASMPET-6151 ](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6151)
* https://github.com/Cray-HPE/cray-vault/pull/10
Adeed test data into vault. Validated that data was accessible after both upgrading and downgrading vault and the vault-operator
When vault is downgraded the …
> CASMPET-6151 Update vault and vault-operator

- rpm/cray/csm/sle-15sp3/index.yaml
Add cilium-operator-replicas, k8s-primary-cni, and kube-proxy-replacement to CSI.
> CASMPET-6145:  Bump cray-site-init to 1.28.0

- manifests/sysmgmt.yaml
Adds the capability in SCSD to enable or disable TPM in the BIOS for castle servers.
* Resolves [CASMHMS-5596](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5596)
* SCSD [PR](https://github.com/Cray-HPE/hms-scsd/pull/53)
* odin
Low risk. It enables a previously unused API on SCSD for castle servers.
> CASMHMS-5596: Update scsd to support setting TPM in BIOS

- CHANGELOG.md
- assets.sh
We were missing changes from recent PR's because the node-images pipeline wasn't building / promoting images correctly. That will be resolved in an upcoming PR to node-images. The images in 0.4.29 were built from HEAD of main without any changes, we just needed to built all of pre-install-toolkit, kubernetes, storage-ceph.
Related to: https://jira-pro.its.hpecorp.net:8443/browse/MTL-2036
* redbull
Images were booted on redbull. Jeanne O. and Brad K. too a look to confirm that their desired changes were in place.
No known risks.
> MTL-2036 & CASMPET-6124: NCN assets

- manifests/platform.yaml
vault 1.12.1 does not work on fresh installs with the latest bank-vaults. We'll need to use 1.10.8 instead. This version is still supported by hashicorp.
* Resolves [CASMINST-5623](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5623)
* https://github.com/Cray-HPE/cray-vault/pull/11
* drax
* 
Validated vault came up properly.
- Was upgrade tested? If not, why? n, already done in previous testing
- Was downgrade tested? If not, why? n, already done in previous testing
- Were new tests (or test issues/Jiras) created for this change? n
> CASMINST-5623 Downgrade vault to 1.10.8

- build/images/extract.sh
We're going to enable authentication on `csm-helm-charts`. In preparation to this, we'll start configuring credentials for this repo in csm build.
* Required by  [CASMINST-5441](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5441)
* Jenkins
* Tested image list generator locally by switching to dev artifactory instance, which does require authentication
* Tested image list generator locally by connecting to main artifactory instance - it does not require authentication yet, but if credentials are provided, they must be correct. Tested all 3 scenarios (no creds, incorrect creds, correct creds).
* Jenkins build produces list of images successfully.
Low - easy to rollback.
> CASMINST-5441 Use authentication for csm-helm-charts [main]

- build/images/extract.sh
We're going to enable authentication on `csm-helm-charts`. In preparation to this, we'll start configuring credentials for this repo in csm build.
* Required by  [CASMINST-5441](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5441)
* Jenkins
* Tested image list generator locally by switching to dev artifactory instance, which does require authentication
* Tested image list generator locally by connecting to main artifactory instance - it does not require authentication yet, but if credentials are provided, they must be correct. Tested all 3 scenarios (no creds, incorrect creds, correct creds).
* Jenkins build produces list of images successfully.
Low - easy to rollback.
> CASMINST-5441 Use authentication for csm-helm-charts [release/1.3]

- manifests/sysmgmt.yaml
This change updates the FAS actions test to better handle unexpected BMC states. Previously the test would fail if there was at least one BMC in HSM with an unexpected state. This case is covered by a separate HSM test, so now the FAS actions test will not fail in this scenario and only requires the minimum of one healthy BMC to run.
This change also updates the FAS CT tests to use the latest hms-test:4.0.0 image and RIE.
* Resolves CASMHMS-5840.
* Chart PR: https://github.com/Cray-HPE/hms-firmware-action-charts/pull/18
This change was tested by verifying that the FAS tests continue to pass in the runCT build environment using RIE emulated hardware. It was also tested on Frigg by upgrading FAS to the new 2.1.6 version of the chart, running the FAS CT tests, and verifying that they passed. …
> CASMHMS-5840 Update FAS actions test to improve handling of unexpected BMC states Main

- manifests/sysmgmt.yaml
This change updates the FAS actions test to better handle unexpected BMC states. Previously the test would fail if there was at least one BMC in HSM with an unexpected state. This case is covered by a separate HSM test, so now the FAS actions test will not fail in this scenario and only requires the minimum of one healthy BMC to run.
This change also updates the FAS CT tests to use the latest hms-test:4.0.0 image and RIE.
* Resolves CASMHMS-5840.
* Chart PR: https://github.com/Cray-HPE/hms-firmware-action-charts/pull/18
This change was tested by verifying that the FAS tests continue to pass in the runCT build environment using RIE emulated hardware. It was also tested on Frigg by upgrading FAS to the new 2.1.6 version of the chart, running the FAS CT tests, and verifying that they passed. …
> CASMHMS-5840 Update FAS actions test to improve handling of unexpected BMC states CSM-1.3.1

- manifests/sysmgmt.yaml
Pull in v2.23.0 version of the collector. Added a message key to kafka messages to ensure events are sent to the same Kafka partition. The message key is the BMC Xname concatenated with the Redfish Event Message ID. For example x3000c0s11b4.EventLog.1.0.PowerStatusChange. This is needed for the the telemetry-metics-filter to work properly.
* Resolves https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5824
_List the environments in which these changes …
> CASMHMS-5824: Pull in newer cary-hms-hmcollector chart

- manifests/sysmgmt.yaml
This adds error checking to the request-ncn-join-token pods. The pods will now error out if it fails 6 times (30 seconds). This should allow them to restart if the istio-proxy sidecar isn't working.
* Resolves [CASMINST-5650](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5650) 
* https://github.com/Cray-HPE/cray-spire/pull/51
* mug
- Were continuous integration tests run? If not, why? Y 
> CASMINST-5650 Bump spire to 2.11.0

- manifests/sysmgmt.yaml
Pull in v2.23.0 version of the collector. Added a message key to kafka messages to ensure events are sent to the same Kafka partition. The message key is the BMC Xname concatenated with the Redfish Event Message ID. For example x3000c0s11b4.EventLog.1.0.PowerStatusChange. This is needed for the the telemetry-metics-filter to work properly.
* Resolves https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5824
_List the environments in which these changes …
> CASMHMS-5824: Pull in newer cary-hms-hmcollector chart for CSM 1.3.1

- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp3-compute/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4-compute/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
This is a change to both BOSv1/BOA and BOSv2 that allows sessiontemplates to omit rootfs_provider and rootfs_passthrough fields. This change also updates the associated build RPMs to those corresponding to this particular build.
* Resolves [CASMCMS-8300](https://github.com/Cray-HPE/csm/pull/new/CASMCMS-8300)]
* Change will also be needed in `Release 1.3.1` of CSM manifest
* `Mug`
> CASMCMS-8300

- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp3-compute/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4-compute/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
This mod allows BOSv1 and BOSv2 sessiontemplates to skip special appending of information to boot parameters when rootfs_provider and rootfs_provider_passthrough are omitted. This allows Mercury the ability to specify their own root=<values> in the parameters itself without getting in the way of COS specific changes to these fields.
* Resolves [CASMCMS-8300](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8300)
* `mug`
The affected code was imported into an interactive interpreter and evaluated for appropriate resolution of null string fields.
> CASMCMS-8300 Backport to 1.3.1

- rpm/cray/csm/sle-15sp3/index.yaml
Modifies the `print_goss_json_results.py` tool so that in addition to what it normally does, it also generates a log file suitable for consumption by grok-exporter. 
* See [the source PR](https://github.com/Cray-HPE/csm-testing/pull/420) for more details
* Resolves [CASMINST-5677](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5677)
* This is to enable part of IUATCT [CASM-3373](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3373). 
* [csm-rpms manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/666)
Tested on frigg to ensure that the new log file is correctly generated, and the existing functionality continues to work as before.
Minor risk, because the changes were very limited in scope.
> CASMINST-5677: Generate Goss log file suitable for consumption by grok-exporter

- assets.sh
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Includes new SP4 LiveCD and SP4 NCN images, as well as several Cray packages that now include SP4 metadata.
Notable updates:
- CASMPET-6084 `cephadm` and `ceph-common` version 17.2.3
- `kernel-*` from `5.3.18-150300.59.87.1` to `5.14.21-150400.24.33.2`
- `kernel-firmware` replaced with `kernel-firmware-all`
- `libfmt7` upgraded to `libfmt8`
- `python39` replaced with `python310`, `3.10` is the newest available in SP4 and `3.9` is no longer available; Python3.6 is still the default Python (defined upstream, by SUSE)
- MTL-1810 a `kernel-mft-mlnx-kmp-default` RPM built against the 5.14.21 kernel is now available (and included in the image), enabling usage of `mst` (provided by `mft`) for managing Mellanox hardware
- MTL-2025 Inclusion of `csm-node-identity` in the tarball for COS compute …
> MTL-1708 SP4 Package updates

- rpm/cray/csm/sle-15sp3/index.yaml
This makes some small modifications to the grok-exporter logging that was added to the `print_goss_json_results.py` tool with [CASMINST-5677](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5677). The changes primarily dealt with the naming and formatting of the log file generated for grok-exporter.
* See [the source PR](https://github.com/Cray-HPE/csm-testing/pull/421) for more details
* Resolves [CASMINST-5686](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5686)
* This is to enable part of IUATCT [CASM-3373](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3373)
* [csm-rpms manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/667)
Tested on frigg to ensure that the new log file is correctly generated, and the existing functionality continues to work as before.
Minor …
> CASMINST-5686: Revisions to grok-exporter logging

- CHANGELOG.md
- manifests/sysmgmt.yaml
- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
Updates CFS so the only one ansible container is used regardless of the number of layers
Also includes changes needed for ARA log collection
* Resolves CASMCMS-8333
* Partially resolves CASMCMS-7690
* Mug
See the individual ticket PRs for test descriptions
None
> CASMCMS-8333: Update CFS to collapse layers

- CHANGELOG.md
- manifests/sysmgmt.yaml
Updates CFS so the only one ansible container is used regardless of the number of layers
* Resolves CASMCMS-8333
* Mug
See the individual ticket PRs for test descriptions
None
> CASMCMS-8333: Update CFS to collapse session layers

- manifests/sysmgmt.yaml
This PR consists of the following changes:
- Update CAPMC CT tests to use latest hms-test:4.0.0 image
- Break out CAPMC CT tests into non-disruptive, disruptive, destructive, and build-pipeline-only test buckets
- Adds many new API tests that execute in the runCT environment in the build pipeline (also able to run on live systems but need to be careful doing this for the disruptive and destructive tests)
* Resolves [CASMHMS-5468](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5468).
- Tests run in the runCT build pipeline environment in GitHub Actions for each branch push and PR.
- Also deployed and ran the non-disruptive tests on Mug and Surtur to verify that they behave as expected.
Adding many new API tests that will gate CAPMC changes if breakages occur.
> CASMHMS-5468 CAPMC/CAPMC-lite tests for HMTH

- manifests/core-services.yaml
- manifests/platform.yaml
* Upgrade PowerDNS to 4.6.4 as version 4.4.3 is EOL as of October and no longer receives security fixes.
* Create Prometheus ServiceMonitor definition to allow collection of PowerDNS metrics
* Resolves [CASMNET-1971](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1971)
* Resolves [CASMNET-1965](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1965)
* `surtur`
* `mug`
Installed build on surtur, the flood of update messages `PowerDNS Security Update Mandatory: Unsupported release (EOL)` is no longer present.
Verified that the ServiceMonitor has been created.
```bash
ncn-m001:~/cspiller # kubectl get servicemonitor -n sysmgmt-health cray-dns-powerdns-exporter
NAME                         AGE
cray-dns-powerdns-exporter   89s
```
Verified metrics are flowing into Prometheus
```bash …
```
> CASMNET-1971 - Upgrade PowerDNS to a supported release

- docker/index.yaml
- manifests/platform.yaml
manifest version bumps for iuf and cray-nls
> CASMINST-5661: manifest version bumps for iuf and cray-nls

- manifests/platform.yaml
Adding hook-delete-policy to delete the failed patch-nodeexporter-alerts job if it failed during installation.
This change is backward-compatible bugfix.
Resolves [issue id](issue link)
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5664
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5589
* `slice`
> CASMINST-5664 Prometheus error with web hook for node exporter fix

- CHANGELOG.md
- manifests/sysmgmt.yaml
Added a feature flag for the user to enable secure DKMS usage inside IMS create and customize jobs. The feature requires that Kata is installed and configured on the worker nodes of the system.
* Resolves [CASM-2374](https://jira-pro.its.hpecorp.net:8443/browse/CASM-2374)
* `Mug`
The version was installed via helm upgrade, then the DKMS flag was enabled, and jobs run to insure that dkms is working correctly and as expected in the jobs that were created. Next the flag was disabled, and I verified that the enhanced security needed to run dkms was no longer allowed in the new jobs.
- Were continuous integration tests run? If not, why? N - not covered
- Was …
> CASM-2374 - add option to IMS to enable secure DKMS usage.

- manifests/sysmgmt.yaml
There was a difference in naming between the early systems with hand-loaded sp4 repos and the final csm install so the names need to be updated in the recipes.
Code PR:
https://github.com/Cray-HPE/image-recipes/pull/37
* Resolves [CASMTRIAGE-4750](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4750)
* `Frigg`
The recipe was updated and worked correctly. This is not a service so there really isn't any upgrade/downgrade to test - it is just a new recipe install.
Very low risk - easy to …
> CASMTRIAGE-4750 - fix barebones image recipe for sp4 repos.

- rpm/cray/csm/sle-15sp4/index.yaml
The set_ssh_keys.py script has a bug in it where it does not properly set a variable and ends up skipping all BMCs other than switch controllers when setting ssh keys. This change reworks an if statement to properly set the variable in all cases.
* Resolves [CASMHMS-5689](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5689)
* `hela`
Code changes were done on hela to fix the problem. The script was then copied to the source.
- Were continuous integration tests run? If not, why? N - N/A
- Was upgrade tested? If not, why? N - Installed via RPM
- Was downgrade tested? If not, why? N - Installed via RPM
No known risks.
> CASMHMS-5689 Fix for unset variable in set_ssh_keys.py

- CHANGELOG.md
- docker/index.yaml
Update the ims-load-artifacts Docker image version to pull in the IUF implementation.
* Resolves [CASM-3718](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3718)
* `frigg`
Tested 2.0.0 version of ims-load-artifacts as part of IUF integration testing.
N/A
> CASM-3718: Update ims-load-artifacts Docker image version

- manifests/platform.yaml
Added a base chart incorrectly, and without namespace so it broke the install.  Removing altogether as the chart will be picked up by other service charts.
* Resolves [CASMTRIAGE-4755](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4755)
N/A
N/A
N/A
Low -- already broken
> Remove cray-etcd-base chart (shouldn't be in manifest anyway)

- manifests/platform.yaml
Update OPA Chart to 1.25.7 with keycloak restrictions
See for details: https://github.com/Cray-HPE/cray-opa/pull/77
> Update OPA Chart to 1.25.7 with keycloak restrictions

- manifests/sysmgmt.yaml
Update the k8s api interface used for the istio service. This will bring us up to date with the most recent version and keep us from having depreciation problems as k8s is upgraded.
* Resolves [CASMCMS-8347](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8347)
* `Surtur`
I upgraded the image being used on surtur and verified that jobs started correctly and the istio connections are created successfully.
This is a low risk change as it upgrades the interface version but there are no …
> CASMCMS-8347 - update istio api version for k8s 1.22 deprecation.

- docker/index.yaml
Update these two images in nexus:
quay.io/cilium/cilium:1.12.4
quay.io/cilium/operator-generic:1.12.4
Add these three images to nexus to be able to run the cilium connectivity tests
quay.io/cilium/alpine-curl:v1.6.0
quay.io/cilium/json-mock:v1.3.3
docker.io/coredns/coredns:1.10.0
* Resolves [[CASMPET-6152](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6152)]
* Merge with/before/after https://github.com/Cray-HPE/node-images/pull/591
* Virtual Shasta - cilium cluster
Deployed cilium with multus.  Deployed a subset of platform charts.  Verified that pods got an IP and could reach each other.   Ran connectivity tests.
> CASMPET-6152:  Update cilium docker images

- manifests/sysmgmt.yaml
New CSM base images have a new kernel which only supports compressed kernel modules as installed. When tftpd's replicaset does a modprobe on necessary kernel modules to get tftpd working, it fails because the version of modprobe within the injection container does not understand compressed kernel modules.
In order to get around this, the replicaset modprobe container was changed to the unified tftpd pod because they were both based on alpine:3. This image is slightly modified to pull in a new version of kmod tools that are compatible with the compressed kernel modules provided.
* Resolves [CASMTRIAGE-4761](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4763)
There may be other products that have similar problems and mismatches as a function of the …
> CASMTRIAGE-4761: Update tftpd deployments to use unified kmod import image

- manifests/core-services.yaml
This change updates the HSM CT tests to use the latest hms-test:4.0.0 image and RIE for HMTH.
* Resolves CASMHMS-5858.
This change was tested by deploying the updated HSM Helm chart on Mug, running the CT tests, and verifying that they passed.
Was a Downgrade tested? Y
Low risk, pulls in new testing infrastructure for HMTH.
> CASMHMS-5858 HSM chart to v4.0.1 for HMTH changes

- manifests/platform.yaml
Prometheus alerts expression fix for POD CPU usage.
Resolves [CASMTRIAGE-4770](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4770)
* `mug`
Changes tested and successfully verified.
> CASMTRIAGE-4770: Prometheus alerts expression fix for POD CPU usage

- manifests/core-services.yaml
Update the cray-smd chart to 4.0.2 for CASMTRIAGE-4744 to fix HSN NIC discovery.
* Resolves [CASMTRIAGE-4744](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4744)
For testing, see https://github.com/Cray-HPE/hms-smd/pull/94
Low
> CASMTRIAGE-4744: Fix HSN NIC Discovery in HSM

- manifests/platform.yaml
Master - CASMPET-6097: Adjust NCN "Memory/Cpu Usage Warning" Too High down from 85% to 80%.
Merge pull request #90 from Cray-HPE/CASMPET-6097
CASMPET-6097
> Master - CASMPET-6097: Adjust NCN "Memory/Cpu Usage Warning" Too High down from 85% to 80%.

- install.sh
This creates `modprobe.d` and `modules-load.d` configuration files that will persist the kernel module fix across reboots. After creating the files this code also restarts the `systemd-load-modules.service` daemon to load the changes and apply them to the current boot session.
> CASMTRIAGE-4693 Persist WAR on reboots

- manifests/core-services.yaml
Update the cray-smd image override to 1.58.2 for CASMTRIAGE-4744 to fix HSN NIC discovery.
* Resolves [CASMTRIAGE-4744](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4744)
For testing, see https://github.com/Cray-HPE/hms-smd/pull/94
Low
> CASMTRIAGE-4744: Fix HSN NIC Discovery in HSM CSM 1.3

- manifests/platform.yaml
Remove opa-gatekeeper for fresh installs.
> CASMSEC-374: Remove opa-gatekeeper for fresh installs

- assets.sh
> CASMTRIAGE-4762: align pip/python3 versions to expected default

- manifests/core-services.yaml
This updates the cray-smd chart to v5.0.0 for removing the v1 APIs from HSM
* Resolves [CASMHMS-5626](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5626)
For testing, see https://github.com/Cray-HPE/hms-smd/pull/96
Low. Everything using HSM directly has been migrated to use the v2 APIs
> CASMHMS-5626: Remove HSM v1 APIs

- manifests/platform.yaml
Bumping up the version for jira "CASMSEC-374: Remove opa-gatekeeper for fresh installs" changes
Reference:
Gatekeeper code removed in https://github.com/Cray-HPE/cray-drydock/pull/31 PR
and updated the chart version in https://github.com/Cray-HPE/cray-drydock/pull/32 PR
> Casmsec-374: Chart version increment for gatekeeper code removing

- manifests/sysmgmt.yaml
Pulls in the cfs-operator change to fix loading of the configurable memory limits for the containers in cfs sessions.
* Resolves CASMCMS-8374
* Wasp
- Successfully ran sessions with the new operator
None
> CASMCMS-8374: Update cfs-operator for fixed session memory limits

- CHANGELOG.md
- manifests/platform.yaml
Pulls in the latest upstream zalando postgres operator into the cray-postgres-operator chart
Updating cray-postgres-operator to the latest upstream postgres operator v1.8.2
This also pulls in newer locally built images for
* spilo-14:2.1-p7
* logical-backup:v1.8.2
* pgbouncer:master-22
* Resolves [CASMINST-5476](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5476)
* Merge with `https://github.com/Cray-HPE/cray-psp/pull/8`
Validated install os upstream cray-postgres-operator which pull in upstream postgres-operator and psql v14
* …
> CASMINST-5476-1.6 : Upgrade to latest zalando postres operator

- manifests/core-services.yaml
- manifests/platform.yaml
During investigation of a customer issue it was observed that Prometheus metrics for Unbound DNS are missing.
The unbound-telemetry process included in the image was not working correctly.
The unbound-telemetry exporter is EOL and the GitHub repo was archived in November with a recommendation to use the letsencrypt unbound exporter instead. 
The unbound-telemetry exporter also contains a security vulnerability (CVE-2020-26235) which will not be patched now the project has been archived.
As the letsencrypt exporter exists in the Alpine Linux edge package repo this PR removes unbound-telemetry and adds the new exporter.
A followup ticket to CASMMON will be required to overhaul the dashboard due to changes in the available metrics.
* Resolves …
> CASMNET-2001 - Unbound metrics missing from Prometheus

- manifests/core-services.yaml
This updates the cray-smd chart to v5.0.0 for removing the v1 APIs from HSM
* Resolves [CASMHMS-5626](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5626)
For testing, see https://github.com/Cray-HPE/hms-smd/pull/96
Low. Everything using HSM directly has been migrated to use the v2 APIs
> CASMHMS-5626: Remove HSM v1 APIs CSM 1.4

- docker/index.yaml
- helm/index.yaml
- manifests/sysmgmt.yaml
This adds PCS to the CSM manifest and deploys the CAPMC shim that calls PCS under the covers.
This also pulls the chart and image for full version of CAPMC into the install but doesn't deploy it.
* Resolves [CASMHMS-5737](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5737)
For testing, see:
PCS - https://github.com/Cray-HPE/hms-power-control/pull/22
CAPMC shim - https://github.com/Cray-HPE/hms-capmc/pull/78
* Shandy
PCS is replacing much of the functionality of CAPMC. Should problems arise from PCS, the CAPMC chart and image is also included in the install for backup.
> CASMHMS-5737: Add PCS to the CSM 1.4 manifest

- docker/index.yaml
- helm/index.yaml
- manifests/sysmgmt.yaml
This adds PCS to the CSM manifest and deploys the CAPMC shim that calls PCS under the covers.
This also pulls the chart and image for full version of CAPMC into the install but doesn't deploy it.
* Resolves [CASMHMS-5737](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5737)
For testing, see:
PCS - https://github.com/Cray-HPE/hms-power-control/pull/22
CAPMC shim - https://github.com/Cray-HPE/hms-capmc/pull/78
* Shandy
PCS is replacing much of the functionality of CAPMC. Should problems arise from PCS, the CAPMC chart and image is also included in the install for backup.
> CASMHMS-5737: Add PCS to the CSM manifest

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4/index.yaml
In csm-testing, print_goss_json_results was logging test duration in seconds using scientific notation (this was happening implicitly, by the Python JSON module). This was unable to be consumed by the grok exporter tool being used to collect the Goss test logs. This PR changes things so that scientific notation is not used. It also fixes a few minor bugs in error paths of print_goss_json_results .
* Resolves [CASMINST-5793](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5793)
* [1.4 source PR](https://github.com/Cray-HPE/csm-testing/pull/427)
* [main source PR](https://github.com/Cray-HPE/csm-testing/pull/428)
* [main csm manifest PR](https://github.com/Cray-HPE/csm/pull/1634)
* [1.4 csm-rpms manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/697)
* [main csm-rpms manifest …
> CASMINST-5793: csm-testing: Log test duration in decimal without scientific notation

- CHANGELOG.md
- manifests/sysmgmt.yaml
- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
Adds cfs-ara to the manifest.  cfs-operator has already been updated to push data to ARA.
* Resolves CASMCMS-7690/CASMTRIAGE-4761
* Mug/Surtur
Deployed chart, ran CFS sessions and verified that ARA was collecting the data.
None
> CASMCMS-7690: Add cfs-ara to the manifest (1.4)

- manifests/platform.yaml
Later changes/builds of the unreleased etcd operator break backup/restore, reverting to working version.  Further engineering effort going into bitnami etcd helm chart.
* Resolves [CASMPET-6122](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6122)
Tested backup/restore on mug with 0.17.3 and worked.
* `mug`
Backed up and restored cray-uas-mgr.
Low
> Downgrade etcd operator to functional version

- manifests/sysmgmt.yaml
This adds new paths to allow the migration of spire-agent binaries from /usr/bin to /opt/cray/cray-spire.
* Resolves [CASMPET-6193](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6193)
* https://github.com/Cray-HPE/cray-spire/pull/56
These changes were cherry picked from the master branch.
This needs additional testing on bare metal machines to validate that the changes work with SKERN changes.
> CASMPET-6193 Bump spire to 2.12.0

- Jenkinsfile.github
- assets.sh
- build/images/inspect.sh
- build/images/sync.sh
- hack/verify-rpm-index.sh
Changes to allow CSM build scripts to authenticate with Algol60 artifactory
* Resolves [CASMINST-5741](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5741)
Tested locally and in the Jenkins pipeline
No known risks
> plumb credentials to verify rpms, skopeo calls

- CHANGELOG.md
- manifests/sysmgmt.yaml
- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
Adds cfs-ara to the manifest.  cfs-operator has already been updated to push data to ARA.
* Resolves CASMCMS-7690/CASMTRIAGE-4761
* Mug/Surtur
Deployed chart, ran CFS sessions and verified that ARA was collecting the data.
None
> CASMCMS-7690: Add cfs-ara to the manifest

- docker/index.yaml
- manifests/sysmgmt.yaml
- upgrade.sh
We are removing the hms-trs-operator and trs-worker. The trs-operator feature is not used by anything. Also, trs operator uses deprecated k8s APIs, which is another reason to remove it.
* Resolves [CASMHMS-5854](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5854)
- mug 
Removed the trs-operator and verified that some hms projects that use trs still work.
The risk is that this will break the next install or upgrade. If there are errors they should be caught in the first install and upgrade tests, and will not make it onto a customer system.
> Removed trs operator

- docker/index.yaml
- lib/setup-nexus.sh
This version of SAT is required by IUF.
This version of SAT is required by IUF. This change is backwards-compatible and low risk.
CRAYSAT-1651
I tested this container image on #frigg by running `sat status` and `sat showrev`.
This is a low-risk change as this version of SAT is fully compatible with the previous version.
> CRAYSAT-1651: Add SAT 3.20.0 to CSM 1.6

- docker/index.yaml
The following images need to be present in Nexus for IUF to be functional.
This commit adds two new container images to the CSM manifest.
* Resolves CASM-3710 and CASM-3758
Tested by building CSM.
This should be relatively low risk as it is adding new images but not changing versions of any existing images.
> CASM-3758, CASM-3710: (IUF) Add images needed by IUF to CSM

- CHANGELOG.md
- docker/index.yaml
Adding cf-gitea-import 1.8.0 to 1.4 docker index.yaml
* Resolves [CASMINST-5816](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5816)
* `Frigg`
> CASMINST-5816: cf-gitea-import 1.8.0 to 1.4 release

- manifests/core-services.yaml
Pull in new version of REDS that does not depend on ETCD anymore.
* Resolves [CASMHMS-5872](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5872)
* Mug …
> CASMHMS-5872 Pull in new version of REDS that does not depend on ETCD

- .github/workflows/backport.yaml
Enables [backport-command](https://github.com/Cray-HPE/backport-command-action) workflow on csm repo. For any existing PR (open or closed), add a comment `/backport target-branch` and this workflow will create a new PR, which backports original PR to `target-branch`.
No testing can be done until workflow is added to main branch.
Low - adds workflow, which is invoked on pr comment only. If it breaks, it may only generate additional comments to the PR.
> CASMINST-5830 Enable backport-command on csm repo

- manifests/sysmgmt.yaml
Update the PCS chart for CASMINST-5823 to fix PCS ETCD image dependency.
* Resolves [CASMINST-5823](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5823)
For testing, see https://github.com/Cray-HPE/hms-power-control-charts/pull/8
Low
> CASMINST-5823: Fix PCS ETCD image dependency CSM 1.4

- manifests/sysmgmt.yaml
Update the PCS chart for CASMINST-5823 to fix PCS ETCD image dependency.
* Resolves [CASMINST-5823](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5823)
For testing, see https://github.com/Cray-HPE/hms-power-control-charts/pull/8
Low
> CASMINST-5823: Fix PCS ETCD image dependency

- assets.sh
The tarball requires the `.packages` file to exist for the PIT ISO so it can include all the dependent packages.
Relates to: #1676
> CASMREL-1340 Add `.packages` file back for the ISO

- assets.sh
The tarball requires the `.packages` file to exist for the PIT ISO so it can include all the dependent packages.
Relates to: #1675
> CASMREL-1340 1.4 packages

- CHANGELOG.md
- manifests/platform.yaml
This change updated the cray-keycloak chart to version 4.0.0 which updates the image to version 16.1.1 from image version 9.0.0
* Resolves [CASMPET-6079](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6079)
* Documentation changes required in [CASMPET-6232](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6232)
* Surtur for upgrade/downgrade …
> CASMPET-6079: Update keycloak to version 4.0.0

- rpm/cray/csm/sle-15sp4/index.yaml
Update `goss-testing/tests/ncn/goss-k8s-resolve-external-dns.yaml` in csm-testing to use CMN for keycloak admin access, use DNS query vs. ping for test. 
Verified RPMs were published into proper artifactory location.
See https://github.com/Cray-HPE/csm-testing/pull/429 for details.
> CASMINST-5838: Use CMN for Keycloak access, use DNS query vs. ping for test

- CHANGELOG.md
- manifests/platform.yaml
Few minor improvements - for Cheshire Cat Release
* correct old issue with helm NOTES
* fix job to include post-install
* change clusterrole and clusterrolebinding to remove extra leading "cray-"
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_ bug fix
* Resolves [CASMPET-6265](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6265)
* vshasta v2 - dorian
* Check that NOTES now give the correct command to verify cray-postgres-operator is runnning
```
pit:/tmp # helm upgrade -n services cray-postgres-operator ./cray-postgres-operator-1.8.3-20230124224850+ddd003b.tgz
Release "cray-postgres-operator" has been …
```
> CASMPET-6265 ChChat : Fix helm output for cray-postgres-operator deployment and other minor improvements

- LICENSE
- rpm/cray/csm/sle-15sp4/index.yaml
This change adds PCS to the run_hms_ct_tests.sh script so that PCS tests are executed during the HMS section of the CSM health validation steps.
* Resolves CASMHMS-5897 in Main.
* Wasp running CSM 1.4.0-beta.36
Ran the updated run_hms_ct_tests.sh script. Verified that the new PCS tests executed along with all of the other HMS tests and that the results were processed successfully. Also verified that run_hms_ct_tests.sh could execute only the PCS tests if desired.
Low risk, impacts HMS testing only.
> CASMHMS-5897 Add PCS to run_hms_ct_tests.sh script Main

- LICENSE
- rpm/cray/csm/sle-15sp4/index.yaml
This change adds PCS to the run_hms_ct_tests.sh script so that PCS tests are executed during the HMS section of the CSM health validation steps.
* Resolves CASMHMS-5897 in CSM-1.4
* Wasp running CSM 1.4.0-beta.36
Ran the updated run_hms_ct_tests.sh script. Verified that the new PCS tests executed along with all of the other HMS tests and that the results were processed successfully. Also verified that run_hms_ct_tests.sh could execute only the PCS tests if desired.
Low risk, impacts HMS testing only.
> CASMHMS-5897 Add PCS to run_hms_ct_tests.sh script CSM-1.4

- manifests/sysmgmt.yaml
Pulls in an updated cfs-operator that increases the memory limit and improves recovery after the pod goes down.
* Resolves CASMCMS-8384
* Resolves CASMCMS-8385
* Mug
Tested stressing the cfs-operator by scaling it down, creating a backlog of events and then scaling it back up.
None
> CASMCMS-8385: Update cfs-operator for memory limit fix (1.4)

- manifests/sysmgmt.yaml
Pulls in an updated cfs-operator that increases the memory limit and improves recovery after the pod goes down.
* Resolves CASMCMS-8384
* Resolves CASMCMS-8385
* Mug
Tested stressing the cfs-operator by scaling it down, creating a backlog of events and then scaling it back up.
None
> CASMCMS-8385: Update cfs-operator for memory limit fix

- manifests/sysmgmt.yaml
CASMCMS-8353: Artifactory authentication
I am adding authentication to Artifactory. Mostly, it takes the
form of adding credentials to the Jenkinsfile.github, so our
automatic versioning tool cms-meta-tools can authenicate itself.
For a few additions, it helps pip authenticate straight to Artifactory.
* Resolves CASMCMS-8353
* The. build system
Everything builds.
- Were continuous integration tests run? If not, why? No.
- Was upgrade tested? If not, why? No.
- Was downgrade tested? If not, why? No.
- Were new tests (or …
> Casmcms 8353

- manifests/sysmgmt.yaml
The latest version of the spire-agent RPM locks down the /var/lib/spire/conf directory, breaking the request-ncn-join-token pod. This fixes the issue, allowing NCNs to be joined to spire.
* Resolves [CASMTRIAGE-4857](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4857)
* https://github.com/Cray-HPE/cray-spire/pull/57
* fanta
validated new chart fixed the issue and that NCNs were properly joined to spire.
> CASMTRIAGE-4857 Bump spire to 2.21.1

- CHANGELOG.md
- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
(cherry picked from commit 253b539e02de0123ae4742ed030eac004106fd8a)
Main backport of https://github.com/Cray-HPE/csm/pull/1680
> CASMCMS-8380: Minor language and formatting corrections to CFS Cray CLI

- CHANGELOG.md
- manifests/platform.yaml
Adds "delete pods" to rbac for the cray-postgres-operator-jobs serviceAccount used to inject secrets.
Also removed "hook-succeeded", added TTL of 24hr and removed ">/dev/null >2&1" to provide more info.
* Resolves [CASMPET-6280](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6280)
* vshasta v2 - dorian
* Verified that the job succeeded
```
Inject postgres-backup-s3-credentials secret into operatorconfiguration...
operatorconfiguration.acid.zalan.do/cray-postgres-operator patched
operatorconfiguration.acid.zalan.do/cray-postgres-operator patched
Restart the cray-postgres-operator...
pod "cray-postgres-operator-7b456b7449-gr52m" deleted
Delete any logical …
```
> CASMPET-6280 ChCat : Add rbac "delete pods" for cray-postgres-operator inject-secret job

- manifests/platform.yaml
_Timing dashboard for monitoring to record timing data for each stage in the install/upgrade of Shasta products._
_Changes in grok exporter configuration as goss tests logs format is changed. We do not want to use scientific notation as the calculation is wrong on Grafana. Hence, when logging test duration is changed to seconds._
_Calculation of execution time for IUF product and IUF stage using the difference of maximum and minimum of operation end and operation start respectively instead of sum in IUF timing dashboard._
_Change is a backward-compatible bugfix._
Resolves 
[CASMMON-256](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-256)
[CASM-3815](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3815)
[CASM-3816](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3816)
* `frigg`
* …
> CASMMON-256, CASM-3815 & CASM-3816  Create timing dashboard, grok-exporter config and IUF timing execution time changes.

- manifests/platform.yaml
_Timing dashboard for monitoring to record timing data for each stage in the install/upgrade of Shasta products._
_Changes in grok exporter configuration as goss tests logs format is changed. We do not want to use scientific notation as the calculation is wrong on Grafana. Hence, when logging test duration is changed to seconds._
_Calculation of execution time for IUF product and IUF stage using the difference of maximum and minimum of operation end and operation start respectively instead of sum in IUF timing dashboard._
_Change is a backward-compatible bugfix._
Resolves 
[CASMMON-256](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-256)
[CASM-3815](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3815)
[CASM-3816](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3816)
* `frigg`
* …
> CASMMON-256, CASM-3815 & CASM-3816 Create timing dashboard, grok-exporter config and IUF timing execution time changes.

- docker/index.yaml
- lib/setup-nexus.sh
Bump SAT image version to 3.21.1.
* Resolves [CRAYSAT-1661](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1661)
> CRAYSAT-1661: Bump SAT image version to 3.21.1

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4/index.yaml
Release csm-testing 1.15.29
- CASMINST-5850: Make check_static_routes.sh handle undefined RVR networks and also test MTN networks
- CASMINST-5819: Add test to check for taints on master nodes
* Resolves [CASMINST-5850](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5850)
* Resolves [CASMINST-5819](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5819)
* `baldar` and `surtur`
Ran the test on balder where there are MTN networks and no RVR networks:
```
ncn-m002:~ # /opt/cray/tests/install/ncn/scripts/check_static_routes.sh -p
---------------- Route Table ----------------
default via 10.102.98.1 dev bond0.cmn0 
10.1.0.0/16 via 10.252.0.1 dev bond0.nmn0 
10.32.0.0/12 dev weave proto kernel scope link src 10.36.0.0 …
```
> CASMINST-5850/5819: Bump csm-testing and goss-servers to 1.16.3

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4/index.yaml
Release csm-testing 1.15.29.  Make check_static_routes.sh handle undefined RVR networks and also test MTN networks
* Resolves [CASMINST-5850](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5850)
* `baldar` and `surtur`
Ran the test on balder where there are MTN networks and no RVR networks:
```
ncn-m002:~ # /opt/cray/tests/install/ncn/scripts/check_static_routes.sh -p
---------------- Route Table ----------------
default via 10.102.98.1 dev bond0.cmn0 
10.1.0.0/16 via 10.252.0.1 dev bond0.nmn0 
10.32.0.0/12 dev weave proto kernel scope link src 10.36.0.0 
10.88.0.0/16 dev cni-podman0 proto kernel scope link src 10.88.0.1 linkdown 
10.92.100.0/24 via 10.252.0.1 dev bond0.nmn0 
10.94.100.0/24 via 10.254.0.1 dev bond0.hmn0 
10.100.0.0/22 via 10.252.0.1 dev bond0.nmn0 
10.102.98.0/25 …
```
> CASMINST-5850:  Bump csm-testing and goss-servers to 1.15.29

- docker/index.yaml
There are critical and high CVEs currently in the cilium/json-mock:v1.3.3 image.  That is the most recent tag for that image currently.   This image is only needed for running the connectivity test.   Since we are not turning on cilium support in 1.4, it is not needed.   Removing it from the build and we will watch for fixes for those CVEs.
* Resolves [CASMPET-6238](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6238)
Testing not needed for this removal.  This image is not being used currently because cilium is not enabled in 1.4.
> CASMPET-6238: Remove the cilium/json-mock container image for now

- manifests/sysmgmt.yaml
When the sysmgmt.yaml manifests were edited in [CASMCMS-8353](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8353), the `namespace` field was accidentally removed from the `cray-console-data` entry. This PR restores it (and also fixes a few other small formatting issues that may or may not have caused problem for CSM installs, but definitely broke Python YAML's ability to load the file).
* Resolves [CASMTRIAGE-4866](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4866) and [CASMINST-5871](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5871)
* Caused accidentally by [CASMCMS-8353](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8353)
* [main backport PR](https://github.com/Cray-HPE/csm/pull/1720) -- I verified that this is needed for main but not needed for …
> CASMTRIAGE-4866: Restore 'namespace' field to cray-console-data chart manifest entry

- CHANGELOG.md
- upgrade.sh
Modify the upgrade script so that it removes the cray-crus chart, if it is installed.
* Part of the [CRUS removal](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8396) epic.
Manually tested the removal on mug.
Low risk.
> CASMINST-5875: Remove CRUS during upgrade to CSM 1.6

- CHANGELOG.md
- docker/index.yaml
Bumping container to 1.8.1 to account for IUF logging.
Backwards compatible.
* Resolves [CASMINST-5866](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5866)
* `frigg`
> CASMINST-5866: Bumping cf-gitea-import to 1.8.1

- CHANGELOG.md
- docker/index.yaml
Backport PR from release/1.4 to main
* Resolves [CASMINST-5866](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5866)
> CASMINST-5866: Backport 1.4 Bumping cf-gitea-import to 1.8.1

- manifests/platform.yaml
Version 1.4.47 of cray-nls uses the updated cray-nls container image which includes the latest sat-general template using SAT 3.21.1, the version currently needed by IUF.
CRAYSAT-1666
Test Description: verified helm chart has been published.
This is a low-risk manifest change, the contents of which have already been tested.
> CRAYSAT-1666: (IUF) Update version of cray-nls

- CHANGELOG.md
- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
* Removes CRUS from the charts manifest
* Update Goss tests to version modified to handle removed CRUS service.
* Update to cmsdev tool which does not include the CRUS service tests.
* Part of the [CRUS removal](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8396) epic.
* [csm-rpms PR](https://github.com/Cray-HPE/csm-rpms/pull/728)
Low risk.
> CASMCMS-8398/CASMINST-5874/CASMCMS-8397: CRUS removal

- rpm/cray/csm/sle-15sp4/index.yaml
Goss Test Update for `goss-k8s-resolve-external-dns.yaml`. 
Update load-balancer ingress path to use for Keycloak interaction, given the master realm admin auth is being requested. This as the CMN LB, specifically the auth.cmn.* ingress paths are now supported for master realm administration.
Use a DNS A record query instead of ping, this to address CAST-31571 as a tangent.
This should be backward compatible with all releases that included CMN.
* Resolves [CASMINST-5845](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5845)
* Merge After: https://github.com/Cray-HPE/csm/pull/1734
* [sm-testing PR ](https://github.com/Cray-HPE/csm-testing/pull/430)](https://github.com/Cray-HPE/csm-testing/pull/430)
* wasp running 1.4.0-beta.36, was forward ported from CSM 1.3.1 to 1.4.0, and main
> CASMINST-5845: Goss Test - use CMN for keycloak admin access, use DNS query vs. ping

- CHANGELOG.md
- manifests/platform.yaml
Modify cray-keycloak :
* Enable the postgres-operator based logical backups to backup the cray-keycloak postgres cluster
* Remove the postgresql-backup CR that was used previously (home-grown postgresql backup solution)
* Add a post-upgrade helm hook job to remove the old cronjob that was created as part of the previous home-grown postgresql backup solution.
Without this change, the cray-keycloak postgresql backups would fails with the latest upgrade of the cray-postgres-operator - since it assumed psql v12 and with the upgraded postgres operator, psql v14 is used.
* Resolves [CASMPET-6228](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6228)
* Merge …
> CASMPET-6228 ChCat : Update cray-keycloak to support cray-postgres-operator:1.8x changes

- CHANGELOG.md
- manifests/velero-1.7-upgrade.yaml
This updates the cray-velero chart in the jump manifest to 1.7.1-1 which changes where the kubectl docker image is. 
* Resolves [CASMPET-5779](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5779)
* Resolves [CASMPET-6237](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6237)
- Was upgrade …
> CASMPET-5779: Update velero jump manifest

- manifests/sysmgmt.yaml
This change updates the non-disruptive PCS CT tests for issues encountered in production environments vs. the runCT simulated environments in the build pipeline. The power-status test now avoids running against the CAN node since it has no ComponentEndpoint which is required to retrieve power-status. It also moves the power-status test cases for Chassis and ChassisBMC to the build pipeline bucket since these components aren't always guaranteed to be present in HSM in production environments.
* Resolves CASMINST-5879 in CSM-1.4
This change was tested by running the updated tests in the build pipeline, verifying that they passed, and that the Chassis and ChassisBMC power-status tests executed in the new test stage.
Low risk.
> CASMINST-5879 PCS CT test updates for production systems CSM-1.4

- manifests/sysmgmt.yaml
This change updates the non-disruptive PCS CT tests for issues encountered in production environments vs. the runCT simulated environments in the build pipeline. The power-status test now avoids running against the CAN node since it has no ComponentEndpoint which is required to retrieve power-status. It also moves the power-status test cases for Chassis and ChassisBMC to the build pipeline bucket since these components aren't always guaranteed to be present in HSM in production environments.
* Resolves CASMINST-5879 in Main
This change was tested by running the updated tests in the build pipeline, verifying that they passed, and that the Chassis and ChassisBMC power-status tests executed in the new test stage.
Low risk.
> CASMINST-5879 PCS CT test updates for production systems Main

- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
Updates the craycli to include the BOS clear-state option.  Also pulls in some linting changes.
* Resolves CASMCMS-8301
See craycli PRs for testing info
None
> CASMCMS-8301: Update craycli to 0.68.0 for new BOS fields (1.4)

- manifests/sysmgmt.yaml
- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
CASMHMS-5911: Pull in newer cray-hms-hmcollector chart that adds `hmcollector.hmnlb.$SYSTEM_NAME.$SITE_DOMAIN` to the list of hosts for the collectors virtual service.
Also updated customizations.yaml to pass the value hmcollector_external_hostname to the collector helm chart to pass system specific hostname
* Resolves [CASMHMS-5911](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5911)
_List the environments in which these …
> CASMHMS-5911: Pull in newer cray-hms-hmcollector chart that adds

- manifests/sysmgmt.yaml
- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
CASMHMS-5911: Pull in newer cray-hms-hmcollector chart that adds `hmcollector.hmnlb.$SYSTEM_NAME.$SITE_DOMAIN` to the list of hosts for the collectors virtual service.
Also updated customizations.yaml to pass the value hmcollector_external_hostname to the collector helm chart to pass system specific hostname
* Resolves [CASMHMS-5911](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5911)
_List the environments in which these …
> (CSM 1.4) CASMHMS-5911: Pull in newer cray-hms-hmcollector chart

- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
Reverts Cray-HPE/csm#1759
Reverting due to pending image builds for CASMREL-1358
> Revert "CASMCMS-8301: Update craycli to 0.68.0 for new BOS fields (1.4)"

- docker/index.yaml
- manifests/platform.yaml
- Fixes: https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5862
```
ncn-m001:~ # kubectl get po -n kube-system kube-multus-ds-rq822 -o yaml | grep image.*cni*
image: artifactory.algol60.net/csm-docker/stable/ghcr.io/k8snetworkplumbingwg/multus-cni:v3.9.3
image: artifactory.algol60.net/csm-docker/stable/ghcr.io/k8snetworkplumbingwg/multus-cni:v3.9.3
image: artifactory.algol60.net/csm-docker/stable/ghcr.io/k8snetworkplumbingwg/multus-cni:v3.9.3
```
```
ncn-m001:~ # kubectl get po -A | grep multus
kube-system   kube-multus-ds-b69n8               1/1     Running   0          13m
kube-system   kube-multus-ds-c522m               1/1     Running   0          13m
kube-system   kube-multus-ds-csx4j               1/1     Running   0          13m
kube-system   kube-multus-ds-rq822 …
```
> Bring in latest multus image for CVE remediation

- docker/index.yaml
This commit updates the version of cray-nexus-setup from 0.9.0 to 0.9.1 to include bug fixes required for IUF.
CASM-3859
Tested the image independently and verified the stable version exists
> CASM-3859: Use cray-nexus-setup 0.9.1 in IUF

- manifests/platform.yaml
Add CAs (via configmap) to `argo` namespace. 
* Resolves [CASMINST-5896](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5896)
* Future work required by [CASMINST-5898](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5898)
* Merge before 1.4 PRs associated with [CASMINST-5843](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5843) 
Tested using local operator test (makefile based). Also deployed to `Frigg` system and verified. 
* `Frigg`
* Mug (after tag and stable build)
Minimal risk. Just adds `argo` to list of namespaces to distribute CA configmap to.
> CASMINST-5896: Add CA managed configmap to argo namespace

- rpm/cray/csm/sle-15sp3/index.yaml
This new framework (https://github.com/Cray-HPE/libCSM) will be used for various things going forward.
This is very safe to pull into the tarball, including this at least gets this in place for if/when docs-csm requires installing it.
> MTL-2071 Include the new `libCSM` framework

- manifests/sysmgmt.yaml
This hook is working on a PVC that is created by the console-operator helm chart. If this chart is deployed before the operator chart, the hook will fail since that PVC isn't created yet. Do not run the hook on an install, just an upgrade since the upgrade case should have the operator already deployed hence the PVC will exist.
I also added a condition to delete the hook job when complete no matter what. The presence of the hook job can keep a handle on the PVC and not allow it to be removed when uninstalling the chart.
Code PR:
https://github.com/Cray-HPE/console-node/pull/68
* Resolves [CASMINST-5878](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5878)
* `Fanta`
I did helm install/uninstall/upgrade operations in every order I …
> CASMINST-5878 - fix cray-console-node helm hooks.

- manifests/sysmgmt.yaml
This hook is working on a PVC that is created by the console-operator helm chart. If this chart is deployed before the operator chart, the hook will fail since that PVC isn't created yet. Do not run the hook on an install, just an upgrade since the upgrade case should have the operator already deployed hence the PVC will exist.
I also added a condition to delete the hook job when complete no matter what. The presence of the hook job can keep a handle on the PVC and not allow it to be removed when uninstalling the chart.
Code PR:
https://github.com/Cray-HPE/console-node/pull/68
csm-1.4 Manifest PR:
https://github.com/Cray-HPE/csm/pull/1773
* Resolves [CASMINST-5878](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5878)
* `Fanta`
I did …
> CASMINST-5878 - fix post install hook in console-node helm chart.

- manifests/sysmgmt.yaml
The post-install hook on this corrects any wrong dir ownership and permissions on the shared PVC so it needs to run after install AND upgrade. This is the chart that creates the PVC, so this is the one that should fix the ownership and permissions. 
Code PR:
https://github.com/Cray-HPE/console-operator/pull/42
* Resolves [CASMTRIAGE-4899](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4899)
* `Fanta`
I used helm to install/uninstall this and console-node together in every combination I could think of. If node is installed first, it will wait in 'pending' until the PVC is created when operator is installed. The operator install/upgrade will create the PVC and fix the ownership and permissions of the dirs needed. If operator is installed first, it will create the PVC and node …
> CASMTRIAGE-4899 - fix console-operator post-install helm hook.

- CHANGELOG.md
- docker/index.yaml
- manifests/platform.yaml
Add changes to the versions of the cray-nls, cf-gitea-import, cf-gitea-update, and cray-ims-load-artifacts images needed for the fixes for CASMINST-5843, CASMINST-5902, and CASMINST-5876.
* Resolves [CASMINST-5843](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5843)
* Resolves [CASMINST-5902](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5902)
* Resolves [CASMINST-5876](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5876)
* `frigg`
- Tested IUF argo runs on Frigg using `deliver-product` stage with Ryan H and Jack S.
- https://argo.cmn.frigg.dev.cray.com/workflows/argo/jesse-test-6-templates-d2dl0-update-vcs-config-xxthq?tab=workflow
- https://argo.cmn.frigg.dev.cray.com/workflows/argo/jesse-test-6-templates-0wtn3-deliver-product …
> CASMINST-5843, CASMINST-5902, CASMINST-5876: Fix bugs in ims-upload, vcs-upload, and update-vcs-config IUF stages

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4/index.yaml
* Updated iuf-cli to 1.4.0 for initial release
Need to update the stable version of the iuf-cli RPM
* Resolves [SCICD-578](https://jira-pro.its.hpecorp.net:8443/browse/SCICD-578)
jenkins
- [ X] License file intact
- [X ] Target branch correct
- [ X] CHANGELOG.md updated
> SCICD-578 Update iuf-cli version for release 1.4

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4/index.yaml
Remove GBP peers goss tests from ncn-upgrde-test-worker goss suite. 
This is a temporary change. BGP peers test requires a switch password as input. We are waiting for a fix where this test pulls this information from vault. …
> CASMINST-5908 Remove GBP peers goss tests from ncn-upgrde-test-worker goss suite

- docker/index.yaml
Update ims-load-artifacts image version to support skipping existing images (requested by UAN).
Depends on https://github.com/Cray-HPE/ims-python-helper/pull/25/files getting merged and a 2.2.0 release being created.
Also needs backport to 1.4 release branch.
* Resolves [CASM-3760](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3760)
> CASM-3760: Update ims-load-artifacts image version

- docker/index.yaml
Test Description: Verified image exists.
See: CASMINST-5920, https://github.com/Cray-HPE/nexus-setup/pull/22
> CASMINST-5920: Use cray-nexus-setup version 0.9.2

- manifests/platform.yaml
Add CAs (via configmap) to `argo` namespace. 
* Resolves [CASMINST-5898](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5898)
* Merge before mainstream PRs associated with [CASMINST-5843](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5843) (actually already merged, this is then needed to fix any fresh install/upgrade to ~ 1.6/main)
* 1.4 PR for this already merged https://github.com/Cray-HPE/trustedcerts-operator/pull/12
Tested using local operator test (makefile based). Also deployed to `Frigg` system and verified. 
* `Frigg`
Minimal risk. Just adds `argo` to list of namespaces to distribute CA configmap to.
> CASMINST-5898: Add CA configmap to argo namespace

- manifests/sysmgmt.yaml
This updates the PCS chart version for CASMHMS-5887 - Fix PCS power-status to use 'unavailable' instead of 'undefined' for ManagementState.
* Resolves [CASMHMS-5887](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5887)
For testing, see https://github.com/Cray-HPE/hms-power-control/pull/27
None
> CASMHMS-5887: Fix PCS power-status ManagementState CSM 1.4

- manifests/sysmgmt.yaml
This updates the PCS chart version for CASMHMS-5887 - Fix PCS power-status to use 'unavailable' instead of 'undefined' for ManagementState.
* Resolves [CASMHMS-5887](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5887)
For testing, see https://github.com/Cray-HPE/hms-power-control/pull/27
None
> CASMHMS-5887: Fix PCS power-status ManagementState

- CHANGELOG.md
- manifests/platform.yaml
The keylcoak upgrade missed a small change in configuration that set the ldap cert. This would only affect systems with self signed certificates which we no longer have internally.
* Resolves [CASMPET-6305](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6305)
* surtur
- …
> CASMPET-6305: Update keycloak ldap configuration

- hack/list-pit-iso-rpms.sh
- release.sh
The packages list related to the pit ISO image is no longer being included in assets.sh, so these changes will generate the RPM index related to the pit ISO by directly querying the RPM database in the image itself. The resulting pit ISO RPM index is then combined with the index from the kubernetes and ceph images to create the embedded repo included in the CSM tarball.
> update pit iso RPM index generation

- manifests/sysmgmt.yaml
Updates the gitea chart to pull in a fix for reverse authentication so that users can login to the UI through keycloak.
* Resolves CASMCMS-8248
* Surtur
Successfully logged into the UI through keycloak
None
> CASMCMS-8248: Update gitea for reverse authentication fix

- docker/index.yaml
Pull in new hardware-topology-assistant to fix some bugs related to adding river cabinets.  https://github.com/Cray-HPE/hardware-topology-assistant/pull/2
* Resolves [CASMHMS-5914](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5914)
* `Mug`
_How were the changes tested and success verified? If schema changes were part of this change, how …
> (CSM 1.4) CASMHMS-5914: Pull in new hardware-topology-assistant to fix some bugs related to adding river cabinets

- docker/index.yaml
Pull in new hardware-topology-assistant to fix some bugs related to adding river cabinets.  https://github.com/Cray-HPE/hardware-topology-assistant/pull/2
* Resolves [CASMHMS-5914](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5914)
* `Mug`
_How were the changes tested and success verified? If schema changes were part of this change, how …
> (CSM 1.3.2) CASMHMS-5914: Pull in new hardware-topology-assistant to fix some bugs

- docker/index.yaml
Pull in new hardware-topology-assistant to fix some bugs related to adding river cabinets.  https://github.com/Cray-HPE/hardware-topology-assistant/pull/2
* Resolves [CASMHMS-5914](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5914)
* `Mug`
_How were the changes tested and success verified? If schema changes were part of this change, how …
> (main) CASMHMS-5914: Pull in new hardware-topology-assistant to fix some bugs

- docker/index.yaml
Update ims-load-artifacts container image version to fix small IUF bug.
* Resolves [CASMINST-5926](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5926)
* `frigg`
Tested using test harness script linked in this PR: https://github.com/Cray-HPE/ims-python-helper/pull/27
> CASMINST-5926: Update ims-load-artifacts container image version

- manifests/sysmgmt.yaml
Update the PCS chart version to change PCS to handle /v1/* URIs inside the service mesh.
* Resolves [CASMHMS-5917](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5917)
For testing, see https://github.com/Cray-HPE/hms-power-control/pull/28
None. PCS still also accepts /* URIs inside the service mesh.
> CASMHMS-5917: Fix PCS to handle /v1/* URIs inside the service mesh

- manifests/core-services.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
This change adds documentation for a new hardware-checks test stage that is separate from the rest of the HMS tests. The tests are optional and do not block CSM installs or upgrades.
* Resolves CASMHMS-5640
This change was tested in the build pipeline, as well as on Surtur by deploying the updated tests and wrapper scripts, executing various sets of tests and hardware checks, and verifying that they all passed. Testing was also completed to verify that both test and hardware-check failures were handled properly.
Low risk, impacts HMS CT testing only.
> CASMHMS-5640 Move hardware-sensitive HMS CT tests into separate stage

- CHANGELOG.md
- manifests/platform.yaml
Update version of cray-nls because of the following issues:
* [CASMINST-5938](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5938)
* [CASMINST-5851](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5851)
* [CASMPET-6312](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6312)
* Resolves: 
* [CASMINST-5938](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5938)
* [CASMINST-5851](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5851)
* [CASMPET-6312](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6312)
frigg, lemondrop
Ran IUF, did node rebuilds
No
> CASMINST-5938

- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
Remove CRUS from the Cray CLI.
* Part of the [remove CRUS from CSM 1.6 epic](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8396).
* [csm-rpms manifest PR](https://github.com/Cray-HPE/csm/pull/1754)
> CASMCMS-8399: Remove CRUS from Cray CLI

- CHANGELOG.md
- manifests/platform.yaml
Removes unused fields from IUF Product Manifest schema.
(cherry picked from commit 2231b292f8a50012e865a9104294bc2e48a8ac41)
* Resolves [CASMINST-5679](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5679)
* Merge the PR that updates the helm chart version first: https://github.com/Cray-HPE/cray-nls-charts/pull/30
See https://github.com/Cray-HPE/cray-nls/pull/158
Low risk.
See https://github.com/Cray-HPE/cray-nls/pull/158
> CASMINST-5679: Update cray-nls chart version to 1.4.55

- rpm/cray/csm/sle-15sp4/index.yaml
Fixes some errors and inconsistencies with the argument parsing of the set-bmc-ntp-dns script. Backwards compatible except for fixing previous bad behavior.
See [source PR](https://github.com/Cray-HPE/hpe-csm-scripts/pull/39) for details.
- Fixes: [CASMINST-2557](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-2557)
- [1.4 manifest PR](https://github.com/Cray-HPE/csm/pull/1826)
- [1.3 manifest PR](https://github.com/Cray-HPE/csm/pull/1827)
- [main csm-rpms manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/741)
- [1.4 csm-rpms manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/742)
- [1.3 csm-rpms manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/743)
Tested on fanta. See [source PR](https://github.com/Cray-HPE/hpe-csm-scripts/pull/39) for details.
Low risk -- no change …
> hpe-csm-scripts RPM: set-bmc-ntp-dns: Improved arg parsing

- CHANGELOG.md
- docker/index.yaml
1.0.4 fixes two release critical bugs.
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5955 Race condition for slingshot repo connections when merging branches.
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5956 git checkout was being used with incorrect flag causing branch history resets thus some files missing after merge.
* `frigg`
> CASMINST-5955-5956: Fix VCS update bugs backport

- CHANGELOG.md
- docker/index.yaml
1.0.4 fixes two release critical bugs.
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5955 Race condition for slingshot repo connections when merging branches.
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5956 git checkout was being used with incorrect flag causing branch history resets thus some files missing after merge.
* `frigg`
> CASMINST-5955-5956: Fix VCS update bugs

- manifests/sysmgmt.yaml
Install `craycli` and `cray-uai-util` through CSM CFS. Previously this was still being done in the COS kiwi recipe. All other packages from CSM had been migrated to CSM CFS (BOS, CFS, etc).
* Resolves [CASMUSER-3131]
* `baldar`
Upgraded cos-config and created a COS kiwi recipe that did not install `cray-uai-util` or `craycli`. Updated `cos-config` included the change to add these two packages during CFS.
Here are results showing the packages in a running compute (without this change), and the packages installed in the modified image
```
ncn-m001:~ # ssh x8000c0s1b0n1 rpm -qa | egrep "craycli|uai"
cray-uai-util-2.1.0-1.x86_64
craycli-0.66.0-1.x86_64
ncn-m001:~ #
ncn-m001:~ # chroot /mnt/developer/alanm/compute/squashfs-root/
ncn-m001:/ #
ncn-m001:/ # rpm -qa | egrep "craycli|uai" …
```
> CASMUSER-3131: Add craycli and cray-uai-util to csm-config

- CHANGELOG.md
- docker/index.yaml
Release critical bug fix for IUF Alice release. Small change to gracefully handle a git error while importing VCS content if folder is empty while committing.
* Resolves [CASMINST-5954](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5954)
* `frigg`
- IUF workflows through Frigg, verified log outputs and results.
> CASMINST-5954: Bumping cf-gitea-import 1.9.1

- CHANGELOG.md
- docker/index.yaml
Release critical bug fix for IUF Alice release. Small change to gracefully handle a git error while importing VCS content if folder is empty while committing.
* Resolves [CASMINST-5954](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5954)
* `frigg`
- IUF workflows through Frigg, verified log outputs and results.
> CASMINST-5954: Bumping gitea-import to 1.9.1

- upgrade.sh
Remove, Namespace, Custerroles and Rolebindings related to opa gatekeeper
```
ncn-m001:/tmp/pradeep/jan21 # ./gatekeeper.sh
Clusterroles related to Gatekeeper are present in the system.
gatekeeper-manager-role
Deleted the cluster role gatekeeper-manager-role successfully
gatekeeper-policy-manager-crd-view
Deleted the cluster role gatekeeper-policy-manager-crd-view successfully
cluster_rolebindings related to Gatekeeper are present in the system.
gatekeeper-manager-rolebinding
Deleted cluster rolebindings gatekeeper-manager-rolebinding successfully
gatekeeper-system namespace is present on the system
gatekeeper-system Active 128d
gatekeeper-system namespace deleted successfully
```
MUG
The commands which remove namespace, clusterroles, rolebindings are tested separately and they are …
> CASMSEC-383: Opa-gatekeeper namespace clean-up in the upgrade

- manifests/platform.yaml
Finally fixes [CASMINST-5851](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5851)
The previous fix didn't work on lemondrop.
I hot-patched a new fix on lemondrop and let it run for a few days. It seems the new fix that was hot-patched has not produced any duplicate workflows.
About the new fix: it tweaks the timeout value for metacontroller from 10s to 30s. This gives enough time for the first call to complete on large stages such as deliver-product.
* Resolves [CASMINST-5851](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5851)
lemondrop
Ran `IUF run` multiple times and didn't notice any duplicate workflows.
No
> CASMINST-5851

- CHANGELOG.md
- manifests/core-services.yaml
- manifests/platform.yaml
During investigation of [CAST-32143](https://jira-pro.its.hpecorp.net:8443/browse/CAST-32143) it was found that in the event of a customer DNS server blip `cray-dns-unbound` can cache a negative response for an hour.
This PR reduces the amount of time Unbound caches a negative response allowing DNS to heal quicker in the event of a customer DNS server outage.
* Resolves [CASMNET-2048](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-2048)
* `surtur`
* Customer test system
Rolled out new version and verified it behaves as expected. This change has also been soak tested on a customer TDS.
Verified `cray-dns-unbound` can be rolled back to the previous release successfully.
> CASMNET-2048 - Reduce time cray-dns-unbound caches negative responses.

- CHANGELOG.md
- manifests/core-services.yaml
- manifests/platform.yaml
During investigation of [CAST-32143](https://jira-pro.its.hpecorp.net:8443/browse/CAST-32143) it was found that in the event of a customer DNS server blip `cray-dns-unbound` can cache a negative response for an hour.
This PR reduces the amount of time Unbound caches a negative response allowing DNS to heal quicker in the event of a customer DNS server outage.
* Resolves [CASMNET-2048](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-2048)
* `surtur`
* Customer test system
Rolled out new version and verified it behaves as expected. This change has also been soak tested on a customer TDS.
Verified `cray-dns-unbound` can be rolled back to the previous release successfully.
> CASMNET-2048 Reduce time cray-dns-unbound caches negative responses.

- Jenkinsfile.github
Trigger deployment onto vShasta v2 environment named `yasha`, after successful build. Triggering happens asynchronously (no wait for completion).
* Resolves [CASMINST-5973](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5973)
* `vex`
* `yasha`
Post-build deployment and test execution was implemented and tested separately `csm-vshatsa-deploy` repo. This change only adds a trigger for already tested job.
Low - post-build activity, invoked asynchronously.
> CASMINST-5973 Establish vShasta v2 automated run post csm build [main]

- Jenkinsfile.github
Trigger deployment onto vShasta v2 environment named `vex`, after successful build. Triggering happens asynchronously (no wait for completion).
* Resolves [CASMINST-5973](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5973)
* `vex`
* `yasha`
Post-build deployment and test execution was implemented and tested separately `csm-vshatsa-deploy` repo. This change only adds a trigger for already tested job.
Low - post-build activity, invoked asynchronously.
> CASMINST-5973 Establish vShasta v2 automated run post csm build [release/1.4]

- rpm/cray/csm/sle-15sp3/index.yaml
Also include `cray-site-init` in the SP3 manifests to facilitate CSM 1.3 upgrades by not having to know the next SLES OS version ahead of an upgrade.
This way CSM 1.3 users upgrading to 1.4 or newer can simply use CSI from their own distro's repository.
Work to mitigate having this package (and others) duplicated in OS-specific repos is logged in CASMINST-5317.
> CASMTRIAGE-4824 Include `cray-site-init` for SP3

- CHANGELOG.md
- manifests/platform.yaml
This PR contains fixes for the following two issues:
* [CASMPET-6323](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6323) IUF abort taking a long time / hanging when pressing Ctrl+C
* [CASMINST-5988](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5988) BREAK/FIX: management-node-rollout breaks with "default" product containing jinja templates
Yes
* Resolves:
* [CASMPET-6323](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6323)
* [CASMINST-5988](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5988)
* Change will also be needed in docs-csm, cray-nls, …
> CASMPET-6323 and CASMINST-5988

- rpm/cray/csm/sle-15sp4/index.yaml
Just language and formatting linting of this RPM. No change in behavior.
* See [source PR](https://github.com/Cray-HPE/hpe-csm-scripts/pull/40) for details
* [csm-rpms manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/757)
* See [source PR](https://github.com/Cray-HPE/hpe-csm-scripts/pull/40) for details
Very low risk.
> CASMINST-5969: hpe-csm-scripts: Linting of minor language and formatting errors

- docker/index.yaml
- manifests/sysmgmt.yaml
- upgrade.sh
Backport of https://github.com/Cray-HPE/csm/pull/1605 
We are removing the hms-trs-operator and trs-worker. The trs-operator feature is not used by anything. Also, trs operator uses deprecated k8s APIs, which is another reason to remove it.
* Resolves [CASMHMS-5854](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5854)
- mug 
Removed the trs-operator and verified that some hms projects that use trs still work.
The risk is that this will break the next install or upgrade. If there are errors they should be caught in the first install and upgrade tests, and will not make it onto a customer system.
> CASMHMS-5854: Removed trs operator backport to CSM 1.4

- CHANGELOG.md
- manifests/platform.yaml
Updated cray-istio charts and cray-kiali chart versions to support istio 1.11.8.
* Resolves [CASM-3619](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3619)
* `surtur`
Upgraded istio to 1.11.8, and validated keycloak, kiali, grafana still works.
Low.
> CASM-3619: cray-istio and cray-kiali versions for istio 1.11.8

- CHANGELOG.md
- manifests/core-services.yaml
- manifests/platform.yaml
* Disable CoreDNS health checking of `cray-dns-unbound` so it can never be marked as down by CoreDNS.
* Enable Unbound probing of upstream DNS servers and decrease probe interval so connection to site DNS can be recovered quicker in the event of disruption.
* Resolves [CASMTRIAGE-4913](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4913), [CAST-32143](https://jira-pro.its.hpecorp.net:8443/browse/CAST-32143)
* `surtur`
Deployed chart to surtur and verified that Unbound can no longer be blocked by CoreDNS when the spine CMN uplink ports are shutdown.
Before
```
ncn-m001:~ # curl -s http://10.16.0.10:9153/metrics | grep healthch
coredns_forward_healthcheck_broken_total 5.4406385e+07 …
```
> CASMTRIAGE-4913 - Local DNS resolution fails when upstream DNS is unavailable

- manifests/sysmgmt.yaml
There was a new version of 'go' installed on the image for the build pipeline. The new 'gofmt' linter objected to a couple of the comments and forced us to change them to allow the linting step to complete happily so the build would complete.
Code PR's:
https://github.com/Cray-HPE/console-node/pull/71
https://github.com/Cray-HPE/console-data/pull/39
https://github.com/Cray-HPE/console-operator/pull/44
* Resolves [CASMCMS-8423](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8423)
* `Surtur`
Installed the new version on surtur and verified the console services work correctly.
- Was upgrade tested? If not, why? Y  …
> CASMCMS-8423 - fix linting errors due to build pipeline changes - release/1.4.

- manifests/sysmgmt.yaml
There was a new version of 'go' installed on the image for the build pipeline. The new 'gofmt' linter objected to a couple of the comments and forced us to change them to allow the linting step to complete happily so the build would complete.
Code PR's:
https://github.com/Cray-HPE/console-node/pull/71
https://github.com/Cray-HPE/console-data/pull/39
https://github.com/Cray-HPE/console-operator/pull/44
* Resolves [CASMCMS-8423](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8423)
* `Surtur`
Installed the new version on surtur and verified the console services work correctly.
- Was upgrade tested? If not, why? Y  …
> CASMCMS-8423 - fix linting errors due to build pipeline changes.

- manifests/sysmgmt.yaml
Update the csm release to 1.4 in the name of the barebones image and recipe installed with csm.
Code PR: https://github.com/Cray-HPE/image-recipes/pull/39
* Resolves [CASMTRIAGE-4950](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4950)
* `Surtur`
Installed via helm on surtur and verified the name of the image and recipe was at the correct 'csm-1.4' instead of the incorrect 'csm-1.3'.
Very low risk - just changing the name of the installed files.
> CASMTRIAGE-4950 - update the csm version of the barebones image and recipe.

- rpm/cray/csm/sle-15sp4/index.yaml
~/workspace/csm-testing(release/1.4=)$ git log --oneline v1.15.30..v1.15.32
a322e4d (HEAD -> release/1.4, tag: v1.15.32, origin/release/1.4) [Backport release/1.4] CASMTRIAGE-4994 Turn off goss-bond-members-have-links on vShasta (#443)
ea46c21 (tag: v1.15.31) CASMPET-6345 1.4 : Update goss test to handle post build and rebuild cases for worker mount usage (#440)
608b6fb CASMINST-5908-csm-1.4 - updated check_bgp_neighbors.sh to load switch admin password from vault (#437)
* Resolves [CASMTRIAGE-4994](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4994)
* Resolves [CASMPET-6345](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6345)
* Resolves [CASMINST-5908](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5908)
> CASMTRIAGE-4994 bump csm-testing to 1.15.32

- rpm/cray/csm/sle-15sp4/index.yaml
~/workspace/csm-testing(main=)$ git log --oneline v1.16.6..v1.16.8
656747f (tag: v1.16.8, origin/main, main) CASMTRIAGE-4994 Turn off goss-bond-members-have-links on vShasta (#442)
452161d (tag: v1.16.7) [Backport main] CASMPET-6345 1.4 : Update goss test to handle post build and rebuild cases for worker mount usage (#441)
* Resolves [CASMTRIAGE-4994](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4994)
* Resolves [CASMPET-6345](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6345)
> CASMTRIAGE-4994 bump csm-testing to 1.16.8

- manifests/platform.yaml
- upgrade.sh
This is an initial checkin with basic backup/restore functionality working for bitnami chart's integration with S3 and support for upgrade.
* Resolves [CASMPET-6182](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6182)
```
ncn-m001-e2e75ea1:/home/bklein # kubectl exec -it -n services $(kubectl get po -n services -l 'app.kubernetes.io/name=cray-etcd-backup' -o jsonpath={.items[0].metadata.name}) -- /bin/sh -c 'restore_from_backup cray-bos db-2023-03-01_01-00'
Scaling etcd statefulset down to zero...
statefulset.apps/cray-bos-bitnami-etcd scaled
Waiting for statefulset spec update to be observed...
waiting for statefulset rolling update to complete 0 pods at revision cray-bos-bitnami-etcd-7977d754f8...
waiting for statefulset rolling update to complete 0 pods at revision …
```
> Add support for upgrade to bitnami etcd chart from old operator

- CHANGELOG.md
- manifests/core-services.yaml
- manifests/platform.yaml
The change introduced by [CASMTRIAGE-4913](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4913) causes initial deployment to fail as Unbound isn't primed with data because cray-dns-unbound-manager hasn't run yet so queries forwarded to Unbound from CoreDNS fail.
This backs out the CoreDNS configuration change.
* Resolves [CASMNET-2070](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-2070)
* `drax`
Tested as part of the fresh install on drax, CoreDNS configuration is as expected without `max_fails 0`.
All Postgres clusters initialised correctly
```
drax-pit:~ # kubectl get postgresql -A
NAMESPACE   NAME                         TEAM                VERSION   PODS   VOLUME   CPU-REQUEST   MEMORY-REQUEST   AGE   STATUS
argo        cray-nls-postgres            cray-nls …
```
> CASMNET-2070 - CoreDNS: max_fail=0 blocks initial deployment

- manifests/platform.yaml
Will need to remove when K8S 1.22 lands, but let's keep it in longer to give etcd clusters time to convert to bitnami.
* Resolves [CASMPET-6374](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6374)
N/A
N/A
N/A
Low
> Reintroduce etcd-operator until etcd charts convert to bitnami (CASMPET-6374)

- CHANGELOG.md
- manifests/platform.yaml
This is a bug that was introduced with patching some security holes in Keycloak. The change blocked all authenticated traffic from Nexus to Keycloak for authentication of users on Nexus. The change added some more allowed endpoints for traffic with a system-nexus token. This should also be merged into main once testing has been done.
* Resolves [CASMPET-6366](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6366)
* Drax with manual change to the config map and check.
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade …
> CASMPET-6366: OPA policy change for nexus-keycloak

- lib/setup-nexus.sh
- nexus-repositories.yaml
These changes to install the "embedded" repo currently available only in the release tarball into nexus at install time.
* Resolves [CASMTRIAGE-5108](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5018)
Manually tested adding changes to nexus-requirements.yaml and lib/setup-nexus.sh by creating and executing analogous files on Groot.
* Groot
Ran a test script to create and populate the csm-1.3.1-embedded repo on Groot
- Were continuous integration tests run? No
- Was upgrade tested? No
- Was downgrade tested? No
- 
No known risks
> updates to add embedded repo to nexus at install

- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
The new `libCSM` uses a `virtualenv`, no longer installing into the system Python environment. The package still depends on `python39-base` or `python310-base` (for SP3 and SP4 respectively) to be installed.
This entailed a package name change since it is now all-inclusive, the canonical naming of `pythonXY-<name>` is only applicable to packages installing into the system Python environment.
> MTL-2076 New `libcsm`

- manifests/sysmgmt.yaml
Updates cfs-ara to fix an issue where the UI was only accessible via ip and not url.
* Resolves CASMCMS-8432
* Lemondrop
Deployed change and accessed UI
None
> CASMCMS-8432: Update cfs-ara to fix UI access (1.4)

- manifests/sysmgmt.yaml
Updates cfs-ara to fix an issue where the UI was only accessible via ip and not url.
* Resolves CASMCMS-8432
* Lemondrop
Deployed change and accessed UI
None
> CASMCMS-8432: Update cfs-ara to fix UI access

- manifests/sysmgmt.yaml
Updates csm-config to include a change to only install packages to Compute nodes during image customization and not at boot time.
* Resolves CASMTRIAGE-5003
* Surtur
Ran the update against a node to confirm the role did not run
None
> CASMTRIAGE-5003: Update csm-config for Compute package install changes

- manifests/sysmgmt.yaml
Updates csm-config to include a change to only install packages to Compute nodes during image customization and not at boot time.
* Resolves CASMTRIAGE-5003
* Surtur
Ran the update against a node to confirm the role did not run
None
> CASMTRIAGE-5003: Update csm-config for Compute package install changes (1.4)

- manifests/sysmgmt.yaml
Updates csm-config to include a change to only install packages to Compute nodes during image customization and not at boot time.
* Resolves CASMTRIAGE-5003
* Surtur
Ran the update against a node to confirm the role did not run
None
> CASMTRIAGE-5003: Update csm-config for Compute package install changes (1.3)

- manifests/core-services.yaml
- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
This change includes many additions, updates, and fixes to the HMS CT tests for the HSM, CAPMC, and PCS services.
Resolves many tickets, but primarily epic [CASMHMS-5747](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5747)
Encapsulating all of this work in one Manifest PR ticket  [CASMHMS-5940](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5940)
See:
- https://github.com/Cray-HPE/hms-smd/pull/107
- https://github.com/Cray-HPE/hms-capmc/pull/83
- https://github.com/Cray-HPE/hms-power-control/pull/29
These changes were tested with local instances of the hms-simulation-environment using the small_mountain and one_of_each_blade hardware configurations, as well as in the runCT GitHub Actions pipeline. Additionally, the HSM and CAPMC changes were verified on Surtur by deploying …
> HMS CT test updates for HSM, CAPMC, and PCS

- rpm/cray/csm/sle-15sp2/index.yaml
- Needed by: [CASMINST-6052](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6052)
Adopt new (forked from upstream and locally modified) version of goss, which now supports adding `<system-output/>` and `<system-err/>` tags in Junit output format, for goss tests of type `command`. As a result, most of the times the reason of test failure is immediately visible in Jenkins report.
New goss package was explicitly installed, tests re-ran with new package and results exported int temporary Jenkins job. results look as expected (system out is included into report).
Low - modification to test framework only.
> CASMINST-6052 Enhance goss - add stdout/stderr to junit output [main]

- rpm/cray/csm/sle-15sp3/index.yaml
- MTL-2097 Brings in a deprecation notice
- MTL-2081 Prevents `csi config init empty` from clobbering an existing `system_config.yaml`
> MTL-2097 Deprecation Notice

- lib/setup-nexus.sh
Prerequisites fails when it shouldn't matching two pods with nexus in their name.
* Resolves [[issue id](issue link)](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5038)
Found the issue on Surtur and validated the fix there as well to move past the issue for testing another issue.
* Surtur
See above
- Were …
> setup-nexus.sh: use labels to match only the nexus pod

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4/index.yaml
Need to bump the iuf-cli version to 1.4.1 for CSM 1.4
- [X ] CHANGELOG.md updated
> CASM-3985 Bump iuf-cli version to 1.4.1

- CHANGELOG.md
- manifests/platform.yaml
Update keycloak to the latest version (20.0.5), and the subchart to the newest version (2.1.1). The latest subchart changed to be called keycloakx to represent keycloak version 17+ with a change to keycloak to quarkus from wildfly. This has no effctive change to our working environments. 
* Resolves [CASMPET-2929](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-2929)
* Documentation changes required in [CASMPET-6399](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6399)
* Fanta
* Drax
* Dorian
_How were the changes tested and success verified? If schema changes were part of this change, how were those …
> CASMPET-2929: Update Keycloak version

- manifests/sysmgmt.yaml
Backport of https://github.com/Cray-HPE/csm/pull/1946
> CASMCMS-8450/CASMCMS-8460: Do not run tftp on master NCNs; tftp use correct ipxe version

- assets.sh
- release.sh
These changes support the alignment of the version of the kernel-default-debuginfo package to the KERNEL_VERSION 
in assets.sh, and append the specified kernel-default-debuginfo package to the embedded repo in release.sh
* Resolves [CASMINST-6059](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6059)
Verified the approach works in v1.4.0-beta.69
No known risks
> update variable name and comments related to kernel-default-debuginfo

- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Resolves:
- [CASMTRIAGE-5050](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5050)
- [CASMCMS-8461](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8461)
- [CASMCMS-8463](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8463)
main PR:
https://github.com/Cray-HPE/csm/pull/1949
See source PRs for details:
- https://github.com/Cray-HPE/csm-config/pull/109
- https://github.com/Cray-HPE/csm-config/pull/111
- https://github.com/Cray-HPE/ansible-execution-environment/pull/34
- https://github.com/Cray-HPE/image-recipes/pull/41
> CASMTRIAGE-5050/CASMCMS-8461/CASMCMS-8463: Update csm-config, csm-ssh-keys, and import-images

- manifests/platform.yaml
* Add DVS namespace
* Bump minor versions to be able to support patching CSM 1.3 and CSM 1.4.
* Resolves [CASMPET-6417](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6417)
* mug
- Were continuous integration tests run? If not, why? 
> CASMPET-6417 Bump cray-drydock to 2.16.0

- manifests/platform.yaml
* Add DVS namespace
* Bump minor versions to be able to support patching CSM 1.3 and CSM 1.4.
* Resolves [CASMPET-6417](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6417)
* mug
- Were continuous integration tests run? If not, why? 
> CASMPET-6417 Bump cray-drydock to 2.17.0

- manifests/sysmgmt.yaml
This adds the dvs-mqtt workloads for use with the dvs-mqtt-client.
* Resolves [CASMPET-6352](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6352)
* mug
Validated I could request a dvs-mqtt workload JWT after upgrading the spire chart and rolling the spire-server stateful set.
- Was downgrade tested? If not, why? N, no need. A downgrade will not remove entries.
> CASMPET-6352 Bump spire to 2.10.2

- manifests/sysmgmt.yaml
This adds the dvs-mqtt workloads for use with the dvs-mqtt-client.
* Resolves [CASMPET-6352](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6352)
* mug
Validated I could request a dvs-mqtt workload JWT after upgrading the spire chart and rolling the spire-server stateful set.
- Was downgrade tested? If not, why? N, no need. A downgrade will not remove entries.
> CASMPET-6352 Bump spire to 2.12.2

- manifests/platform.yaml
The daemonset-controller is not able to create the weave pod because it cannot get to kyverno to call the webhook.
Before Change
-------------
```
pit:~ # kubectl get pods -o wide -A | grep weave
kube-system      weave-net-45np9                                                   2/2     Running            0          2m21s   10.252.1.9    ncn-w003   <none>           <none>
kube-system      weave-net-67ttc                                                   2/2     Running            1          2d16h   10.252.1.8    ncn-w002   <none>           <none>
kube-system      weave-net-92tls                                                   0/2     Terminating        1          2d16h   10.252.1.11   ncn-m002   <none>           <none>
kube-system      weave-net-g9d5f …
```
> CASMPET-6398 Bump kyverno to 1.4.1

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4/index.yaml
With the latest upstream postgres-operator, we are changing from our home-grown backup solution to the logical-backup solution provided by the operator. 
This change updates the postgresql backup check - for those clusters with logical backups enabled; the test will pass unless the latest logical-backup job has failed or the logical-backup completed but no backup exists in s3.
* Resolves [CASMPET-6283](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6283)
Also pulls in changes from Mikhail for
[CASMINST-6080](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6080) & a fix for shell error checks
* …
> CASMPET-6283 1.5 : Rework postgres backup goss tests

- rpm/cray/csm/sle-15sp4/index.yaml
CASMINST-6080 - fix goss-servers configuration on PIT node.
New release `v1.15.36` was already created for `csm-testing` and `goss-servers` packages (we have 2 packages produced from single repo). Version for `csm-testing` was already bumped in manifest with https://github.com/Cray-HPE/csm/pull/1953. This PR is to align version of `goss-servers` with version of `csm-testing`.
* Resolves [CASMINST-6080](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6080)
Installed modified packages and tested that `goss-servers` systemd service can start on `pit` node.
Low - fixing testing config which was never working before.
> CASMINST-6080 Align versions of goss-servers and csm-testing

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4/index.yaml
Fixes two csm-vshasta-deploy test failures.
* goss-k8s-velero-no-failed-backups - needed to wait for backup to be deleted from k8s perspective
* k8s_postgres_clusters_have_leaders - need to update based on log changes with recent postgres changes
* Resolves 
[CASMPET-6425](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6425)
csm-vshasta-deploy test failure : k8s_postgres_clusters_have_leaders
[CASMPET-6424](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6424)
csm-vshasta-deploy test failure : goss-k8s-velero-no-failed-backups
* Merge with/before/after - This will …
> CASMPET-6424-1.5 : Fix two csm-vshasta-deploy test failures (CASMPET-6424,6425)

- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
- Modifies cmsdev tool to omit tftp file transfer subtest on master NCNs
- Updates Goss suite to run that test on worker NCNs
- [csm main backport manifest PR](https://github.com/Cray-HPE/csm/pull/1964)
- [csm-rpms 1.4 manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/780)
- [csm-rpms main backport manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/781)
- Resolves [CASMCMS-8473](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8473)
- Problem created by the change made in [CASMCMS-8450](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8450)
- Problem reported by [CASMTRIAGE-5071](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5071)
- [cmsdev test tool source PR](https://github.com/Cray-HPE/cms-tools/pull/73)
- [csm-testing Goss source …
> CASMCMS-8473: Run tftp file transger subtest on workers not masters

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4/index.yaml
This test now checks to see whether an LDAP server has been configured and does not FAIL when no LDAP server is configured.
* Resolves [CASMPET-6420](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6420)/[CAST-32467](https://jira-pro.its.hpecorp.net:8443/browse/CAST-32467)
Also includes CASMCMS-8475,CASMCMS-8475,CASMTRIAGE-5066
* Change will also be needed in `release/1.3 and release/1.4`
* Documentation changes required in [NA
* Merge with/before/after `TBD`
* groot (airgpapped)
* wasp (not airgapped)
Original test vs fixed version
* groot - air …
> CASMPET-6420 1.4 : fix test to not fail when LDAP server not configured

- CHANGELOG.md
- rpm/cray/csm/sle-15sp3/index.yaml
This test now checks to see whether an LDAP server has been configured and does not FAIL when no LDAP server is configured.
* Resolves [CASMPET-6420](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6420)/[CAST-32467](https://jira-pro.its.hpecorp.net:8443/browse/CAST-32467)
* Change will also be needed in `release/1.3 and release/1.4`
* Documentation changes required in [NA
* Merge with/before/after `TBD`
* groot (airgpapped)
* wasp (not airgapped)
Original test vs fixed version
* groot - air gapped where LDAP is not configured
```
ncn-m001:~ # …
```
> CASMPET-6420 1.3 : fix test to not fail when LDAP server not configured

- Jenkinsfile.github
Currently, a pre-release check (checking that tip of docs-csm branch has tag) is executed after image validation, at the beginning of `Release`. If it fails, it wastes ~ 10 min of already calculated and verified image indexes. Also, Slack reporting in `post` block outs meaningless message into casm_release_management channel. 
This PR makes the following changes:
1. Introduces `Pre-Release validation` stage, which is executed before regular `Validation`, but only on release event (e.g. when tag is present). This validation fails early, if docs-csm is not tagged. No need to wait for image validation to complete to learn the result.
2. Added one more validation check - we'd want post-build vShasta deployment to happen on dedicated branch (`release/1.4`, `main`, etc). This is needed to …
> Improve pre-release valiadation - add deploy branch check, fail early

- CHANGELOG.md
- manifests/core-services.yaml
- manifests/platform.yaml
Pull in new cray-postgresql subchart in order to maintain compatibility with K8s 1.22 / CSM 1.5
* Resolves [CASMNET-2079](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-2079)
* `ashton`
* Upgraded `cray-powerdns-manager` to this release and checked that cray-dns-powerdns database and service came up and was responding to DNS queries.
* Verified chart could be rolled back to previous release and continued to respond to queries.
* Uninstalled existing `cray-powerdns-manager` release then installed chart and checked cray-dns-powerdns database came up and server was populated by `cray-powerdns-manager`
> CASMNET-2079 - Update cray-dns-powerdns to pull in cray-postgresql to maintain postgres support with K8s 1.22

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4/index.yaml
This adds the goss-check-taints test.   This test runs on master nodes only and checks that the node-role.kubernetes.io/master:NoSchedule taint exists for the node on which the test is running.  This test has been added to the ncn-healthcheck-master.yaml suite to be run anytime NCN healthcheck tests are run on master nodes and it has been added to the  ncn-upgrade-tests-master.yaml suite to be run after each master node is upgraded.
* Resolves [CASMPET-6426](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6426)
* Related to [CASMTRIAGE-5049](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5049)
* `fanta`
* Virtual Shasta - `beau`
Fanta is a system where we recently found that the master taint is missing on m002.   I ran this test on both m002 where it failed and on m003 where …
> CASMPET-6426:  Release csm-testing v1.15.40

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4/index.yaml
This adds the goss-check-taints test.   This test runs on master nodes only and checks that the node-role.kubernetes.io/master:NoSchedule taint exists for the node on which the test is running.  This test has been added to the ncn-healthcheck-master.yaml suite to be run anytime NCN healthcheck tests are run on master nodes and it has been added to the  ncn-upgrade-tests-master.yaml suite to be run after each master node is upgraded.
* Resolves [CASMPET-6426](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6426)
* Related to [CASMTRIAGE-5049](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5049)
* `fanta`
* Virtual Shasta - `beau`
Fanta is a system where we recently found that the master taint is missing on m002.   I ran this test on both m002 where it failed and on m003 where …
> CASMPET-6426:  Release csm-testing v1.16.19

- CHANGELOG.md
- rpm/cray/csm/sle-15sp2/index.yaml
Update to index to pull in v1.5.1 released version of csm-utils
Update changelog: - Released csm-utils v1.5.1 for recent changes (CASMPET-5937, CASSMPET-5787)
* CASMPET-5937
* CASMPET-5787
Master - CASMPET-5937: When the ncnGetXnames.sh tool fails to obtain a token, only print unavailable
Update the ncnGetXnames tool to handle a missing TOKEN, check metal.no-wipe status via NCN bootparameters rather than bootscript. Fix bug in ncnHealthChecks handling missing TOKEN. In both ncnGetXnames and ncnHealthChecks add ssh timeout.
Tested on dorian, 1.5.0-alpha.15, 1.5.0-alpha.17.
Was a fresh Install tested? N - N/A
Was an Upgrade tested? N - N/A
Was a Downgrade tested? N - N/A
Low - well …
> Casmpet 5937 main

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4/index.yaml
Found that goss-servers doesn't have access to the HOSTNAME env at startup.   This makes sure it is set to run any tests that need to know the current hostname.
* Resolves [CASMINST-6103](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6103)
* `drax`
Tested without the change and verified that goss-servers service fails.   Tested with this change and verified that the goss-servers services is running and I was able to run the ncn-healthcheck-master endpoint.
> CASMINST-6103: Release csm-testing v1.15.41

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4/index.yaml
Found that goss-servers doesn't have access to the HOSTNAME env at startup.   This makes sure it is set to run any tests that need to know the current hostname.
* Resolves [CASMINST-6103](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6103)
* `drax`
Tested without the change and verified that goss-servers service fails.   Tested with this change and verified that the goss-servers services is running and I was able to run the ncn-healthcheck-master endpoint.
> CASMINST-6103: Release csm-testing v1.16.21

- rpm/cray/csm/sle-15sp4/index.yaml
This change adds a '-p' command line option to the HMS CT test wrapper script that will print the logs of failed test pods to stdout at the end of the test run. By default it is not enabled since we only want to print the test run summary under normal conditions during CSM installs and upgrades. We plan to enable this option in the vShasta CI/CD pipeline when executing under goss so that more debugging output can be collected when failures occur.
* Resolves CASMHMS-5944.
This change was tested on Dorian by executing different sets of HMS CT tests using the updated wrapper script and verifying that the correct pods logs were printed under various conditions.
Low risk.
> CASMHMS-5944 Add -p option to HMS CT test wrapper to print pod logs

- manifests/sysmgmt.yaml
Bumps cms-ipxe to 1.11.1 to enhance LACP capabilities in support of NMN bonding on UANs.
> Update cms-ipxe to 1.11.1 (Papaya)

- CHANGELOG.md
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Make Cray CLI's BOS command default to version v2 rather than v1.
Make Cray CLI's BOS command default to version v2
* Resolves [CASMCMS-8481](issue link)
I do not know if this RPM needs to be included in the SLES* indices used by the compute nodes.
It was present for SLES2 and SLES3, but not SLES4. I added it, but if this was a mistake, then it should be removed from all three locations.
- Were …
> CASMCMS-8481: Make Cray CLI's BOS command default to version v2

- CHANGELOG.md
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Make Cray CLI's BOS command default to version v2 rather than v1.
Make Cray CLI's BOS command default to version v2
* Resolves [CASMCMS-8481](issue link)
I do not know if this RPM needs to be included in the SLES* indices used by the compute nodes.
It was present for SLES2 and SLES3, but not SLES4. I added it, but if this was a mistake, then it should be removed from all three locations.
- Were …
> CASMCMS-8481: Make BOS V2 the default for the Cray CLI bos command

- manifests/platform.yaml
* Remove `kube-system` from Kyverno webhook inspection, this to prevent chicken-and-egg problems with `weave` pod restarts
* Increase pod resource (cpu, memory) requests and limits to avoid resource exhaustion
* Resolves [CASMPET-6398](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6398)
* Relates to [CASMSEC-385](https://jira-pro.its.hpecorp.net:8443/browse/CASMSEC-385) 
* Future work required by (will edit to add)
See https://github.com/Cray-HPE/cray-kyverno/pull/12. 
* `Fanta`
- Were …
> Prevent Kyverno and Weave Circular Dependency Issue+

- CHANGELOG.md
- manifests/platform.yaml
This fixed a change in the keycloak upstream chart that took the startup scripts and mounted them but never ran them. They have now been moved to an init container as documented in the upstream notes. The change allowed for self signed certs for ldap as well as RSA implementation to work again.
* Resolves [CASMPET-6431](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6431)
* Dorian …
> CASMPET-6431: Update keycloak for startup scripts.

- manifests/sysmgmt.yaml
Updates the BOS chart to pull in changes to use PCS, and changes to the etcd chart to use the bitnami base-chart.
* Resolves CASMCMS-8356
* Ashton
Deployed and verified BOS functionality.
None
> CASMCMS-8356: Update BOS for PCS and bitnami chart changes

- CHANGELOG.md
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
Make Cray CLI's BOS command default to version v2 rather than v1.
Make Cray CLI's BOS command default to version v2
* Resolves [CASMCMS-8481](issue link)
I do not know if this RPM needs to be included in the SLES* indices used by the compute nodes.
It was present for SLES2 and SLES3, but not SLES4. I added it, but if this was a mistake, then it should be removed from all three locations.
- Were …
> Revert "rollback craycli to v0.70" -- craycli goes to v0.71

- manifests/platform.yaml
This adds the MQTT broker to the ingress gateway and uses it to terminate TLS.
* Resolves [CASMPET-6393](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6393)
* groot
Validated certificates were added and that MQTT worked with this chart change.
> CASMPET-6393 Bump cray-istio to 1.9.0

- manifests/platform.yaml
This adds the MQTT broker to the ingress gateway and uses it to terminate TLS.
* Resolves [CASMPET-6393](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6393)
* groot
Validated certificates were added and that MQTT worked with this chart change.
> CASMPET-6393 Bump istio to 1.7.1

- manifests/sysmgmt.yaml
- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
Updates the gitea chart and customizations to use the new postgres operator and base-chart.
* Resolves CASMCMS-8457
* Dorian
Deployed changes with new customizations and verified that data was migrated and gitea was functioning
None
> CASMCMS-8457: Update gitea chart and customizations for new postgres base chart

- install.sh
- manifests/vshasta.yaml
This PR add a loftsman manifest for services that are indented to only be installed in vshasta and not baremetal CSM. The function `is_vshasta_node` is the same check that is used in our Goss tests to determine if they are running in a vshasta environment. https://github.com/Cray-HPE/csm-testing/blob/main/goss-testing/automated/run-ncn-tests.sh#L48-L56
Currently the new vshasta manifest contains the new RIE helm chart. This helm chart deploys the CSM Redfish Interface Emulator (RIE) into a CSM system. By default the RIE helm chart will add a single chassis of emulated mountain hardware to system, and have it discovered automatically by MEDS just like real …
> CASMHMS-5823: Add vshasta specific manifest to deploy RIE

- manifests/sysmgmt.yaml
This adds the cray-spire chart and moves the spire chart into maintenance mode in order to support migration from spire 0.12.2 to spire 1.5.5.
> CASMPET-6421 Add dual spire charts

- rpm/cray/csm/sle-15sp4/index.yaml
Already baked into the NCNs.
This just aligns CSM to csm-rpms for release/1.4.
> MTL-2025 catch up

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4/index.yaml
This version of the cli enhances the debugability significantly.
> CASM-4054: Bump iuf-cli version to 1.4.3

- manifests/platform.yaml
- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
CASM-3884: Upgrade Prometheus Operator to latest version
This PR includes cray-sysmgmt-health chart version bump, customizations.yaml file changes 
Upgrade script changes with respect to Prometheus-operator upgrade from 9.3.1 to 45.1.1 (latest) version is moved to docs-csm as suggested by Dennis walker - https://github.com/Cray-HPE/docs-csm/tree/main/upgrade/scripts
PR for docs-csm: [https://github.com/Cray-HPE/docs-csm/pull/3487](url)
* Resolves …
> CASM-3884: Upgrade Prometheus Operator to latest version

- manifests/sysmgmt.yaml
Updates to csm-config with a slightly modified build process. Resulting image should be identical, but it will save us confusion in the future by updating the manifest to point to this one.
Source PR:
https://github.com/Cray-HPE/csm-config/pull/114
No main PR -- this is being included as part of a different PR for main branch.
Very low risk. No change to csm-config itself.
> CASMCMS-8470: csm-config: Use artifactory authentication instead of unauthenticated mirrors

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4/index.yaml
Bump the version of iuf-cli to 1.4.4.
> CASM-4056: iuf-cli version bump

- manifests/platform.yaml
CSM 1.5 Uses a newer version of opa. We should pre-cache the newer version.
* Cloudy with a chance to resolve [CASMPET-6445](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6445)
> CASMPET-6445 Update opa pre-cache image

- rpm/cray/csm/sle-15sp4/index.yaml
This updates csm-testing RPM to v1.16.25, which includes updated tests for spire and cray-spire charts.
> CASMPET-6447 Update csm-testing to v1.16.25

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4/index.yaml
The HOSTNAME var being set in start-goss-servers.sh doesn't handle the hostname of the pit in vshasta because it is just "pit".   I removed the grep filter that was being used on the hostname.   It was only there because I borrowed the regex from run-ncn-tests.sh.   It is not necessary in this case.   This change will all the goss-servers service to not fail if the node has an unexpected hostname.
* Resolves [CASMINST-6130](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6130)
* `fanta`
* Virtual Shasta - `cilium`
On both fanta's m002 and cilium's pit node, I started the goss-servers service and made sure that there were no errors.  I also ran `curl http://ncn-m002.hmn:8997/ncn-healthcheck-master` on fanta to make sure the endpoint still works.
> CASMINST-6130: Release csm-testing v1.16.23

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4/index.yaml
The HOSTNAME var being set in start-goss-servers.sh doesn't handle the hostname of the pit in vshasta because it is just "pit".   I removed the grep filter that was being used on the hostname.   It was only there because I borrowed the regex from run-ncn-tests.sh.   It is not necessary in this case.   This change will all the goss-servers service to not fail if the node has an unexpected hostname.
* Resolves [CASMINST-6130](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6130)
* `fanta`
* Virtual Shasta - `cilium`
On both fanta's m002 and cilium's pit node, I started the goss-servers service and made sure that there were no errors.  I also ran `curl http://ncn-m002.hmn:8997/ncn-healthcheck-master` on fanta to make sure the endpoint still works.
> CASMINST-6130: Release csm-testing v1.15.42

- manifests/sysmgmt.yaml
This adds a backoff to the update-bss job and adds a 15 second timer to its curl command. This should allow it to complete properly when run from our csm test pipeline.
* Resolves [CASMPET-6447](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6447)
* drax
Generated the job template using helm template and applied it on drax with some minor modifications so it worked with the existing spire install.
- Was upgrade tested? If not, why? N, no environment available
- Was downgrade tested? If not, why? N, no environment available
Limited testing was done due to the lack of …
> CASMPET-6447 Bump cray-spire to 1.1.3

- docker/index.yaml
- lib/setup-nexus.sh
- manifests/platform.yaml
Update the cray-sat image version to 3.21.3 to update SAT's default BOS version, as well as a few small security fixes.
* Resolves [CRAYSAT-1700](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1700)
> CRAYSAT-1700: Update cray-sat image version

- manifests/platform.yaml
This adds a network policy to limit network access for the DVS namespace.
* Resolves [CASMPET-6455](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6455)
* drax
Validated that dvs pods could not access other namespaces and that the continued to function properly.
> Casmpet 6455

- manifests/platform.yaml
This adds a network policy to limit network access for the DVS namespace.
* Resolves [CASMPET-6455](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6455)
* drax
Validated that dvs pods could not access other namespaces and that the continued to function properly.
> Casmpet 6455 1.4

- manifests/platform.yaml
This adds a network policy to limit network access for the DVS namespace.
* Resolves [CASMPET-6455](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6455)
* drax
Validated that dvs pods could not access other namespaces and that the continued to function properly.
> Casmpet 6455 1.3

- manifests/platform.yaml
Address build failure due to partial annotations on chart.
> CASMPET-6455: Fixup chart build (meta) to address build issue

- manifests/sysmgmt.yaml
* csm-config 1.16.1: To facilitate adding `enable-chn.yml` into default bootprep automation files for NCNs, allow `enable-chn.yml` to be a no-op during CFS Image Customization ([CASMNET-2085](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-2085))
* csm-config 1.16.2: Modify CFS plays so that SSH keys and root passwords are set during NCN image customization. ([CASMINST-6131](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6131))
* Resolves [CASMNET-2085](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-2085)
* Resolves [CASMINST-6131](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6131)
* `lemondrop`
Tested an image build using `sat bootprep`. The additional CFS layer shows up in the image build, but it is skipped. Checked all three NCN image builds …
> CASMNET-2085: Update enable-chn.yml to noop during CFS IC; CASMINST-6131: Allow CFS to set credentials in NCN images

- CHANGELOG.md
- manifests/platform.yaml
Update cray-nls and cray-iuf to use new postgres operator.
* Resolves CASMPET-6403
* `dorian`
Upgraded cray-nls chart and made sure that both cray-nls-postgres cluster and cray-nls pod are up and running. Verified that the old db-backup cronjob is gone and the new logical-backup cronjob is present.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation …
> CASMPET-6403: update cray-nls to use new postgres operator

- docker/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
Include CANU 1.7.0 in CSM base packages.  Includes dozens of bugfixes as well as customer acceptance required changes.
- Fixes: JIRA (CASMNET-2056)
Full gamut of changes at:  https://github.com/Cray-HPE/canu/releases/tag/1.7.0
> Bump canu to 1.7.0

- install.sh
Cleanup tds script for metallb daemonset and run on new PoR systems with 4 workers.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5110
* frigg
Prior to running three workers were at 99%:
```
Resource           Requests            Limits
--------           --------            ------
cpu                43749m (68%)        596250m (931%)
memory             161364476672 (59%)  811658718464 (301%)
Resource           Requests           Limits
--------           --------           ------
cpu                41774m (65%)       609850m (952%)
memory             96787884288 (35%)  758387690752 (281%)
Resource           Requests         Limits
--------           --------         ------
cpu                4936m (7%)       71600m (111%)
memory             7817211136 (2%)  130756455680 (48%) …
```
> Updates to TDS settings and run on 4 worker node systems (CASMTRIAGE-5110)

- manifests/sysmgmt.yaml
- Fixed incorrect namespace in cray-spire networkpolicy
- Fixed /tokens path permission issues between request-ncn-join-token and spire-agent 1.5.5
- Increased the time spire-update-bss will take to attempt to update BSS and how long it keeps the job pods around.
* Resolves [CASMPET-6447](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6447)
* yasha
Validated Charts changes fixed the issue on yasha …
> CASMPET-6447 Bump cray-spire to 1.1.4

- manifests/sysmgmt.yaml
This updates the cray-power-control chart for CASMHMS-5919 - Fix PCS hardware scan hang
* Resolves [CASMHMS-5919](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5919)
For testing, see https://github.com/Cray-HPE/hms-power-control/pull/30
none
> CASMHMS-5919: Fix PCS hardware scan

- rpm/cray/csm/sle-15sp4/index.yaml
Fix logic for detecting statefulset age.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6461
* yasha
```
ncn-m002:/opt/cray/tests/install/ncn/scripts # export GOSS_BASE=/opt/cray/tests/install/ncn; goss -g /opt/cray/tests/install/ncn/tests/goss-k8s-etcd-backups.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate
..
Total Duration: 0.582s
```
Low
* Nothing
> Fix logic for etcd backup test (CASMPET-6461) (superseded by #2046)

- rpm/cray/csm/sle-15sp4/index.yaml
1.4 backport of https://github.com/Cray-HPE/csm/pull/2043
> CASMCMS-8495: cmsdev: Update default CLI BOS version to v2

- rpm/cray/csm/sle-15sp4/index.yaml
Brings in version `1.16.27` of `csm-testing` and `goss-servers`, which supports additional test suites for HMS and CMS post-installation testing.
FYI - this supersedes https://github.com/Cray-HPE/csm/pull/2041.
* Resolves [CASMINST-6097](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6097)
Tested in vShasta by overriding stock `csm-testing` and `goss-servers` packages and running tests:
https://jenkins.algol60.net/blue/organizations/jenkins/Cray-HPE%2Fcsm-vshasta-deploy/detail/feature%2Fhms-cms-tests/40/tests
New tests are executed, output recorded.
Low - test framework only.
> CASMINST-6097 Add HMS CT tests and CMS service tests

- manifests/sysmgmt.yaml
This job is causing test failures due to BSS failing to come up before its retries are exceeded. This updates those retries to fix this issue.
* Resolves [CASMPET-6439](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6439)
Back ports a change that was tested in the 1.5 testing pipeline.
> CASMPET-6439 Increase update-bss job retries

- rpm/cray/csm/sle-15sp4/index.yaml
The /root/spire path is obsolete and should be changed to it's new path, /var/lib/spire.
* Resolves [CASMPET-6447](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6447)
No environments available to test.
This is another attempt to fix a test being run in the CSM 1.5 test pipeline.
This may not be the issue, but it should still be updated.
> CASMPET-6447 Update spire-agent socket paths in tests

- rpm/cray/csm/sle-15sp4/index.yaml
Partial backup of https://github.com/Cray-HPE/csm/pull/2046 (CMS tests only) into `release/1.4`.
> CASMINST-6097 Add CMS service tests

- CHANGELOG.md
- manifests/platform.yaml
Issue: Try to run management node rollout with Management_Master first, then Management_Worker next. The second run doesn't work, and it keeps trying to do Management_Master.
Root cause: Patch activity was not implemented as a true patching capability ... it was basically replacing input parameters whenever it received a patch request where the input parameters at least had the media directory set. In a particular case, the admin was not even specifying media directory on the command line, and hence because of the absence of media directory, the change from Management_Master to Management_Worker was not being persisted.
Fix: Use proper patching capability, where a struct with pointers is used to unmarshal the incoming json so that we can detect the difference between an empty value that …
> CASMTRIAGE-5124 backport to release/1.4

- CHANGELOG.md
- manifests/platform.yaml
Issue: Try to run management node rollout with Management_Master first, then Management_Worker next. The second run doesn't work, and it keeps trying to do Management_Master.
Root cause: Patch activity was not implemented as a true patching capability ... it was basically replacing input parameters whenever it received a patch request where the input parameters at least had the media directory set. In a particular case, the admin was not even specifying media directory on the command line, and hence because of the absence of media directory, the change from Management_Master to Management_Worker was not being persisted.
Fix: Use proper patching capability, where a struct with pointers is used to unmarshal the incoming json so that we can detect the difference between an empty value that …
> CASMTRIAGE-5124 patch activity doesn't truly work like patch activity

- docker/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
Include CANU 1.7.1 in CSM base packages.  Rolls back a python library in CANU that broke the RPM build.
- Fixes: JIRA (CASMNET-2056)
https://github.com/Cray-HPE/canu/releases/tag/1.7.1
> CASMNET-2056 1.3

- docker/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Include CANU 1.7.1 in CSM base packages.  Rolls back a python library in CANU that broke the RPM build.
- Fixes: JIRA (CASMNET-2056)
https://github.com/Cray-HPE/canu/releases/tag/1.7.1
> CASMNET-2056 main

- docker/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Include CANU 1.7.1 in CSM base packages.  Rolls back a python library in CANU that broke the RPM build.
- Fixes: JIRA (CASMNET-2056)
https://github.com/Cray-HPE/canu/releases/tag/1.7.1
> CASMNET-2056 1.4

- assets.sh
Due to CASMTRIAGE-5033's persistence, we are pulling the old 1.3 storage-ceph images into 1.4.0. This entails pulling in an old kernel as well.
> MTL-2132 Downgrade storage-CEPH

- manifests/platform.yaml
- manifests/sysmgmt.yaml
[SKERN-6686](https://jira-pro.its.hpecorp.net:8443/browse/SKERN-6686):
cray-opa: Add a cos-config-service API in OPA rule and related unit tests.
cray-spire: Add workloads for cos-config-service.
[CASMCMS-8463](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8436)
cray-opa: This mod grants several specific verb privilege to accounts that match the tenant-admin role. The tenant-admin role is applied to specific keycloak groups for individual tenants, and will be populated to the group automatically via tapms instantiation of tenants.
> Bump cray-opa to 1.32.3

- rpm/cray/csm/sle-15sp4/index.yaml
Dependabot reported a couple of CVEs in dependencies of cms-tools.
They aren't critical CVEs and I suspect we aren't using the affected code in a way that would cause us problems, but may as well update the dependencies to avoid the risk. This does that.
I am not backporting to 1.3 since they are not big issues and I don't think we're shipping more RPMs for 1.3. I will backport to 1.4 however.
- [csm-rpms main manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/809)
- [csm 1.4 manifest PR](https://github.com/Cray-HPE/csm/pull/2065)
- [csm-rpms 1.4 manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/810)
I tested on wasp to make sure no regressions were introduced.
Low risk.
> CASMCMS-8502: cmsdev: Update dependencies to resolve CVEs

- manifests/platform.yaml
sysmgmt-health version bump for CASMTRIAGE-5137: prometheus-cray-sysmgmt-health-kube-p-prometheus-0 in IPBO
* Resolves - https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5137
> CASMTRIAGE-5137: prometheus-cray-sysmgmt-health-kube-p-prometheus-0 in IPBO

- manifests/storage.yaml
Add missing parms to cephfs storage class with sp3 image
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6471
* `vex`
```
pit:~ # kubectl get sc ceph-cephfs-external -o yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"ceph-cephfs-external"},"parameters":{"clusterID":"e1b63294-d356-11ed-a56f-42010afc0104","csi.storage.k8s.io/controller-expand-secret-name":"csi-cephfs-secret","csi.storage.k8s.io/controller-expand-secret-namespace":"default","csi.storage.k8s.io/node-stage-secret-name":"csi-cephfs-secret","csi.storage.k8s.io/node-stage-secret-namespace":"default","csi.storage.k8s.io/provisioner-secret-name":"csi-ceph …
```
> Add missing parms to cephfs storage class with sp3 image (CASMPET-6471)

- CHANGELOG.md
- manifests/core-services.yaml
- manifests/platform.yaml
Create "short" zones in PowerDNS (`nmn` for example) and an associated DNAME record linking it to the fully qualified domain.
This allows PowerDNS to respond to short name queries so the caller doesn't need to know the FQDN of the system e.g.
```
ncn-m001:~ # host api.nmnlb 10.92.100.85
Using domain server:
Name: 10.92.100.85
Address: 10.92.100.85#53
Aliases:
api.nmnlb.mug.hpc.amslabs.hpecorp.net has address 10.92.100.71
api.nmnlb is an alias for api.nmnlb.mug.hpc.amslabs.hpecorp.net.
nmnlb has DNAME record nmnlb.mug.hpc.amslabs.hpecorp.net.
```
* Resolves [CASMNET-2082](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-2082) and [CASMNET-1806](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1806)
* `mug`
Deployed on mug, all short zones are created …
> CASMNET-2082 - Create short zones and DNAME records in PowerDNS

- rpm/cray/csm/sle-15sp3/index.yaml
In order to support SP3 storage nodes with SP4 K8S nodes, also put the rpms required by cloud-init into the sp3 repo.
> CASMINST-6194: also put cloud-init-required rpms in the SP3 repo

- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Pull `canu`, `csm-testing`, and `goss-servers` from their SP3 repo to keep things kosher.
PR #2075 pulled these from SP4 repos into the SP3 CSM repo definition, but `csm-testing` and `goss-servers` were already published to an SP3 endpoint. `canu` recently had SP3 builds disabled, and these were toggled back on last night.
> CASMINST-6194 Undo SP4/SP3 repo tom-foolery

- docker/index.yaml
- manifests/sysmgmt.yaml
This includes two things:
1. [CASMTRIAGE-5163](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5163): main backport of [this 1.4 manifest PR](https://github.com/Cray-HPE/csm/pull/2082)
2. [CASMCMS-8512](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8512): Update to a Gitea chart with a typo fixed, so that the database backups will work
The Gitea fix is only needed for CSM 1.5.
- [gitea source PR](https://github.com/Cray-HPE/gitea/pull/45)
See source PR.
Low risk. And without this, the VCS database will not be backed up.
> CASMCMS-8512/CASMTRIAGE-5163: Fix problems with product catalog & gitea

- docker/index.yaml
- manifests/sysmgmt.yaml
1) Update the overall Cray Product Catalog chart to the latest
2) Update to a version of the barebones image importer that uses the latest Cray Product Catalog updater
3) Explicitly pull in other Cray Product Catalog updater images that may be needed by other products
- Resolves [CASMTRIAGE-5163](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5163)
- [cray-import-kiwi-recipe-image source PR](https://github.com/Cray-HPE/cray-import-kiwi-recipe-image/pull/25)
- [image-recipes source PR](https://github.com/Cray-HPE/image-recipes/pull/48)
- [main manifest PR](https://github.com/Cray-HPE/csm/pull/2083)
The latest updater version has been available for a while and has been extensively tested. We were already including it in our builds, we just weren't using it for this one thing (the …
> CASMTRIAGE-5163: Update to latest product catalog

- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Change bgp test when run after worker rebuild to only check that worker.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5164
* `surtur`
```
ncn-w003:~ # TARGET_NCN=ncn-w003 GOSS_BASE=/opt/cray/tests/install/ncn SW_ADMIN_PASSWORD='!nitial0' /opt/cray/tests/install/ncn/scripts/check_bgp_neighbors_established_brad.sh
NAME      DATA   AGE
metallb   1      3d5h
CAN
Running: canu validate network bgp --verbose --network all --password XXXXXXXX
PASS
```
Low
* Nothing
> Change bgp test to test only the worker being rebuilt (CASMTRIAGE-5164)

- rpm/cray/csm/sle-15sp4/index.yaml
Fixes bugs causing the BOS and VCS tests to fail on CSM 1.5. Simplifies the BOS test to avoid false failures. Reduces redundancy in test output. Includes additional debug information on failures.
- [CASMCMS-8496 source PR](https://github.com/Cray-HPE/cms-tools/pull/93)
- [CASMCMS-8513 source PR](https://github.com/Cray-HPE/cms-tools/pull/96/)
- [CASMCMS-8514 source PR](https://github.com/Cray-HPE/cms-tools/pull/97/)
- Resolves [CASMCMS-8496](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8496), [CASMCMS-8513](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8513), [CASMCMS-8514](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8514), [CASMTRIAGE-5129](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5129), [CASMTRIAGE-5130](https://jira-pro.its.hpecorp.net:8443/browse/ …
> CASMCMS-8496/CASMCMS-8513/CASMCMS-8514/CASMCMS-8529: cmsdev: Test fixes and improvements

- rpm/cray/csm/sle-15sp4/index.yaml
Minor simplifcations to BOS test to avoid potential false failures.
[csm-rpms 1.4 manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/817)
Also included the fix for CASMCMS-8529 to provide additional debug information on test failures.
I tested on wasp to verify that the BOS test still worked, and to verify that no regression bugs were introduced.
Small change. Worth the risk to avoid BOS false failures.
> CASMCMS-8514/CASMCMS-8529 cmsdev: Simplify BOS test, provide additional debug information on failures.

- docker/index.yaml
- lib/setup-nexus.sh
Normally, a BOS v2 staged session will reach the state "running" when it is considered finished staging. However, if that BOS v2 staged session does not apply to any components (for example, when a limit parameter is used that does not overlap with any of the nodes in the session template), the session will go straight to "complete" instead.
Rename the `target_state` argument to the BOSV2SessionWaiter to `target_states` and change the type to a list of acceptable target states. This allows us to call it with the single state "complete" when waiting on a non-staged session and to call it with the states "complete" and "running" when waiting on a staged session.
* Resolves [CRAYSAT-1705](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1705)
* locally on macbook
* gamora
Added new unit …
> CRAYSAT-1705: Bump cray-sat to 3.21.4

- hack/load-container-image.sh
Change parsing of podman output to allow for other graphOption array entries.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5174
* `beau`
```
pit:~ # podman info -f json | jq -r '.store.graphOptions["overlay.mount_program"].Executable'
/usr/bin/fuse-overlayfs
```
Low
* Nothing
> Be specific about podman graphOption index (CASMTRIAGE-5174)

- assets.sh
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
`craycli` was upgraded to Python 3.10, and had some build changes to its pipeline. `craycli` now publishes to 15.3 and 15.4 repositories.
> CASMCLOUD-1219

- manifests/platform.yaml
Later code for bitnami etcd chart and fixes for CLBO after power off/on.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6365
* `ashton`
Scale down to zero and back up to three members:
```
etcd 19:09:19.70
etcd 19:09:19.70 Welcome to the Bitnami etcd container
etcd 19:09:19.71 Subscribe to project updates by watching https://github.com/bitnami/containers
etcd 19:09:19.72 Submit issues and feature requests at https://github.com/bitnami/containers/issues
etcd 19:09:19.73
etcd 19:09:19.74 INFO  ==> ** Starting etcd setup **
etcd 19:09:19.77 INFO  ==> Validating settings in ETCD_* env vars..
etcd 19:09:19.80 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
etcd 19:09:19.82 INFO  ==> …
```
> Update bitnami docker image with latest (CASMPET-6365)

- manifests/platform.yaml
Increase size of etcd cephfs pvc for snapshots.  Going with 200G which should leave more than enough space based on audit of current usage of the etcd-backups bucket:
```
11958904 ~12G (mug)
14889340 ~14G (baldar)
17817388 ~17G (shandy)
21434928 ~21G (hela)
```
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6419
* `ashton`
```
ncn-m002:~ # kubectl get pvc -n services bitnami-etcd-snapshotter -o json | jq -r .spec.resources.requests.storage
200G
```
Low
* Nothing
> Increase size of common etcd snapshot PVC (CASMPET-6419)

- manifests/core-services.yaml
Updates the cray-smd chart version for CASMTRIAGE-5190 - Fix HSM Empty Memory Discovery for EX Hardware
* Merge after https://github.com/Cray-HPE/csm/pull/2104
* Resolves [CASMTRIAGE-5190](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5190)
For testing, see https://github.com/Cray-HPE/hms-smd/pull/108
Low
> CASMTRIAGE-5190: Fix HSM Empty Memory Discovery for EX Hardware

- manifests/core-services.yaml
- manifests/sysmgmt.yaml
Updates HMS charts to use ETCD and Postgresql break-out charts. This is necessary for ETCD due to the changes in the upcoming k8s 1.22. Postgres changes were done to mirror the ETCD changes.
Once we move to k8s 1.22 these changes are not backwards compatible.
* Resolves
* [CASMHMS-5946](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5946)
* [CASMHMS-5947](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5947)
* [CASMHMS-5871](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5871)
* [CASMHMS-5869](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5869)
* [CASMHMS-5945](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5945)
* [CASMHMS-5868](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5868)
* These changes are ONLY FOR CSM 1.5, they will not work in older CSMs
* …
> Use new HMS services that have new etcd and postgres charts

- docker/index.yaml
main backport of https://github.com/Cray-HPE/csm/pull/2111
> CASMCMS-8540: Update cf-gitea-import version to resolve security vulnerability

- manifests/sysmgmt.yaml
Bump docker and chart versions to match.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5215
Low
* Nothing
> tapms: bump docker and chart version to match (CASMTRIAGE-5215)

- CHANGELOG.md
- manifests/sysmgmt.yaml
Update cms-ipxe to 1.11.2 to support vShasta. The cms-ipxe customizations can now be set up to tell cray-ipxe to generate the KPXE binaries needed by vShasta to support CSM mediated network boot of nodes.
This is a backward compatible restoration of previously lost funtionality.
* Resolves [VSHA-553](https://jira-pro.its.hpecorp.net:8443/browse/VSHA-553)
Configured cms-ipxe for KPXE binaries and verified that I could pull the binary through cray-tftp and that the resulting binary was, indeed, a KPXE binary. Removed the special configuration and verified that the original EFI binary was generated.
- Was upgrade tested? …
> VSHA-553 Update cms-ipxe to 1.11.2 for vshasta support

- CHANGELOG.md
- docker/index.yaml
Updates cf-gitea-import to use a shallow clone that reduces memory consumption.
* Resolves CASMCMS-8531
* Mug
See cf-gitea-import PR
None
> CASMCMS-8531: Update cf-gitea-import to 1.9.4

- CHANGELOG.md
- docker/index.yaml
Updates cf-gitea-import to use a shallow clone that reduces memory consumption.
* Resolves [CASMCMS-8531](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8531)
* Also resolves [CASMCMS-8540](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8540) by being built on top of the version that fixed that ticket. Since this manifest PR supersedes the one for that ticket, I've closed [the 1.4 manifest PR for CASMCMS-8540](https://github.com/Cray-HPE/csm/pull/2111).
* Mug
See cf-gitea-import PR
None
> CASMCMS-8531/CASMCMS-8540: Update cf-gitea-import to 1.9.4 (1.4)

- manifests/core-services.yaml
Updates the cray-smd chart version for CASMTRIAGE-5190 - Fix HSM Empty Memory Discovery for EX Hardware
This also pulls in the following HSM changes to CSM 1.4:
- Added CT test coverage for most remaining APIs.
- Fixed several CT test bugs and made various improvements.
- Moved hardware-sensitive CT tests into separate stage.
- CASMHMS-5863 - Added Reacquire() function to the reservations client library.
- CASMHMS-5902: Linting of language in API spec (no content changes); corrected markdown formatting issue in changelog
All of which are not functional changes to HSM itself.
* Resolves [CASMTRIAGE-5190](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5190)
For testing, see https://github.com/Cray-HPE/hms-smd/pull/108
Low
> CASMTRIAGE-5190: Fix HSM Empty Memory Discovery for EX Hardware CSM 1.4

- manifests/sysmgmt.yaml
Updates HBTD chart to use ETCD  break-out chart. This is necessary for ETCD due to the changes in the upcoming k8s 1.22.
Once we move to k8s 1.22 these changes are not backwards compatible.
This was missed in the original PR for this work.
* Resolves
* [CASMHMS-5870](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5870)
* These changes are ONLY FOR CSM 1.5, they will not work in older CSMs
* Virtual Shasta Ashton
Manually upgraded and downgraded all charts. Verified as much as I could in the environment that the services worked after the upgrades and data was preserved in the ETCD instance.
- …
> Update HBTD chart for ETCD changes

- manifests/core-services.yaml
Fix CT test issues for HSM caused by unintentionally bringing in CSM 1.5 CT functionality.
* Resolves [CASMINST-6238](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6238)
For testing see https://github.com/Cray-HPE/hms-smd/pull/110
Low.
> CASMINST-6238: Back out HSM CT Test Changes from CSM 1.4

- manifests/sysmgmt.yaml
Use standard port, get path and dns name working so services can hit api like: 
http://cray-tapms/v1/tenants
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6433
Low
* Nothing
> Read-only api cleanup to follow CSM standards (CASMPET-6433)

- manifests/platform.yaml
Need patched version of SMA-1.7 that allows Nersc to install HPE-built software and keep their scalability settings. 
e.g. rsyslog-aggregator config file needs to persist, a number of instances of rsyslog-aggregator, kafka, elasticsearch need to persist, and es-curator needs to create indexes with the configured number of shards. The Kafka partition count needs to persist. 
[CASMSMF-7353](https://jira-pro.its.hpecorp.net:8443/browse/CASMSMF-7353)
* Resolves [CASMMON-296](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-296) and [CASMMON-295](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-295)
* `<drax>`
Tested successfully.
- Was the upgrade tested? Yes.
> CASMMON-295 Monitor the SMF Kafka server and zookeeper

- Jenkinsfile.github
Latest 1.4.0 build failed with the error:
Error when executing success post condition:
org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use method hudson.model.Item getFullName
at org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.StaticWhitelist.rejectMethod(StaticWhitelist.java:229)
This happened, because there was an explicit override placed for `hudson.model.Item getFullName` in Jenkins settings before, and it was accidentally cleared. Generally, we should not rely on such overrides in jenkins settings. In this particular case, we just don't need to use this method.
> Stop using hudson.model.Item getFullName, which requires approval

- manifests/sysmgmt.yaml
Assign tenant-admin role to tenant specific keycloak groups.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6503
```
1.6824523041273134e+09	INFO	controllers.Tenants	Created Keycloak group: vcluster-coke-tenant-admin	{"tenants": "tenants/vcluster-coke"}
1.6824523041273816e+09	INFO	controllers.Tenants	Ensuring Keycloak realm role (tenant-admin) is assigned to Keycloak group: vcluster-coke-tenant-admin	{"tenants": "tenants/vcluster-coke"}
1.68245230897035e+09	INFO	controllers.Tenants	Assigned Keycloak realm role (tenant-admin) to Keycloak group: %!(EXTRA string=vcluster-coke-tenant-admin)	{"tenants": "tenants/vcluster-coke"}
1.6824523089704456e+09	INFO	controllers.Tenants	Updating tenant status	{"tenants": "tenants/vcluster-coke"}
```
Was an Upgrade …
> Add tenant-admin role mapping to tenant keycloak groups (CASMPET-6503)

- rpm/cray/csm/sle-15sp4/index.yaml
Allow for more than the minimum etcd pods, in case we've got one stuck in terminating on a dead worker.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6507
```
ncn-m002:/opt/cray/tests/install/ncn/scripts # ./etcd_health_check.sh
--- Check that the Correct Number of Pods Running, Check Endpoint Health, Check if Any Alarms are Set ---
PASS                cray-bos: Expected 3 etcd members, got 3 members. Endpoint health check passed. No alarms set.
PASS                cray-bss: Expected 3 etcd members, got 3 members. Endpoint health check passed. No alarms set.
PASS                cray-fas: Expected 3 etcd members, got 3 members. Endpoint health check passed. No alarms set.
PASS              cray-hmnfd: Expected 3 etcd members, got 3 members. Endpoint health check passed. No alarms …
```
> Fix etcd balance test to allow for stuck/dead pods (CASMPET-6507)

- manifests/sysmgmt.yaml
Fixes an issue where dvs-mqtt workloads were incorrectly created with the wrong SpiffeID.
* Resolves [CASMPET-6488](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6488)
Validated correct workloads were created
- Were continuous integration tests run? If not, why Y
- Was downgrade tested? If not, why? N, would have no affect
> CASMPET-6488 Bump spire to 2.10.3

- manifests/platform.yaml
Version number bump up for main branch due to the fix in CASMPET-6438
https://github.com/Cray-HPE/cray-kyverno/pull/13
> CASMPET-6438: (CSM 1.5/main) kyverno prevents weave-net daemonset from creating pods

- vendor/stash.us.cray.com/scm/shasta-cfg/stable/customizations.yaml
This allows the fqdn to be registered via externaldns.
> CASMPET-6517 Override cray-spire server.fqdn

- Jenkinsfile.github
We calculate `build/images/index.txt` twice during CSM build, once during mandatory `Validate Images` stage, second time during `Release` stage (invoked only on tagged builds). Second time, file is not reused, because it gets cleaned up between 1st and 2nd stage. The suggestion is to move cleanup to the beginning  of build. so that file generated at 1st step will be reused at 2nd step.
* Resolves [CASMINST-6282](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6282)
* not tested
Testing this will require full build. We'll do a full build eventually (probably today) and will see if this change cause any trouble. If it is, it will be very easy to rollback.
Low - pipeline change only, easy to rollback.
> CASMINST-6282 Avoid duplicate image list calculation

- Jenkinsfile.github
- release.sh
We need to store `build/images/index.txt` as a separate asset. We will use it later to produce patch builds, perform troubleshooting, re-generate snyk scans (if needed), etc.
* Resolves [CASMINST-6275](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6275)
* Part of [CASMINST-6221](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6221) epic
* not tested
Testing this will require full build. We'll do a full build eventually (probably today) and will see if this change cause any trouble. If it is, it will be very easy to rollback.
Low - pipeline change only, easy to rollback.
> CASMINST-6275 Publish image digest along with CSM tarball

- CHANGELOG.md
- manifests/platform.yaml
Update the virtual service to use the new custoomer-admin-gateway that will be required in 1.5 for all customer accessible services
* Resolves [CASMPET-4948](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-4948)
* Fanta
- Were continuous integration tests run? If not, why?y
- Was upgrade tested? If not, why?y
- Was downgrade tested? If not, why?y
- Were new tests …
> CASMPET-4948: Update cray-kiali for cmn separation

- CHANGELOG.md
- manifests/platform.yaml
This change only adds a group mapper to the shasta client and adds a new realm role. This is backward compatible and is needed for Multi tenancy work.
* Resolves [CASMINST-6105](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6105)
* ashton
- Was downgrade tested? If not, …
> CASMINST-6105: Update keycloak to include MT work

- assets.sh
Includes new images with some minor package updates, also leverages the new metal-provision Ansible for installing packages vs. csm-rpms.
> CASMINST-4571 New NCN Images

- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
Restore CRUS subcommands to Cray CLI.
- Corresponding docs PR to document known issue in 1.4.0: https://github.com/Cray-HPE/docs-csm/pull/3759
> CASMTRIAGE-5317: Restore CRUS subcommands to Cray CLI

- docker/index.yaml
- manifests/sysmgmt.yaml
[main branch manifest PR](https://github.com/Cray-HPE/csm/pull/2132)
Update `ims-load-artifacts` image to 2.3.0 to pull in changes to check if recipes and images are already updated based on their artifact checksums, instead of just on their names.
* Resolves [CASM-3868](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3868)
* Also resolves [CASMINST-6081](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6081)
This was tested manually against the `ims-python-helper` library with a test harness script by uploading the same recipe multiple times, and then checking with recipes with different contents, and with recipes with the same name but empty links.
See testing here: https://gist.github.com/jack-stanek-hpe/e8f01617d29a6a588156a2e2cca49b35
N/A
> CASM-3868: Improve existing image check logic for ims-python-helper

- docker/index.yaml
- manifests/sysmgmt.yaml
> Revert "CASM-3868: Improve existing image check logic for ims-python-helper"

- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Add tenant configuration option, pass cray-tenant-name header value if specified.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6319
Configuration without tenant:
```
ncn-w001:~/.config/cray/configurations # cray init
Overwrite configuration file at: /root/.config/cray/configurations/default ? [y/N]: y
Cray Hostname: https://api-gw-service-nmn.local/
Tenant Name (leave blank for global scope): []:
Username: vers
Password:
Success!
Initialization complete.
ncn-w001:~/.config/cray/configurations # cat default
[core]
hostname = "https://api-gw-service-nmn.local/"
tenant = ""
[auth.login]
username = "vers"
```
Configuration without tenant:
```
ncn-w001:~/.config/cray/configurations # cray init
Overwrite configuration file at: /root/.config/cray/configurations/default ? [y/N]: y
Cray …
```
> Add tenant name/id header when scoped to tenant (CASMPET-6319)

- manifests/sysmgmt.yaml
Updates the gitea chart for a change that adds the CMN/customer-admin-gateway to the gateways for the external ui and git endpoints. 
* Resolves CASMCMS-7594
* Mug
Deployed and validated access via endpoints
None
> CASMCMS-7594: Update gitea to add CMN gateway

- release.sh
- rpm/cray/csm/sle-15sp4/index.yaml
Backport of https://github.com/Cray-HPE/csm/pull/2179 into `release/1.4`.
> CASMINST-6336 Package latest versioned docs-csm with csm build [release/1.4]

- release.sh
- rpm/cray/csm/sle-15sp4/index.yaml
Currently, we package `docs-csm` by referring it in `rpm/cray/csm/sle-15sp4/index.yaml` file. This approach has some issues:
1. Version of docs-csm must be updated manually before each build - a lot of redundant builds and some manual work
2. We can't implement [CASMINST-6284](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6284) (auto-tag docs-csm during csm build)
3. Even though we refer to specific version in `rpm/cray/csm/sle-15sp4/index.yaml` file, the file packaged with csm tarball is actually `docs-csm-latest.noarch.rpm`. This happens to a bug in packaging tools (`nevra` field for docs-csm-latest still contains version of original package, so it overrides original package):
https://jenkins.algol60.net/job/Cray-HPE/job/csm/job/v1.5.0-alpha.39/2/consoleText
... …
> CASMINST-6336 Package latest versioned docs-csm with csm build [main]

- manifests/core-services.yaml
- manifests/sysmgmt.yaml
This updates cray-reds, cray-smd, cray-power-control, and cray-hms-rts to provide status tracking for all management switches for CASM-2974 - xtalive equivalent API in PCS.
cray-reds - Adds default SNMP credentials to vault for management switches
cray-hms-rts - Stands up a SNMP backed redfish interface for HSM and PCS to talk to
cray-smd - Discovers the management switches via RTS's redfish interface
cray-power-control - Gets availability status of the management switches from RTS's redfish interface.
* Resolves [CASMHMS-5950](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5950)
For testing, see:
cray-reds - https://github.com/Cray-HPE/hms-reds/pull/37
cray-hms-rts - https://github.com/Cray-HPE/hms-redfish-translation-layer/pull/46
cray-smd - …
> Add management switches to HSM/PCS for status tracking

- rpm/cray/csm/sle-15sp4/index.yaml
This PR improves the cmsdev iPXE/TFTP test so that it covers all iPXE binaries being generated, and so that it uses the `cray-ipxe-settings` configmap as its source of truth, rather than using hard-coded default values. This makes it a more comprehensive and robust test, and also lays the groundwork for further changes needed as part of the ARM enablement work.
- [source PR](https://github.com/Cray-HPE/cms-tools/pull/105)
See source PR for details.
Low risk. On systems with default configurations, the change is slight. On other systems, without these changes, the existing test would fail.
> CASMCMS-8602: TESTS: cmsdev: Get values from cray-ipxe-settings configmap instead of using hard-coded defaults

- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp3-compute/index.yaml
- rpm/cray/csm/sle-15sp4-compute/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Once CASMINST-6284 is completed, we'll be auto-generating docs for our APIs. Because of that, we want to backport these minor BOS changes to CSM 1.4.1 in order to bring the published spec and actual behavior more closely in alignment. Almost all of the changes here are to the spec, with just one minor (and well-tested) bug fix in the service itself.
See [source PR](https://github.com/Cray-HPE/bos/pull/119) for details.
Without this, there is a much greater risk of customer problems if they try to use BOS via the published API spec.
> CASMCMS-8610: Bring BOS API spec in line with actual API

- manifests/platform.yaml
As part of cert-manager upgrades, remove cray-certmanager-init, which no longer exists as all it did was install crd's in the past. cray-certmanager is bumped to 0.7.0 to include 1.5.5 with default params to take its place.
This change is not backwards compatible at all due to how cert-manager works.
betrand
* betrand
_How were the changes tested and success verified? If schema …
> CASMPET-6161: Bump cray-certmanager to 0.7.0 rm cray-certmanager-init

- CHANGELOG.md
- manifests/core-services.yaml
- manifests/platform.yaml
When the `cray-dns-unbound` Helm chart is upgraded it replaces the `binaryData.records.json.gz` portion of the `cray-dns-unbound` ConfigMap with an empty list. This could lead to a DNS outage if pods are restarted before `cray-dns-unbound-manager` has had a chance to run.
This PR changes the install/upgrade behaviour of the chart. If the `cray-dns-unbound` ConfigMap exists and contains `records.json.gz` then that data will be used rather than overwriting the ConfigMap with an empty record set. In the event that the `cray-dns-unbound` ConfigMap doesn't exist or doesn't contain `records.json.gz` the behaviour is as before and the ConfigMap will be created with the empty record set.
This PR also contains a minor change to `manager.py` as a rebuild of the image pulls in requests v2.30.0 and …
> CASMNET-2121 - Upgrading the cray-dns-unbound Helm chart should not wipe the DNS records.

- docker/index.yaml
- lib/setup-nexus.sh
Address critical CVE-2023-27536 in the cray-sat docker image.
* Resolves [CRAYSAT-1719](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1719)
Tested in corresponding SAT change.
> CRAYSAT-1719: Bump cray-sat image version to 3.21.5

- manifests/platform.yaml
_Grok-exporter is not running on ncn-m001 as it comes up last when nodes are installed on pit. The other master nodes of m002 or m003 is taking ownership of the m001 instance before it is up._
_This fix will resolve the issue and wait for m001 to take the ownership of the pod._
_Minor fix with canu-test dashboard filename as it is conflicting with the config-map of the same name and causing issues._
* Resolves [CASMMON-299](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-299)
* Resolves [CASMTRIAGE-5335](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5335)
* `<mug>`
* `<hela>`
_Tested and success verified._
ncn-m001:/mnt/developer/sum # kubectl get all -n sysmgmt-health | grep grok …
> CASMMON-299 Grok-exporter issue with running on ncn-m001

- manifests/platform.yaml
_Grok-exporter is not running on ncn-m001 as it comes up last when nodes are installed on pit. The other master nodes of m002 or m003 is taking ownership of the m001 instance before it is up._
_This fix will resolve the issue and wait for m001 to take the ownership of the pod._
* Resolves [CASMMON-299](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-299)
* `<mug>`
* `<hela>`
_Tested and success verified._
ncn-m001:/mnt/developer/sum # kubectl get all -n sysmgmt-health | grep grok
pod/cray-sysmgmt-health-grok-exporter-6b64849ff5-2cc8z              1/1     Running            0          3m34s
pod/cray-sysmgmt-health-grok-exporter-6b64849ff5-htsps              1/1     Running            0          3m35s …
> CASMMON-299 Grok-exporter issue with running on ncn-m001 Release/1.4

- CHANGELOG.md
- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Add the first round of support for arm64 to the IMS service.  This allows recipes to be built using an arm64 emulator on standard x86 ncn worker nodes. There will be followup patches as this is used more and can be tested with additional workflows.
* Resolves [CASMCMS-8565](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8565)
* `Mug`
Installed the version on Mug via helm upgrade. Tested existing x86 recipe builds and image customizations. The arm64 recipes start to build, but there are problem with the recipes themselves that need to be resolved before they can build successfully.
- Was …
> CASMCMS-8565 - add arm64 support to IMS.

- CHANGELOG.md
- docker/index.yaml
This updates the cilium images and adds the hubble images to the tarball.   Cilium is not installed by default at this time.   This makes the images available if we turn on the cilium flag at fresh install or migrate from weave.
Updating the cilium images will also address the CVEs that are currently flagged in cilium 1.12.4 since we will no longer be including 1.12.4 in the tarball.
* Resolves [CASMPET-6479](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6479)
* Resolves [CASMPET-6330](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6330)
* Virtual Shasta - cilium cluster
I have used these images (imported manually) to go through the migration process on the cilium cluster
> CASMPET-6479: Update cilium images to 1.13.2 and add Hubble images

- CHANGELOG.md
- docker/index.yaml
Snyk found 1 High vulnerability in the cilium v1.12.4 container image.   We are not using cilium yet in 1.4 so I am removing those container images.   These images will be upgraded in 1.5.
* Resolves [CASMPET-6330](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6330)
This is just removing unused container images.   The builds for this PR will be the test.
> CASMPET-6330: Removes Cilium container images to remove CVEs.

- manifests/platform.yaml
cray-certmanager 0.7.1 should have image fixes that were causing build issues with 0.7.0. 
* Resolves CASMPET-6172 …
> Casmpet 6173 main

- manifests/sysmgmt.yaml
This updates the RTS chart version for CASMTRIAGE-5352: Fix RTS creating K8s Service Entries with the Incorrect Selector Labels.
* Resolves [CASMTRIAGE-5352](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5352)
For testing, see https://github.com/Cray-HPE/hms-redfish-translation-layer/pull/47
None
> CASMTRIAGE-5352: Fix RTS creating K8s Service Entries with the Incorrect Selector Labels

- manifests/sysmgmt.yaml
Pulls in a fix for BOS that was slowing down power-on operations on large systems.  
Also pulls in some build fixes and corrections to the api spec.  (No changes to the api behavior)
* Resolves CASMCMS-8609
* crossroads
Tested shutdown, boot and reboot sessions for all compute nodes.
None
> CASMCMS-8609: Update bos for power-on status fix (1.3)

- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp3-compute/index.yaml
- rpm/cray/csm/sle-15sp4-compute/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Pulls in a fix for BOS that was slowing down power-on operations on large systems.  
Also includes changes to the BOS API spec to make it match the actual BOS behavior (for the benefit of the auto-generated API docs).
* Resolves CASMCMS-8609 (power-on operations)
* Resolves CASMCMS-8561/CASMCMS-8575 (API spec discrepancies)
* crossroads
Tested shutdown, boot and reboot sessions for all compute nodes.
None
> CASMCMS-8609: Update bos for power-on status fix (1.4)

- manifests/sysmgmt.yaml
CASMHMS-6012 - Adds definition of SPIRE_TOKEN_URL to over-ride the default to reflect the new spire endpoint.
* Resolves [CASMHMS-6012](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-6012)
* surtur
Verified the changed chart had the SPIRE_TOKEN_URL env variable properly reflected and used in the BSS pod.
Requires the spire service endpoint to be updated.
- [ x ] Version number(s) incremented, if applicable
- [ x ] Copyrights updated
- [ x ] License file intact
- [ x ] Target branch correct
- [ x ] CHANGELOG.md updated
- [ x ] Testing is appropriate and complete, if applicable
> Manifest update for BSS change for CASMHMS-6012

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4-compute/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
ARM work requires to change some x86 rpms to build as noarch instead. Currently cfs state reporter has released and is
now publishing noarch rpms.
Resolves - https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8603
> CASMCMS-8516: cfs-reporter rpm noarch

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4/index.yaml
Bump the version of iuf-cli from iuf-cli-1.5.0~alpha.1-1.x86_64 to iuf-cli-1.5.1-1.x86_64.
> CASM-4261: iuf-cli Version Bump

- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp3-compute/index.yaml
- rpm/cray/csm/sle-15sp4-compute/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
ARM work defined in epic - [CASM-4066](https://jira-pro.its.hpecorp.net:8443/browse/CASM-4066) requires that RPMs be built as `noarch` from `x86_64`
- Fixes: [CASMCMS-8604](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8604)
> CASMCSM-8517: Updating rpms for bos-reporter

- rpm/cray/csm/sle-15sp4/index.yaml
Increase platform-ca-in-bundle test time out to 20 seconds.
* Resolves [CASMTRIAGE-5354](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5354)
- Were the …
> CASMTRIAGE-5354: increase platform-ca-in-bundle test time out

- rpm/cray/csm/sle-15sp4/index.yaml
Increase platform-ca-in-bundle goss testing timeout to 20 seconds. 
* Resolves [CASMTRIAGE-5354](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5354)
- Were the …
> CASMTRIAGE-5354: increase platform-ca-in-bundle test times out

- manifests/platform.yaml
Prometheus resources were not updating due to old name (prometheus-operator) in csm/manifest/platform.yaml. 
Changed the name to kube-prometheus-stack to support the latest version of prometheus-operator.
* Resolves - https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5371
> CASMTRIAGE-5371

- CHANGELOG.md
- manifests/platform.yaml
Update cray-drydock to 2.18.1 to add argo namespace to allow cray-nls postgres backup job to succeed.
* Resolves [CASMPET-6583](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6583)
* `drax`
- Were …
> CASMPET-6583: update cray-drydock to 2.18.1

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4/index.yaml
The goss-rgw-health test fails on vshasta because it doesn't have an HMN network.   Adding the vshasta skip to this test.
* Resolves [CASMINST-6342](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6342)
* Virtual Shasta - grog
Ran the preflight checks in prerequisites on grog and verified that this test was skipped.
Low
> CASMINST-6342: Release csm-testing v1.16.34

- assets.sh
- hack/gen-rpm-index.sh
- hack/list-pit-iso-rpms.sh
- hack/list-squashfs-rpms.sh
- hack/load-container-image.sh
- hack/snyk-scan.sh
- hack/verify-helm-index.sh
- hack/verify-rpm-index.sh
- lib/install-goss-tests.sh
- lib/setup-nexus.sh
- manifests/sysmgmt.yaml
- manifests/velero-1.7-upgrade.yaml
- release.sh
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
- rpm/cray/csm/sle-15sp3-compute/index.yaml
- rpm/cray/csm/sle-15sp4-compute/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
- security/snyk-aggregate-results/snyk-aggregate-results.py
- upgrade.sh
This PR contains several fixes to the BOS API spec (including one that fixes a customer-reporter problem):
* [CASMCMS-8447](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8447): Update API spec to show that GET of session templates can return v1 or v2 templates
* [CASMCMS-8572](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8572): Update API spec to reflect that creating a BOS v1 session requires operation AND templateName/templateUuid
* [CASMCMS-8576](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8576): Update API spec to reflect that GET /v1/session returns list of IDs not sessions
* [CASMCMS-8577](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8577): Update the spec to accurately reflect what is returned when creating or getting a BOS v1 session
* …
> BOS API spec fixes & one small BOS code fix

- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp3-compute/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4-compute/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
One of the fixes to the API spec caused a regression bug when creating v1 sessions using the deprecated templateUuid parameter. This changes the spec to prevent the bug.
* Resolves [CASMTRIAGE-5404](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5404) for the CSM 1.3 and 1.4 backports. (I will make a separate PR to fix this more satisfyingly in the develop branch.)
* [Source PR](https://github.com/Cray-HPE/bos/pull/138)
I deployed the updated BOS on Crossroads and verified that the problem no longer occurred, and the BOS regression test suite passed without problems.
Low risk.
> CASMTRIAGE-5404: Update BOS to fix v1 session creation regression bug

- manifests/sysmgmt.yaml
This updates gitea to fix the POSTGRES_HOST value in the chart.
This does not fix the whole upgrade issue with VCS postgres, but the remaining portion is a upgrade process issue.
* Partially Resolves CASMPET-6571
* Drax
Deployed successfully.
None
> CASMPET-6571: Update gitea for fixed postgres host

- build/images/inspect.sh
- build/images/sync.sh
Skopeo operations (`skopeo inspect` and `skopeo copy`) were updated to always use Artifactory credentials.However, if source container image is not in Artifactory and getting pulled directly from `docker.io` or `quay.io`, this causes HTTP 401 errors. We do allow direct pulls `docker.io` or `quay.io` as fail safe mechanism.
* Jenkins
Ran build with `cray-certmanager` chart temporarily downgraded to version `0.7.0`:
https://jenkins.algol60.net/blue/organizations/jenkins/Cray-HPE%2Fcsm/detail/feature%2Fskopeo-auth/7/pipeline
This version of `cray-certmanager` chart pulls one image directly from `quay.io`:
$ helm template csm-algol60/cray-certmanager --version 0.7.0 | grep image:
image: "artifactory.algol60.net/csm-docker/stable/quay.io/jetstack/cert-manager-cainjector:v1.5.5"
image: …
> Set skopeo creds only if pulling from artifactory

- manifests/platform.yaml
Bump for cray-metrics-server to use 1.22 compatible api's.
* Resolves CASMPET-6177
vshasta though we'll need to install 1.22 to know for sure all is ok. …
> CASMPET-6177: Bump cray-metrics-server to 0.4.1

- rpm/cray/csm/sle-15sp3/index.yaml
Update csm-testing and goss-servers rpms in sle15-sp3 manifest since that is the one that gets installed in the 1.4 CI pipeline.
* Resolves [CASMINST-6383](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6383)
* Related to [CASMTRIAGE-5354](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5354)
* Virtual Shasta - grog
Verified that the correct rpm gets selected for installation.
Low
> CASMINST-6383: Sync up csm-testing rpms in sle-15sp3 and sle-15-sp4

- manifests/sysmgmt.yaml
Add required disasterRecovery chart section to allow for ETCD backups.
* Resolves [CASMTRIAGE-5390](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5390)
* Resolves [CASMTRIAGE-5391](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5391)
* Resolves [CASMTRIAGE-5392](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5392)
* Resolves [CASMTRIAGE-5393](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5393)
* Resolves [CASMTRIAGE-5394](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5394)
* `drax`
- Were new tests (or test …
> Add disasterRecovery to hms charts that use ETCD

- manifests/sysmgmt.yaml
Update hms-hmcollector to version 2.16.1
hmcollector 2.16.1 automatically removes stale redfish subscriptions. Stale subscriptions happen when the hardware is moved.
CASMHMS-5685
* https://github.com/Cray-HPE/hms-hmcollector/pull/49
https://github.com/Cray-HPE/hms-hmcollector-charts/pull/22
see PRs:
https://github.com/Cray-HPE/hms-hmcollector/pull/49
https://github.com/Cray-HPE/hms-hmcollector-charts/pull/22
* docker compose env
* …
> Update hms-hmcollector to version 2.16.1

- manifests/platform.yaml
Needed for a version that can run in k8s 1.22.
Bumps sealed secrets to 0.4.0 which includes an updated version of upstream sealed secrets that can work in k8s 1.22.
* Resolves CASMPET-6174
Tested by installing the updated sealed secrets on caleb and unsealing existing secrets.
* Virtual Shasta - caleb
Manually updated
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? no, caleb wasn't running a full csm stack 
- Were …
> Bump sealed secrets to 0.4.0

- manifests/platform.yaml
Bump the version of cray-nls and cray-iuf from 3.1.0 to 3.1.1. 
Update cray-nls image from "https://raw.githubusercontent.com/Cray-HPE/cray-nls/v0.10.9/docs/NLS_swagger.yaml" to "https://raw.githubusercontent.com/Cray-HPE/cray-nls/v0.10.10/docs/NLS_swagger.yaml"
> CASMINT-5749: update cray-nls and cray-iuf

- manifests/sysmgmt.yaml
Refactor structure for versioned releases, add power control functionality.
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6317
Verified image on redbull:
```
{
"vcluster-green-slurm"
],
{
"forcepoweroff": false,
"hsmgrouplabel": "green",
"xnames": [
"x3000c0s19b3n0"
]
},
{
"forcepoweroff": true,
"hsmgrouplabel": "green",
"type": "application",
"xnames": [
"x3000c0s32b0n0"
]
}
],
"uuid": "7450f2d0-1a7c-4f36-9898-8a73e6c9fc9a"
}
Deployed
```
Low
* …
> Automated power control on node exit/entry from/to tenant (CASMPET-6317)

- manifests/platform.yaml
Update precache images for K8S 1.22 
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6586
Verified image list on redbull with NCN image change.
Low
* Nothing
> Update precache images for K8S 1.22 (CASMPET-6586)

- CHANGELOG.md
- manifests/core-services.yaml
- manifests/platform.yaml
This PR addresses the following issues
The Kea API returns a HTTP response code 200 before dhcp-helper has run and generated the Kea configuration and populated the lease database.
This in turn can cause cray-dns-unbound-manager to delete records when it receives a 200 response from Kea but no leases.
The existing implementation also does not validate the generated Kea configuration before loading it which can leave the pod in a bad state, this PR now uses Kea to test the generated configuration before loading it ensuring the configuration is always valid.
cray-dhcp-kea now backup the generated configuration to the `cray-dhcp-kea-backup` ConfigMap. If the pod is restarted this configuration is used rather than rebuilding it from scratch.
Provide the option for a node to boot a manually …
> CASMTRIAGE-5222/CASMNET-2110 - restarting kea on large systems wipe DNS records from configmap

- manifests/platform.yaml
The previous network policy was not correctly implemented. This will allow dvs mqtt client to talk to the dvs activemq artemis server on clusters that have working NetworkPolicies
> CASMPET-6590 Update cray-drydock

- manifests/sysmgmt.yaml
This fixes an issue where NCNs are unable to connect to the spire-server.
> casmpet-6502 Update cray-spire to 1.4.0

- manifests/sysmgmt.yaml
Updates BOS to fix an issue that can occur on large systems when rebooting with v2 but not changing the artifacts being booted.  
* Resolves CASMCMS-8613
* Ashton
Tested new response code
None
> CASMCMS-8613: Update BOS to fix issue with v2 reboots (1.4)

- manifests/sysmgmt.yaml
Update UAS to use the new bitnami etcd chart.
Update python requirements for a clean build (and address dependabot security alerts)
* Resolves [CASMUSER-3148](https://jira-pro.it.hpe.com:8443/browse/CASMUSER-3148)
* `ashton`
```
cray-uas-mgr-556d5f5f88-gn2hd                                     2/2     Running            0          19m
cray-uas-mgr-556d5f5f88-pfmgv                                     2/2     Running            0          18m
cray-uas-mgr-bitnami-etcd-0                                       2/2     Running            0          29m
cray-uas-mgr-bitnami-etcd-1                                       2/2     Running            0          30m
cray-uas-mgr-bitnami-etcd-2                                       2/2     Running            0          31m …
```
> Update UAS to 1.23.0 for etcd bitnami

- manifests/core-services.yaml
This updates the cray-smd chart version for CASMHMS-5958 to allow HSM to discover ARM node architecture.
* Resolves [CASMHMS-5958](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5958)
For testing, see https://github.com/Cray-HPE/hms-smd/pull/114
Low
> CASMHMS-5958: Fix HSM Node Architecture Discovery for ARM

- lib/setup-nexus.sh
- rpm/cray/csm/noos/index.yaml
- rpm/cray/csm/sle-15sp2/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
This adds the `noos` repo, and moves one of the first packages to publish there into it (`platform-utils`).
> CASMINST-3421 CASMINST-6410 Add `noos` repo

- CHANGELOG.md
- manifests/platform.yaml
Adding priorityClassName csm-high-priority-service to the cray-vault-operator for CSM 1.5
* Resolves [CASMPET-6591](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6591)
* Change will also be needed in `NA`
drax (1.5.0-beta.1)
* Pre check using helm template
```
$ helm template .
apiVersion: apps/v1
kind: Deployment
metadata:
name: RELEASE-NAME-vault-operator
labels:
helm.sh/chart: vault-operator-1.16.1
app.kubernetes.io/name: vault-operator
app.kubernetes.io/instance: RELEASE-NAME
app.kubernetes.io/managed-by: Helm
spec:
strategy:
type: Recreate
replicas: 1
selector:
matchLabels:
app.kubernetes.io/name: vault-operator
template: …
```
> CASMPET-6591: Set priorityClassName for cray-vault-operator deployment

- manifests/platform.yaml
This reverts commit deacc5687ef2f7c4f6ea1a89b6186909ec459d39.
0.4.0 doesn't work on unsealing new secrets just revert this change for now.
Surtur …
> Revert "Bump sealed secrets to 0.4.0"

- manifests/sysmgmt.yaml
spire-server needs to be reinstalled if there's a problems. Backups will restore old authentication data that will cause unexpected issues.
> CASMPET-6580 Disable spire postgres backups

- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Updates the csm-ssh-keys Ansible content to pull in a change that will create a file with more restricted permissions to address a security concern.
* Resolves CASMCMS-8581
Tested by LANL
None
> CASMCMS-8581: Update csm-ssh-keys Ansible to restrict file permissions

- lib/setup-nexus.sh
- nexus-repositories.yaml
Fixes failing test in csm-install, which was waiting on `csm-${RELEASE_VERSION}-noos` to exist.
Fallout from #2299.
> CASMINST-3421 Fixup

- manifests/sysmgmt.yaml
Includes `csm-auth-utils` in the CFS `csm_packages` variable file.
CASMINST-3431 - includes the `noos` repo in the CFS `csm_repos` variable file.
> MTL-2016 New CFS play for `csm-auth-utils`

- CHANGELOG.md
- rpm/cray/csm/sle-15sp4/index.yaml
Discovered that we have two different master taint tests in goss.   One of them I added to 1.6 about 5 months ago.   Then a couple of months later when we were still hitting the master taint issue in 1.4, I looked for the test and didn't find it.   Therefore, I added the test to both 1.4 and main.    This resulted in the two different tests in main.
I am removing the one I added originally because the new test handles the case where ncn-m001 is not deployed yet.
I also added goss-check-taints.yaml to the ncn-kubernetes-tests-master suite.
* Resolves [CASMTRIAGE-5475](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5475)
* `surtur`
I ran `csm pit validate --k8s` after removing `goss-k8s-nodes-master-taint.yaml` from the `ncn-kubernetes-tests-master-single` suite.  I verified in the full …
> CASMTRIAGE-5475: Release csm-testing v1.16.35

- CHANGELOG.md
- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp4-compute/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
- Updating the `cfs-trust` versions to point to newer `noarch` rpms
> CASMCMS-8621: Add noarch rpms support for cfs-trust

- rpm/cray/csm/sle-15sp4/index.yaml
Addresses a failed goss test that broke from MTL-2139.
> MTL-2167 Fix goss test for ipxe files

- CHANGELOG.md
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Move cray-site-init RPM to 1.31.2 which makes the `bond0` interface on NCNs optional to permit vShasta to populate BSS, and adds public key authentication to the SSH invocations used when populating BSS. The SSH authentication will try to use public key authentication first, then fall back to password based authentication. In the case of a fallback, it will prompt for the password once. That password will then be used for any NCN that fails public key authentication. If any NCN fails both, SSH will retry password based authentication prompting for a new password (and tell the user which NCN it is trying to reach). Rinse and repeat.
In addition to this, if `bond0` cannot be found on an NCN, the code will now issue a warning and continue. This allows vShasta to work without having `bond0` …
> CASMINST-6333 Bump CSI to 1.31.3

- manifests/sysmgmt.yaml
The hostPath has changed for this chart. However, the PSP was not updated along with this path change, causing the spire-jwks service to fail to start. This fixes the permission issue.
> casmpet-6615 Bump cray-spire to 1.4.2

- rpm/cray/csm/noos/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
New `ilorest` 4.2.0.0 provides Gen11 support, and can be pulled from SP4 and noos repos. It'll be mentioned in both sp4 and noos until we're ready to just use the noos copy.
> MTL-2165 New `ilorest`

- CHANGELOG.md
- manifests/platform.yaml
Fix manifest error, cray-precache-images was not configured to cache the version of cray-dhcp-kea that was shipped.
* Resolves [CASMTRIAGE-5494](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5494)
* `fanta`
Re-deployed cray-precache-images with new values, the correct version of cray-dhcp-kea is now cached.
```
ncn-m002:~ # kubectl -n nexus logs cray-precache-images-8kgm8 | grep -A1 cray-dhcp-kea
Caching image: artifactory.algol60.net/csm-docker/stable/cray-dhcp-kea:0.10.23
Image is up to date for sha256:8ba80b66441bf09e4929927e2764c49d89ad0fc93859afd605b37ade4d5aeea8
```
> CASMTRIAGE-5494 - csm-1.3.4 upgrade failure pulling image: connection refused

- CHANGELOG.md
- manifests/platform.yaml
Fix manifest error, cray-precache-images was not configured to cache the version of cray-dhcp-kea that was shipped.
* Resolves [CASMTRIAGE-5494](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5494)
* `fanta`
Re-deployed cray-precache-images with new values, the correct version of cray-dhcp-kea is now cached.
```
ncn-m002:~ # kubectl -n nexus logs cray-precache-images-8kgm8 | grep -A1 cray-dhcp-kea
Caching image: artifactory.algol60.net/csm-docker/stable/cray-dhcp-kea:0.10.23
Image is up to date for sha256:8ba80b66441bf09e4929927e2764c49d89ad0fc93859afd605b37ade4d5aeea8
```
> CASMTRIAGE-5494 - upgrade failure pulling image: connection refused

- manifests/platform.yaml
Exclude wait-for jobs from auto three day cleanup
* https://jira-pro.it.hpe.com:8443/browse/CASMINST-6453
Drax:
```
cray-bss-567f949774-46q6t                                         2/2     Running            0          3h7m
cray-bss-567f949774-dxbtt                                         2/2     Running            0          32m
cray-bss-567f949774-xvk2t                                         2/2     Running            0          3h20m
```
```
ncn-m001:~ # kubectl get job -n services cray-bss-wait-for-etcd-3 -o yaml | grep ttl
ncn-m001:~ #
```
Low
* Nothing
> Exclude wait-for jobs from auto three day cleanup (CASMINST-6453)

- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Fixing a bug with the API spec regular expressions introduced a new bug for creating session templates. This updates to a BOS version with the new bug fixed. See source PR for details.
* Resolves [CASMINST-6451](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6451)
* Caused by fix for [CASMTRIAGE-5367](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5367).
* [Source PR](https://github.com/Cray-HPE/bos/pull/146)
* [PR to update 1.3 hotfix](https://github.com/Cray-HPE/csm-hotfixes/pull/20)
* [1.4 manifest PR](https://github.com/Cray-HPE/csm/pull/2324)
* [1.3 manifest PR](https://github.com/Cray-HPE/csm/pull/2325)
See source PR for details.
Low risk. See source PR for details.
> CASMINST-6451: Fix bug creating BOS session templates

- manifests/platform.yaml
Update trustedcerts-operator to 0.8.1 which bumps all crd resources from using v1beta1 api to v1
* Resolves CASMPET-6605
Grog and fearne
- …
> CASMPET-6605: trustedcerts-operator to 0.8.1

- manifests/sysmgmt.yaml
The nightly rebuilds were picking up a version of ims-python-helper that was too new to use with this release. I pinned the version of the python module to what was needed for this release, so it will not pick up the newer versions.
Code PR's:
https://github.com/Cray-HPE/ims-utils/pull/57
https://github.com/Cray-HPE/ims-kiwi-ng-opensuse-x86_64-builder/pull/51
* Resolves [CASMINST-6450](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6450)
* `Fanta`
I duplicated the problem that NERSC was seeing with the install, then tested the new versions of the dependent images and observed them work correctly. …
> CASMINST-6450 - pin ims dependencies for csm-1.3.4 release.

- manifests/platform.yaml
Updates sealed secrets to latest release for 1.22 compatibility.
* Resolves [CASMPET-6604]
fearne/grog
I've got an update to the sealed-secrets readme but I ran through creating a new secret, updating it, deleting it after upgrading to this new version on 1.22 (fearne) and grog (when it was 1.21) this version of sealed secrets should still run on any 1.16+ cluster but for now lets constrain …
> CASMPET-6604: Update sealed-secrets to 0.4.1

- CHANGELOG.md
- manifests/platform.yaml
- vendor/github.com/Cray-HPE/shasta-cfg/customizations.yaml
This moves the istiogateway-cmn to use the customer admin pods instead of the istio-ingressgateway pods.
* Resolves [CASMPET-5797](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5797)
* Additional PR to be merged at the same time https://github.com/Cray-HPE/docs-csm/pull/3854
* ashton
- Was upgrade tested? …
> CASMPET-5797: Move istio-ingressgateway-cmn to customer-admin

- manifests/sysmgmt.yaml
In hms-rts-charts updated cert-manager version for the k8s 1.22 upgrade.
* Resolves [CASMHMS-5879](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-5879)
* drax
- Were continuous integration tests run? If not, why? Yes
- Was downgrade tested? If not, why? Yes
- Were new tests (or test issues/Jiras) created for this change? Yes
> Updated cray-rts version to 4.0.0

- docker/index.yaml
- manifests/platform.yaml
- manifests/sysmgmt.yaml
As part of the initiative CASM-3946 for enhancing IUF logging, modified various repo whose PR's are listed below. Updating CSM with the latest image versions of all the products. 
https://github.com/Cray-HPE/cray-nls/pull/179                               - CASM-4314
https://github.com/Cray-HPE/cray-product-catalog/pull/228         - CASM-4224
https://github.com/Cray-HPE/iuf-containers/pull/16                       - CASM-4225/CASM-4226
https://github.com/Cray-HPE/nexus-setup/pull/25                          - CASM-4227/CASM-4228/CASM-4229/CASM-4230
https://github.com/Cray-HPE/cf-gitea-import/pull/84                     - CASM-4231
https://github.com/Cray-HPE/ims-load-artifacts/pull/62                 - CASM-4232
https://github.com/Cray-HPE/ims-python-helper/pull/41               - …
> CASM-3946: Logging improvements for IUF

- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
* Update the BSS API spec to remove references to long-dead ARS
* Update the Cray CLI with the updated BSS API spec
* Remove long-defunct ARS code from Cray CLI
* Minor language linting of Cray CLI
* [Cray CLI source PR for BSS/ARS changes](https://github.com/Cray-HPE/craycli/pull/108)
* [Cray CLI source PR for linting changes](https://github.com/Cray-HPE/craycli/pull/107)
* [BSS source PR](https://github.com/Cray-HPE/hms-bss/pull/60)
* Resolves [CASMCMS-8651](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8651)
* Resolves [CASMCLOUD-1220](https://jira-pro.it.hpe.com:8443/browse/CASMCLOUD-1220)
See source PRs for details.
Very low risk. ARS is long gone. See source PRs for details.
> CASMCMS-8651/CASMCLOUD-1220: Remove ARS from Cray CLI; remove references to ARS from BSS API spec

- docker/index.yaml
- manifests/platform.yaml
cray-sysmgmt-health fails to install on k8s 1.22
[CASMTRIAGE-5496](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5496)
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-282
https://jira-pro.its.hpecorp.net:8443/browse/CASM-3884
Implementation of the upgraded jettech/kube-webhook-certgen image from 1.2.1 to 1.3.0
Updating the grafterm version in index.yaml for the CASM-3884: Upgrade Prometheus Operator to latest version.
This PR includes index.yaml file change for same.
Tested on Starlord system.
All images and chart gets deployed without issues -
```
ncn-m001:/mnt/developer/sum # kubectl get all -n sysmgmt-health
NAME                                                                READY   STATUS      RESTARTS   AGE …
```
> CASMTRIAGE-5496 cray-sysmgmt-health fails to install on k8s 1.22 - main

- docker/index.yaml
- manifests/platform.yaml
cray-sysmgmt-health fails to install on k8s 1.22
[CASMTRIAGE-5496](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5496)
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-282
https://jira-pro.its.hpecorp.net:8443/browse/CASM-3884
Implementation of the upgraded jettech/kube-webhook-certgen image from 1.2.1 to 1.3.0
Updating the grafterm version in index.yaml for the CASM-3884: Upgrade Prometheus Operator to latest version.
This PR includes index.yaml file change for same.
Tested on Starlord system.
All images and chart gets deployed without issues -
```
ncn-m001:/mnt/developer/sum # kubectl get all -n sysmgmt-health
NAME                                                                READY   STATUS      RESTARTS   AGE …
```
> CASMTRIAGE-5496 cray-sysmgmt-health fails to install on k8s 1.22 - stable/1.5

- docker/index.yaml
- lib/setup-nexus.sh
Update the `cray-sat` container image version to 3.23.0.
* Resolves [CRAYSAT-1725](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1725)
> CRAYSAT-1725: Update cray-sat container image version

- manifests/sysmgmt.yaml
This updates the helm chart version for:
CASMHMS-5995 - Changes PCS to utilize PowerMaps from HSM when available to honor power hierarchy failures when PDU outlets are involved.
CASMHMS-5998 - Fixes a memory leak in the transition and power-cap domain functions.
CASMHMS-5996 - This fixes a naming inconsistency between snapshots and parsing HSM data inside PCS.
* Resolves [CASMHMS-5995](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5995)
* Resolves [CASMHMS-5998](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5998)
* Resolves [CASMHMS-5996](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5996)
For testing, see https://github.com/Cray-HPE/hms-power-control/pull/34
low
> CASMHMS-5995: Utilize HSM PowerMaps in PCS

- manifests/sysmgmt.yaml
This updates the helm chart version for:
CASMHMS-5995 - Changes PCS to utilize PowerMaps from HSM when available to honor power hierarchy failures when PDU outlets are involved.
CASMHMS-5998 - Fixes a memory leak in the transition and power-cap domain functions.
* Resolves [CASMHMS-5995](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5995)
* Resolves [CASMHMS-5998](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5998)
For testing, see https://github.com/Cray-HPE/hms-power-control/pull/34
low
> CASMHMS-5995: Utilize HSM PowerMaps in PCS CSM 1.4

- manifests/platform.yaml
cray-sysmgmt-health fails to install on k8s 1.22 using jettech/kube-webhook-certgen:v1.3.0 as well.
This PR uses the registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.3.0 to fix it.
[CASMMON-322](https://jira-pro.it.hpe.com:8443/browse/CASMMON-322)
Implementation of the registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.3.0 image.
Tested on vShasta Ashton system.
All images and chart gets deployed without issues -
```
Type    Reason          Age   From               Message
----    ------          ----  ----               -------
Normal  Scheduled       65s   default-scheduler  Successfully assigned sysmgmt-health/cray-sysmgmt-health-kube-p-admission-patch-qjkcb to ncn-w003
Normal  AddedInterface  65s   multus             Add eth0 …
```
> CASMMON-322 jettech/kube-webhook-certgen:v1.3.0 doesn't work with k8s 1.22 - stable/1.5

- manifests/platform.yaml
cray-sysmgmt-health fails to install on k8s 1.22 using jettech/kube-webhook-certgen:v1.3.0 as well.
This PR uses the registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.3.0 to fix it.
[CASMMON-322](https://jira-pro.it.hpe.com:8443/browse/CASMMON-322)
Implementation of the registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.3.0 image.
Tested on vShasta Ashton system.
All images and chart gets deployed without issues -
```
Type    Reason          Age   From               Message
----    ------          ----  ----               -------
Normal  Scheduled       65s   default-scheduler  Successfully assigned sysmgmt-health/cray-sysmgmt-health-kube-p-admission-patch-qjkcb to ncn-w003
Normal  AddedInterface  65s   multus             Add eth0 …
```
> CASMMON-322 jettech/kube-webhook-certgen:v1.3.0 doesn't work with k8s 1.22 - main

- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
(cherry picked from commit e26744f8aa0f73db307e2b4a63fda8634c968fdb)
from https://github.com/Cray-HPE/csm/pull/2346
> CASMCMS-8651: Remove ARS from Cray CLI; remove references to ARS from BSS API spec

- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
This reverts commit 965b1441761cc4eb9a76a1c1431ecada5feb188a.
Restore the contents of this PR:
https://github.com/Cray-HPE/csm/pull/2346
> Revert "Revert "CASMCMS-8651/CASMCLOUD-1220: Remove ARS from Cray CLI; remove references to ARS from BSS API spec""

- docker/index.yaml
Adds k8s 1.22.13 images for precaching support. While here remove a duplicate key for docker.io/coredns/coredns:1.6.2 that appears to be overridden later and not in use. A similar action was done for 1.4 but never brought into main.
* Resolves CASMPET-6638 …
> CASMPET-6638: Add k8s 1.22.13 images, remove duplicate key

- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Switch craycli from deprecated keycloak client
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6640
Tested on ashton during MT OPA demo
Low
* Nothing
> Change craycli to use shasta keycloak client instead of deprecated cray client (CASMPET-6640)

- CHANGELOG.md
- rpm/cray/csm/noos/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
This updates the fix-spire-on-storage.sh script to use the new spire server, cray-spire-server. This is used as part of the migration from 0.12.2 to 1.5.5
> CASMPET-6643 Update platform-utils to 1.6.0

- CHANGELOG.md
- manifests/core-services.yaml
- manifests/platform.yaml
If a client issues a query for a record in the hsn local-zone that Unbound can't answer then the query will be forwarded to the site DNS server which is undesirable.
* Resolves [CASMNET-2139](https://jira-pro.it.hpe.com:8443/browse/CASMNET-2139), [CASMTRIAGE-5515](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5515)
* `mug`
Tested change on mug, verified query for a record that doesn't exist isn't being forwarded to site DNS.
Old behaviour
```
[1686672774] unbound[11:0] info: resolving x3000c0s30b2n0h1.hsn. A IN
[1686672774] unbound[11:0] info: processQueryTargets: x3000c0s30b2n0h1.hsn. A IN
[1686672774] unbound[11:0] info: sending query: x3000c0s30b2n0h1.hsn. A IN
[1686672774] unbound[11:0] debug: sending to target: <.> 16.110.135.51#53
[1686672774] unbound[11:0] debug: cache memory …
```
> CASMNET-2139 - Unbound should not forward .hsn queries to the site DNS

- manifests/sysmgmt.yaml
Fixes an issue where a wrapper used to handle multi-tenancy on the v1 endpoints was changing the signature of the function.
Also updates the tapms endpoint used by BOS.
* Resolves CASMTRIAGE-5525
* Resolves CASMCMS-8665
See individual tickets
None
> CASMTRIAGE-5525: Fixes BOS v1 error from multi-tenancy changes

- manifests/sysmgmt.yaml
Add arm64 support to the installed barebones image recipe. There are now 2 recipes installed - one for x86_64 and one for arm64. There is still only one pre-built image installed - the x86 version.
* Resolves [CASMCMS-8365](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8365)
* `Mug`
I installed the new versions via helm deployment, then built both recipes successfully on Mug.
This is a fairly low risk change. It just adds one more recipe that isn't used in the install or by most users.
> CASMCMS-8365 - add arm64 support to barebones image.

- CHANGELOG.md
- manifests/core-services.yaml
- manifests/platform.yaml
External DNS changed the format of their TXT records in version 0.12. The TXT record now contains a prefix indicating the record type e.g. a-foo.example.com which means it no longer directly matches the corresponding A record.
A second bug was also identified where the `allZones` slice was being sorted while being iterated over which messed up zone processing and caused some zones to get processed twice and others not at all.
* Resolves [CASMNET-2122](https://jira-pro.it.hpe.com:8443/browse/CASMNET-2122)
* Ashton
* Tested using the following
* Helm chart: cray-externaldns 1.5.0-20230511191813+6f5436c
* Image: artifactory.algol60.net/csm-docker/stable/docker.io/bitnami/external-dns  0.13.4-debian-11-r14
* Verified externaldns-manager no longer crashes when a …
> CASMNET-2122 - cray-externaldns-manager crashes when used with external-dns 0.13

- CHANGELOG.md
- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Updates both `IMS` and `craycli` to reflect changes required for default handling for kernel file names when calling `IMS` from the cli.
* Resolves [CASMCMS-8624](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8624)
* `mug`
> CASMCMS-8624: craycli 0.82.2 ims 3.9.3

- CHANGELOG.md
- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Updates both IMS and craycli to reflect changes required for default handling for kernel file names when calling IMS from the cli. Backport to 1.5 stable.
Resolves [CASMCMS-8624](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8624)
* `Mug`
> CASMCMS-8624: Update IMS, Craycli

- CHANGELOG.md
- docker/index.yaml
- lib/setup-nexus.sh
- manifests/platform.yaml
Corresponding docs-csm PR: https://github.com/Cray-HPE/docs-csm/pull/3891
Do not merge docs-csm PR before merging this PR.
Remove installation of dependencies using zypper entirely to rely upon the host for dependencies.
We are removing these because the dependencies in the host are more up-to-date, as opposed to the embedding them within this container which doesn't get updated often.
Yes
* Resolves [CASM-4352](https://jira-pro.it.hpe.com:8443/browse/CASM-4352)
* Merged code PR: https://github.com/Cray-HPE/iuf-containers/pull/18
Drax
Removed internally embedded dependencies from …
> CASM-4352 Remove installation of dependencies using zypper entirely to rely upon the host for dependencies

- CHANGELOG.md
- docker/index.yaml
- lib/setup-nexus.sh
- manifests/platform.yaml
Corresponding docs-csm PR: https://github.com/Cray-HPE/docs-csm/pull/3892
Do not merge docs-csm PR before merging this PR.
Remove installation of dependencies using zypper entirely to rely upon the host for dependencies.
We are removing these because the dependencies in the host are more up-to-date, as opposed to the embedding them within this container which doesn't get updated often.
Yes
* Resolves [CASM-4352](https://jira-pro.it.hpe.com:8443/browse/CASM-4352)
* Merged code PR: https://github.com/Cray-HPE/iuf-containers/pull/18
Drax
Removed internally embedded dependencies from …
> CASM-4352 Backport to release/1.4

- CHANGELOG.md
- docker/index.yaml
- lib/setup-nexus.sh
- manifests/platform.yaml
Remove installation of dependencies using zypper entirely to rely upon the host for dependencies.
We are removing these because the dependencies in the host are more up-to-date, as opposed to the embedding them within this container which doesn't get updated often.
Yes
* Resolves [CASM-4352](https://jira-pro.it.hpe.com:8443/browse/CASM-4352)
* Merged code PR: https://github.com/Cray-HPE/iuf-containers/pull/18
Drax
Removed internally embedded dependencies from the image, volume mounted the host /usr/bin directory, appended the $PATH inside the container, and checked if the …
> CASM-4352 Backport to stable/1.5

- manifests/sysmgmt.yaml
Modifies the cms-ipxe deployment that builds ipxe binaries used to chain to BSS bootscripts produce both x86 and aarch64 versions.
* Resolves [CASMCMS-8505](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8505)
See extensive testing done as part of associated tickets.
* `tyr`
Helmcharts were deployed in full on `tyr`; the resultant ipxe binaries for x86 and aarch64 were vetted on system.
Low; though these building images are larger than their predecessor so that they can perform cross compiles.
> Bump cms-ipxe for aarch64 crosscompile building

- manifests/sysmgmt.yaml
Added virtiofs daemon configuration annotation to IMS configmaps. This resolves a bug where images built without DKMS  and subsequently customized with DKMS enabled would result in filesystem extended attributes failing to write.
* Resolves [CASMCMS-8362](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8362)
This fix was tested on the Mug system.
Added the annotations to IMS configmaps and ran jobs successfully.
The bug was the risk. 
No risk that I can foresee for this inclusion.
> increment ims version to 3.9.5

- Jenkinsfile.github
- hack/gen-rpm-index.sh
- lib/setup-nexus.sh
- nexus-repositories.yaml
- release.sh
- rpm/cray/csm/sle-15sp5/index.yaml
- validate.sh
The main purpose of this PR is just to add the SLES15SP5 noarch RPMs into Nexus, for use on Arm64 computes in CSM 1.5. But I noticed that a bunch of scripts referenced Artifactory RPM repos for SP4 but excluded the SP5 resources on there. I updated them to include the corresponding SP5 repos. Note that some of the repos which exist on artifactory for SP4 do not exist for SP5 -- in those cases, I omitted the nonexistent SP5 versions.
> Add CMS SLES15SP5 noarch RPMs for Arm computes; add relevant Artifactory repos to relevant scripts

- manifests/platform.yaml
Chart version is bumped due to changes submitted for Kyverno upgrade from version 1.6.2 to 1.7.5
The changes are submitted through the PR mentioned below,
https://github.com/Cray-HPE/cray-kyverno/pull/17
Testing: Tested on MUG:
[TestLogs14.txt](https://github.com/Cray-HPE/csm/files/11849464/TestLogs14.txt)
> CASMSEC-400: Update platform.yaml for kyverno upgrade

- manifests/platform.yaml
Chart version is bumped due to changes submitted for Kyverno upgrade from version 1.6.2 to 1.7.5
The changes are submitted through the PR mentioned below,
https://github.com/Cray-HPE/cray-kyverno/pull/18
Testing: Tested on MUG
[TestLogs15.txt](https://github.com/Cray-HPE/csm/files/11849501/TestLogs15.txt)
> CASMSEC-397: Kyverno Upgrade Needed for N-2 Support Policy

- rpm/cray/csm/noos/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
These version bumps include some build pipeline (CI) related fixes, and change our manifests to including them via the `noos` repo.
> MTL-2171 No-op Builds

- docker/index.yaml
- lib/setup-nexus.sh
Update the cray-sat container to version 3.24.0, which is the latest version included in the latest SAT 2.6 release.
* Partially resolves [CRAYSAT-1738](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1738)
* Jenkins
The individual features included in this new version of cray-sat were tested on various development systems during development.
Jenkins should be sufficient to test the build of the CSM product with the changes in this PR.
No.
> CRAYSAT-1738: Update cray-sat container version

- manifests/platform.yaml
cray-sysmgmt-health grok-exporter node affinity is wrong for mercury. It is using ncn-m001, ncn-m002 and ncn-m003 by default. But mercury has no NCNs and it will fail.
_This change is a backward-compatible bugfix_
* Resolves [CASMPET-6651](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6651)
* https://jira-pro.it.hpe.com:8443/browse/CASMMON-323
https://jira-pro.it.hpe.com:8443/browse/CASMMON-321
https://jira-pro.it.hpe.com:8443/browse/CASMMON-327
* `<frigg>`
* `<Mug>`
* `<Starlord>`
* Virtual Shasta - Ashton
* Mercury
_The changes tested and success verified._
```
sysmgmt-health   cray-sysmgmt-health-grok-exporter-6dfd6c455b-9r7xn                1/1     Running                      0              3m20s   10.32.128.5     k8s-master-sigma7-3    <none> …
```
> CASMPET-6651, CASMMON-321, 323 & 327 - stable/1.5

- manifests/platform.yaml
cray-sysmgmt-health grok-exporter node affinity is wrong for mercury. It is using ncn-m001, ncn-m002 and ncn-m003 by default. But mercury has no NCNs and it will fail.
_This change is a backward-compatible bugfix_
* Resolves [CASMPET-6651](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6651)
* https://jira-pro.it.hpe.com:8443/browse/CASMMON-323
https://jira-pro.it.hpe.com:8443/browse/CASMMON-321
https://jira-pro.it.hpe.com:8443/browse/CASMMON-327
* `<frigg>`
* `<Mug>`
* `<Starlord>`
* Virtual Shasta - Ashton
* Mercury
_The changes tested and success verified._
```
sysmgmt-health   cray-sysmgmt-health-grok-exporter-6dfd6c455b-9r7xn                1/1     Running                      0              3m20s   10.32.128.5     k8s-master-sigma7-3    <none> …
```
> CASMPET-6651, CASMMON-321, 323 & 327 - main

- CHANGELOG.md
- rpm/cray/csm/noos/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
(1) Remove the patronictl version case and use the code that is currently defined under 1.6.5. The output format for 1.6.5 is the same as that for 2.1.4.  Version 1.6.4 was needed for CSM 1.2.
(2) Also modify the test so that it can distinguish between spire-postgres and cray-spire-postgres – spire-postgres will be removed in the future, but it is possible that both could exist until CSM 1.6.
* Resolves [CASMPET-6659](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6659)
* Change will also be needed in `NA`
* Merge with/before/after `NA`
Although the change is not needed for CSM 1.4, tested on CSM 1.4 and CSM …
> CASMPET-6659 1.5 : Fix ncnPostgresHealthCheck for version and spire issues

- manifests/sysmgmt.yaml
Update to ETCD portion of chart due to release critical issue in the old ETCD chart.
* Resolves [CASMHMS-6047](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6047)
* Resolves [CASMHMS-6048](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6048)
* Resolves [CASMHMS-6049](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6049)
* Resolves [CASMHMS-6050](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6050)
* Resolves [CASMHMS-6051](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6051)
Tested on:
* `ashton`
Test description:
Validate I can deploy the new chart and the proper version of ETCD was included. …
> Hms etcd rc updates

- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp2-compute/index.yaml
- rpm/cray/csm/sle-15sp3-compute/index.yaml
- rpm/cray/csm/sle-15sp4-compute/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Revert changes to BOS API spec which caused a breakage in the v1 session status update code.
* Resolves [CASMTRIAGE-5575](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5575) for CSM 1.4
> CASMTRIAGE-5575: Fix BOS session status error

- CHANGELOG.md
- manifests/platform.yaml
- vendor/github.com/Cray-HPE/shasta-cfg/customizations.yaml
This update the upstream url for the customer management proxy to allow for a disconnection from the nmn gateway for all cmn traffic.
* Resolves [CASMPET-6664](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6664)
* Additional changes needed in [CASMPET-6664](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6664)
* drax
Tested by manually updating the URL and discovered there was also a need for a customization change to allow for a different upstream url with a updated certificate
- Were continuous integration tests run? If not, why?y
- Was upgrade tested? If not, why?y
- Was …
> CASMPET-6664: Update oauth2-proxies to use cmn gateway

- manifests/core-services.yaml
Rebuilt sls and smd to use the latest base-charts. 10.0.2 for cray-service and 1.0.1 for cray-postgres. These new charts don't use any k8s deprecated APIs
* Resolves [CASMHMS-5880](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-5880)
* Resolves [CASMHMS-5881](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-5881)
> Updated sls to 5.1.1 and smd to 7.0.4 for the k8s 1.22 upgrade

- manifests/platform.yaml
Bumping up the kyverno-policy chart version as we have submitted 2 new policies for gitea through PR https://github.com/Cray-HPE/cray-kyverno-policies/pull/11
ncn-m001:/tmp/pradeep # kubectl get pol -A | grep -i gitea
ncn-m001:/tmp/pradeep # cd ../kyverno/
ncn-m001:/tmp/kyverno # ls -ltr
total 112
-rw-r--r-- 1 root root 51772 Jun 23 14:22 cray-kyverno-1.5.3.tgz
-rw-r--r-- 1 root root 51772 Jun 23 14:23 cray-kyverno-1.4.3.tgz
-rw-r--r-- 1 root root  6283 Jun 23 14:46 kyverno-policy-1.4.3.tgz
ncn-m001:/tmp/kyverno # helm upgrade -n kyverno kyverno-policy /tmp/kyverno/kyverno-policy-1.4.3.tgz^C
ncn-m001:/tmp/kyverno # helm ls -n kyverno
NAME                            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART …
> CASMCMS-8290: Update platform.yaml for gitea vcs policy addition

- manifests/platform.yaml
- vendor/github.com/Cray-HPE/shasta-cfg/customizations.yaml
Backport of https://github.com/Cray-HPE/csm/pull/2329. Cherry-picked from  for branch stable/1.5.
> [Backport stable/1.5] CASMPET-5797: Move istio-ingressgateway-cmn to customer-admin

- CHANGELOG.md
- manifests/platform.yaml
Backport of https://github.com/Cray-HPE/csm/pull/2397. Cherry-picked from  for branch stable/1.5.
> [Backport stable/1.5] CASMTRIAGE-5527: Update keycloak to address upstream bug

- CHANGELOG.md
- manifests/core-services.yaml
- manifests/platform.yaml
- rpm/cray/csm/noos/index.yaml
Backport of https://github.com/Cray-HPE/csm/pull/2399. Cherry-picked from  for branch stable/1.5.
> [Backport stable/1.5] CASMNET-2095, MTL-2018, MTL-2019

- CHANGELOG.md
- rpm/cray/csm/noos/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Backport of https://github.com/Cray-HPE/csm/pull/2425. Cherry-picked from  for branch stable/1.5.
> [Backport stable/1.5] CASMPET-6659 1.5 : Fix ncnPostgresHealthCheck for version and spire issues

- CHANGELOG.md
- manifests/platform.yaml
- vendor/github.com/Cray-HPE/shasta-cfg/customizations.yaml
Backport of https://github.com/Cray-HPE/csm/pull/2432. Cherry-picked from  for branch stable/1.5.
> [Backport stable/1.5] CASMPET-6664: Update oauth2-proxies to use cmn gateway

- CHANGELOG.md
- docker/index.yaml
Latest version 2.6.0 of `ims-load-artifacts` is required for arch IUF manifest changes to process correctly.
Must merge with:
https://github.com/Cray-HPE/cray-nls/pull/181 - [CASMCMS-8623](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8623)
> CASMCMS-8623: Updating latest ims-load-artifacts

- rpm/cray/csm/sle-15sp4/index.yaml
The cmsdev test tool failed to compress test artifacts recently when bzip2 was not found on the node where it was running. This modifies cmsdev to use the more widely available gzip for artifact compression. No functional change to the tests, and no change to good path behavior of the tool (artifacts are only collected on failure)
Tested on drax -- forced a failure of a test and verified that the gzip compression worked.
Low risk.
> CASMTRIAGE-5598: cmsdev: Compress test artifacts using gzip on failure

- manifests/platform.yaml
> Revert "[Backport stable/1.5] CASMTRIAGE-5599: Update platform manifest to use 1.7.5 kyverno as 1.6…"

- manifests/sysmgmt.yaml
There are 2 issues wrapped together in this hotfix:
CASMCMS-8686 - fix jobs record scheme change on helm update.
CASMCMS-8687 - fix global require-dkms setting usage.
Both were found when doing more extensive testing of the csm-1.5 release version of IMS.
Code PR: https://github.com/Cray-HPE/ims/pull/87
* Resolves [CASMCMS-8686](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8686)
* Resolves [CASMCMS-8687](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8687)
* `Mug`
I did a clean install of the csm-1.4 version of IMS on Mug, then did helm upgrade/downgrade testing to insure the schema of the jobs records is correctly updated, and the global require-dkms flag is being used as expected.
- …
> CASMCMS-8686/8687 - ims fixes for dkms and job records.

- docker/index.yaml
- lib/setup-nexus.sh
This resolves 6 vulnerabilities detected by Snyk scanning.
* Resolves [CRAYSAT-1742](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1742)
* Corresponding update to the SAT 2.5 product release distribution is here: https://github.com/Cray-HPE/sat-product-stream/pull/53
* Jenkins
Jenkins build will test that the cray-sat container image version specified can be pulled.
Performed a quick smoke test of the cray-sat:3.21.6 container image by downloading it on mug and running `sat status` and `sat showrev` which exercised access to CSM APIs, K8s API, and S3 API.
Low risk.
> CRAYSAT-1742: Update cray-sat version from 3.21.5 to 3.21.6

- manifests/platform.yaml
New metric-server image for K8S 1.22, fixes namespace delete issue
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6639
Tested on ashton:
```
pit:~/brad # kubectl delete -f ./blue.yaml -n tenants
tenant.tapms.hpe.com "vcluster-blue" deleted
```
```
pit:~/brad # kubectl get ns | grep blue
pit:~/brad
```
```
pit:~ # helm history -n kube-system cray-metrics-server
REVISION	UPDATED                 	STATUS    	CHART                    	APP VERSION	DESCRIPTION
1       	Sun Jun 25 14:37:38 2023	superseded	cray-metrics-server-0.4.1	v0.3.6     	Install complete
2       	Wed Jun 28 17:23:51 2023	deployed  	cray-metrics-server-0.5.0	v0.6.3     	Upgrade complete
```
```
pit:~/brad # kubectl logs -n kube-system metrics-server-86bff57b87-cw2j4
I0628 17:30:26.279095       1 serving.go:342] Generated …
```
> Update metrics-server to K8S 1.22 compatible version (CASMPET-6639)

- manifests/sysmgmt.yaml
Included is a new ansible reference role to be used as a method for introspecting specific settings that are set by IMS in the context of image customization, in particular as it pertains to DKMS and IMS image architecture.
* Resolves [CASMCMS-8537](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8537)
> CASMCMS-8537: Include new reference role for introspecting IMS variables

- rpm/cray/csm/sle-15sp4/index.yaml
When iPXE started building binaries for additional architectures, it ended up creating additional pods, and also changed the behavior of its settings configmap. All of these things resulted in the existing iPXE test failing. This PR updates to a version of the test which has been updated to account for these changes. The updated test verifies that the binaries for the different architectures are being successfully built and are able to be TFTPed.
* Resolves [CASMCMS-8504](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8504)
* Resolves [CASMTRIAGE-5597](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5597)
* [Source PR](https://github.com/Cray-HPE/cms-tools/pull/114)
* [stable/1.5 backport PR](https://github.com/Cray-HPE/csm/pull/2478)
Tested on ashton (installed with 1.5.0-alpha.66). …
> CASMCMS-8504: cmsdev: Update test to support iPXE binaries for multiple architectures being built

- docker/index.yaml
- lib/setup-nexus.sh
Update the version of the cray-sat container image. This will pull in support for specifying the new DKMS parameter in layers of CFS configurations created by `sat bootprep`.
* Resolves [CRAYSAT-1741](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1741)
* Corresponding update to the SAT 2.6 release: https://github.com/Cray-HPE/sat-product-stream/pull/54
* mug
This new version of the cray-sat container image was tested as described in the commit and pull request to the sat repository.
Low risk.
> CRAYSAT-1741: Update cray-sat version

- rpm/cray/csm/sle-15sp4/index.yaml
In CSM 1.5, cray-ipxe now has two pods -- one which builds x86-64 binaries, and one which builds aarch64. The labels of these pods are both different from the previous iPXE pod label, which is causing a Goss test to fail. This test is run to ensure that NCN boots will work, so in that context we are only concerned with the x86-64 iPXE pod. The cmsdev test tool already includes more complete test coverage of iPXE, including the new aarch64 binaries, so it doesn't make sense to duplicate that here.
This modifies the test to use the correct label for the x86-64 pod.
* Resolves [CASMTRIAGE-5616](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5616)
* Related to the changes made to cmsdev with [CASMCMS-8504](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8504)
* [Source …
> CASMTRIAGE-5616: Update Goss iPXE test to look for the x86-64 iPXE pod

- rpm/cray/csm/noos/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Change health script to check for a dynamic list of etcd clusters when verifying we've got a backup in the past 24 hours.
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6668
Tested on ashton:
```
ncn-m002:~/brad # ./ncnHealthChecks.sh -s etcd_backups_check
**************************************************************************
=== Verify etcd clusters have a backup in the last 24 hours. ===
=== The complete list of backups can be listed as follows:
=== % /opt/cray/platform-utils/etcd/etcd-util.sh list_backups -
Wed 28 Jun 2023 08:00:52 PM UTC
-- cray-bos -- backups
PASS: backup found less than 24 hours old.
-- cray-bss -- backups
PASS: backup found less than 24 hours old.
-- cray-fas -- backups
PASS: backup found less than 24 hours old.
-- cray-hbtd -- backups
PASS: backup found …
```
> Fix etcd backups check to dynamically list the clusters (CASMPET-6668)

- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
In CSM 1.4, BOS added the include_disabled option when creating V2 sessions. This exposes that option for use in the CLI. This adds a single flag to a single BOS CLI command.
* Resolves [CASMCMS-8599](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8599)
* [stable/1.5 backport PR](https://github.com/Cray-HPE/csm/pull/2487)
* [release/1.4 backport PR](https://github.com/Cray-HPE/csm/pull/2489)
* [metal-provision main PR](https://github.com/Cray-HPE/metal-provision/pull/225)
* [metal-provision lts/csm-1.5 PR](https://github.com/Cray-HPE/metal-provision/pull/226)
Ran CLI regression tests (including a new test added to cover this option specifically).
Low risk -- single new option to single BOS command.
> CASMCMS-8599: Add CLI support for BOS v2 session include_disabled option

- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Change --tenant argument to be optional to prevent BW incompatible change for non-interactive use cases.
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6649
Tested on ashton:
```
ncn-m003:~/.config/cray/configurations # cray init --hostname https://api-gw-service-nmn.local
Overwrite configuration file at: /root/.config/cray/configurations/default ? [y/N]: y
Username: vshasta
Password:
Success!
Initialization complete.
ncn-m003:~/.config/cray/configurations # cat default
[core]
hostname = "https://api-gw-service-nmn.local"
tenant = ""
[auth.login]
username = "vshasta"
```
```
ncn-m003:~/.config/cray/configurations # cray init --hostname https://api-gw-service-nmn.local --tenant vcluster-blue
Overwrite configuration file at: /root/.config/cray/configurations/default ? [y/N]: y
Username: …
```
> Remove required tenant prompt when initializing (CASMPET-6649)

- .gitignore
- release.sh
- rpm/cloud-init.yaml
- rpm/cray/csm/noos/index.yaml
- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
This stages a new manifest for packages to install via cloud-init. The new `cloud-init.yaml` file will be read during fresh installs and upgrades by `pit-init.sh` and `prerequisites.sh` in order to generate cloud-init data.
This is just staging the change, eventually this will replace `lib/install-goss-tests.sh` once the change is made active through a new NCN image once everything is staged.
A new `cray-site-init` and `pit-init` are pulled in that has the ability to read this file, but this is also a staging change.
> MTL-2000 Add `cloud-init.yaml`

- rpm/cray/csm/sle-15sp4/index.yaml
Remove test that fails if etcd clusters haven't yet been migrated.  This is necessary as cray-fox (diags) uses a separate installer and this test will always fail.  All jiras associated with the bitnami migration are done, so removing the test.
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6642
Just removing a test
Low
* Nothing
> Remove etcd cluster migration test (CASMPET-6642)

- manifests/sysmgmt.yaml
Adds back missing support for undionly.kpxe for vshasta
* Resolves [CASMCMS-8692](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8692)
* Change will also be needed in `release/1.5`
> Adds undionly.kpxe build options for vShasta.

- rpm/cray/csm/sle-15sp4/index.yaml
Cleanup goss-k8s-pods-ips-in-nmn-pool.yaml test, parse K8S 1.22 output correct and discover NMN subnet from SLS.
* https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5638
* https://jira-pro.it.hpe.com:8443/browse/CASMINST-3769
drax:
```
ncn-m001:/opt/cray/tests/install/ncn # export GOSS_BASE=/opt/cray/tests/install/ncn; goss -g /opt/cray/tests/install/ncn/tests/goss-k8s-pods-ips-in-nmn-pool-brad.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate
..
Total Duration: 0.747s
```
Low
* Nothing
> Fixes for goss-k8s-pods-ips-in-nmn-pool.yaml in CSM 1.5 (CASMTRIAGE-5638)

- manifests/sysmgmt.yaml
Updates FAS chart to v3.0.4 FAS v1.29.0 for bugfix of Action IDs becoming NIL
> CASMHMS-6055 - Update FAS Chart to 3.0.4 for FAS v1.29.0 - Main

- manifests/sysmgmt.yaml
Updates FAS chart to v3.0.4 FAS v1.29.0 for bugfix of Action IDs becoming NIL
> CASMHMS-6055 - Update FAS Chart to 3.0.4 for FAS v1.29.0 - CSM 1.5

- manifests/platform.yaml
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASMPET-6669
* Requires - https://github.com/Cray-HPE/cray-sysmgmt-health/pull/125
mug
> CASMPET-6669: sysmgmt: thanos has hard-coded S3 endpoint of "rgw-vip.nmn"

- manifests/sysmgmt.yaml
This update the list of RPMs that are installed/updated from Nexus by CFS. Among other things, this will address the fact that it was not updating the Cray CLI RPM on NCNs.
* Resolves [CASMINST-6532](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6532)
* Resolves [CASMINST-6535](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6535)
* [Source PR](https://github.com/Cray-HPE/csm-config/pull/142)
* [stable/1.5 backport PR](https://github.com/Cray-HPE/csm/pull/2526)
* [release/1.4 PR](https://github.com/Cray-HPE/csm/pull/2525)
I tested the updated configuration on bradi, where the problem was originally discovered after it was updated to CSM 1.4.1.
Low risk
> CASMINST-6532/CASMINST-6535: Update lists of RPMs that CFS installs/updates on nodes

- manifests/platform.yaml
- manifests/sysmgmt.yaml
Update the chart versions of cray-vault, cray-tapms, and cray-tapms-crd as required to add Vault support into the multi-tenancy TAPMS operator.
* Resolves [CASMPET-6520](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6520) as well as several items in the master epic [CASM-3945](https://jira-pro.it.hpe.com:8443/browse/CASM-3945)
* Details in 
* https://github.com/Cray-HPE/cray-tapms-operator/pull/32
* https://github.com/Cray-HPE/docs-csm/pull/3944
> CASMPET-6520 Multi-tenancy: add Vault Transit (KMS) Support

- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Use boto3 pagination api to fully list bucket contents.
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6168
mug:
Before:
```
cray artifacts list thanos | grep ^Key | wc -l
1000
cray artifacts list velero | grep ^Key | wc -l
1000
```
After:
```
cray artifacts list thanos | grep ^Key | wc -l
1583
cray artifacts list velero | grep ^Key | wc -l
2913
```
Low
* Nothing
> Change cray artifacts to return more than 1000 files (CASMPET-6168)

- rpm/cray/csm/sle-15sp3/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Change how tenant name header is passed to also work with other headers.
* https://jira-pro.it.hpe.com:8443/browse/CASMINST-6514
mug:
```
ncn-w004:~/.config/cray/configurations # cray uas create --publickey ~/.ssh/id_rsa.pub --format toml -vvvv
Loaded token: /root/.config/cray/tokens/api_gw_service_nmn_local.vers
REQUEST: POST to https://api-gw-service-nmn.local/apis/uas-mgr/v1/uas
OPTIONS: {'params': {'imagename': None, 'ports': None}, 'data': <MultipartEncoder: {'publickey': ('id_rsa.pub', <_io.BufferedReader name='/root/.ssh/id_rsa.pub'>)}>, 'headers': {'Content-Type': 'multipart/form-data; boundary=183efc470a9645c4af49e8b12f917d14', 'Cray-Tenant-Name': 'vcluster-blue'}, 'verify': False}
uai_age = "0m"
uai_connect_string = "ssh vers@10.102.162.162"
uai_host = "ncn-w006"
uai_img = …
```
> Add tenant name header allowing other headers (CASMINST-6514)

- manifests/sysmgmt.yaml
The build arch env variable was not being set in all containers for the IMS jobs kicked off. That meant that it was defaulting to 'x86_64' and in the case of customizing an 'aarch64' image, when complete it was getting incorrectly uploaded and labeled as an 'x86_64' image.
This adds the 'BUILD_ARCH' env variable to the job templates for the containers that was missing that variable. This will get set to the correct value when IMS templates the job and now flows through with the correct value.
Code PR: https://github.com/Cray-HPE/ims/pull/89
* Resolves [CASMCMS-8707](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8707)
* `Mug`
I installed the new IMS helm chart on Mug, then ran jobs to insure the correct values are getting picked up and set.
- Were the install/upgrade-based validation …
> CASMCMS-8707 - fix arch of image upload after customization.

- manifests/platform.yaml
Use locally built image, change cronjob to not ddos with tons of error pods if backups fail.
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6676
ashton (before with config error):
```
pod/kube-etcdbackup-28149980-zs4jm     0/1     Completed                    0               34m
pod/kube-etcdbackup-28149990-rgl2m     0/1     CreateContainerConfigError   0               24m
pod/kube-etcdbackup-28150000-r4rjj     0/1     CreateContainerConfigError   0               14m
pod/kube-etcdbackup-28150008-h8vp4     0/1     CreateContainerConfigError   0               6m34s
pod/kube-etcdbackup-28150009-fjt4m     0/1     CreateContainerConfigError   0               5m34s
pod/kube-etcdbackup-28150010-2j6h8     0/1     CreateContainerConfigError   0               4m34s …
```
> Use locally built image, prevent slew of error'd pods if jobs failing (CASMPET-6676)

- CHANGELOG.md
- manifests/platform.yaml
Update cray-externaldns to 1.5.0 for CVE remediation.
* Resolves [CASMPET-6554](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6554)
* Change will also be needed in `stable/1.5`
* `ashton`
- Were …
> CASMPET-6554: update cray-externaldns to 1.5.0

- rpm/cray/csm/sle-15sp4/index.yaml
Enhance goss-k8s-pods-ips-in-nmn-pool.yaml test to attempt to find sls file on filesystem if sls not available, as well as use nmap to determine if IP is in subnet range.
* https://jira-pro.it.hpe.com:8443/browse/CASMINST-6527
Drax:
```
ncn-m001:~/brad # export GOSS_BASE=/opt/cray/tests/install/ncn; goss -g /opt/cray/tests/install/ncn/tests/goss-k8s-pods-ips-in-nmn-pool-brad.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate
..
Total Duration: 1.660s
```
```
ncn-m001:~/brad # ./check_goss_k8s_pods_ips_in_nmn_pool.sh
Successfully called sls search networks...
PASS: All K8S pod IPs are in the NMN Bootstrap DNCP Subnet
```
```
ncn-m001:~/brad # ./check_goss_k8s_pods_ips_in_nmn_pool.sh
Failed to talk to sls, looking for sls_input_file.json …
```
> Fix nmn pool test to attempt to find input file if sls not up yet (CASMINST-6527)

- manifests/sysmgmt.yaml
This PR adds retries to the bootscript CT test cases. Sometimes BSS returns a bootscript to re-attempt getting a bootscript, and this normally happens when BSS is syncing with HSM. Add retries to account for this.
* Resolves [CASMHMS-5970](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-5970).
Low risk, fixes an issue that only seems to occur in the hms-nightly-integration test runs.
> CASMHMS-5970 Add retries to BSS bootscript test cases

- CHANGELOG.md
- manifests/platform.yaml
This changes the TTL for deletion of the keycloak-users-localize job so it no longer gets deleted automatically so the test for this job being done never fails, as well as changes the initial setup of LDAP on keycloak so the LDAP federation on keycloak is enabled at startup which allows all users to be seen right after sync instead of having an error.
* Resolves [CASMTRIAGE-5647](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5647)
* Resolves [CASMPET-6645](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6645)
* Fanta
Ran the new version on fanta to check the ttl was correct in the new job and that the admin UI had users available after sync without disabling and enabling.
- Were …
> CASMTRIAGE-5647: Update cray-keycloak-users-localize

- manifests/platform.yaml
_Dashboard for kafka-connect after implementation of the jmx-exporter in [CASMMON-330](https://jira-pro.it.hpe.com:8443/browse/CASMMON-330)._
* Resolves [CASMMON-331](https://jira-pro.it.hpe.com:8443/browse/CASMMON-331)
* Merge after `<https://github.hpe.com/hpe/hpc-car-sma-kafka-connect/pull/17>`
* `<mug>`
* `<hela>`
_The changes tested and success verified._
https://grafana.cmn.mug.hpc.amslabs.hpecorp.net/d/connect/kafka-connect?orgId=1&refresh=10s
```
ncn-m001:/mnt/developer/sum # helm upgrade -n sma cp-kafka-connect cp-kafka-connect-1.4.0.tgz
Release "cp-kafka-connect" has been upgraded. Happy Helming!
NAME: cp-kafka-connect
LAST DEPLOYED: Thu Jul  6 05:32:58 2023
NAMESPACE: sma
STATUS: deployed
REVISION: 26
TEST SUITE: None
NOTES:
This chart installs a …
```
> CASMMON-331 Add kafka-connect dashboard in cray-sysmgmt-health

- manifests/sysmgmt.yaml
A new variable was exposed to the ipxe building processes, but was not exposed in a meaningful way through the helm chart values file. As a result, there was not a good way to programmatically inject the correct value in a non-interactive way.
* Resolves [CASMCMS-8699](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8699)
* Change will also be needed in `stable/1.5`
Low risk; this is a new variable to the values file.
> Bump version of csm-ipxe to pick up new helm-chart variable

- rpm/cray/csm/sle-15sp4/index.yaml
This corrects the iPXE check failure seen during 1.5 to 1.5 upgrades.
* See [source PR](https://github.com/Cray-HPE/csm-testing/pull/512) for details
* Resolves [CASMINST-6523](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6523)/[CASMINST-6541](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6541)
* [stable/1.5 backport](https://github.com/Cray-HPE/csm/pull/2561)
* [metal-provision main PR](https://github.com/Cray-HPE/metal-provision/pull/264)
* [metal-provision lts/csm-1.5 PR](https://github.com/Cray-HPE/metal-provision/pull/265)
> CASMINST-6523: Create modified iPXE check that looks for either CSM 1.4 or CSM 1.5 style iPXE deployment

- CHANGELOG.md
- manifests/sysmgmt.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
This PR includes the following changes for HMNFD targeting CSM-1.6:
* Refactored docker-compose file for runCT environment and replaced RTS with RIE.
* Updated CT tests to hms-test:5.1.0 image.
* Added non-disruptive, disruptive, and destructive Tavern CT tests for HMNFD.
* Made minor corrections and cleaned up the API swagger_v2 specification.
* Resolves CASMHMS-3700.
Unit, integration, CT smoke and Tavern tests passing in GitHub actions. Deployed updated tests on Dorian vShasta system running CSM-1.5.0-beta.10 and verified they passed.
Was a Downgrade tested? Y
Low risk, adds test coverage for HMNFD.
> CASMHMS-3700 Add Tavern CT tests for HMNFD

- CHANGELOG.md
- manifests/platform.yaml
This updates the TTL in keycloak-users-localize to max int so the job will not be deleted. This is needed to keep existing documentation and tests.
* Resolves [CASMTRIAGE-5694](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5694)
* drax
Tested install and upgrade. Small one line change to the ttlSecondsAfterFinished.
- Were continuous integration tests run? If not, why?y
- Was upgrade tested? If not, why?y
- Was downgrade tested? If not, why?y
- Were new tests (or test issues/Jiras) created for this change?y
No risk …
> CASMTRIAGE-5694: Update TTL to max int for users-localize

- rpm/cray/csm/noos/index.yaml
- rpm/cray/csm/sle-15sp4/index.yaml
Change cpu throttle detection script to not assume kubectl output order.
* https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5697
Dorian:
```
ncn-m001:~ # /opt/cray/platform-utils/detect_cpu_throttling.sh nls
Checking cray-nls-678b49ffdb-wbnkd
*** CPU throttling for containerid a41c13afb6624a2edcd56c3212e73f67c51a668d84ed212252c06f32360ddf5e: ***
nr_periods 1167749
nr_throttled 307
throttled_time 4771194407
Checking cray-nls-argo-workflows-server-85d4d8866d-tkw54
*** CPU throttling for containerid c63c012d528a43f6a321cb5dcdf870fbd82f0eb8db8c61bdd1f2e08d56017718: ***
nr_periods 1124931
nr_throttled 1
throttled_time 2555416
Checking cray-nls-argo-workflows-workflow-controller-66fcbc9679-hwgkd
Checking cray-nls-postgres-0
*** CPU throttling for containerid …
```
> Change cpu throttle script to be k8s version agnostic (CASMTRIAGE-5697)

- CHANGELOG.md
- docker/index.yaml
Include container images needed for storage node in csm docker manifest. These will no longer be loaded locally on storage nodes but will be loaded into pit-nexus and regular nexus so that storage nodes don't need to run a local docker registry.
> CASMPET-6650-stable/1.5 put ceph monitoring images needed in csm docker manifest 

- manifests/sysmgmt.yaml
Updates HMNFD chart to 4.0.0 - This was updated in main several weeks ago, but not in branch stable/1.5
* CASMTRIAGE-5692
No testing - original PR was tested on release 1.5
> CASMTRIAGE-5692 - HMNFD chart to 4.0.0, v1.19.0 for branch 1.5

- rpm/cray/csm/sle-15sp4/index.yaml
Add combined health check for use after CSM services are upgraded, but NCNs have not yet rolled by IUF management node rollout.
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6670
Drax (one expected failure):
```
ncn-m003:~ # /opt/cray/tests/install/ncn/automated/ncn-k8s-combined-healthcheck-post-service-upgrade
NCN and Kubernetes Checks (post CSM services upgrade)
------------------------------
Writing full output to /opt/cray/tests/install/logs/print_goss_json_results/20230718_212313.352790-566853-ygO1buGe/out
Running tests
Checking test results
Only errors will be printed to the screen
Result: FAIL
Source: http://ncn-m001.hmn:9008/ncn-healthcheck-master-single-post-service-upgrade
Test Name: Check hmnfd service
Description: Performs a basic health check on the hmnfd service. If this …
```
> Include post services install suite in ncn-k8s-combined-healthcheck (CASMPET-6670)
